package fhir

import (
	"encoding/json"

	"go.uber.org/zap"
	"gorm.io/gorm"

	"kb-patient-profile/internal/models"
)

// Publisher subscribes to KB-20 events and writes them back to the FHIR Store
// as DetectedIssue (threshold crossings) and Condition (CKD status) resources.
// Only active when FHIR_WRITE_BACK=true.
type Publisher struct {
	client *FHIRClient
	db     *gorm.DB
	logger *zap.Logger
}

// NewPublisher creates a FHIR write-back publisher.
func NewPublisher(client *FHIRClient, db *gorm.DB, logger *zap.Logger) *Publisher {
	return &Publisher{
		client: client,
		db:     db,
		logger: logger,
	}
}

// HandleThresholdCrossed writes a FHIR DetectedIssue when a medication threshold is crossed.
func (p *Publisher) HandleThresholdCrossed(event models.Event) {
	// Unmarshal the payload
	payloadBytes, err := json.Marshal(event.Payload)
	if err != nil {
		p.logger.Error("Failed to marshal threshold event payload", zap.Error(err))
		return
	}

	var payload models.MedicationThresholdCrossedPayload
	if err := json.Unmarshal(payloadBytes, &payload); err != nil {
		p.logger.Error("Failed to unmarshal threshold event", zap.Error(err))
		return
	}

	// Resolve FHIR Patient ID
	fhirPatientID := p.resolveFHIRPatientID(event.PatientID)
	if fhirPatientID == "" {
		p.logger.Warn("Cannot write-back DetectedIssue: no FHIR Patient ID",
			zap.String("patient_id", event.PatientID))
		return
	}

	issue := ThresholdCrossingToDetectedIssue(fhirPatientID, &payload)

	if err := p.client.UpsertDetectedIssue(issue); err != nil {
		p.logger.Error("Failed to write DetectedIssue to FHIR Store",
			zap.String("patient_id", event.PatientID),
			zap.Error(err))
		return
	}

	p.logger.Info("DetectedIssue written to FHIR Store",
		zap.String("patient_id", event.PatientID),
		zap.Float64("threshold", payload.ThresholdCrossed))
}

// HandleStratumChange writes a FHIR Condition when CKD status is confirmed.
func (p *Publisher) HandleStratumChange(event models.Event) {
	// Look up the patient profile to check CKD status
	var profile models.PatientProfile
	if err := p.db.Where("patient_id = ?", event.PatientID).First(&profile).Error; err != nil {
		p.logger.Warn("Cannot write-back CKD Condition: patient not found",
			zap.String("patient_id", event.PatientID))
		return
	}

	if profile.CKDStatus != "CONFIRMED" && profile.CKDStatus != "SUSPECTED" {
		return // No CKD to report
	}

	if profile.FHIRPatientID == "" {
		p.logger.Warn("Cannot write-back CKD Condition: no FHIR Patient ID",
			zap.String("patient_id", event.PatientID))
		return
	}

	condition := CKDStatusToFHIRCondition(&profile)

	if err := p.client.UpsertCondition(condition); err != nil {
		p.logger.Error("Failed to write CKD Condition to FHIR Store",
			zap.String("patient_id", event.PatientID),
			zap.Error(err))
		return
	}

	p.logger.Info("CKD Condition written to FHIR Store",
		zap.String("patient_id", event.PatientID),
		zap.String("ckd_status", profile.CKDStatus),
		zap.String("ckd_stage", profile.CKDStage))
}

// HandleDecisionCard writes a FHIR CommunicationRequest when a
// decision card is generated by KB-23. This is the outbound FHIR
// write-back for clinical intelligence outputs — the card's
// clinician summary becomes the CommunicationRequest's payload,
// and the card's urgency maps to the FHIR priority code.
//
// Phase 10 Gap 9: extends the existing publisher (which already
// handles threshold crossings + CKD status) with the third and
// most important event type — the decision card that tells a
// clinician "call this patient today."
//
// FHIR resource mapping:
//   - DecisionCard → CommunicationRequest (R4)
//   - CardID → CommunicationRequest.identifier
//   - ClinicianSummary → CommunicationRequest.payload[0].contentString
//   - SafetyTier → CommunicationRequest.priority (routine|urgent|stat)
//   - PatientID → CommunicationRequest.subject (Patient reference)
func (p *Publisher) HandleDecisionCard(event models.Event) {
	payloadBytes, err := json.Marshal(event.Payload)
	if err != nil {
		p.logger.Error("Failed to marshal decision card event payload", zap.Error(err))
		return
	}

	// The payload is a minimal projection of the card —
	// CardID, TemplateID, ClinicianSummary, SafetyTier, MCUGate.
	// We don't send the full card because the FHIR resource
	// is a pointer to the source system, not a copy of the data.
	var cardPayload struct {
		CardID           string `json:"card_id"`
		TemplateID       string `json:"template_id"`
		ClinicianSummary string `json:"clinician_summary"`
		SafetyTier       string `json:"safety_tier"`
		MCUGate          string `json:"mcu_gate"`
	}
	if err := json.Unmarshal(payloadBytes, &cardPayload); err != nil {
		p.logger.Error("Failed to unmarshal decision card payload", zap.Error(err))
		return
	}

	fhirPatientID := p.resolveFHIRPatientID(event.PatientID)
	if fhirPatientID == "" {
		p.logger.Warn("Cannot write-back CommunicationRequest: no FHIR Patient ID",
			zap.String("patient_id", event.PatientID))
		return
	}

	// Map SafetyTier to FHIR priority
	priority := "routine"
	switch cardPayload.SafetyTier {
	case "IMMEDIATE":
		priority = "stat"
	case "URGENT":
		priority = "urgent"
	}

	// Build FHIR CommunicationRequest resource
	commRequest := map[string]interface{}{
		"resourceType": "CommunicationRequest",
		"status":       "active",
		"priority":     priority,
		"subject": map[string]string{
			"reference": "Patient/" + fhirPatientID,
		},
		"identifier": []map[string]string{
			{
				"system": "urn:cardiofit:decision-card",
				"value":  cardPayload.CardID,
			},
		},
		"payload": []map[string]interface{}{
			{
				"contentString": cardPayload.ClinicianSummary,
			},
		},
		"category": []map[string]interface{}{
			{
				"coding": []map[string]string{
					{
						"system":  "urn:cardiofit:card-template",
						"code":    cardPayload.TemplateID,
						"display": cardPayload.TemplateID,
					},
				},
			},
		},
	}

	if err := p.client.UpsertResource("CommunicationRequest", commRequest); err != nil {
		p.logger.Error("Failed to write CommunicationRequest to FHIR Store",
			zap.String("patient_id", event.PatientID),
			zap.String("card_id", cardPayload.CardID),
			zap.Error(err))
		return
	}

	p.logger.Info("CommunicationRequest written to FHIR Store",
		zap.String("patient_id", event.PatientID),
		zap.String("card_id", cardPayload.CardID),
		zap.String("priority", priority))
}

// resolveFHIRPatientID looks up the FHIR Patient ID from the KB-20 patient profile.
func (p *Publisher) resolveFHIRPatientID(patientID string) string {
	var profile models.PatientProfile
	if err := p.db.Select("fhir_patient_id").
		Where("patient_id = ?", patientID).
		First(&profile).Error; err != nil {
		return ""
	}
	return profile.FHIRPatientID
}
