// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/clinical_reasoning.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type AssertionPriority int32

const (
	AssertionPriority_PRIORITY_UNSPECIFIED AssertionPriority = 0
	AssertionPriority_PRIORITY_LOW         AssertionPriority = 1
	AssertionPriority_PRIORITY_NORMAL      AssertionPriority = 2
	AssertionPriority_PRIORITY_HIGH        AssertionPriority = 3
	AssertionPriority_PRIORITY_CRITICAL    AssertionPriority = 4
)

// Enum value maps for AssertionPriority.
var (
	AssertionPriority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_CRITICAL",
	}
	AssertionPriority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_NORMAL":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_CRITICAL":    4,
	}
)

func (x AssertionPriority) Enum() *AssertionPriority {
	p := new(AssertionPriority)
	*p = x
	return p
}

func (x AssertionPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssertionPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clinical_reasoning_proto_enumTypes[0].Descriptor()
}

func (AssertionPriority) Type() protoreflect.EnumType {
	return &file_proto_clinical_reasoning_proto_enumTypes[0]
}

func (x AssertionPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssertionPriority.Descriptor instead.
func (AssertionPriority) EnumDescriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{0}
}

type AssertionSeverity int32

const (
	AssertionSeverity_SEVERITY_UNSPECIFIED AssertionSeverity = 0
	AssertionSeverity_SEVERITY_INFO        AssertionSeverity = 1
	AssertionSeverity_SEVERITY_LOW         AssertionSeverity = 2
	AssertionSeverity_SEVERITY_MODERATE    AssertionSeverity = 3
	AssertionSeverity_SEVERITY_HIGH        AssertionSeverity = 4
	AssertionSeverity_SEVERITY_CRITICAL    AssertionSeverity = 5
)

// Enum value maps for AssertionSeverity.
var (
	AssertionSeverity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_LOW",
		3: "SEVERITY_MODERATE",
		4: "SEVERITY_HIGH",
		5: "SEVERITY_CRITICAL",
	}
	AssertionSeverity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_LOW":         2,
		"SEVERITY_MODERATE":    3,
		"SEVERITY_HIGH":        4,
		"SEVERITY_CRITICAL":    5,
	}
)

func (x AssertionSeverity) Enum() *AssertionSeverity {
	p := new(AssertionSeverity)
	*p = x
	return p
}

func (x AssertionSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssertionSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clinical_reasoning_proto_enumTypes[1].Descriptor()
}

func (AssertionSeverity) Type() protoreflect.EnumType {
	return &file_proto_clinical_reasoning_proto_enumTypes[1]
}

func (x AssertionSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssertionSeverity.Descriptor instead.
func (AssertionSeverity) EnumDescriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{1}
}

type InteractionSeverity int32

const (
	InteractionSeverity_INTERACTION_SEVERITY_UNSPECIFIED     InteractionSeverity = 0
	InteractionSeverity_INTERACTION_SEVERITY_MINOR           InteractionSeverity = 1
	InteractionSeverity_INTERACTION_SEVERITY_MODERATE        InteractionSeverity = 2
	InteractionSeverity_INTERACTION_SEVERITY_MAJOR           InteractionSeverity = 3
	InteractionSeverity_INTERACTION_SEVERITY_CONTRAINDICATED InteractionSeverity = 4
)

// Enum value maps for InteractionSeverity.
var (
	InteractionSeverity_name = map[int32]string{
		0: "INTERACTION_SEVERITY_UNSPECIFIED",
		1: "INTERACTION_SEVERITY_MINOR",
		2: "INTERACTION_SEVERITY_MODERATE",
		3: "INTERACTION_SEVERITY_MAJOR",
		4: "INTERACTION_SEVERITY_CONTRAINDICATED",
	}
	InteractionSeverity_value = map[string]int32{
		"INTERACTION_SEVERITY_UNSPECIFIED":     0,
		"INTERACTION_SEVERITY_MINOR":           1,
		"INTERACTION_SEVERITY_MODERATE":        2,
		"INTERACTION_SEVERITY_MAJOR":           3,
		"INTERACTION_SEVERITY_CONTRAINDICATED": 4,
	}
)

func (x InteractionSeverity) Enum() *InteractionSeverity {
	p := new(InteractionSeverity)
	*p = x
	return p
}

func (x InteractionSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InteractionSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clinical_reasoning_proto_enumTypes[2].Descriptor()
}

func (InteractionSeverity) Type() protoreflect.EnumType {
	return &file_proto_clinical_reasoning_proto_enumTypes[2]
}

func (x InteractionSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InteractionSeverity.Descriptor instead.
func (InteractionSeverity) EnumDescriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{2}
}

type AlertSeverity int32

const (
	AlertSeverity_ALERT_SEVERITY_UNSPECIFIED AlertSeverity = 0
	AlertSeverity_ALERT_SEVERITY_INFO        AlertSeverity = 1
	AlertSeverity_ALERT_SEVERITY_WARNING     AlertSeverity = 2
	AlertSeverity_ALERT_SEVERITY_CRITICAL    AlertSeverity = 3
)

// Enum value maps for AlertSeverity.
var (
	AlertSeverity_name = map[int32]string{
		0: "ALERT_SEVERITY_UNSPECIFIED",
		1: "ALERT_SEVERITY_INFO",
		2: "ALERT_SEVERITY_WARNING",
		3: "ALERT_SEVERITY_CRITICAL",
	}
	AlertSeverity_value = map[string]int32{
		"ALERT_SEVERITY_UNSPECIFIED": 0,
		"ALERT_SEVERITY_INFO":        1,
		"ALERT_SEVERITY_WARNING":     2,
		"ALERT_SEVERITY_CRITICAL":    3,
	}
)

func (x AlertSeverity) Enum() *AlertSeverity {
	p := new(AlertSeverity)
	*p = x
	return p
}

func (x AlertSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clinical_reasoning_proto_enumTypes[3].Descriptor()
}

func (AlertSeverity) Type() protoreflect.EnumType {
	return &file_proto_clinical_reasoning_proto_enumTypes[3]
}

func (x AlertSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertSeverity.Descriptor instead.
func (AlertSeverity) EnumDescriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{3}
}

type ContraindicationSeverity int32

const (
	ContraindicationSeverity_CONTRAINDICATION_SEVERITY_UNSPECIFIED ContraindicationSeverity = 0
	ContraindicationSeverity_CONTRAINDICATION_SEVERITY_RELATIVE    ContraindicationSeverity = 1
	ContraindicationSeverity_CONTRAINDICATION_SEVERITY_ABSOLUTE    ContraindicationSeverity = 2
)

// Enum value maps for ContraindicationSeverity.
var (
	ContraindicationSeverity_name = map[int32]string{
		0: "CONTRAINDICATION_SEVERITY_UNSPECIFIED",
		1: "CONTRAINDICATION_SEVERITY_RELATIVE",
		2: "CONTRAINDICATION_SEVERITY_ABSOLUTE",
	}
	ContraindicationSeverity_value = map[string]int32{
		"CONTRAINDICATION_SEVERITY_UNSPECIFIED": 0,
		"CONTRAINDICATION_SEVERITY_RELATIVE":    1,
		"CONTRAINDICATION_SEVERITY_ABSOLUTE":    2,
	}
)

func (x ContraindicationSeverity) Enum() *ContraindicationSeverity {
	p := new(ContraindicationSeverity)
	*p = x
	return p
}

func (x ContraindicationSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContraindicationSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clinical_reasoning_proto_enumTypes[4].Descriptor()
}

func (ContraindicationSeverity) Type() protoreflect.EnumType {
	return &file_proto_clinical_reasoning_proto_enumTypes[4]
}

func (x ContraindicationSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContraindicationSeverity.Descriptor instead.
func (ContraindicationSeverity) EnumDescriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{4}
}

type CAEHealthStatus int32

const (
	CAEHealthStatus_CAE_HEALTH_STATUS_UNSPECIFIED CAEHealthStatus = 0
	CAEHealthStatus_CAE_HEALTH_STATUS_HEALTHY     CAEHealthStatus = 1
	CAEHealthStatus_CAE_HEALTH_STATUS_UNHEALTHY   CAEHealthStatus = 2
	CAEHealthStatus_CAE_HEALTH_STATUS_DEGRADED    CAEHealthStatus = 3
)

// Enum value maps for CAEHealthStatus.
var (
	CAEHealthStatus_name = map[int32]string{
		0: "CAE_HEALTH_STATUS_UNSPECIFIED",
		1: "CAE_HEALTH_STATUS_HEALTHY",
		2: "CAE_HEALTH_STATUS_UNHEALTHY",
		3: "CAE_HEALTH_STATUS_DEGRADED",
	}
	CAEHealthStatus_value = map[string]int32{
		"CAE_HEALTH_STATUS_UNSPECIFIED": 0,
		"CAE_HEALTH_STATUS_HEALTHY":     1,
		"CAE_HEALTH_STATUS_UNHEALTHY":   2,
		"CAE_HEALTH_STATUS_DEGRADED":    3,
	}
)

func (x CAEHealthStatus) Enum() *CAEHealthStatus {
	p := new(CAEHealthStatus)
	*p = x
	return p
}

func (x CAEHealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CAEHealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clinical_reasoning_proto_enumTypes[5].Descriptor()
}

func (CAEHealthStatus) Type() protoreflect.EnumType {
	return &file_proto_clinical_reasoning_proto_enumTypes[5]
}

func (x CAEHealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CAEHealthStatus.Descriptor instead.
func (CAEHealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{5}
}

type UpdateType int32

const (
	UpdateType_UPDATE_TYPE_UNSPECIFIED         UpdateType = 0
	UpdateType_UPDATE_TYPE_ASSERTION_ADDED     UpdateType = 1
	UpdateType_UPDATE_TYPE_ASSERTION_UPDATED   UpdateType = 2
	UpdateType_UPDATE_TYPE_ASSERTION_REMOVED   UpdateType = 3
	UpdateType_UPDATE_TYPE_PROCESSING_COMPLETE UpdateType = 4
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "UPDATE_TYPE_UNSPECIFIED",
		1: "UPDATE_TYPE_ASSERTION_ADDED",
		2: "UPDATE_TYPE_ASSERTION_UPDATED",
		3: "UPDATE_TYPE_ASSERTION_REMOVED",
		4: "UPDATE_TYPE_PROCESSING_COMPLETE",
	}
	UpdateType_value = map[string]int32{
		"UPDATE_TYPE_UNSPECIFIED":         0,
		"UPDATE_TYPE_ASSERTION_ADDED":     1,
		"UPDATE_TYPE_ASSERTION_UPDATED":   2,
		"UPDATE_TYPE_ASSERTION_REMOVED":   3,
		"UPDATE_TYPE_PROCESSING_COMPLETE": 4,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clinical_reasoning_proto_enumTypes[6].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_proto_clinical_reasoning_proto_enumTypes[6]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{6}
}

// Clinical assertion request
type ClinicalAssertionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PatientId      string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	MedicationIds  []string               `protobuf:"bytes,3,rep,name=medication_ids,json=medicationIds,proto3" json:"medication_ids,omitempty"`
	ConditionIds   []string               `protobuf:"bytes,4,rep,name=condition_ids,json=conditionIds,proto3" json:"condition_ids,omitempty"`
	PatientContext *structpb.Struct       `protobuf:"bytes,5,opt,name=patient_context,json=patientContext,proto3" json:"patient_context,omitempty"`
	Priority       AssertionPriority      `protobuf:"varint,6,opt,name=priority,proto3,enum=clinical_hub.cae.v1.AssertionPriority" json:"priority,omitempty"`
	ReasonerTypes  []string               `protobuf:"bytes,7,rep,name=reasoner_types,json=reasonerTypes,proto3" json:"reasoner_types,omitempty"` // ["interaction", "dosing", "contraindication"]
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClinicalAssertionRequest) Reset() {
	*x = ClinicalAssertionRequest{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClinicalAssertionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicalAssertionRequest) ProtoMessage() {}

func (x *ClinicalAssertionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicalAssertionRequest.ProtoReflect.Descriptor instead.
func (*ClinicalAssertionRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{0}
}

func (x *ClinicalAssertionRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ClinicalAssertionRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ClinicalAssertionRequest) GetMedicationIds() []string {
	if x != nil {
		return x.MedicationIds
	}
	return nil
}

func (x *ClinicalAssertionRequest) GetConditionIds() []string {
	if x != nil {
		return x.ConditionIds
	}
	return nil
}

func (x *ClinicalAssertionRequest) GetPatientContext() *structpb.Struct {
	if x != nil {
		return x.PatientContext
	}
	return nil
}

func (x *ClinicalAssertionRequest) GetPriority() AssertionPriority {
	if x != nil {
		return x.Priority
	}
	return AssertionPriority_PRIORITY_UNSPECIFIED
}

func (x *ClinicalAssertionRequest) GetReasonerTypes() []string {
	if x != nil {
		return x.ReasonerTypes
	}
	return nil
}

// Clinical assertion response
type ClinicalAssertionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Assertions    []*ClinicalAssertion   `protobuf:"bytes,3,rep,name=assertions,proto3" json:"assertions,omitempty"`
	Metadata      *AssertionMetadata     `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClinicalAssertionResponse) Reset() {
	*x = ClinicalAssertionResponse{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClinicalAssertionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicalAssertionResponse) ProtoMessage() {}

func (x *ClinicalAssertionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicalAssertionResponse.ProtoReflect.Descriptor instead.
func (*ClinicalAssertionResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{1}
}

func (x *ClinicalAssertionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClinicalAssertionResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ClinicalAssertionResponse) GetAssertions() []*ClinicalAssertion {
	if x != nil {
		return x.Assertions
	}
	return nil
}

func (x *ClinicalAssertionResponse) GetMetadata() *AssertionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClinicalAssertionResponse) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

// Individual clinical assertion
type ClinicalAssertion struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AssertionId         string                 `protobuf:"bytes,1,opt,name=assertion_id,json=assertionId,proto3" json:"assertion_id,omitempty"`
	ReasonerType        string                 `protobuf:"bytes,2,opt,name=reasoner_type,json=reasonerType,proto3" json:"reasoner_type,omitempty"`
	Severity            AssertionSeverity      `protobuf:"varint,3,opt,name=severity,proto3,enum=clinical_hub.cae.v1.AssertionSeverity" json:"severity,omitempty"`
	Message             string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Description         string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	AffectedMedications []string               `protobuf:"bytes,6,rep,name=affected_medications,json=affectedMedications,proto3" json:"affected_medications,omitempty"`
	AffectedConditions  []string               `protobuf:"bytes,7,rep,name=affected_conditions,json=affectedConditions,proto3" json:"affected_conditions,omitempty"`
	Evidence            *structpb.Struct       `protobuf:"bytes,8,opt,name=evidence,proto3" json:"evidence,omitempty"`
	ConfidenceScore     float32                `protobuf:"fixed32,9,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Recommendations     []string               `protobuf:"bytes,10,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	Metadata            *structpb.Struct       `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClinicalAssertion) Reset() {
	*x = ClinicalAssertion{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClinicalAssertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicalAssertion) ProtoMessage() {}

func (x *ClinicalAssertion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicalAssertion.ProtoReflect.Descriptor instead.
func (*ClinicalAssertion) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{2}
}

func (x *ClinicalAssertion) GetAssertionId() string {
	if x != nil {
		return x.AssertionId
	}
	return ""
}

func (x *ClinicalAssertion) GetReasonerType() string {
	if x != nil {
		return x.ReasonerType
	}
	return ""
}

func (x *ClinicalAssertion) GetSeverity() AssertionSeverity {
	if x != nil {
		return x.Severity
	}
	return AssertionSeverity_SEVERITY_UNSPECIFIED
}

func (x *ClinicalAssertion) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClinicalAssertion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ClinicalAssertion) GetAffectedMedications() []string {
	if x != nil {
		return x.AffectedMedications
	}
	return nil
}

func (x *ClinicalAssertion) GetAffectedConditions() []string {
	if x != nil {
		return x.AffectedConditions
	}
	return nil
}

func (x *ClinicalAssertion) GetEvidence() *structpb.Struct {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *ClinicalAssertion) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *ClinicalAssertion) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *ClinicalAssertion) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Assertion metadata
type AssertionMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReasonerVersion  string                 `protobuf:"bytes,1,opt,name=reasoner_version,json=reasonerVersion,proto3" json:"reasoner_version,omitempty"`
	KnowledgeVersion string                 `protobuf:"bytes,2,opt,name=knowledge_version,json=knowledgeVersion,proto3" json:"knowledge_version,omitempty"`
	ProcessingTimeMs int32                  `protobuf:"varint,3,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	Warnings         []string               `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssertionMetadata) Reset() {
	*x = AssertionMetadata{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertionMetadata) ProtoMessage() {}

func (x *AssertionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertionMetadata.ProtoReflect.Descriptor instead.
func (*AssertionMetadata) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{3}
}

func (x *AssertionMetadata) GetReasonerVersion() string {
	if x != nil {
		return x.ReasonerVersion
	}
	return ""
}

func (x *AssertionMetadata) GetKnowledgeVersion() string {
	if x != nil {
		return x.KnowledgeVersion
	}
	return ""
}

func (x *AssertionMetadata) GetProcessingTimeMs() int32 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *AssertionMetadata) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Medication interaction request
type MedicationInteractionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PatientId      string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	MedicationIds  []string               `protobuf:"bytes,2,rep,name=medication_ids,json=medicationIds,proto3" json:"medication_ids,omitempty"`
	PatientContext *structpb.Struct       `protobuf:"bytes,3,opt,name=patient_context,json=patientContext,proto3" json:"patient_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MedicationInteractionRequest) Reset() {
	*x = MedicationInteractionRequest{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedicationInteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedicationInteractionRequest) ProtoMessage() {}

func (x *MedicationInteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedicationInteractionRequest.ProtoReflect.Descriptor instead.
func (*MedicationInteractionRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{4}
}

func (x *MedicationInteractionRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *MedicationInteractionRequest) GetMedicationIds() []string {
	if x != nil {
		return x.MedicationIds
	}
	return nil
}

func (x *MedicationInteractionRequest) GetPatientContext() *structpb.Struct {
	if x != nil {
		return x.PatientContext
	}
	return nil
}

// Medication interaction response
type MedicationInteractionResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Interactions  []*MedicationInteraction `protobuf:"bytes,1,rep,name=interactions,proto3" json:"interactions,omitempty"`
	Metadata      *AssertionMetadata       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MedicationInteractionResponse) Reset() {
	*x = MedicationInteractionResponse{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedicationInteractionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedicationInteractionResponse) ProtoMessage() {}

func (x *MedicationInteractionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedicationInteractionResponse.ProtoReflect.Descriptor instead.
func (*MedicationInteractionResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{5}
}

func (x *MedicationInteractionResponse) GetInteractions() []*MedicationInteraction {
	if x != nil {
		return x.Interactions
	}
	return nil
}

func (x *MedicationInteractionResponse) GetMetadata() *AssertionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Medication interaction
type MedicationInteraction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InteractionId   string                 `protobuf:"bytes,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	MedicationIds   []string               `protobuf:"bytes,2,rep,name=medication_ids,json=medicationIds,proto3" json:"medication_ids,omitempty"`
	Severity        InteractionSeverity    `protobuf:"varint,3,opt,name=severity,proto3,enum=clinical_hub.cae.v1.InteractionSeverity" json:"severity,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Mechanism       string                 `protobuf:"bytes,5,opt,name=mechanism,proto3" json:"mechanism,omitempty"`
	Recommendations []string               `protobuf:"bytes,6,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	Evidence        *structpb.Struct       `protobuf:"bytes,7,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MedicationInteraction) Reset() {
	*x = MedicationInteraction{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedicationInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedicationInteraction) ProtoMessage() {}

func (x *MedicationInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedicationInteraction.ProtoReflect.Descriptor instead.
func (*MedicationInteraction) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{6}
}

func (x *MedicationInteraction) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

func (x *MedicationInteraction) GetMedicationIds() []string {
	if x != nil {
		return x.MedicationIds
	}
	return nil
}

func (x *MedicationInteraction) GetSeverity() InteractionSeverity {
	if x != nil {
		return x.Severity
	}
	return InteractionSeverity_INTERACTION_SEVERITY_UNSPECIFIED
}

func (x *MedicationInteraction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MedicationInteraction) GetMechanism() string {
	if x != nil {
		return x.Mechanism
	}
	return ""
}

func (x *MedicationInteraction) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *MedicationInteraction) GetEvidence() *structpb.Struct {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// Dosing calculation request
type DosingCalculationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PatientId      string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	MedicationId   string                 `protobuf:"bytes,2,opt,name=medication_id,json=medicationId,proto3" json:"medication_id,omitempty"`
	PatientContext *structpb.Struct       `protobuf:"bytes,3,opt,name=patient_context,json=patientContext,proto3" json:"patient_context,omitempty"`
	Indication     string                 `protobuf:"bytes,4,opt,name=indication,proto3" json:"indication,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DosingCalculationRequest) Reset() {
	*x = DosingCalculationRequest{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DosingCalculationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DosingCalculationRequest) ProtoMessage() {}

func (x *DosingCalculationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DosingCalculationRequest.ProtoReflect.Descriptor instead.
func (*DosingCalculationRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{7}
}

func (x *DosingCalculationRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *DosingCalculationRequest) GetMedicationId() string {
	if x != nil {
		return x.MedicationId
	}
	return ""
}

func (x *DosingCalculationRequest) GetPatientContext() *structpb.Struct {
	if x != nil {
		return x.PatientContext
	}
	return nil
}

func (x *DosingCalculationRequest) GetIndication() string {
	if x != nil {
		return x.Indication
	}
	return ""
}

// Dosing calculation response
type DosingCalculationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Recommendation *DosingRecommendation  `protobuf:"bytes,1,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	Alerts         []*DosingAlert         `protobuf:"bytes,2,rep,name=alerts,proto3" json:"alerts,omitempty"`
	Metadata       *AssertionMetadata     `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DosingCalculationResponse) Reset() {
	*x = DosingCalculationResponse{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DosingCalculationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DosingCalculationResponse) ProtoMessage() {}

func (x *DosingCalculationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DosingCalculationResponse.ProtoReflect.Descriptor instead.
func (*DosingCalculationResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{8}
}

func (x *DosingCalculationResponse) GetRecommendation() *DosingRecommendation {
	if x != nil {
		return x.Recommendation
	}
	return nil
}

func (x *DosingCalculationResponse) GetAlerts() []*DosingAlert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *DosingCalculationResponse) GetMetadata() *AssertionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Dosing recommendation
type DosingRecommendation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MedicationId    string                 `protobuf:"bytes,1,opt,name=medication_id,json=medicationId,proto3" json:"medication_id,omitempty"`
	RecommendedDose string                 `protobuf:"bytes,2,opt,name=recommended_dose,json=recommendedDose,proto3" json:"recommended_dose,omitempty"`
	Frequency       string                 `protobuf:"bytes,3,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Route           string                 `protobuf:"bytes,4,opt,name=route,proto3" json:"route,omitempty"`
	Duration        string                 `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Adjustments     []string               `protobuf:"bytes,6,rep,name=adjustments,proto3" json:"adjustments,omitempty"`
	Rationale       *structpb.Struct       `protobuf:"bytes,7,opt,name=rationale,proto3" json:"rationale,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DosingRecommendation) Reset() {
	*x = DosingRecommendation{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DosingRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DosingRecommendation) ProtoMessage() {}

func (x *DosingRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DosingRecommendation.ProtoReflect.Descriptor instead.
func (*DosingRecommendation) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{9}
}

func (x *DosingRecommendation) GetMedicationId() string {
	if x != nil {
		return x.MedicationId
	}
	return ""
}

func (x *DosingRecommendation) GetRecommendedDose() string {
	if x != nil {
		return x.RecommendedDose
	}
	return ""
}

func (x *DosingRecommendation) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *DosingRecommendation) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *DosingRecommendation) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *DosingRecommendation) GetAdjustments() []string {
	if x != nil {
		return x.Adjustments
	}
	return nil
}

func (x *DosingRecommendation) GetRationale() *structpb.Struct {
	if x != nil {
		return x.Rationale
	}
	return nil
}

// Dosing alert
type DosingAlert struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AlertId        string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Severity       AlertSeverity          `protobuf:"varint,2,opt,name=severity,proto3,enum=clinical_hub.cae.v1.AlertSeverity" json:"severity,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Recommendation string                 `protobuf:"bytes,4,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DosingAlert) Reset() {
	*x = DosingAlert{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DosingAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DosingAlert) ProtoMessage() {}

func (x *DosingAlert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DosingAlert.ProtoReflect.Descriptor instead.
func (*DosingAlert) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{10}
}

func (x *DosingAlert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *DosingAlert) GetSeverity() AlertSeverity {
	if x != nil {
		return x.Severity
	}
	return AlertSeverity_ALERT_SEVERITY_UNSPECIFIED
}

func (x *DosingAlert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DosingAlert) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

// Contraindication request
type ContraindicationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PatientId      string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	MedicationIds  []string               `protobuf:"bytes,2,rep,name=medication_ids,json=medicationIds,proto3" json:"medication_ids,omitempty"`
	ConditionIds   []string               `protobuf:"bytes,3,rep,name=condition_ids,json=conditionIds,proto3" json:"condition_ids,omitempty"`
	PatientContext *structpb.Struct       `protobuf:"bytes,4,opt,name=patient_context,json=patientContext,proto3" json:"patient_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContraindicationRequest) Reset() {
	*x = ContraindicationRequest{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContraindicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContraindicationRequest) ProtoMessage() {}

func (x *ContraindicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContraindicationRequest.ProtoReflect.Descriptor instead.
func (*ContraindicationRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{11}
}

func (x *ContraindicationRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ContraindicationRequest) GetMedicationIds() []string {
	if x != nil {
		return x.MedicationIds
	}
	return nil
}

func (x *ContraindicationRequest) GetConditionIds() []string {
	if x != nil {
		return x.ConditionIds
	}
	return nil
}

func (x *ContraindicationRequest) GetPatientContext() *structpb.Struct {
	if x != nil {
		return x.PatientContext
	}
	return nil
}

// Contraindication response
type ContraindicationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Contraindications []*Contraindication    `protobuf:"bytes,1,rep,name=contraindications,proto3" json:"contraindications,omitempty"`
	Metadata          *AssertionMetadata     `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContraindicationResponse) Reset() {
	*x = ContraindicationResponse{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContraindicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContraindicationResponse) ProtoMessage() {}

func (x *ContraindicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContraindicationResponse.ProtoReflect.Descriptor instead.
func (*ContraindicationResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{12}
}

func (x *ContraindicationResponse) GetContraindications() []*Contraindication {
	if x != nil {
		return x.Contraindications
	}
	return nil
}

func (x *ContraindicationResponse) GetMetadata() *AssertionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Contraindication
type Contraindication struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	ContraindicationId string                   `protobuf:"bytes,1,opt,name=contraindication_id,json=contraindicationId,proto3" json:"contraindication_id,omitempty"`
	MedicationId       string                   `protobuf:"bytes,2,opt,name=medication_id,json=medicationId,proto3" json:"medication_id,omitempty"`
	ConditionId        string                   `protobuf:"bytes,3,opt,name=condition_id,json=conditionId,proto3" json:"condition_id,omitempty"`
	Severity           ContraindicationSeverity `protobuf:"varint,4,opt,name=severity,proto3,enum=clinical_hub.cae.v1.ContraindicationSeverity" json:"severity,omitempty"`
	Description        string                   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Recommendations    []string                 `protobuf:"bytes,6,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	Evidence           *structpb.Struct         `protobuf:"bytes,7,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Contraindication) Reset() {
	*x = Contraindication{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contraindication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contraindication) ProtoMessage() {}

func (x *Contraindication) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contraindication.ProtoReflect.Descriptor instead.
func (*Contraindication) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{13}
}

func (x *Contraindication) GetContraindicationId() string {
	if x != nil {
		return x.ContraindicationId
	}
	return ""
}

func (x *Contraindication) GetMedicationId() string {
	if x != nil {
		return x.MedicationId
	}
	return ""
}

func (x *Contraindication) GetConditionId() string {
	if x != nil {
		return x.ConditionId
	}
	return ""
}

func (x *Contraindication) GetSeverity() ContraindicationSeverity {
	if x != nil {
		return x.Severity
	}
	return ContraindicationSeverity_CONTRAINDICATION_SEVERITY_UNSPECIFIED
}

func (x *Contraindication) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Contraindication) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *Contraindication) GetEvidence() *structpb.Struct {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// Health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{14}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// Health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CAEHealthStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=clinical_hub.cae.v1.CAEHealthStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckResponse) GetStatus() CAEHealthStatus {
	if x != nil {
		return x.Status
	}
	return CAEHealthStatus_CAE_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

// Clinical assertion update (for streaming)
type ClinicalAssertionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdateId      string                 `protobuf:"bytes,1,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	UpdateType    UpdateType             `protobuf:"varint,3,opt,name=update_type,json=updateType,proto3,enum=clinical_hub.cae.v1.UpdateType" json:"update_type,omitempty"`
	Assertion     *ClinicalAssertion     `protobuf:"bytes,4,opt,name=assertion,proto3" json:"assertion,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClinicalAssertionUpdate) Reset() {
	*x = ClinicalAssertionUpdate{}
	mi := &file_proto_clinical_reasoning_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClinicalAssertionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicalAssertionUpdate) ProtoMessage() {}

func (x *ClinicalAssertionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinical_reasoning_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicalAssertionUpdate.ProtoReflect.Descriptor instead.
func (*ClinicalAssertionUpdate) Descriptor() ([]byte, []int) {
	return file_proto_clinical_reasoning_proto_rawDescGZIP(), []int{16}
}

func (x *ClinicalAssertionUpdate) GetUpdateId() string {
	if x != nil {
		return x.UpdateId
	}
	return ""
}

func (x *ClinicalAssertionUpdate) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ClinicalAssertionUpdate) GetUpdateType() UpdateType {
	if x != nil {
		return x.UpdateType
	}
	return UpdateType_UPDATE_TYPE_UNSPECIFIED
}

func (x *ClinicalAssertionUpdate) GetAssertion() *ClinicalAssertion {
	if x != nil {
		return x.Assertion
	}
	return nil
}

func (x *ClinicalAssertionUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_clinical_reasoning_proto protoreflect.FileDescriptor

const file_proto_clinical_reasoning_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/clinical_reasoning.proto\x12\x13clinical_hub.cae.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x02\n" +
	"\x18ClinicalAssertionRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12%\n" +
	"\x0emedication_ids\x18\x03 \x03(\tR\rmedicationIds\x12#\n" +
	"\rcondition_ids\x18\x04 \x03(\tR\fconditionIds\x12@\n" +
	"\x0fpatient_context\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x0epatientContext\x12B\n" +
	"\bpriority\x18\x06 \x01(\x0e2&.clinical_hub.cae.v1.AssertionPriorityR\bpriority\x12%\n" +
	"\x0ereasoner_types\x18\a \x03(\tR\rreasonerTypes\"\xac\x02\n" +
	"\x19ClinicalAssertionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12F\n" +
	"\n" +
	"assertions\x18\x03 \x03(\v2&.clinical_hub.cae.v1.ClinicalAssertionR\n" +
	"assertions\x12B\n" +
	"\bmetadata\x18\x04 \x01(\v2&.clinical_hub.cae.v1.AssertionMetadataR\bmetadata\x12=\n" +
	"\fgenerated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"\xfe\x03\n" +
	"\x11ClinicalAssertion\x12!\n" +
	"\fassertion_id\x18\x01 \x01(\tR\vassertionId\x12#\n" +
	"\rreasoner_type\x18\x02 \x01(\tR\freasonerType\x12B\n" +
	"\bseverity\x18\x03 \x01(\x0e2&.clinical_hub.cae.v1.AssertionSeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x121\n" +
	"\x14affected_medications\x18\x06 \x03(\tR\x13affectedMedications\x12/\n" +
	"\x13affected_conditions\x18\a \x03(\tR\x12affectedConditions\x123\n" +
	"\bevidence\x18\b \x01(\v2\x17.google.protobuf.StructR\bevidence\x12)\n" +
	"\x10confidence_score\x18\t \x01(\x02R\x0fconfidenceScore\x12(\n" +
	"\x0frecommendations\x18\n" +
	" \x03(\tR\x0frecommendations\x123\n" +
	"\bmetadata\x18\v \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xb5\x01\n" +
	"\x11AssertionMetadata\x12)\n" +
	"\x10reasoner_version\x18\x01 \x01(\tR\x0freasonerVersion\x12+\n" +
	"\x11knowledge_version\x18\x02 \x01(\tR\x10knowledgeVersion\x12,\n" +
	"\x12processing_time_ms\x18\x03 \x01(\x05R\x10processingTimeMs\x12\x1a\n" +
	"\bwarnings\x18\x04 \x03(\tR\bwarnings\"\xa6\x01\n" +
	"\x1cMedicationInteractionRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12%\n" +
	"\x0emedication_ids\x18\x02 \x03(\tR\rmedicationIds\x12@\n" +
	"\x0fpatient_context\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0epatientContext\"\xb3\x01\n" +
	"\x1dMedicationInteractionResponse\x12N\n" +
	"\finteractions\x18\x01 \x03(\v2*.clinical_hub.cae.v1.MedicationInteractionR\finteractions\x12B\n" +
	"\bmetadata\x18\x02 \x01(\v2&.clinical_hub.cae.v1.AssertionMetadataR\bmetadata\"\xca\x02\n" +
	"\x15MedicationInteraction\x12%\n" +
	"\x0einteraction_id\x18\x01 \x01(\tR\rinteractionId\x12%\n" +
	"\x0emedication_ids\x18\x02 \x03(\tR\rmedicationIds\x12D\n" +
	"\bseverity\x18\x03 \x01(\x0e2(.clinical_hub.cae.v1.InteractionSeverityR\bseverity\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tmechanism\x18\x05 \x01(\tR\tmechanism\x12(\n" +
	"\x0frecommendations\x18\x06 \x03(\tR\x0frecommendations\x123\n" +
	"\bevidence\x18\a \x01(\v2\x17.google.protobuf.StructR\bevidence\"\xc0\x01\n" +
	"\x18DosingCalculationRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12#\n" +
	"\rmedication_id\x18\x02 \x01(\tR\fmedicationId\x12@\n" +
	"\x0fpatient_context\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0epatientContext\x12\x1e\n" +
	"\n" +
	"indication\x18\x04 \x01(\tR\n" +
	"indication\"\xec\x01\n" +
	"\x19DosingCalculationResponse\x12Q\n" +
	"\x0erecommendation\x18\x01 \x01(\v2).clinical_hub.cae.v1.DosingRecommendationR\x0erecommendation\x128\n" +
	"\x06alerts\x18\x02 \x03(\v2 .clinical_hub.cae.v1.DosingAlertR\x06alerts\x12B\n" +
	"\bmetadata\x18\x03 \x01(\v2&.clinical_hub.cae.v1.AssertionMetadataR\bmetadata\"\x8f\x02\n" +
	"\x14DosingRecommendation\x12#\n" +
	"\rmedication_id\x18\x01 \x01(\tR\fmedicationId\x12)\n" +
	"\x10recommended_dose\x18\x02 \x01(\tR\x0frecommendedDose\x12\x1c\n" +
	"\tfrequency\x18\x03 \x01(\tR\tfrequency\x12\x14\n" +
	"\x05route\x18\x04 \x01(\tR\x05route\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\tR\bduration\x12 \n" +
	"\vadjustments\x18\x06 \x03(\tR\vadjustments\x125\n" +
	"\trationale\x18\a \x01(\v2\x17.google.protobuf.StructR\trationale\"\xaa\x01\n" +
	"\vDosingAlert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12>\n" +
	"\bseverity\x18\x02 \x01(\x0e2\".clinical_hub.cae.v1.AlertSeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12&\n" +
	"\x0erecommendation\x18\x04 \x01(\tR\x0erecommendation\"\xc6\x01\n" +
	"\x17ContraindicationRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12%\n" +
	"\x0emedication_ids\x18\x02 \x03(\tR\rmedicationIds\x12#\n" +
	"\rcondition_ids\x18\x03 \x03(\tR\fconditionIds\x12@\n" +
	"\x0fpatient_context\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x0epatientContext\"\xb3\x01\n" +
	"\x18ContraindicationResponse\x12S\n" +
	"\x11contraindications\x18\x01 \x03(\v2%.clinical_hub.cae.v1.ContraindicationR\x11contraindications\x12B\n" +
	"\bmetadata\x18\x02 \x01(\v2&.clinical_hub.cae.v1.AssertionMetadataR\bmetadata\"\xd7\x02\n" +
	"\x10Contraindication\x12/\n" +
	"\x13contraindication_id\x18\x01 \x01(\tR\x12contraindicationId\x12#\n" +
	"\rmedication_id\x18\x02 \x01(\tR\fmedicationId\x12!\n" +
	"\fcondition_id\x18\x03 \x01(\tR\vconditionId\x12I\n" +
	"\bseverity\x18\x04 \x01(\x0e2-.clinical_hub.cae.v1.ContraindicationSeverityR\bseverity\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12(\n" +
	"\x0frecommendations\x18\x06 \x03(\tR\x0frecommendations\x123\n" +
	"\bevidence\x18\a \x01(\v2\x17.google.protobuf.StructR\bevidence\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xa0\x01\n" +
	"\x13HealthCheckResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2$.clinical_hub.cae.v1.CAEHealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\adetails\x18\x03 \x01(\v2\x17.google.protobuf.StructR\adetails\"\x9f\x02\n" +
	"\x17ClinicalAssertionUpdate\x12\x1b\n" +
	"\tupdate_id\x18\x01 \x01(\tR\bupdateId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12@\n" +
	"\vupdate_type\x18\x03 \x01(\x0e2\x1f.clinical_hub.cae.v1.UpdateTypeR\n" +
	"updateType\x12D\n" +
	"\tassertion\x18\x04 \x01(\v2&.clinical_hub.cae.v1.ClinicalAssertionR\tassertion\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*~\n" +
	"\x11AssertionPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x04*m\n" +
	"\x11AssertionSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x03*\xc8\x01\n" +
	"\x13InteractionSeverity\x12$\n" +
	" INTERACTION_SEVERITY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aINTERACTION_SEVERITY_MINOR\x10\x01\x12!\n" +
	"\x1dINTERACTION_SEVERITY_MODERATE\x10\x02\x12\x1e\n" +
	"\x1aINTERACTION_SEVERITY_MAJOR\x10\x03\x12(\n" +
	"$INTERACTION_SEVERITY_CONTRAINDICATED\x10\x04*\x81\x01\n" +
	"\rAlertSeverity\x12\x1e\n" +
	"\x1aALERT_SEVERITY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ALERT_SEVERITY_INFO\x10\x01\x12\x1a\n" +
	"\x16ALERT_SEVERITY_WARNING\x10\x02\x12\x1b\n" +
	"\x17ALERT_SEVERITY_CRITICAL\x10\x03*\x95\x01\n" +
	"\x18ContraindicationSeverity\x12)\n" +
	"%CONTRAINDICATION_SEVERITY_UNSPECIFIED\x10\x00\x12&\n" +
	"\"CONTRAINDICATION_SEVERITY_RELATIVE\x10\x01\x12&\n" +
	"\"CONTRAINDICATION_SEVERITY_ABSOLUTE\x10\x02*\x94\x01\n" +
	"\x0fCAEHealthStatus\x12!\n" +
	"\x1dCAE_HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CAE_HEALTH_STATUS_HEALTHY\x10\x01\x12\x1f\n" +
	"\x1bCAE_HEALTH_STATUS_UNHEALTHY\x10\x02\x12\x1e\n" +
	"\x1aCAE_HEALTH_STATUS_DEGRADED\x10\x03*\xb5\x01\n" +
	"\n" +
	"UpdateType\x12\x1b\n" +
	"\x17UPDATE_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bUPDATE_TYPE_ASSERTION_ADDED\x10\x01\x12!\n" +
	"\x1dUPDATE_TYPE_ASSERTION_UPDATED\x10\x02\x12!\n" +
	"\x1dUPDATE_TYPE_ASSERTION_REMOVED\x10\x03\x12#\n" +
	"\x1fUPDATE_TYPE_PROCESSING_COMPLETE\x10\x042\xd4\x05\n" +
	"\x18ClinicalReasoningService\x12s\n" +
	"\x12GenerateAssertions\x12-.clinical_hub.cae.v1.ClinicalAssertionRequest\x1a..clinical_hub.cae.v1.ClinicalAssertionResponse\x12\x84\x01\n" +
	"\x1bCheckMedicationInteractions\x121.clinical_hub.cae.v1.MedicationInteractionRequest\x1a2.clinical_hub.cae.v1.MedicationInteractionResponse\x12p\n" +
	"\x0fCalculateDosing\x12-.clinical_hub.cae.v1.DosingCalculationRequest\x1a..clinical_hub.cae.v1.DosingCalculationResponse\x12u\n" +
	"\x16CheckContraindications\x12,.clinical_hub.cae.v1.ContraindicationRequest\x1a-.clinical_hub.cae.v1.ContraindicationResponse\x12`\n" +
	"\vHealthCheck\x12'.clinical_hub.cae.v1.HealthCheckRequest\x1a(.clinical_hub.cae.v1.HealthCheckResponse\x12q\n" +
	"\x10StreamAssertions\x12-.clinical_hub.cae.v1.ClinicalAssertionRequest\x1a,.clinical_hub.cae.v1.ClinicalAssertionUpdate0\x01B\x1fZ\x1dsafety-gateway-platform/protob\x06proto3"

var (
	file_proto_clinical_reasoning_proto_rawDescOnce sync.Once
	file_proto_clinical_reasoning_proto_rawDescData []byte
)

func file_proto_clinical_reasoning_proto_rawDescGZIP() []byte {
	file_proto_clinical_reasoning_proto_rawDescOnce.Do(func() {
		file_proto_clinical_reasoning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_clinical_reasoning_proto_rawDesc), len(file_proto_clinical_reasoning_proto_rawDesc)))
	})
	return file_proto_clinical_reasoning_proto_rawDescData
}

var file_proto_clinical_reasoning_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_proto_clinical_reasoning_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_clinical_reasoning_proto_goTypes = []any{
	(AssertionPriority)(0),                // 0: clinical_hub.cae.v1.AssertionPriority
	(AssertionSeverity)(0),                // 1: clinical_hub.cae.v1.AssertionSeverity
	(InteractionSeverity)(0),              // 2: clinical_hub.cae.v1.InteractionSeverity
	(AlertSeverity)(0),                    // 3: clinical_hub.cae.v1.AlertSeverity
	(ContraindicationSeverity)(0),         // 4: clinical_hub.cae.v1.ContraindicationSeverity
	(CAEHealthStatus)(0),                  // 5: clinical_hub.cae.v1.CAEHealthStatus
	(UpdateType)(0),                       // 6: clinical_hub.cae.v1.UpdateType
	(*ClinicalAssertionRequest)(nil),      // 7: clinical_hub.cae.v1.ClinicalAssertionRequest
	(*ClinicalAssertionResponse)(nil),     // 8: clinical_hub.cae.v1.ClinicalAssertionResponse
	(*ClinicalAssertion)(nil),             // 9: clinical_hub.cae.v1.ClinicalAssertion
	(*AssertionMetadata)(nil),             // 10: clinical_hub.cae.v1.AssertionMetadata
	(*MedicationInteractionRequest)(nil),  // 11: clinical_hub.cae.v1.MedicationInteractionRequest
	(*MedicationInteractionResponse)(nil), // 12: clinical_hub.cae.v1.MedicationInteractionResponse
	(*MedicationInteraction)(nil),         // 13: clinical_hub.cae.v1.MedicationInteraction
	(*DosingCalculationRequest)(nil),      // 14: clinical_hub.cae.v1.DosingCalculationRequest
	(*DosingCalculationResponse)(nil),     // 15: clinical_hub.cae.v1.DosingCalculationResponse
	(*DosingRecommendation)(nil),          // 16: clinical_hub.cae.v1.DosingRecommendation
	(*DosingAlert)(nil),                   // 17: clinical_hub.cae.v1.DosingAlert
	(*ContraindicationRequest)(nil),       // 18: clinical_hub.cae.v1.ContraindicationRequest
	(*ContraindicationResponse)(nil),      // 19: clinical_hub.cae.v1.ContraindicationResponse
	(*Contraindication)(nil),              // 20: clinical_hub.cae.v1.Contraindication
	(*HealthCheckRequest)(nil),            // 21: clinical_hub.cae.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),           // 22: clinical_hub.cae.v1.HealthCheckResponse
	(*ClinicalAssertionUpdate)(nil),       // 23: clinical_hub.cae.v1.ClinicalAssertionUpdate
	(*structpb.Struct)(nil),               // 24: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),         // 25: google.protobuf.Timestamp
}
var file_proto_clinical_reasoning_proto_depIdxs = []int32{
	24, // 0: clinical_hub.cae.v1.ClinicalAssertionRequest.patient_context:type_name -> google.protobuf.Struct
	0,  // 1: clinical_hub.cae.v1.ClinicalAssertionRequest.priority:type_name -> clinical_hub.cae.v1.AssertionPriority
	9,  // 2: clinical_hub.cae.v1.ClinicalAssertionResponse.assertions:type_name -> clinical_hub.cae.v1.ClinicalAssertion
	10, // 3: clinical_hub.cae.v1.ClinicalAssertionResponse.metadata:type_name -> clinical_hub.cae.v1.AssertionMetadata
	25, // 4: clinical_hub.cae.v1.ClinicalAssertionResponse.generated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: clinical_hub.cae.v1.ClinicalAssertion.severity:type_name -> clinical_hub.cae.v1.AssertionSeverity
	24, // 6: clinical_hub.cae.v1.ClinicalAssertion.evidence:type_name -> google.protobuf.Struct
	24, // 7: clinical_hub.cae.v1.ClinicalAssertion.metadata:type_name -> google.protobuf.Struct
	24, // 8: clinical_hub.cae.v1.MedicationInteractionRequest.patient_context:type_name -> google.protobuf.Struct
	13, // 9: clinical_hub.cae.v1.MedicationInteractionResponse.interactions:type_name -> clinical_hub.cae.v1.MedicationInteraction
	10, // 10: clinical_hub.cae.v1.MedicationInteractionResponse.metadata:type_name -> clinical_hub.cae.v1.AssertionMetadata
	2,  // 11: clinical_hub.cae.v1.MedicationInteraction.severity:type_name -> clinical_hub.cae.v1.InteractionSeverity
	24, // 12: clinical_hub.cae.v1.MedicationInteraction.evidence:type_name -> google.protobuf.Struct
	24, // 13: clinical_hub.cae.v1.DosingCalculationRequest.patient_context:type_name -> google.protobuf.Struct
	16, // 14: clinical_hub.cae.v1.DosingCalculationResponse.recommendation:type_name -> clinical_hub.cae.v1.DosingRecommendation
	17, // 15: clinical_hub.cae.v1.DosingCalculationResponse.alerts:type_name -> clinical_hub.cae.v1.DosingAlert
	10, // 16: clinical_hub.cae.v1.DosingCalculationResponse.metadata:type_name -> clinical_hub.cae.v1.AssertionMetadata
	24, // 17: clinical_hub.cae.v1.DosingRecommendation.rationale:type_name -> google.protobuf.Struct
	3,  // 18: clinical_hub.cae.v1.DosingAlert.severity:type_name -> clinical_hub.cae.v1.AlertSeverity
	24, // 19: clinical_hub.cae.v1.ContraindicationRequest.patient_context:type_name -> google.protobuf.Struct
	20, // 20: clinical_hub.cae.v1.ContraindicationResponse.contraindications:type_name -> clinical_hub.cae.v1.Contraindication
	10, // 21: clinical_hub.cae.v1.ContraindicationResponse.metadata:type_name -> clinical_hub.cae.v1.AssertionMetadata
	4,  // 22: clinical_hub.cae.v1.Contraindication.severity:type_name -> clinical_hub.cae.v1.ContraindicationSeverity
	24, // 23: clinical_hub.cae.v1.Contraindication.evidence:type_name -> google.protobuf.Struct
	5,  // 24: clinical_hub.cae.v1.HealthCheckResponse.status:type_name -> clinical_hub.cae.v1.CAEHealthStatus
	24, // 25: clinical_hub.cae.v1.HealthCheckResponse.details:type_name -> google.protobuf.Struct
	6,  // 26: clinical_hub.cae.v1.ClinicalAssertionUpdate.update_type:type_name -> clinical_hub.cae.v1.UpdateType
	9,  // 27: clinical_hub.cae.v1.ClinicalAssertionUpdate.assertion:type_name -> clinical_hub.cae.v1.ClinicalAssertion
	25, // 28: clinical_hub.cae.v1.ClinicalAssertionUpdate.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 29: clinical_hub.cae.v1.ClinicalReasoningService.GenerateAssertions:input_type -> clinical_hub.cae.v1.ClinicalAssertionRequest
	11, // 30: clinical_hub.cae.v1.ClinicalReasoningService.CheckMedicationInteractions:input_type -> clinical_hub.cae.v1.MedicationInteractionRequest
	14, // 31: clinical_hub.cae.v1.ClinicalReasoningService.CalculateDosing:input_type -> clinical_hub.cae.v1.DosingCalculationRequest
	18, // 32: clinical_hub.cae.v1.ClinicalReasoningService.CheckContraindications:input_type -> clinical_hub.cae.v1.ContraindicationRequest
	21, // 33: clinical_hub.cae.v1.ClinicalReasoningService.HealthCheck:input_type -> clinical_hub.cae.v1.HealthCheckRequest
	7,  // 34: clinical_hub.cae.v1.ClinicalReasoningService.StreamAssertions:input_type -> clinical_hub.cae.v1.ClinicalAssertionRequest
	8,  // 35: clinical_hub.cae.v1.ClinicalReasoningService.GenerateAssertions:output_type -> clinical_hub.cae.v1.ClinicalAssertionResponse
	12, // 36: clinical_hub.cae.v1.ClinicalReasoningService.CheckMedicationInteractions:output_type -> clinical_hub.cae.v1.MedicationInteractionResponse
	15, // 37: clinical_hub.cae.v1.ClinicalReasoningService.CalculateDosing:output_type -> clinical_hub.cae.v1.DosingCalculationResponse
	19, // 38: clinical_hub.cae.v1.ClinicalReasoningService.CheckContraindications:output_type -> clinical_hub.cae.v1.ContraindicationResponse
	22, // 39: clinical_hub.cae.v1.ClinicalReasoningService.HealthCheck:output_type -> clinical_hub.cae.v1.HealthCheckResponse
	23, // 40: clinical_hub.cae.v1.ClinicalReasoningService.StreamAssertions:output_type -> clinical_hub.cae.v1.ClinicalAssertionUpdate
	35, // [35:41] is the sub-list for method output_type
	29, // [29:35] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_proto_clinical_reasoning_proto_init() }
func file_proto_clinical_reasoning_proto_init() {
	if File_proto_clinical_reasoning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_clinical_reasoning_proto_rawDesc), len(file_proto_clinical_reasoning_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_clinical_reasoning_proto_goTypes,
		DependencyIndexes: file_proto_clinical_reasoning_proto_depIdxs,
		EnumInfos:         file_proto_clinical_reasoning_proto_enumTypes,
		MessageInfos:      file_proto_clinical_reasoning_proto_msgTypes,
	}.Build()
	File_proto_clinical_reasoning_proto = out.File
	file_proto_clinical_reasoning_proto_goTypes = nil
	file_proto_clinical_reasoning_proto_depIdxs = nil
}
