// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: proto/safety_gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Safety status enumeration
type SafetyStatus int32

const (
	SafetyStatus_SAFETY_STATUS_UNSPECIFIED   SafetyStatus = 0
	SafetyStatus_SAFETY_STATUS_SAFE          SafetyStatus = 1
	SafetyStatus_SAFETY_STATUS_UNSAFE        SafetyStatus = 2
	SafetyStatus_SAFETY_STATUS_WARNING       SafetyStatus = 3
	SafetyStatus_SAFETY_STATUS_MANUAL_REVIEW SafetyStatus = 4
	SafetyStatus_SAFETY_STATUS_ERROR         SafetyStatus = 5
)

// Enum value maps for SafetyStatus.
var (
	SafetyStatus_name = map[int32]string{
		0: "SAFETY_STATUS_UNSPECIFIED",
		1: "SAFETY_STATUS_SAFE",
		2: "SAFETY_STATUS_UNSAFE",
		3: "SAFETY_STATUS_WARNING",
		4: "SAFETY_STATUS_MANUAL_REVIEW",
		5: "SAFETY_STATUS_ERROR",
	}
	SafetyStatus_value = map[string]int32{
		"SAFETY_STATUS_UNSPECIFIED":   0,
		"SAFETY_STATUS_SAFE":          1,
		"SAFETY_STATUS_UNSAFE":        2,
		"SAFETY_STATUS_WARNING":       3,
		"SAFETY_STATUS_MANUAL_REVIEW": 4,
		"SAFETY_STATUS_ERROR":         5,
	}
)

func (x SafetyStatus) Enum() *SafetyStatus {
	p := new(SafetyStatus)
	*p = x
	return p
}

func (x SafetyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SafetyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_safety_gateway_proto_enumTypes[0].Descriptor()
}

func (SafetyStatus) Type() protoreflect.EnumType {
	return &file_proto_safety_gateway_proto_enumTypes[0]
}

func (x SafetyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SafetyStatus.Descriptor instead.
func (SafetyStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{0}
}

// Explanation level
type ExplanationLevel int32

const (
	ExplanationLevel_EXPLANATION_LEVEL_UNSPECIFIED ExplanationLevel = 0
	ExplanationLevel_EXPLANATION_LEVEL_BASIC       ExplanationLevel = 1
	ExplanationLevel_EXPLANATION_LEVEL_DETAILED    ExplanationLevel = 2
	ExplanationLevel_EXPLANATION_LEVEL_EXPERT      ExplanationLevel = 3
)

// Enum value maps for ExplanationLevel.
var (
	ExplanationLevel_name = map[int32]string{
		0: "EXPLANATION_LEVEL_UNSPECIFIED",
		1: "EXPLANATION_LEVEL_BASIC",
		2: "EXPLANATION_LEVEL_DETAILED",
		3: "EXPLANATION_LEVEL_EXPERT",
	}
	ExplanationLevel_value = map[string]int32{
		"EXPLANATION_LEVEL_UNSPECIFIED": 0,
		"EXPLANATION_LEVEL_BASIC":       1,
		"EXPLANATION_LEVEL_DETAILED":    2,
		"EXPLANATION_LEVEL_EXPERT":      3,
	}
)

func (x ExplanationLevel) Enum() *ExplanationLevel {
	p := new(ExplanationLevel)
	*p = x
	return p
}

func (x ExplanationLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExplanationLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_safety_gateway_proto_enumTypes[1].Descriptor()
}

func (ExplanationLevel) Type() protoreflect.EnumType {
	return &file_proto_safety_gateway_proto_enumTypes[1]
}

func (x ExplanationLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExplanationLevel.Descriptor instead.
func (ExplanationLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{1}
}

// Override level
type OverrideLevel int32

const (
	OverrideLevel_OVERRIDE_LEVEL_UNSPECIFIED OverrideLevel = 0
	OverrideLevel_OVERRIDE_LEVEL_RESIDENT    OverrideLevel = 1
	OverrideLevel_OVERRIDE_LEVEL_ATTENDING   OverrideLevel = 2
	OverrideLevel_OVERRIDE_LEVEL_PHARMACIST  OverrideLevel = 3
	OverrideLevel_OVERRIDE_LEVEL_CHIEF       OverrideLevel = 4
)

// Enum value maps for OverrideLevel.
var (
	OverrideLevel_name = map[int32]string{
		0: "OVERRIDE_LEVEL_UNSPECIFIED",
		1: "OVERRIDE_LEVEL_RESIDENT",
		2: "OVERRIDE_LEVEL_ATTENDING",
		3: "OVERRIDE_LEVEL_PHARMACIST",
		4: "OVERRIDE_LEVEL_CHIEF",
	}
	OverrideLevel_value = map[string]int32{
		"OVERRIDE_LEVEL_UNSPECIFIED": 0,
		"OVERRIDE_LEVEL_RESIDENT":    1,
		"OVERRIDE_LEVEL_ATTENDING":   2,
		"OVERRIDE_LEVEL_PHARMACIST":  3,
		"OVERRIDE_LEVEL_CHIEF":       4,
	}
)

func (x OverrideLevel) Enum() *OverrideLevel {
	p := new(OverrideLevel)
	*p = x
	return p
}

func (x OverrideLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OverrideLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_safety_gateway_proto_enumTypes[2].Descriptor()
}

func (OverrideLevel) Type() protoreflect.EnumType {
	return &file_proto_safety_gateway_proto_enumTypes[2]
}

func (x OverrideLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OverrideLevel.Descriptor instead.
func (OverrideLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{2}
}

// Engine status
type EngineStatus int32

const (
	EngineStatus_ENGINE_STATUS_UNSPECIFIED EngineStatus = 0
	EngineStatus_ENGINE_STATUS_HEALTHY     EngineStatus = 1
	EngineStatus_ENGINE_STATUS_DEGRADED    EngineStatus = 2
	EngineStatus_ENGINE_STATUS_UNHEALTHY   EngineStatus = 3
)

// Enum value maps for EngineStatus.
var (
	EngineStatus_name = map[int32]string{
		0: "ENGINE_STATUS_UNSPECIFIED",
		1: "ENGINE_STATUS_HEALTHY",
		2: "ENGINE_STATUS_DEGRADED",
		3: "ENGINE_STATUS_UNHEALTHY",
	}
	EngineStatus_value = map[string]int32{
		"ENGINE_STATUS_UNSPECIFIED": 0,
		"ENGINE_STATUS_HEALTHY":     1,
		"ENGINE_STATUS_DEGRADED":    2,
		"ENGINE_STATUS_UNHEALTHY":   3,
	}
)

func (x EngineStatus) Enum() *EngineStatus {
	p := new(EngineStatus)
	*p = x
	return p
}

func (x EngineStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EngineStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_safety_gateway_proto_enumTypes[3].Descriptor()
}

func (EngineStatus) Type() protoreflect.EnumType {
	return &file_proto_safety_gateway_proto_enumTypes[3]
}

func (x EngineStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EngineStatus.Descriptor instead.
func (EngineStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{3}
}

// Health status
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_UNHEALTHY":   3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_safety_gateway_proto_enumTypes[4].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_proto_safety_gateway_proto_enumTypes[4]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{4}
}

// Safety validation request
type SafetyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ClinicianId   string                 `protobuf:"bytes,3,opt,name=clinician_id,json=clinicianId,proto3" json:"clinician_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	MedicationIds []string               `protobuf:"bytes,6,rep,name=medication_ids,json=medicationIds,proto3" json:"medication_ids,omitempty"`
	ConditionIds  []string               `protobuf:"bytes,7,rep,name=condition_ids,json=conditionIds,proto3" json:"condition_ids,omitempty"`
	AllergyIds    []string               `protobuf:"bytes,8,rep,name=allergy_ids,json=allergyIds,proto3" json:"allergy_ids,omitempty"`
	Context       map[string]string      `protobuf:"bytes,9,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SafetyRequest) Reset() {
	*x = SafetyRequest{}
	mi := &file_proto_safety_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafetyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafetyRequest) ProtoMessage() {}

func (x *SafetyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafetyRequest.ProtoReflect.Descriptor instead.
func (*SafetyRequest) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *SafetyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SafetyRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *SafetyRequest) GetClinicianId() string {
	if x != nil {
		return x.ClinicianId
	}
	return ""
}

func (x *SafetyRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *SafetyRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *SafetyRequest) GetMedicationIds() []string {
	if x != nil {
		return x.MedicationIds
	}
	return nil
}

func (x *SafetyRequest) GetConditionIds() []string {
	if x != nil {
		return x.ConditionIds
	}
	return nil
}

func (x *SafetyRequest) GetAllergyIds() []string {
	if x != nil {
		return x.AllergyIds
	}
	return nil
}

func (x *SafetyRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SafetyRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SafetyRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// Safety validation response
type SafetyResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestId          string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status             SafetyStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=safety_gateway.SafetyStatus" json:"status,omitempty"`
	RiskScore          float64                `protobuf:"fixed64,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	CriticalViolations []string               `protobuf:"bytes,4,rep,name=critical_violations,json=criticalViolations,proto3" json:"critical_violations,omitempty"`
	Warnings           []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	EngineResults      []*EngineResult        `protobuf:"bytes,6,rep,name=engine_results,json=engineResults,proto3" json:"engine_results,omitempty"`
	EnginesFailed      []string               `protobuf:"bytes,7,rep,name=engines_failed,json=enginesFailed,proto3" json:"engines_failed,omitempty"`
	Explanation        *Explanation           `protobuf:"bytes,8,opt,name=explanation,proto3" json:"explanation,omitempty"`
	OverrideToken      *OverrideToken         `protobuf:"bytes,9,opt,name=override_token,json=overrideToken,proto3" json:"override_token,omitempty"`
	ProcessingTimeMs   int64                  `protobuf:"varint,10,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	ContextVersion     string                 `protobuf:"bytes,11,opt,name=context_version,json=contextVersion,proto3" json:"context_version,omitempty"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SafetyResponse) Reset() {
	*x = SafetyResponse{}
	mi := &file_proto_safety_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafetyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafetyResponse) ProtoMessage() {}

func (x *SafetyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafetyResponse.ProtoReflect.Descriptor instead.
func (*SafetyResponse) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *SafetyResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SafetyResponse) GetStatus() SafetyStatus {
	if x != nil {
		return x.Status
	}
	return SafetyStatus_SAFETY_STATUS_UNSPECIFIED
}

func (x *SafetyResponse) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *SafetyResponse) GetCriticalViolations() []string {
	if x != nil {
		return x.CriticalViolations
	}
	return nil
}

func (x *SafetyResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *SafetyResponse) GetEngineResults() []*EngineResult {
	if x != nil {
		return x.EngineResults
	}
	return nil
}

func (x *SafetyResponse) GetEnginesFailed() []string {
	if x != nil {
		return x.EnginesFailed
	}
	return nil
}

func (x *SafetyResponse) GetExplanation() *Explanation {
	if x != nil {
		return x.Explanation
	}
	return nil
}

func (x *SafetyResponse) GetOverrideToken() *OverrideToken {
	if x != nil {
		return x.OverrideToken
	}
	return nil
}

func (x *SafetyResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *SafetyResponse) GetContextVersion() string {
	if x != nil {
		return x.ContextVersion
	}
	return ""
}

func (x *SafetyResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SafetyResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Engine result
type EngineResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EngineId      string                 `protobuf:"bytes,1,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`
	EngineName    string                 `protobuf:"bytes,2,opt,name=engine_name,json=engineName,proto3" json:"engine_name,omitempty"`
	Status        SafetyStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=safety_gateway.SafetyStatus" json:"status,omitempty"`
	RiskScore     float64                `protobuf:"fixed64,4,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Violations    []string               `protobuf:"bytes,5,rep,name=violations,proto3" json:"violations,omitempty"`
	Warnings      []string               `protobuf:"bytes,6,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Confidence    float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	DurationMs    int64                  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Tier          int32                  `protobuf:"varint,9,opt,name=tier,proto3" json:"tier,omitempty"`
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineResult) Reset() {
	*x = EngineResult{}
	mi := &file_proto_safety_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineResult) ProtoMessage() {}

func (x *EngineResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineResult.ProtoReflect.Descriptor instead.
func (*EngineResult) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *EngineResult) GetEngineId() string {
	if x != nil {
		return x.EngineId
	}
	return ""
}

func (x *EngineResult) GetEngineName() string {
	if x != nil {
		return x.EngineName
	}
	return ""
}

func (x *EngineResult) GetStatus() SafetyStatus {
	if x != nil {
		return x.Status
	}
	return SafetyStatus_SAFETY_STATUS_UNSPECIFIED
}

func (x *EngineResult) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *EngineResult) GetViolations() []string {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *EngineResult) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *EngineResult) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *EngineResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *EngineResult) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *EngineResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EngineResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Explanation
type Explanation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         ExplanationLevel       `protobuf:"varint,1,opt,name=level,proto3,enum=safety_gateway.ExplanationLevel" json:"level,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Details       []*ExplanationDetail   `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Evidence      []*Evidence            `protobuf:"bytes,5,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Actionable    []*ActionableGuidance  `protobuf:"bytes,6,rep,name=actionable,proto3" json:"actionable,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Explanation) Reset() {
	*x = Explanation{}
	mi := &file_proto_safety_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Explanation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Explanation) ProtoMessage() {}

func (x *Explanation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Explanation.ProtoReflect.Descriptor instead.
func (*Explanation) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *Explanation) GetLevel() ExplanationLevel {
	if x != nil {
		return x.Level
	}
	return ExplanationLevel_EXPLANATION_LEVEL_UNSPECIFIED
}

func (x *Explanation) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Explanation) GetDetails() []*ExplanationDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Explanation) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Explanation) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Explanation) GetActionable() []*ActionableGuidance {
	if x != nil {
		return x.Actionable
	}
	return nil
}

func (x *Explanation) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

// Explanation detail
type ExplanationDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Category          string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Severity          string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ClinicalRationale string                 `protobuf:"bytes,4,opt,name=clinical_rationale,json=clinicalRationale,proto3" json:"clinical_rationale,omitempty"`
	Confidence        float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	EngineSource      string                 `protobuf:"bytes,6,opt,name=engine_source,json=engineSource,proto3" json:"engine_source,omitempty"`
	RecommendedAction string                 `protobuf:"bytes,7,opt,name=recommended_action,json=recommendedAction,proto3" json:"recommended_action,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExplanationDetail) Reset() {
	*x = ExplanationDetail{}
	mi := &file_proto_safety_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplanationDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplanationDetail) ProtoMessage() {}

func (x *ExplanationDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplanationDetail.ProtoReflect.Descriptor instead.
func (*ExplanationDetail) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ExplanationDetail) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ExplanationDetail) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ExplanationDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExplanationDetail) GetClinicalRationale() string {
	if x != nil {
		return x.ClinicalRationale
	}
	return ""
}

func (x *ExplanationDetail) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ExplanationDetail) GetEngineSource() string {
	if x != nil {
		return x.EngineSource
	}
	return ""
}

func (x *ExplanationDetail) GetRecommendedAction() string {
	if x != nil {
		return x.RecommendedAction
	}
	return ""
}

// Evidence
type Evidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Strength      string                 `protobuf:"bytes,4,opt,name=strength,proto3" json:"strength,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_proto_safety_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *Evidence) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Evidence) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Evidence) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Evidence) GetStrength() string {
	if x != nil {
		return x.Strength
	}
	return ""
}

func (x *Evidence) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Evidence) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Actionable guidance
type ActionableGuidance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Priority      string                 `protobuf:"bytes,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Steps         []string               `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	Monitoring    []string               `protobuf:"bytes,4,rep,name=monitoring,proto3" json:"monitoring,omitempty"`
	Timeline      string                 `protobuf:"bytes,5,opt,name=timeline,proto3" json:"timeline,omitempty"`
	Responsible   string                 `protobuf:"bytes,6,opt,name=responsible,proto3" json:"responsible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionableGuidance) Reset() {
	*x = ActionableGuidance{}
	mi := &file_proto_safety_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionableGuidance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionableGuidance) ProtoMessage() {}

func (x *ActionableGuidance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionableGuidance.ProtoReflect.Descriptor instead.
func (*ActionableGuidance) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *ActionableGuidance) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionableGuidance) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *ActionableGuidance) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *ActionableGuidance) GetMonitoring() []string {
	if x != nil {
		return x.Monitoring
	}
	return nil
}

func (x *ActionableGuidance) GetTimeline() string {
	if x != nil {
		return x.Timeline
	}
	return ""
}

func (x *ActionableGuidance) GetResponsible() string {
	if x != nil {
		return x.Responsible
	}
	return ""
}

// Override token
type OverrideToken struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TokenId         string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	RequestId       string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PatientId       string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DecisionSummary *DecisionSummary       `protobuf:"bytes,4,opt,name=decision_summary,json=decisionSummary,proto3" json:"decision_summary,omitempty"`
	RequiredLevel   OverrideLevel          `protobuf:"varint,5,opt,name=required_level,json=requiredLevel,proto3,enum=safety_gateway.OverrideLevel" json:"required_level,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ContextHash     string                 `protobuf:"bytes,7,opt,name=context_hash,json=contextHash,proto3" json:"context_hash,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Signature       string                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OverrideToken) Reset() {
	*x = OverrideToken{}
	mi := &file_proto_safety_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideToken) ProtoMessage() {}

func (x *OverrideToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideToken.ProtoReflect.Descriptor instead.
func (*OverrideToken) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *OverrideToken) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *OverrideToken) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OverrideToken) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *OverrideToken) GetDecisionSummary() *DecisionSummary {
	if x != nil {
		return x.DecisionSummary
	}
	return nil
}

func (x *OverrideToken) GetRequiredLevel() OverrideLevel {
	if x != nil {
		return x.RequiredLevel
	}
	return OverrideLevel_OVERRIDE_LEVEL_UNSPECIFIED
}

func (x *OverrideToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *OverrideToken) GetContextHash() string {
	if x != nil {
		return x.ContextHash
	}
	return ""
}

func (x *OverrideToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OverrideToken) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// Decision summary
type DecisionSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             SafetyStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=safety_gateway.SafetyStatus" json:"status,omitempty"`
	CriticalViolations []string               `protobuf:"bytes,2,rep,name=critical_violations,json=criticalViolations,proto3" json:"critical_violations,omitempty"`
	EnginesFailed      []string               `protobuf:"bytes,3,rep,name=engines_failed,json=enginesFailed,proto3" json:"engines_failed,omitempty"`
	RiskScore          float64                `protobuf:"fixed64,4,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Explanation        string                 `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DecisionSummary) Reset() {
	*x = DecisionSummary{}
	mi := &file_proto_safety_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionSummary) ProtoMessage() {}

func (x *DecisionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionSummary.ProtoReflect.Descriptor instead.
func (*DecisionSummary) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *DecisionSummary) GetStatus() SafetyStatus {
	if x != nil {
		return x.Status
	}
	return SafetyStatus_SAFETY_STATUS_UNSPECIFIED
}

func (x *DecisionSummary) GetCriticalViolations() []string {
	if x != nil {
		return x.CriticalViolations
	}
	return nil
}

func (x *DecisionSummary) GetEnginesFailed() []string {
	if x != nil {
		return x.EnginesFailed
	}
	return nil
}

func (x *DecisionSummary) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *DecisionSummary) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

// Engine status request
type EngineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EngineId      string                 `protobuf:"bytes,1,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"` // Optional: specific engine, empty for all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineStatusRequest) Reset() {
	*x = EngineStatusRequest{}
	mi := &file_proto_safety_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineStatusRequest) ProtoMessage() {}

func (x *EngineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineStatusRequest.ProtoReflect.Descriptor instead.
func (*EngineStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *EngineStatusRequest) GetEngineId() string {
	if x != nil {
		return x.EngineId
	}
	return ""
}

// Engine status response
type EngineStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engines       []*EngineInfo          `protobuf:"bytes,1,rep,name=engines,proto3" json:"engines,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineStatusResponse) Reset() {
	*x = EngineStatusResponse{}
	mi := &file_proto_safety_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineStatusResponse) ProtoMessage() {}

func (x *EngineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineStatusResponse.ProtoReflect.Descriptor instead.
func (*EngineStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *EngineStatusResponse) GetEngines() []*EngineInfo {
	if x != nil {
		return x.Engines
	}
	return nil
}

func (x *EngineStatusResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Engine information
type EngineInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Tier          int32                  `protobuf:"varint,4,opt,name=tier,proto3" json:"tier,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Status        EngineStatus           `protobuf:"varint,7,opt,name=status,proto3,enum=safety_gateway.EngineStatus" json:"status,omitempty"`
	LastCheck     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	FailureCount  int32                  `protobuf:"varint,9,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineInfo) Reset() {
	*x = EngineInfo{}
	mi := &file_proto_safety_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineInfo) ProtoMessage() {}

func (x *EngineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineInfo.ProtoReflect.Descriptor instead.
func (*EngineInfo) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *EngineInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EngineInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EngineInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *EngineInfo) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *EngineInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *EngineInfo) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *EngineInfo) GetStatus() EngineStatus {
	if x != nil {
		return x.Status
	}
	return EngineStatus_ENGINE_STATUS_UNSPECIFIED
}

func (x *EngineInfo) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

func (x *EngineInfo) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *EngineInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Override validation request
type OverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	ClinicianId   string                 `protobuf:"bytes,2,opt,name=clinician_id,json=clinicianId,proto3" json:"clinician_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideRequest) Reset() {
	*x = OverrideRequest{}
	mi := &file_proto_safety_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideRequest) ProtoMessage() {}

func (x *OverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideRequest.ProtoReflect.Descriptor instead.
func (*OverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *OverrideRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *OverrideRequest) GetClinicianId() string {
	if x != nil {
		return x.ClinicianId
	}
	return ""
}

func (x *OverrideRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Override validation response
type OverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Token         *OverrideToken         `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	ClinicianId   string                 `protobuf:"bytes,4,opt,name=clinician_id,json=clinicianId,proto3" json:"clinician_id,omitempty"`
	ValidatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=validated_at,json=validatedAt,proto3" json:"validated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideResponse) Reset() {
	*x = OverrideResponse{}
	mi := &file_proto_safety_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideResponse) ProtoMessage() {}

func (x *OverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideResponse.ProtoReflect.Descriptor instead.
func (*OverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *OverrideResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *OverrideResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OverrideResponse) GetToken() *OverrideToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *OverrideResponse) GetClinicianId() string {
	if x != nil {
		return x.ClinicianId
	}
	return ""
}

func (x *OverrideResponse) GetValidatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidatedAt
	}
	return nil
}

// Health check request
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detailed      bool                   `protobuf:"varint,1,opt,name=detailed,proto3" json:"detailed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_safety_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *HealthRequest) GetDetailed() bool {
	if x != nil {
		return x.Detailed
	}
	return false
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=safety_gateway.HealthStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_safety_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_safety_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_safety_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_safety_gateway_proto protoreflect.FileDescriptor

const file_proto_safety_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/safety_gateway.proto\x12\x0esafety_gateway\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x03\n" +
	"\rSafetyRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12!\n" +
	"\fclinician_id\x18\x03 \x01(\tR\vclinicianId\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\tR\n" +
	"actionType\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12%\n" +
	"\x0emedication_ids\x18\x06 \x03(\tR\rmedicationIds\x12#\n" +
	"\rcondition_ids\x18\a \x03(\tR\fconditionIds\x12\x1f\n" +
	"\vallergy_ids\x18\b \x03(\tR\n" +
	"allergyIds\x12D\n" +
	"\acontext\x18\t \x03(\v2*.safety_gateway.SafetyRequest.ContextEntryR\acontext\x128\n" +
	"\ttimestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06source\x18\v \x01(\tR\x06source\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x05\n" +
	"\x0eSafetyResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.safety_gateway.SafetyStatusR\x06status\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x01R\triskScore\x12/\n" +
	"\x13critical_violations\x18\x04 \x03(\tR\x12criticalViolations\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\x12C\n" +
	"\x0eengine_results\x18\x06 \x03(\v2\x1c.safety_gateway.EngineResultR\rengineResults\x12%\n" +
	"\x0eengines_failed\x18\a \x03(\tR\renginesFailed\x12=\n" +
	"\vexplanation\x18\b \x01(\v2\x1b.safety_gateway.ExplanationR\vexplanation\x12D\n" +
	"\x0eoverride_token\x18\t \x01(\v2\x1d.safety_gateway.OverrideTokenR\roverrideToken\x12,\n" +
	"\x12processing_time_ms\x18\n" +
	" \x01(\x03R\x10processingTimeMs\x12'\n" +
	"\x0fcontext_version\x18\v \x01(\tR\x0econtextVersion\x128\n" +
	"\ttimestamp\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12H\n" +
	"\bmetadata\x18\r \x03(\v2,.safety_gateway.SafetyResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x03\n" +
	"\fEngineResult\x12\x1b\n" +
	"\tengine_id\x18\x01 \x01(\tR\bengineId\x12\x1f\n" +
	"\vengine_name\x18\x02 \x01(\tR\n" +
	"engineName\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.safety_gateway.SafetyStatusR\x06status\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x04 \x01(\x01R\triskScore\x12\x1e\n" +
	"\n" +
	"violations\x18\x05 \x03(\tR\n" +
	"violations\x12\x1a\n" +
	"\bwarnings\x18\x06 \x03(\tR\bwarnings\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x03R\n" +
	"durationMs\x12\x12\n" +
	"\x04tier\x18\t \x01(\x05R\x04tier\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12F\n" +
	"\bmetadata\x18\v \x03(\v2*.safety_gateway.EngineResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf5\x02\n" +
	"\vExplanation\x126\n" +
	"\x05level\x18\x01 \x01(\x0e2 .safety_gateway.ExplanationLevelR\x05level\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12;\n" +
	"\adetails\x18\x03 \x03(\v2!.safety_gateway.ExplanationDetailR\adetails\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x124\n" +
	"\bevidence\x18\x05 \x03(\v2\x18.safety_gateway.EvidenceR\bevidence\x12B\n" +
	"\n" +
	"actionable\x18\x06 \x03(\v2\".safety_gateway.ActionableGuidanceR\n" +
	"actionable\x12=\n" +
	"\fgenerated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"\x90\x02\n" +
	"\x11ExplanationDetail\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12-\n" +
	"\x12clinical_rationale\x18\x04 \x01(\tR\x11clinicalRationale\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12#\n" +
	"\rengine_source\x18\x06 \x01(\tR\fengineSource\x12-\n" +
	"\x12recommended_action\x18\a \x01(\tR\x11recommendedAction\"\x87\x02\n" +
	"\bEvidence\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bstrength\x18\x04 \x01(\tR\bstrength\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12B\n" +
	"\bmetadata\x18\x06 \x03(\v2&.safety_gateway.Evidence.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x01\n" +
	"\x12ActionableGuidance\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\tR\bpriority\x12\x14\n" +
	"\x05steps\x18\x03 \x03(\tR\x05steps\x12\x1e\n" +
	"\n" +
	"monitoring\x18\x04 \x03(\tR\n" +
	"monitoring\x12\x1a\n" +
	"\btimeline\x18\x05 \x01(\tR\btimeline\x12 \n" +
	"\vresponsible\x18\x06 \x01(\tR\vresponsible\"\xb1\x03\n" +
	"\rOverrideToken\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12J\n" +
	"\x10decision_summary\x18\x04 \x01(\v2\x1f.safety_gateway.DecisionSummaryR\x0fdecisionSummary\x12D\n" +
	"\x0erequired_level\x18\x05 \x01(\x0e2\x1d.safety_gateway.OverrideLevelR\rrequiredLevel\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12!\n" +
	"\fcontext_hash\x18\a \x01(\tR\vcontextHash\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1c\n" +
	"\tsignature\x18\t \x01(\tR\tsignature\"\xe0\x01\n" +
	"\x0fDecisionSummary\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.safety_gateway.SafetyStatusR\x06status\x12/\n" +
	"\x13critical_violations\x18\x02 \x03(\tR\x12criticalViolations\x12%\n" +
	"\x0eengines_failed\x18\x03 \x03(\tR\renginesFailed\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x04 \x01(\x01R\triskScore\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\"2\n" +
	"\x13EngineStatusRequest\x12\x1b\n" +
	"\tengine_id\x18\x01 \x01(\tR\bengineId\"\xd9\x01\n" +
	"\x14EngineStatusResponse\x124\n" +
	"\aengines\x18\x01 \x03(\v2\x1a.safety_gateway.EngineInfoR\aengines\x12N\n" +
	"\bmetadata\x18\x02 \x03(\v22.safety_gateway.EngineStatusResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x03\n" +
	"\n" +
	"EngineInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\x05R\x04tier\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x03R\ttimeoutMs\x124\n" +
	"\x06status\x18\a \x01(\x0e2\x1c.safety_gateway.EngineStatusR\x06status\x129\n" +
	"\n" +
	"last_check\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\x12#\n" +
	"\rfailure_count\x18\t \x01(\x05R\ffailureCount\x12D\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2(.safety_gateway.EngineInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x0fOverrideRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12!\n" +
	"\fclinician_id\x18\x02 \x01(\tR\vclinicianId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xd7\x01\n" +
	"\x10OverrideResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x123\n" +
	"\x05token\x18\x03 \x01(\v2\x1d.safety_gateway.OverrideTokenR\x05token\x12!\n" +
	"\fclinician_id\x18\x04 \x01(\tR\vclinicianId\x12=\n" +
	"\fvalidated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vvalidatedAt\"+\n" +
	"\rHealthRequest\x12\x1a\n" +
	"\bdetailed\x18\x01 \x01(\bR\bdetailed\"\x9d\x02\n" +
	"\x0eHealthResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.safety_gateway.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12E\n" +
	"\adetails\x18\x03 \x03(\v2+.safety_gateway.HealthResponse.DetailsEntryR\adetails\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xb4\x01\n" +
	"\fSafetyStatus\x12\x1d\n" +
	"\x19SAFETY_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SAFETY_STATUS_SAFE\x10\x01\x12\x18\n" +
	"\x14SAFETY_STATUS_UNSAFE\x10\x02\x12\x19\n" +
	"\x15SAFETY_STATUS_WARNING\x10\x03\x12\x1f\n" +
	"\x1bSAFETY_STATUS_MANUAL_REVIEW\x10\x04\x12\x17\n" +
	"\x13SAFETY_STATUS_ERROR\x10\x05*\x90\x01\n" +
	"\x10ExplanationLevel\x12!\n" +
	"\x1dEXPLANATION_LEVEL_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EXPLANATION_LEVEL_BASIC\x10\x01\x12\x1e\n" +
	"\x1aEXPLANATION_LEVEL_DETAILED\x10\x02\x12\x1c\n" +
	"\x18EXPLANATION_LEVEL_EXPERT\x10\x03*\xa3\x01\n" +
	"\rOverrideLevel\x12\x1e\n" +
	"\x1aOVERRIDE_LEVEL_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17OVERRIDE_LEVEL_RESIDENT\x10\x01\x12\x1c\n" +
	"\x18OVERRIDE_LEVEL_ATTENDING\x10\x02\x12\x1d\n" +
	"\x19OVERRIDE_LEVEL_PHARMACIST\x10\x03\x12\x18\n" +
	"\x14OVERRIDE_LEVEL_CHIEF\x10\x04*\x81\x01\n" +
	"\fEngineStatus\x12\x1d\n" +
	"\x19ENGINE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ENGINE_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16ENGINE_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17ENGINE_STATUS_UNHEALTHY\x10\x03*\x81\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x032\xe1\x02\n" +
	"\rSafetyGateway\x12O\n" +
	"\x0eValidateSafety\x12\x1d.safety_gateway.SafetyRequest\x1a\x1e.safety_gateway.SafetyResponse\x12\\\n" +
	"\x0fGetEngineStatus\x12#.safety_gateway.EngineStatusRequest\x1a$.safety_gateway.EngineStatusResponse\x12U\n" +
	"\x10ValidateOverride\x12\x1f.safety_gateway.OverrideRequest\x1a .safety_gateway.OverrideResponse\x12J\n" +
	"\tGetHealth\x12\x1d.safety_gateway.HealthRequest\x1a\x1e.safety_gateway.HealthResponseB\x1fZ\x1dsafety-gateway-platform/protob\x06proto3"

var (
	file_proto_safety_gateway_proto_rawDescOnce sync.Once
	file_proto_safety_gateway_proto_rawDescData []byte
)

func file_proto_safety_gateway_proto_rawDescGZIP() []byte {
	file_proto_safety_gateway_proto_rawDescOnce.Do(func() {
		file_proto_safety_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_safety_gateway_proto_rawDesc), len(file_proto_safety_gateway_proto_rawDesc)))
	})
	return file_proto_safety_gateway_proto_rawDescData
}

var file_proto_safety_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_safety_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_safety_gateway_proto_goTypes = []any{
	(SafetyStatus)(0),             // 0: safety_gateway.SafetyStatus
	(ExplanationLevel)(0),         // 1: safety_gateway.ExplanationLevel
	(OverrideLevel)(0),            // 2: safety_gateway.OverrideLevel
	(EngineStatus)(0),             // 3: safety_gateway.EngineStatus
	(HealthStatus)(0),             // 4: safety_gateway.HealthStatus
	(*SafetyRequest)(nil),         // 5: safety_gateway.SafetyRequest
	(*SafetyResponse)(nil),        // 6: safety_gateway.SafetyResponse
	(*EngineResult)(nil),          // 7: safety_gateway.EngineResult
	(*Explanation)(nil),           // 8: safety_gateway.Explanation
	(*ExplanationDetail)(nil),     // 9: safety_gateway.ExplanationDetail
	(*Evidence)(nil),              // 10: safety_gateway.Evidence
	(*ActionableGuidance)(nil),    // 11: safety_gateway.ActionableGuidance
	(*OverrideToken)(nil),         // 12: safety_gateway.OverrideToken
	(*DecisionSummary)(nil),       // 13: safety_gateway.DecisionSummary
	(*EngineStatusRequest)(nil),   // 14: safety_gateway.EngineStatusRequest
	(*EngineStatusResponse)(nil),  // 15: safety_gateway.EngineStatusResponse
	(*EngineInfo)(nil),            // 16: safety_gateway.EngineInfo
	(*OverrideRequest)(nil),       // 17: safety_gateway.OverrideRequest
	(*OverrideResponse)(nil),      // 18: safety_gateway.OverrideResponse
	(*HealthRequest)(nil),         // 19: safety_gateway.HealthRequest
	(*HealthResponse)(nil),        // 20: safety_gateway.HealthResponse
	nil,                           // 21: safety_gateway.SafetyRequest.ContextEntry
	nil,                           // 22: safety_gateway.SafetyResponse.MetadataEntry
	nil,                           // 23: safety_gateway.EngineResult.MetadataEntry
	nil,                           // 24: safety_gateway.Evidence.MetadataEntry
	nil,                           // 25: safety_gateway.EngineStatusResponse.MetadataEntry
	nil,                           // 26: safety_gateway.EngineInfo.MetadataEntry
	nil,                           // 27: safety_gateway.HealthResponse.DetailsEntry
	(*timestamppb.Timestamp)(nil), // 28: google.protobuf.Timestamp
}
var file_proto_safety_gateway_proto_depIdxs = []int32{
	21, // 0: safety_gateway.SafetyRequest.context:type_name -> safety_gateway.SafetyRequest.ContextEntry
	28, // 1: safety_gateway.SafetyRequest.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 2: safety_gateway.SafetyResponse.status:type_name -> safety_gateway.SafetyStatus
	7,  // 3: safety_gateway.SafetyResponse.engine_results:type_name -> safety_gateway.EngineResult
	8,  // 4: safety_gateway.SafetyResponse.explanation:type_name -> safety_gateway.Explanation
	12, // 5: safety_gateway.SafetyResponse.override_token:type_name -> safety_gateway.OverrideToken
	28, // 6: safety_gateway.SafetyResponse.timestamp:type_name -> google.protobuf.Timestamp
	22, // 7: safety_gateway.SafetyResponse.metadata:type_name -> safety_gateway.SafetyResponse.MetadataEntry
	0,  // 8: safety_gateway.EngineResult.status:type_name -> safety_gateway.SafetyStatus
	23, // 9: safety_gateway.EngineResult.metadata:type_name -> safety_gateway.EngineResult.MetadataEntry
	1,  // 10: safety_gateway.Explanation.level:type_name -> safety_gateway.ExplanationLevel
	9,  // 11: safety_gateway.Explanation.details:type_name -> safety_gateway.ExplanationDetail
	10, // 12: safety_gateway.Explanation.evidence:type_name -> safety_gateway.Evidence
	11, // 13: safety_gateway.Explanation.actionable:type_name -> safety_gateway.ActionableGuidance
	28, // 14: safety_gateway.Explanation.generated_at:type_name -> google.protobuf.Timestamp
	24, // 15: safety_gateway.Evidence.metadata:type_name -> safety_gateway.Evidence.MetadataEntry
	13, // 16: safety_gateway.OverrideToken.decision_summary:type_name -> safety_gateway.DecisionSummary
	2,  // 17: safety_gateway.OverrideToken.required_level:type_name -> safety_gateway.OverrideLevel
	28, // 18: safety_gateway.OverrideToken.expires_at:type_name -> google.protobuf.Timestamp
	28, // 19: safety_gateway.OverrideToken.created_at:type_name -> google.protobuf.Timestamp
	0,  // 20: safety_gateway.DecisionSummary.status:type_name -> safety_gateway.SafetyStatus
	16, // 21: safety_gateway.EngineStatusResponse.engines:type_name -> safety_gateway.EngineInfo
	25, // 22: safety_gateway.EngineStatusResponse.metadata:type_name -> safety_gateway.EngineStatusResponse.MetadataEntry
	3,  // 23: safety_gateway.EngineInfo.status:type_name -> safety_gateway.EngineStatus
	28, // 24: safety_gateway.EngineInfo.last_check:type_name -> google.protobuf.Timestamp
	26, // 25: safety_gateway.EngineInfo.metadata:type_name -> safety_gateway.EngineInfo.MetadataEntry
	12, // 26: safety_gateway.OverrideResponse.token:type_name -> safety_gateway.OverrideToken
	28, // 27: safety_gateway.OverrideResponse.validated_at:type_name -> google.protobuf.Timestamp
	4,  // 28: safety_gateway.HealthResponse.status:type_name -> safety_gateway.HealthStatus
	27, // 29: safety_gateway.HealthResponse.details:type_name -> safety_gateway.HealthResponse.DetailsEntry
	28, // 30: safety_gateway.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 31: safety_gateway.SafetyGateway.ValidateSafety:input_type -> safety_gateway.SafetyRequest
	14, // 32: safety_gateway.SafetyGateway.GetEngineStatus:input_type -> safety_gateway.EngineStatusRequest
	17, // 33: safety_gateway.SafetyGateway.ValidateOverride:input_type -> safety_gateway.OverrideRequest
	19, // 34: safety_gateway.SafetyGateway.GetHealth:input_type -> safety_gateway.HealthRequest
	6,  // 35: safety_gateway.SafetyGateway.ValidateSafety:output_type -> safety_gateway.SafetyResponse
	15, // 36: safety_gateway.SafetyGateway.GetEngineStatus:output_type -> safety_gateway.EngineStatusResponse
	18, // 37: safety_gateway.SafetyGateway.ValidateOverride:output_type -> safety_gateway.OverrideResponse
	20, // 38: safety_gateway.SafetyGateway.GetHealth:output_type -> safety_gateway.HealthResponse
	35, // [35:39] is the sub-list for method output_type
	31, // [31:35] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_proto_safety_gateway_proto_init() }
func file_proto_safety_gateway_proto_init() {
	if File_proto_safety_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_safety_gateway_proto_rawDesc), len(file_proto_safety_gateway_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_safety_gateway_proto_goTypes,
		DependencyIndexes: file_proto_safety_gateway_proto_depIdxs,
		EnumInfos:         file_proto_safety_gateway_proto_enumTypes,
		MessageInfos:      file_proto_safety_gateway_proto_msgTypes,
	}.Build()
	File_proto_safety_gateway_proto = out.File
	file_proto_safety_gateway_proto_goTypes = nil
	file_proto_safety_gateway_proto_depIdxs = nil
}
