-- KB-10 Clinical Rules Engine - Alerts Table Migration
-- Version: 1.0.0
-- Date: 2025-01-05

-- Alerts table - stores triggered clinical alerts
CREATE TABLE IF NOT EXISTS alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rule_id VARCHAR(100) NOT NULL,
    rule_name VARCHAR(255),
    patient_id VARCHAR(100) NOT NULL,
    encounter_id VARCHAR(100),
    severity VARCHAR(50) NOT NULL,
    category VARCHAR(100),
    message TEXT NOT NULL,
    details TEXT,
    context JSONB,
    status VARCHAR(50) DEFAULT 'active',
    priority VARCHAR(50),
    acknowledged_by VARCHAR(100),
    acknowledged_at TIMESTAMP WITH TIME ZONE,
    resolved_by VARCHAR(100),
    resolved_at TIMESTAMP WITH TIME ZONE,
    resolution TEXT,
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_alerts_patient ON alerts(patient_id);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_rule ON alerts(rule_id);
CREATE INDEX IF NOT EXISTS idx_alerts_created ON alerts(created_at);
CREATE INDEX IF NOT EXISTS idx_alerts_encounter ON alerts(encounter_id);

-- Alert statuses:
-- active - Alert is active and requires attention
-- acknowledged - Alert has been acknowledged by clinician
-- resolved - Alert has been resolved (action taken or condition resolved)
-- expired - Alert expired without action

-- Severity levels:
-- CRITICAL - Immediate action required (e.g., K > 6.5, BP < 80)
-- HIGH - Urgent attention needed (e.g., sepsis suspected)
-- MODERATE - Review required (e.g., lab trending abnormal)
-- LOW - Informational (e.g., routine reminder)

COMMENT ON TABLE alerts IS 'KB-10 Clinical alerts generated by rule engine evaluation';
COMMENT ON COLUMN alerts.status IS 'Alert status: active, acknowledged, resolved, expired';
COMMENT ON COLUMN alerts.severity IS 'Alert severity: CRITICAL, HIGH, MODERATE, LOW';
COMMENT ON COLUMN alerts.context IS 'JSONB snapshot of patient context at alert time';
