// Package overrides implements the override-reason taxonomy for clinical-safety
// audit capture.
//
// VisibilityClass: AD — override capture for clinical-safety audit per Guidelines §5
//
// The 20 reason codes are split into two groups:
//   - 12 Wright/McCoy foundation codes: alert_fatigue, irrelevant_to_patient,
//     patient_preference, clinical_judgment, alternative_pursued,
//     monitoring_in_place, low_priority, documentation_concern,
//     uncertain_evidence, system_error, workflow_constraint, duplicative_alert.
//   - 8 ACOP extension codes: goals_of_care_aligned, deprescribing_underway,
//     frailty_consideration, family_consensus_pending, sdm_review_required,
//     trial_period_active, audit_visit_imminent, cross_resident_pattern.
//
// Reason codes mirror the CHECK constraint that will be emitted by migration 042.
// AppropriatenessFlag values mirror the CHECK constraint in the same migration.
package overrides

import (
	"errors"
	"time"
)

// ---------------------------------------------------------------------------
// Sentinel errors
// ---------------------------------------------------------------------------

// ErrInvalidReasonCode is returned when an OverrideReason carries a ReasonCode
// that is not in the canonical set of 20 codes defined by the Recommendation
// Craft Guidelines Part 5. The check is case-sensitive.
var ErrInvalidReasonCode = errors.New("overrides: invalid reason code")

// ErrInvalidFlag is returned when an OverrideReason carries an
// AppropriatenessFlag that is not one of the three accepted values:
// "appropriate_override", "inappropriate_override", "mixed".
var ErrInvalidFlag = errors.New("overrides: invalid appropriateness flag")

// ErrEmptyReasoning is returned when an OverrideReason has an empty Reasoning
// field. Free-text rationale is mandatory for every captured override.
var ErrEmptyReasoning = errors.New("overrides: reasoning must not be empty")

// ---------------------------------------------------------------------------
// Canonical code sets
// ---------------------------------------------------------------------------

// wrightMcCoyFoundation is the set of 12 codes from the Wright/McCoy
// foundational alert-override taxonomy (Recommendation Craft Guidelines §5.1).
var wrightMcCoyFoundation = map[string]struct{}{
	"alert_fatigue":         {},
	"irrelevant_to_patient": {},
	"patient_preference":    {},
	"clinical_judgment":     {},
	"alternative_pursued":   {},
	"monitoring_in_place":   {},
	"low_priority":          {},
	"documentation_concern": {},
	"uncertain_evidence":    {},
	"system_error":          {},
	"workflow_constraint":   {},
	"duplicative_alert":     {},
}

// acopExtension is the set of 8 codes from the ACOP (Aged Care Quality and
// Safety) extension (Recommendation Craft Guidelines §5.2).
var acopExtension = map[string]struct{}{
	"goals_of_care_aligned":   {},
	"deprescribing_underway":  {},
	"frailty_consideration":   {},
	"family_consensus_pending": {},
	"sdm_review_required":     {},
	"trial_period_active":     {},
	"audit_visit_imminent":    {},
	"cross_resident_pattern":  {},
}

// ValidReasonCodes is the exported ordered slice of all 20 canonical override
// reason codes. The ordering is deterministic: Wright/McCoy foundation (12)
// followed by ACOP extensions (8), matching the sequence in Guidelines §5.
//
// Downstream consumers (e.g. migration 042's CHECK constraint generator) should
// use this slice directly rather than duplicating the list.
var ValidReasonCodes = []string{
	// Wright/McCoy foundation (12)
	"alert_fatigue",
	"irrelevant_to_patient",
	"patient_preference",
	"clinical_judgment",
	"alternative_pursued",
	"monitoring_in_place",
	"low_priority",
	"documentation_concern",
	"uncertain_evidence",
	"system_error",
	"workflow_constraint",
	"duplicative_alert",
	// ACOP extensions (8)
	"goals_of_care_aligned",
	"deprescribing_underway",
	"frailty_consideration",
	"family_consensus_pending",
	"sdm_review_required",
	"trial_period_active",
	"audit_visit_imminent",
	"cross_resident_pattern",
}

// validFlags is the canonical set of appropriateness flag values. Mirrors the
// CHECK constraint that will be generated by migration 042.
var validFlags = map[string]struct{}{
	"appropriate_override":   {},
	"inappropriate_override": {},
	"mixed":                  {},
}

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

// IsValidReasonCode reports whether s is one of the 20 canonical override
// reason codes. The check is case-sensitive; "Patient_Preference" is not
// equivalent to "patient_preference".
func IsValidReasonCode(s string) bool {
	_, inFoundation := wrightMcCoyFoundation[s]
	if inFoundation {
		return true
	}
	_, inACOP := acopExtension[s]
	return inACOP
}

// IsValidFlag reports whether s is one of the three canonical appropriateness
// flag values: "appropriate_override", "inappropriate_override", "mixed".
// The check is case-sensitive.
func IsValidFlag(s string) bool {
	_, ok := validFlags[s]
	return ok
}

// IsWrightMcCoyFoundation reports whether s is one of the 12 Wright/McCoy
// foundation override reason codes. Returns false for ACOP extension codes
// and any unrecognised value.
//
// This helper is intended for the rule-tuning feedback loop (Phase 2b Task 4)
// which may weight foundation codes differently from ACOP extensions when
// computing per-rule override signal.
func IsWrightMcCoyFoundation(s string) bool {
	_, ok := wrightMcCoyFoundation[s]
	return ok
}

// IsACOPExtension reports whether s is one of the 8 ACOP extension override
// reason codes. Returns false for Wright/McCoy foundation codes and any
// unrecognised value.
//
// This helper is intended for the rule-tuning feedback loop (Phase 2b Task 4)
// which may weight ACOP extension codes differently from foundation codes when
// computing per-rule override signal.
func IsACOPExtension(s string) bool {
	_, ok := acopExtension[s]
	return ok
}

// ---------------------------------------------------------------------------
// OverrideReason struct
// ---------------------------------------------------------------------------

// OverrideReason captures a single clinician override of a recommendation,
// including the structured reason code and mandatory free-text rationale.
//
// This record is the primary unit of clinical-safety audit data for the
// override analytics pipeline (Guidelines §5). Every field except ID is
// required; ID may be populated by the persistence layer after insertion.
type OverrideReason struct {
	// ID is the unique identifier assigned by the persistence layer.
	// May be empty before the record is persisted.
	ID string

	// RecommendationID is the identifier of the recommendation that was
	// overridden. Must not be empty; validated at the persistence layer.
	RecommendationID string

	// ReasonCode is the structured override reason from the canonical set of
	// 20 codes (Guidelines §5). Must pass IsValidReasonCode.
	ReasonCode string

	// AppropriatenessFlag classifies the override as clinically appropriate,
	// inappropriate, or mixed. Must pass IsValidFlag.
	AppropriatenessFlag string

	// Reasoning is mandatory free-text capturing why the override was made.
	// Must not be empty; the structured code alone is insufficient for audit
	// purposes.
	Reasoning string

	// CapturedAt is the timestamp at which the override was recorded.
	CapturedAt time.Time

	// CapturedBy is the identifier of the clinician who made the override.
	CapturedBy string
}

// Validate checks that the OverrideReason is internally consistent and ready
// for persistence. Validation order:
//  1. ReasonCode must be a valid canonical code (ErrInvalidReasonCode).
//  2. AppropriatenessFlag must be a valid canonical flag (ErrInvalidFlag).
//  3. Reasoning must not be empty (ErrEmptyReasoning).
//
// Returns the first error encountered; callers should use errors.Is for
// sentinel matching.
func (o OverrideReason) Validate() error {
	if !IsValidReasonCode(o.ReasonCode) {
		return ErrInvalidReasonCode
	}
	if !IsValidFlag(o.AppropriatenessFlag) {
		return ErrInvalidFlag
	}
	if o.Reasoning == "" {
		return ErrEmptyReasoning
	}
	return nil
}
