package com.cardiofit.flink.cds.pathways;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for PathwayInstance
 * Phase 8 Module 3 - Clinical Pathways Engine
 *
 * Test Coverage:
 * - Instance creation and state management
 * - Step execution tracking
 * - Deviation recording and tracking
 * - Adherence score calculation
 * - Progress tracking
 * - Quality measure recording
 * - Pathway completion and discontinuation
 *
 * @author CardioFit Testing Team
 * @version 1.0.0
 * @since Phase 8
 */
@DisplayName("PathwayInstance Tests")
class PathwayInstanceTest {

    private PathwayInstance instance;
    private static final String TEST_PATIENT_ID = "PATIENT-12345";
    private static final String TEST_PATHWAY_ID = "ACS-PATHWAY-001";
    private static final String TEST_PATHWAY_NAME = "Acute Coronary Syndrome Pathway";

    @BeforeEach
    void setUp() {
        instance = new PathwayInstance(TEST_PATIENT_ID, TEST_PATHWAY_ID, TEST_PATHWAY_NAME);
    }

    @Nested
    @DisplayName("Instance Creation Tests")
    class InstanceCreationTests {

        @Test
        @DisplayName("Should create instance with required fields")
        void testInstanceCreation() {
            assertNotNull(instance);
            assertEquals(TEST_PATIENT_ID, instance.getPatientId());
            assertEquals(TEST_PATHWAY_ID, instance.getPathwayId());
            assertEquals(TEST_PATHWAY_NAME, instance.getPathwayName());
            assertEquals(PathwayInstance.InstanceStatus.INITIATED, instance.getStatus());
        }

        @Test
        @DisplayName("Should auto-generate unique instance ID")
        void testAutoGeneratedInstanceId() throws InterruptedException {
            assertNotNull(instance.getInstanceId());
            assertTrue(instance.getInstanceId().startsWith("PATHWAY-INST-"));

            Thread.sleep(1); // Ensure different timestamp
            PathwayInstance instance2 = new PathwayInstance(TEST_PATIENT_ID, TEST_PATHWAY_ID, TEST_PATHWAY_NAME);
            assertNotEquals(instance.getInstanceId(), instance2.getInstanceId());
        }

        @Test
        @DisplayName("Should initialize start time")
        void testStartTimeInitialization() {
            assertNotNull(instance.getStartTime());
            assertTrue(instance.getStartTime().isBefore(LocalDateTime.now().plusSeconds(1)));
        }

        @Test
        @DisplayName("Should initialize empty collections")
        void testCollectionInitialization() {
            assertNotNull(instance.getCompletedSteps());
            assertNotNull(instance.getPendingSteps());
            assertNotNull(instance.getDeviations());
            assertNotNull(instance.getPatientData());
            assertNotNull(instance.getQualityMeasuresMet());
            assertNotNull(instance.getClinicianActions());

            assertEquals(0, instance.getCompletedSteps().size());
            assertEquals(0, instance.getPendingSteps().size());
            assertEquals(0, instance.getDeviations().size());
            assertFalse(instance.isHasDeviations());
            assertEquals(0, instance.getDeviationCount());
        }

        @Test
        @DisplayName("Should support all instance statuses")
        void testAllInstanceStatuses() {
            PathwayInstance.InstanceStatus[] statuses = PathwayInstance.InstanceStatus.values();

            assertEquals(7, statuses.length);
            assertTrue(containsStatus(statuses, PathwayInstance.InstanceStatus.INITIATED));
            assertTrue(containsStatus(statuses, PathwayInstance.InstanceStatus.IN_PROGRESS));
            assertTrue(containsStatus(statuses, PathwayInstance.InstanceStatus.SUSPENDED));
            assertTrue(containsStatus(statuses, PathwayInstance.InstanceStatus.DEVIATED));
            assertTrue(containsStatus(statuses, PathwayInstance.InstanceStatus.COMPLETED));
            assertTrue(containsStatus(statuses, PathwayInstance.InstanceStatus.DISCONTINUED));
            assertTrue(containsStatus(statuses, PathwayInstance.InstanceStatus.FAILED));
        }

        private boolean containsStatus(PathwayInstance.InstanceStatus[] statuses,
                                       PathwayInstance.InstanceStatus target) {
            for (PathwayInstance.InstanceStatus status : statuses) {
                if (status == target) return true;
            }
            return false;
        }
    }

    @Nested
    @DisplayName("Step Execution Tests")
    class StepExecutionTests {

        @Test
        @DisplayName("Should start step execution")
        void testStartStep() {
            PathwayInstance.StepExecution execution = instance.startStep("STEP-001", "Initial Assessment");

            assertNotNull(execution);
            assertEquals("STEP-001", execution.getStepId());
            assertEquals("Initial Assessment", execution.getStepName());
            assertNotNull(execution.getStartTime());
            assertFalse(execution.isCompleted());
            assertEquals(PathwayInstance.InstanceStatus.IN_PROGRESS, instance.getStatus());
            assertEquals("STEP-001", instance.getCurrentStepId());
        }

        @Test
        @DisplayName("Should complete step execution")
        void testCompleteStep() throws InterruptedException {
            PathwayInstance.StepExecution execution = instance.startStep("STEP-001", "Initial Assessment");

            // Simulate some time passing
            Thread.sleep(10);

            instance.completeStep(execution, true);

            assertTrue(execution.isCompleted());
            assertTrue(execution.isOnTime());
            assertNotNull(execution.getEndTime());
            assertNotNull(execution.getDurationMinutes());
            assertEquals(1, instance.getCompletedSteps().size());
            assertEquals(execution, instance.getCompletedSteps().get(0));
        }

        @Test
        @DisplayName("Should track multiple completed steps")
        void testMultipleStepCompletion() {
            PathwayInstance.StepExecution step1 = instance.startStep("STEP-001", "Assessment");
            instance.completeStep(step1, true);

            PathwayInstance.StepExecution step2 = instance.startStep("STEP-002", "ECG");
            instance.completeStep(step2, true);

            PathwayInstance.StepExecution step3 = instance.startStep("STEP-003", "Labs");
            instance.completeStep(step3, false);

            assertEquals(3, instance.getCompletedSteps().size());
            assertTrue(step1.isOnTime());
            assertTrue(step2.isOnTime());
            assertFalse(step3.isOnTime());
        }

        @Test
        @DisplayName("Should track step execution data")
        void testStepExecutionDataTracking() {
            PathwayInstance.StepExecution execution = instance.startStep("STEP-001", "ECG");

            execution.getActionsPerformed().add("12-lead ECG obtained");
            execution.getActionsPerformed().add("ECG interpreted by physician");
            execution.getDataCollected().put("ecg_finding", "STEMI");
            execution.getDataCollected().put("ecg_duration", 8); // minutes
            execution.setExecutedBy("Dr. Smith");
            execution.setNotes("Anterior STEMI confirmed");

            assertEquals(2, execution.getActionsPerformed().size());
            assertEquals(2, execution.getDataCollected().size());
            assertEquals("STEMI", execution.getDataCollected().get("ecg_finding"));
            assertEquals("Dr. Smith", execution.getExecutedBy());
            assertEquals("Anterior STEMI confirmed", execution.getNotes());
        }

        @Test
        @DisplayName("Should calculate step duration on completion")
        void testStepDurationCalculation() throws InterruptedException {
            PathwayInstance.StepExecution execution = instance.startStep("STEP-001", "Assessment");

            // Simulate some processing time
            Thread.sleep(100);

            execution.complete();

            assertNotNull(execution.getDurationMinutes());
            assertTrue(execution.getDurationMinutes() >= 0);
            assertTrue(execution.isCompleted());
        }
    }

    @Nested
    @DisplayName("Deviation Tracking Tests")
    class DeviationTrackingTests {

        @Test
        @DisplayName("Should record deviation")
        void testRecordDeviation() {
            instance.recordDeviation(
                PathwayInstance.Deviation.DeviationType.TIME_EXCEEDED,
                "STEP-002",
                "ECG took 15 minutes instead of 10",
                PathwayInstance.Deviation.Severity.MODERATE
            );

            assertTrue(instance.isHasDeviations());
            assertEquals(1, instance.getDeviationCount());
            assertEquals(1, instance.getDeviations().size());

            PathwayInstance.Deviation deviation = instance.getDeviations().get(0);
            assertEquals(PathwayInstance.Deviation.DeviationType.TIME_EXCEEDED, deviation.getDeviationType());
            assertEquals("STEP-002", deviation.getStepId());
            assertEquals("ECG took 15 minutes instead of 10", deviation.getReason());
            assertEquals(PathwayInstance.Deviation.Severity.MODERATE, deviation.getSeverity());
            assertFalse(deviation.isWasResolved());
        }

        @Test
        @DisplayName("Should mark instance as deviated for high/critical severity")
        void testHighSeverityChangesInstanceStatus() {
            instance.recordDeviation(
                PathwayInstance.Deviation.DeviationType.STEP_SKIPPED,
                "STEP-003",
                "Blood cultures not obtained due to patient refusal",
                PathwayInstance.Deviation.Severity.HIGH
            );

            assertEquals(PathwayInstance.InstanceStatus.DEVIATED, instance.getStatus());
        }

        @Test
        @DisplayName("Should mark instance as deviated for critical severity")
        void testCriticalSeverityChangesInstanceStatus() {
            instance.recordDeviation(
                PathwayInstance.Deviation.DeviationType.ADVERSE_EVENT,
                "STEP-004",
                "Anaphylaxis to antibiotic",
                PathwayInstance.Deviation.Severity.CRITICAL
            );

            assertEquals(PathwayInstance.InstanceStatus.DEVIATED, instance.getStatus());
        }

        @Test
        @DisplayName("Should not change status for low/moderate severity")
        void testLowModerateSeverityDoesNotChangeStatus() {
            instance.setStatus(PathwayInstance.InstanceStatus.IN_PROGRESS);

            instance.recordDeviation(
                PathwayInstance.Deviation.DeviationType.TIME_EXCEEDED,
                "STEP-002",
                "Minor delay",
                PathwayInstance.Deviation.Severity.LOW
            );

            assertEquals(PathwayInstance.InstanceStatus.IN_PROGRESS, instance.getStatus());
        }

        @Test
        @DisplayName("Should track multiple deviations")
        void testMultipleDeviations() {
            instance.recordDeviation(
                PathwayInstance.Deviation.DeviationType.TIME_EXCEEDED,
                "STEP-001",
                "Assessment delayed",
                PathwayInstance.Deviation.Severity.LOW
            );

            instance.recordDeviation(
                PathwayInstance.Deviation.DeviationType.STEP_SKIPPED,
                "STEP-002",
                "Patient refused",
                PathwayInstance.Deviation.Severity.MODERATE
            );

            instance.recordDeviation(
                PathwayInstance.Deviation.DeviationType.CONTRAINDICATION,
                "STEP-003",
                "Allergy discovered",
                PathwayInstance.Deviation.Severity.HIGH
            );

            assertEquals(3, instance.getDeviationCount());
            assertEquals(3, instance.getDeviations().size());
        }

        @Test
        @DisplayName("Should support all deviation types")
        void testAllDeviationTypes() {
            PathwayInstance.Deviation.DeviationType[] types = PathwayInstance.Deviation.DeviationType.values();

            assertEquals(9, types.length);
            assertTrue(containsDeviationType(types, PathwayInstance.Deviation.DeviationType.STEP_SKIPPED));
            assertTrue(containsDeviationType(types, PathwayInstance.Deviation.DeviationType.TIME_EXCEEDED));
            assertTrue(containsDeviationType(types, PathwayInstance.Deviation.DeviationType.WRONG_SEQUENCE));
            assertTrue(containsDeviationType(types, PathwayInstance.Deviation.DeviationType.MISSING_DATA));
            assertTrue(containsDeviationType(types, PathwayInstance.Deviation.DeviationType.CONTRAINDICATION));
            assertTrue(containsDeviationType(types, PathwayInstance.Deviation.DeviationType.PATIENT_REFUSAL));
            assertTrue(containsDeviationType(types, PathwayInstance.Deviation.DeviationType.RESOURCE_UNAVAILABLE));
            assertTrue(containsDeviationType(types, PathwayInstance.Deviation.DeviationType.CLINICAL_OVERRIDE));
            assertTrue(containsDeviationType(types, PathwayInstance.Deviation.DeviationType.ADVERSE_EVENT));
        }

        @Test
        @DisplayName("Should support all severity levels")
        void testAllSeverityLevels() {
            PathwayInstance.Deviation.Severity[] severities = PathwayInstance.Deviation.Severity.values();

            assertEquals(4, severities.length);
            assertTrue(containsSeverity(severities, PathwayInstance.Deviation.Severity.LOW));
            assertTrue(containsSeverity(severities, PathwayInstance.Deviation.Severity.MODERATE));
            assertTrue(containsSeverity(severities, PathwayInstance.Deviation.Severity.HIGH));
            assertTrue(containsSeverity(severities, PathwayInstance.Deviation.Severity.CRITICAL));
        }

        @Test
        @DisplayName("Should auto-generate deviation ID")
        void testAutoGeneratedDeviationId() {
            PathwayInstance.Deviation deviation = new PathwayInstance.Deviation(
                PathwayInstance.Deviation.DeviationType.TIME_EXCEEDED,
                "STEP-001",
                "Delay"
            );

            assertNotNull(deviation.getDeviationId());
            assertTrue(deviation.getDeviationId().startsWith("DEV-"));
        }

        @Test
        @DisplayName("Should set clinical justification and resolution")
        void testDeviationJustificationAndResolution() {
            PathwayInstance.Deviation deviation = new PathwayInstance.Deviation(
                PathwayInstance.Deviation.DeviationType.CLINICAL_OVERRIDE,
                "STEP-004",
                "Physician override"
            );

            deviation.setClinicalJustification("Patient condition deteriorated, immediate intervention required");
            deviation.setWasResolved(true);
            deviation.setResolution("Patient stabilized with alternative treatment");

            assertEquals("Patient condition deteriorated, immediate intervention required",
                        deviation.getClinicalJustification());
            assertTrue(deviation.isWasResolved());
            assertEquals("Patient stabilized with alternative treatment", deviation.getResolution());
        }

        private boolean containsDeviationType(PathwayInstance.Deviation.DeviationType[] types,
                                              PathwayInstance.Deviation.DeviationType target) {
            for (PathwayInstance.Deviation.DeviationType type : types) {
                if (type == target) return true;
            }
            return false;
        }

        private boolean containsSeverity(PathwayInstance.Deviation.Severity[] severities,
                                         PathwayInstance.Deviation.Severity target) {
            for (PathwayInstance.Deviation.Severity severity : severities) {
                if (severity == target) return true;
            }
            return false;
        }
    }

    @Nested
    @DisplayName("Adherence Score Tests")
    class AdherenceScoreTests {

        @Test
        @DisplayName("Should calculate 100% adherence for all on-time steps")
        void testPerfectAdherence() {
            PathwayInstance.StepExecution step1 = instance.startStep("STEP-001", "Assessment");
            instance.completeStep(step1, true);

            PathwayInstance.StepExecution step2 = instance.startStep("STEP-002", "ECG");
            instance.completeStep(step2, true);

            PathwayInstance.StepExecution step3 = instance.startStep("STEP-003", "Labs");
            instance.completeStep(step3, true);

            instance.complete("Pathway completed successfully");

            assertEquals(1.0, instance.getAdherenceScore(), 0.001);
        }

        @Test
        @DisplayName("Should reduce adherence for delayed steps")
        void testReducedAdherenceForDelays() {
            PathwayInstance.StepExecution step1 = instance.startStep("STEP-001", "Assessment");
            instance.completeStep(step1, true);  // On time

            PathwayInstance.StepExecution step2 = instance.startStep("STEP-002", "ECG");
            instance.completeStep(step2, false);  // Delayed

            PathwayInstance.StepExecution step3 = instance.startStep("STEP-003", "Labs");
            instance.completeStep(step3, true);  // On time

            instance.complete("Completed with one delay");

            // 2 out of 3 on time = 0.67
            assertEquals(0.67, instance.getAdherenceScore(), 0.01);
        }

        @Test
        @DisplayName("Should penalize adherence for deviations")
        void testDeviationPenalty() {
            PathwayInstance.StepExecution step1 = instance.startStep("STEP-001", "Assessment");
            instance.completeStep(step1, true);

            PathwayInstance.StepExecution step2 = instance.startStep("STEP-002", "ECG");
            instance.completeStep(step2, true);

            // Record a deviation
            instance.recordDeviation(
                PathwayInstance.Deviation.DeviationType.STEP_SKIPPED,
                "STEP-003",
                "Patient refused",
                PathwayInstance.Deviation.Severity.MODERATE
            );

            instance.complete("Completed with deviation");

            // Base adherence = 1.0 (all on-time), penalty = 0.1 for 1 deviation
            assertEquals(0.9, instance.getAdherenceScore(), 0.001);
        }

        @Test
        @DisplayName("Should cap deviation penalty at 30%")
        void testMaximumDeviationPenalty() {
            PathwayInstance.StepExecution step1 = instance.startStep("STEP-001", "Assessment");
            instance.completeStep(step1, true);

            // Record 5 deviations (would be 50% penalty without cap)
            for (int i = 0; i < 5; i++) {
                instance.recordDeviation(
                    PathwayInstance.Deviation.DeviationType.TIME_EXCEEDED,
                    "STEP-00" + i,
                    "Delay " + i,
                    PathwayInstance.Deviation.Severity.LOW
                );
            }

            instance.complete("Completed with multiple deviations");

            // Base adherence = 1.0, max penalty = 0.3
            assertEquals(0.7, instance.getAdherenceScore(), 0.001);
        }

        @Test
        @DisplayName("Should return zero adherence for no completed steps")
        void testZeroAdherenceForNoSteps() {
            instance.complete("No steps completed");

            assertEquals(0.0, instance.getAdherenceScore(), 0.001);
        }
    }

    @Nested
    @DisplayName("Progress Tracking Tests")
    class ProgressTrackingTests {

        @Test
        @DisplayName("Should calculate progress percentage")
        void testProgressPercentageCalculation() {
            instance.getCompletedSteps().add(new PathwayInstance.StepExecution("STEP-001", "Done"));
            instance.getCompletedSteps().add(new PathwayInstance.StepExecution("STEP-002", "Done"));
            instance.getPendingSteps().add(new PathwayInstance.StepExecution("STEP-003", "Pending"));
            instance.getPendingSteps().add(new PathwayInstance.StepExecution("STEP-004", "Pending"));

            // 2 completed out of 4 total = 50%
            assertEquals(50.0, instance.getProgressPercentage(), 0.01);
        }

        @Test
        @DisplayName("Should return zero progress for no steps")
        void testZeroProgressForNoSteps() {
            assertEquals(0.0, instance.getProgressPercentage(), 0.01);
        }

        @Test
        @DisplayName("Should return 100% progress when all steps completed")
        void testFullProgress() {
            instance.getCompletedSteps().add(new PathwayInstance.StepExecution("STEP-001", "Done"));
            instance.getCompletedSteps().add(new PathwayInstance.StepExecution("STEP-002", "Done"));

            assertEquals(100.0, instance.getProgressPercentage(), 0.01);
        }

        @Test
        @DisplayName("Should detect if pathway is behind schedule")
        void testBehindScheduleDetection() {
            // Expected duration 30 minutes
            Integer expectedDuration = 30;

            // Just started, should not be behind schedule
            assertFalse(instance.isBehindSchedule(expectedDuration));
        }

        @Test
        @DisplayName("Should handle null expected duration")
        void testBehindScheduleWithNullDuration() {
            assertFalse(instance.isBehindSchedule(null));
        }
    }

    @Nested
    @DisplayName("Patient Data Management Tests")
    class PatientDataManagementTests {

        @Test
        @DisplayName("Should update patient data")
        void testUpdatePatientData() {
            instance.updatePatientData("troponin", 0.08);
            instance.updatePatientData("BP_systolic", 120);
            instance.updatePatientData("ecg_finding", "STEMI");

            assertEquals(3, instance.getPatientData().size());
            assertEquals(0.08, instance.getPatientData().get("troponin"));
            assertEquals(120, instance.getPatientData().get("BP_systolic"));
            assertEquals("STEMI", instance.getPatientData().get("ecg_finding"));
        }

        @Test
        @DisplayName("Should set complete patient data map")
        void testSetPatientDataMap() {
            Map<String, Object> data = new HashMap<>();
            data.put("age", 65);
            data.put("diagnosis", "ACS");
            data.put("risk_score", 0.75);

            instance.setPatientData(data);

            assertEquals(3, instance.getPatientData().size());
            assertEquals(65, instance.getPatientData().get("age"));
        }

        @Test
        @DisplayName("Should update last update time when patient data changes")
        void testLastUpdateTimeOnDataChange() throws InterruptedException {
            LocalDateTime initialTime = instance.getLastUpdateTime();

            Thread.sleep(10);

            instance.updatePatientData("lactate", 2.5);

            assertTrue(instance.getLastUpdateTime().isAfter(initialTime));
        }
    }

    @Nested
    @DisplayName("Quality Measure Tests")
    class QualityMeasureTests {

        @Test
        @DisplayName("Should record quality measures")
        void testRecordQualityMeasures() {
            instance.recordQualityMeasure("door_to_ecg_10min", true);
            instance.recordQualityMeasure("aspirin_given", true);
            instance.recordQualityMeasure("door_to_balloon_90min", false);

            assertEquals(3, instance.getQualityMeasuresMet().size());
            assertTrue(instance.getQualityMeasuresMet().get("door_to_ecg_10min"));
            assertTrue(instance.getQualityMeasuresMet().get("aspirin_given"));
            assertFalse(instance.getQualityMeasuresMet().get("door_to_balloon_90min"));
        }

        @Test
        @DisplayName("Should track clinician actions")
        void testTrackClinicianActions() {
            instance.recordAction("ECG obtained at 10:05");
            instance.recordAction("Aspirin 325mg PO given at 10:07");
            instance.recordAction("Cardiology consulted at 10:15");

            assertEquals(3, instance.getClinicianActions().size());
            assertTrue(instance.getClinicianActions().get(0).contains("ECG"));
        }

        @Test
        @DisplayName("Should set initiated by and completed by")
        void testAuditTrail() {
            instance.setInitiatedBy("Dr. Smith");
            instance.setCompletedBy("Dr. Jones");

            assertEquals("Dr. Smith", instance.getInitiatedBy());
            assertEquals("Dr. Jones", instance.getCompletedBy());
        }
    }

    @Nested
    @DisplayName("Pathway Completion Tests")
    class PathwayCompletionTests {

        @Test
        @DisplayName("Should complete pathway successfully")
        void testCompletePathway() throws InterruptedException {
            PathwayInstance.StepExecution step1 = instance.startStep("STEP-001", "Assessment");
            instance.completeStep(step1, true);

            Thread.sleep(10);

            instance.complete("Patient stabilized and transferred to ICU");

            assertEquals(PathwayInstance.InstanceStatus.COMPLETED, instance.getStatus());
            assertEquals("Patient stabilized and transferred to ICU", instance.getFinalOutcome());
            assertNotNull(instance.getEndTime());
            assertNotNull(instance.getTotalDurationMinutes());
            assertTrue(instance.getTotalDurationMinutes() >= 0);
        }

        @Test
        @DisplayName("Should discontinue pathway with reason")
        void testDiscontinuePathway() throws InterruptedException {
            PathwayInstance.StepExecution step1 = instance.startStep("STEP-001", "Assessment");
            instance.completeStep(step1, true);

            Thread.sleep(10);

            instance.discontinue("Patient condition improved, pathway no longer needed");

            assertEquals(PathwayInstance.InstanceStatus.DISCONTINUED, instance.getStatus());
            assertEquals("Patient condition improved, pathway no longer needed", instance.getOutcomeNotes());
            assertNotNull(instance.getEndTime());
            assertNotNull(instance.getTotalDurationMinutes());
        }

        @Test
        @DisplayName("Should set clinical status and diagnosis")
        void testClinicalStatusTracking() {
            instance.setAdmissionDiagnosis("Chest pain, rule out ACS");
            instance.setCurrentClinicalStatus("Stable, awaiting troponin results");

            assertEquals("Chest pain, rule out ACS", instance.getAdmissionDiagnosis());
            assertEquals("Stable, awaiting troponin results", instance.getCurrentClinicalStatus());
        }
    }

    @Nested
    @DisplayName("toString Tests")
    class ToStringTests {

        @Test
        @DisplayName("Should generate meaningful string representation")
        void testToString() {
            PathwayInstance.StepExecution step1 = instance.startStep("STEP-001", "Assessment");
            instance.completeStep(step1, true);

            instance.getPendingSteps().add(new PathwayInstance.StepExecution("STEP-002", "Pending"));

            String str = instance.toString();

            assertTrue(str.contains(TEST_PATIENT_ID));
            assertTrue(str.contains(TEST_PATHWAY_NAME));
            assertTrue(str.contains("IN_PROGRESS"));
            assertTrue(str.contains("50.0%")); // 1 of 2 steps done
        }

        @Test
        @DisplayName("Should generate StepExecution toString")
        void testStepExecutionToString() throws InterruptedException {
            PathwayInstance.StepExecution execution = instance.startStep("STEP-001", "ECG");

            Thread.sleep(10);

            execution.complete();

            String str = execution.toString();

            assertTrue(str.contains("STEP-001"));
            assertTrue(str.contains("ECG"));
            assertTrue(str.contains("completed=true"));
        }

        @Test
        @DisplayName("Should generate Deviation toString")
        void testDeviationToString() {
            PathwayInstance.Deviation deviation = new PathwayInstance.Deviation(
                PathwayInstance.Deviation.DeviationType.TIME_EXCEEDED,
                "STEP-002",
                "ECG delayed"
            );
            deviation.setSeverity(PathwayInstance.Deviation.Severity.MODERATE);
            deviation.setWasResolved(false);

            String str = deviation.toString();

            assertTrue(str.contains("TIME_EXCEEDED"));
            assertTrue(str.contains("STEP-002"));
            assertTrue(str.contains("MODERATE"));
            assertTrue(str.contains("resolved=false"));
        }
    }
}
