package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	"kb-patient-safety/internal/thresholds"
	"kb-patient-safety/pkg/analytics"
	"kb-patient-safety/pkg/explainability"
	grpcserver "kb-patient-safety/pkg/grpc"
	"kb-patient-safety/pkg/graphql"
	"kb-patient-safety/pkg/safety"
)

// KB-4 Patient Safety Service with comprehensive safety checking
const serviceName = "kb4-patient-safety"
const serviceVersion = "3.0.0"

// Global safety checker instance
var safetyChecker *safety.SafetyChecker

// Global explainability instance
var alertExplainer *explainability.Explainer

// Global analytics instances
var signalDetector *analytics.SignalDetector
var trendAnalyzer *analytics.TrendAnalyzer

// Global subscription manager
var subscriptionManager *graphql.SubscriptionManager

// Safety Alert model for KB-4
type SafetyAlert struct {
	ID               uint      `json:"id" gorm:"primaryKey"`
	AlertID          string    `json:"alert_id" gorm:"uniqueIndex"`
	PatientID        string    `json:"patient_id"`
	DrugCode         string    `json:"drug_code"`
	RuleID           string    `json:"rule_id"`
	Severity         string    `json:"severity"` // CRITICAL, WARN, INFO
	Action           string    `json:"action"`   // VETO, WARN, PASS
	Message          string    `json:"message"`
	KB1RuleRefs      []string  `json:"kb1_rule_refs" gorm:"type:text[]"`
	KB3EvidenceRefs  []string  `json:"kb3_evidence_refs" gorm:"type:text[]"`
	PatientContext   string    `json:"patient_context" gorm:"type:jsonb"`
	OverrideStatus   string    `json:"override_status" gorm:"default:active"`
	OverrideReason   string    `json:"override_reason"`
	OverrideBy       string    `json:"override_by"`
	OverrideTime     *time.Time `json:"override_timestamp"`
	CreatedBy        string    `json:"created_by" gorm:"default:system"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

// GraphQL Federation v2 schema for KB-4 Patient Safety
const federationSchema = `
directive @key(fields: String!) on OBJECT | INTERFACE
directive @requires(fields: String!) on FIELD_DEFINITION
directive @provides(fields: String!) on FIELD_DEFINITION
directive @external on FIELD_DEFINITION
directive @tag(name: String!) on FIELD_DEFINITION | OBJECT | INTERFACE | UNION | ARGUMENT_DEFINITION | SCALAR | ENUM | ENUM_VALUE | INPUT_OBJECT | INPUT_FIELD_DEFINITION
directive @extends on OBJECT | INTERFACE
directive @shareable on FIELD_DEFINITION | OBJECT
directive @link(url: String!, as: String) on SCHEMA

extend schema @link(url: "https://specs.apollographql.org/federation/v2.0")

"""Patient safety alert generated by KB-4"""
type SafetyAlert @key(fields: "alertId") {
  alertId: String!
  patientId: String!
  drugCode: String!
  ruleId: String!
  severity: String!
  action: String!
  message: String!
  kb1RuleRefs: [String!]!
  kb3EvidenceRefs: [String!]
  patientContext: String
  overrideStatus: String!
  overrideReason: String
  overrideBy: String
  overrideTimestamp: String
  createdBy: String!
  createdAt: String!
  updatedAt: String!
}

"""Drug rule entity extended with safety monitoring"""
type DrugRule @key(fields: "drugId version") @extends {
  drugId: String! @external
  version: String! @external
  safetyAlerts: [SafetyAlert!]!
  riskScore: Float
  lastEvaluated: String
}

"""Patient safety monitoring event"""
type MonitoringEvent {
  eventId: String!
  patientId: String!
  eventType: String!
  drugCodes: [String!]
  labValues: String
  vitalSigns: String
  clinicalNotes: String
  sourceSystem: String
  createdBy: String!
  timestamp: String!
}

type Query {
  """Get safety alerts by patient ID"""
  safetyAlerts(patientId: String!, active: Boolean): [SafetyAlert!]!

  """Get safety alert by specific alert ID"""
  safetyAlert(alertId: String!): SafetyAlert

  """Get safety alerts by drug code"""
  safetyAlertsByDrug(drugCode: String!): [SafetyAlert!]!

  """Get safety alerts by severity"""
  safetyAlertsBySeverity(severity: String!): [SafetyAlert!]!

  """Get service statistics"""
  kb4Statistics: KB4Statistics!
}

"""KB-4 service statistics"""
type KB4Statistics {
  totalAlerts: Int!
  criticalAlerts: Int!
  activeAlerts: Int!
  resolvedAlerts: Int!
  patientsMonitored: Int!
  lastUpdated: String!
}

type Mutation {
  """Create new safety alert"""
  createSafetyAlert(input: CreateSafetyAlertInput!): CreateSafetyAlertResult!

  """Override safety alert"""
  overrideSafetyAlert(input: OverrideSafetyAlertInput!): OverrideSafetyAlertResult!
}

"""Input for creating safety alert"""
input CreateSafetyAlertInput {
  patientId: String!
  drugCode: String!
  ruleId: String!
  severity: String!
  action: String!
  message: String!
  kb1RuleRefs: [String!]!
  patientContext: String
}

"""Result of creating safety alert"""
type CreateSafetyAlertResult {
  success: Boolean!
  alertId: String
  message: String!
  safetyAlert: SafetyAlert
}

"""Input for overriding safety alert"""
input OverrideSafetyAlertInput {
  alertId: String!
  overrideReason: String!
  overrideBy: String!
}

"""Result of overriding safety alert"""
type OverrideSafetyAlertResult {
  success: Boolean!
  message: String!
  safetyAlert: SafetyAlert
}
`

// GraphQL request/response types
type GraphQLRequest struct {
	Query         string                 `json:"query"`
	Variables     map[string]interface{} `json:"variables,omitempty"`
	OperationName string                 `json:"operationName,omitempty"`
}

type GraphQLResponse struct {
	Data   interface{}   `json:"data,omitempty"`
	Errors []GraphQLError `json:"errors,omitempty"`
}

type GraphQLError struct {
	Message string        `json:"message"`
	Path    []interface{} `json:"path,omitempty"`
}

func main() {
	log.Printf("🚀 Starting %s v%s...", serviceName, serviceVersion)

	// Initialize safety checker with governed knowledge if available
	knowledgePath := os.Getenv("KNOWLEDGE_PATH")
	jurisdictionStr := os.Getenv("JURISDICTION")
	useGoverned := os.Getenv("USE_GOVERNED_KNOWLEDGE") == "true"

	if useGoverned && knowledgePath != "" {
		// Map jurisdiction string to type
		jurisdiction := safety.JurisdictionGlobal
		switch strings.ToUpper(jurisdictionStr) {
		case "US":
			jurisdiction = safety.JurisdictionUS
		case "AU":
			jurisdiction = safety.JurisdictionAU
		case "IN":
			jurisdiction = safety.JurisdictionIN
		}

		log.Printf("📚 Loading governed knowledge from: %s (jurisdiction: %s)", knowledgePath, jurisdiction)
		var err error
		safetyChecker, err = safety.NewJurisdictionAwareSafetyChecker(knowledgePath, jurisdiction)
		if err != nil {
			log.Printf("⚠️  Failed to load governed knowledge: %v (falling back to built-in)", err)
			safetyChecker = safety.NewSafetyChecker()
			log.Println("✅ Safety checker initialized with built-in drug database")
		} else {
			stats := safetyChecker.GetKnowledgeStats()
			log.Printf("✅ Safety checker initialized with governed knowledge (%d total entries)", stats["total_entries"])
			log.Printf("   📋 BlackBox: %d | HighAlert: %d | Beers: %d | Pregnancy: %d | Lactation: %d",
				stats["blackbox_warnings"], stats["high_alert_medications"], stats["beers_entries"],
				stats["pregnancy_safety"], stats["lactation_safety"])
			log.Printf("   📋 Labs: %d | ACB: %d | Contraindications: %d",
				stats["lab_requirements"], stats["anticholinergic_burdens"], stats["contraindications"])
		}
	} else {
		safetyChecker = safety.NewSafetyChecker()
		log.Println("✅ Safety checker initialized with built-in drug database")
	}

	// Initialize analytics components
	signalDetector = analytics.NewSignalDetector()
	trendAnalyzer = analytics.NewTrendAnalyzer()
	log.Println("✅ Analytics engine initialized (Signal Detection + Trend Analysis)")

	// Initialize explainability layer
	alertExplainer = explainability.NewExplainer(safetyChecker)
	log.Println("✅ Explainability layer initialized (Clinical Decision Explanations)")

	// Initialize database
	db, err := initDatabase()
	if err != nil {
		log.Fatalf("❌ Failed to initialize database: %v", err)
	}
	log.Println("✅ Database connected successfully")

	// Auto-migrate models — skip if table already exists from SQL migrations
	if !db.Migrator().HasTable(&SafetyAlert{}) {
		if err := db.AutoMigrate(&SafetyAlert{}); err != nil {
			log.Printf("⚠️  Auto-migration warning: %v", err)
		}
	} else {
		log.Println("ℹ️  safety_alerts table exists (from SQL migrations), skipping GORM AutoMigrate")
	}

	// Initialize Gin router
	gin.SetMode(gin.ReleaseMode)
	router := gin.New()
	router.Use(gin.Logger())
	router.Use(gin.Recovery())

	// Add CORS middleware
	router.Use(func(c *gin.Context) {
		c.Header("Access-Control-Allow-Origin", "*")
		c.Header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Content-Type, Authorization, Upgrade, Connection")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}

		c.Next()
	})

	// Setup routes
	setupRoutes(router, db)

	// Setup GraphQL Federation endpoints
	setupGraphQLFederation(router, db)

	// Initialize GraphQL Subscription Manager
	subscriptionManager = graphql.NewSubscriptionManager(signalDetector, trendAnalyzer)
	subscriptionManager.RegisterGraphQLRoutes(router)
	log.Println("✅ GraphQL Subscriptions initialized (WebSocket support)")

	// Start gRPC server (Phase 5)
	grpcPort := os.Getenv("GRPC_PORT")
	if grpcPort == "" {
		grpcPort = "50051" // Default gRPC port
	}
	grpcPortInt, _ := strconv.Atoi(grpcPort)
	go func() {
		grpcServer, err := grpcserver.StartGRPCServer(grpcPortInt, safetyChecker)
		if err != nil {
			log.Printf("⚠️  gRPC server failed to start: %v", err)
		} else {
			log.Printf("✅ gRPC server started on port %s", grpcPort)
			_ = grpcServer // Keep reference
		}
	}()

	// Start HTTP server
	port := os.Getenv("PORT")
	if port == "" {
		port = "8088" // Default port for KB-4 Patient Safety (per CLAUDE.md)
	}

	log.Printf("🌐 HTTP Server starting on port %s", port)
	log.Printf("🔌 gRPC Server starting on port %s", grpcPort)
	log.Printf("📋 Available endpoints:")
	log.Printf("   GET  /health - Health check")
	log.Printf("   GET  /ready - Readiness check")
	log.Printf("   GET  /v1/alerts - Get safety alerts")
	log.Printf("   POST /v1/alerts - Create safety alert")
	log.Printf("   POST /v1/check - Safety check")
	log.Printf("   GET  /v1/stats - Service statistics")
	log.Printf("   GET  /api/federation - GraphQL Federation schema")
	log.Printf("   POST /api/federation - GraphQL Federation query")
	log.Printf("   GET  /graphql/subscriptions - WebSocket subscriptions")
	log.Printf("   POST /v1/analytics/signals - Signal detection")
	log.Printf("   POST /v1/analytics/trends - Trend analysis")
	log.Printf("   GET  /v1/analytics/dashboard - Safety dashboard")

	if err := http.ListenAndServe(":"+port, router); err != nil {
		log.Fatalf("❌ Server failed to start: %v", err)
	}
}

func initDatabase() (*gorm.DB, error) {
	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		dsn = "postgres://kb4_safety_user:kb4_safety_password@localhost:5436/kb4_patient_safety?sslmode=disable"
	}

	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		return nil, err
	}

	// Test connection
	sqlDB, err := db.DB()
	if err != nil {
		return nil, err
	}

	if err := sqlDB.Ping(); err != nil {
		return nil, err
	}

	return db, nil
}

func setupRoutes(router *gin.Engine, db *gorm.DB) {
	// Health endpoints
	router.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status":    "healthy",
			"service":   serviceName,
			"timestamp": time.Now().UTC(),
			"version":   serviceVersion,
			"features":  []string{"Safety Monitoring", "Apollo Federation", "TimescaleDB"},
		})
	})

	router.GET("/ready", func(c *gin.Context) {
		sqlDB, err := db.DB()
		if err != nil || sqlDB.Ping() != nil {
			c.JSON(503, gin.H{"status": "not ready", "error": "database unavailable"})
			return
		}
		c.JSON(200, gin.H{
			"status":    "ready",
			"service":   serviceName,
			"database":  "connected",
			"timestamp": time.Now().UTC(),
		})
	})

	// API v1 routes
	v1 := router.Group("/v1")
	{
		// Existing alert management endpoints
		v1.GET("/alerts", getSafetyAlerts(db))
		v1.POST("/alerts", createSafetyAlert(db))
		v1.GET("/stats", getServiceStats(db))
		v1.PUT("/alerts/:alert_id/override", overrideSafetyAlert(db))

		// NEW: Core safety check endpoints
		v1.POST("/check", handleSafetyCheck())
		v1.POST("/check/comprehensive", handleComprehensiveSafetyCheck())

		// NEW: Black Box Warning endpoints
		v1.GET("/blackbox", handleGetBlackBoxWarning())
		v1.GET("/blackbox/list", handleListBlackBoxWarnings())
		v1.GET("/blackbox/search", handleSearchBlackBoxWarnings())

		// NEW: Contraindication endpoints
		v1.GET("/contraindications", handleGetContraindications())
		v1.POST("/contraindications/check", handleCheckContraindications())

		// NEW: Dose limit endpoints
		v1.GET("/limits/dose", handleGetDoseLimits())
		v1.GET("/limits/age", handleGetAgeLimits())
		v1.POST("/limits/validate", handleValidateDose())

		// NEW: Pregnancy/Lactation endpoints
		v1.GET("/pregnancy", handleGetPregnancySafety())
		v1.GET("/lactation", handleGetLactationSafety())

		// NEW: High-Alert medication endpoints
		v1.GET("/high-alert", handleGetHighAlertStatus())
		v1.GET("/high-alert/list", handleListHighAlertMedications())

		// NEW: Beers Criteria endpoints
		v1.GET("/beers", handleGetBeersEntry())
		v1.POST("/beers/check", handleCheckBeersCriteria())

		// NEW: Anticholinergic burden endpoints
		v1.GET("/anticholinergic", handleGetAnticholinergicBurden())
		v1.POST("/anticholinergic/burden", handleCalculateAnticholinergicBurden())

		// NEW: Lab requirements endpoint
		v1.GET("/labs", handleGetLabRequirements())

		// NEW: Explainability endpoints (P1 - Clinical Decision Explanation)
		v1.GET("/explain/blackbox", handleExplainBlackBox())
		v1.GET("/explain/alert/:alertId", handleExplainAlert())
		v1.POST("/explain/check", handleExplainSafetyCheck())

		// NEW: Clinical threshold endpoints (consumed by Flink BroadcastState)
		v1.GET("/thresholds/vitals", thresholds.HandleGetVitalThresholds)
		v1.GET("/thresholds/early-warning-scores", thresholds.HandleGetEarlyWarningScores)
	}

	// Also mount under /api/v1 for compatibility
	apiV1 := router.Group("/api/v1")
	{
		apiV1.POST("/check", handleSafetyCheck())
		apiV1.POST("/check/comprehensive", handleComprehensiveSafetyCheck())
		apiV1.GET("/blackbox", handleGetBlackBoxWarning())
		apiV1.GET("/blackbox/list", handleListBlackBoxWarnings())
		apiV1.GET("/contraindications", handleGetContraindications())
		apiV1.GET("/limits/dose", handleGetDoseLimits())
		apiV1.GET("/pregnancy", handleGetPregnancySafety())
		apiV1.GET("/lactation", handleGetLactationSafety())
		apiV1.GET("/high-alert", handleGetHighAlertStatus())
		apiV1.GET("/high-alert/list", handleListHighAlertMedications())
		apiV1.GET("/beers", handleGetBeersEntry())
		apiV1.GET("/anticholinergic", handleGetAnticholinergicBurden())
		apiV1.GET("/labs", handleGetLabRequirements())
	}
}

func getSafetyAlerts(db *gorm.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		patientID := c.Query("patient_id")
		severity := c.Query("severity")
		active := c.Query("active")

		var alerts []SafetyAlert
		query := db.Model(&SafetyAlert{})

		if patientID != "" {
			query = query.Where("patient_id = ?", patientID)
		}
		if severity != "" {
			query = query.Where("severity = ?", severity)
		}
		if active != "" {
			if active == "true" {
				query = query.Where("override_status = ?", "active")
			}
		}

		if err := query.Order("created_at DESC").Find(&alerts).Error; err != nil {
			c.JSON(500, gin.H{
				"success": false,
				"error":   "Failed to retrieve safety alerts",
				"details": err.Error(),
			})
			return
		}

		c.JSON(200, gin.H{
			"success": true,
			"alerts":  alerts,
			"count":   len(alerts),
		})
	}
}

func createSafetyAlert(db *gorm.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var request struct {
			PatientID       string   `json:"patient_id" binding:"required"`
			DrugCode        string   `json:"drug_code" binding:"required"`
			RuleID          string   `json:"rule_id" binding:"required"`
			Severity        string   `json:"severity" binding:"required"`
			Action          string   `json:"action" binding:"required"`
			Message         string   `json:"message" binding:"required"`
			KB1RuleRefs     []string `json:"kb1_rule_refs"`
			PatientContext  string   `json:"patient_context"`
		}

		if err := c.ShouldBindJSON(&request); err != nil {
			c.JSON(400, gin.H{
				"success": false,
				"error":   "Invalid request format",
				"details": err.Error(),
			})
			return
		}

		alert := &SafetyAlert{
			AlertID:         fmt.Sprintf("KB4-%d", time.Now().Unix()),
			PatientID:       request.PatientID,
			DrugCode:        request.DrugCode,
			RuleID:          request.RuleID,
			Severity:        request.Severity,
			Action:          request.Action,
			Message:         request.Message,
			KB1RuleRefs:     request.KB1RuleRefs,
			PatientContext:  request.PatientContext,
			OverrideStatus:  "active",
			CreatedBy:       "kb4-safety-engine",
		}

		if err := db.Create(alert).Error; err != nil {
			c.JSON(500, gin.H{
				"success": false,
				"error":   "Failed to create safety alert",
				"details": err.Error(),
			})
			return
		}

		log.Printf("✅ Safety alert created: %s for patient %s", alert.AlertID, alert.PatientID)

		c.JSON(200, gin.H{
			"success":  true,
			"alert_id": alert.AlertID,
			"message":  "Safety alert created successfully",
			"alert":    alert,
		})
	}
}

func overrideSafetyAlert(db *gorm.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		alertID := c.Param("alert_id")

		var request struct {
			OverrideReason string `json:"override_reason" binding:"required"`
			OverrideBy     string `json:"override_by" binding:"required"`
		}

		if err := c.ShouldBindJSON(&request); err != nil {
			c.JSON(400, gin.H{
				"success": false,
				"error":   "Invalid request format",
				"details": err.Error(),
			})
			return
		}

		var alert SafetyAlert
		if err := db.Where("alert_id = ?", alertID).First(&alert).Error; err != nil {
			c.JSON(404, gin.H{
				"success": false,
				"error":   "Safety alert not found",
				"alert_id": alertID,
			})
			return
		}

		now := time.Now()
		alert.OverrideStatus = "overridden"
		alert.OverrideReason = request.OverrideReason
		alert.OverrideBy = request.OverrideBy
		alert.OverrideTime = &now

		if err := db.Save(&alert).Error; err != nil {
			c.JSON(500, gin.H{
				"success": false,
				"error":   "Failed to override safety alert",
				"details": err.Error(),
			})
			return
		}

		log.Printf("✅ Safety alert overridden: %s by %s", alert.AlertID, request.OverrideBy)

		c.JSON(200, gin.H{
			"success": true,
			"message": "Safety alert overridden successfully",
			"alert":   alert,
		})
	}
}

func getServiceStats(db *gorm.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var totalAlerts int64
		db.Model(&SafetyAlert{}).Count(&totalAlerts)

		var criticalAlerts int64
		db.Model(&SafetyAlert{}).Where("severity = ?", "CRITICAL").Count(&criticalAlerts)

		var activeAlerts int64
		db.Model(&SafetyAlert{}).Where("override_status = ?", "active").Count(&activeAlerts)

		var patientsMonitored int64
		db.Model(&SafetyAlert{}).Distinct("patient_id").Count(&patientsMonitored)

		c.JSON(200, gin.H{
			"success":           true,
			"total_alerts":      totalAlerts,
			"critical_alerts":   criticalAlerts,
			"active_alerts":     activeAlerts,
			"resolved_alerts":   totalAlerts - activeAlerts,
			"patients_monitored": patientsMonitored,
			"service":          serviceName,
			"version":          serviceVersion,
			"last_updated":     time.Now().UTC(),
		})
	}
}

// GraphQL Federation setup
func setupGraphQLFederation(router *gin.Engine, db *gorm.DB) {
	// Apollo Federation introspection endpoint
	router.POST("/api/federation", handleGraphQLFederation(db))

	// Schema introspection for Federation v2
	router.GET("/api/federation", func(c *gin.Context) {
		c.Header("Content-Type", "application/json")
		response := map[string]interface{}{
			"data": map[string]interface{}{
				"_service": map[string]interface{}{
					"sdl": federationSchema,
				},
			},
		}
		c.JSON(200, response)
	})
}

func handleGraphQLFederation(db *gorm.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req GraphQLRequest
		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(400, GraphQLResponse{
				Errors: []GraphQLError{{Message: "Invalid GraphQL request"}},
			})
			return
		}

		// Handle introspection queries
		if strings.Contains(req.Query, "_service") {
			c.JSON(200, GraphQLResponse{
				Data: map[string]interface{}{
					"_service": map[string]interface{}{
						"sdl": federationSchema,
					},
				},
			})
			return
		}

		// Handle entity resolution queries
		if strings.Contains(req.Query, "_entities") {
			handleEntityResolution(c, req, db)
			return
		}

		// Handle regular queries
		handleGraphQLQuery(c, req, db)
	}
}

func handleEntityResolution(c *gin.Context, req GraphQLRequest, db *gorm.DB) {
	// Extract representations from variables
	representations, ok := req.Variables["representations"].([]interface{})
	if !ok {
		c.JSON(400, GraphQLResponse{
			Errors: []GraphQLError{{Message: "Invalid representations"}},
		})
		return
	}

	entities := make([]interface{}, 0)

	for _, repr := range representations {
		reprMap, ok := repr.(map[string]interface{})
		if !ok {
			continue
		}

		typename, _ := reprMap["__typename"].(string)

		switch typename {
		case "SafetyAlert":
			if alertId, ok := reprMap["alertId"].(string); ok {
				entity := resolveSafetyAlertEntity(alertId, db)
				entities = append(entities, entity)
			}
		case "DrugRule":
			if drugId, ok := reprMap["drugId"].(string); ok {
				entity := resolveDrugRuleEntity(drugId, reprMap, db)
				entities = append(entities, entity)
			}
		}
	}

	c.JSON(200, GraphQLResponse{
		Data: map[string]interface{}{
			"_entities": entities,
		},
	})
}

func handleGraphQLQuery(c *gin.Context, req GraphQLRequest, db *gorm.DB) {
	// Simple query routing based on operation
	query := strings.ToLower(req.Query)

	if strings.Contains(query, "safetyalerts") {
		handleSafetyAlertsQuery(c, req, db)
	} else if strings.Contains(query, "kb4statistics") {
		handleKB4StatisticsQuery(c, req, db)
	} else {
		c.JSON(400, GraphQLResponse{
			Errors: []GraphQLError{{Message: "Unsupported GraphQL operation"}},
		})
	}
}

func handleSafetyAlertsQuery(c *gin.Context, req GraphQLRequest, db *gorm.DB) {
	// Extract patientId from variables or query
	patientId := extractStringVariable(req.Variables, "patientId")

	var alerts []SafetyAlert
	query := db.Model(&SafetyAlert{})

	if patientId != "" {
		query = query.Where("patient_id = ?", patientId)
	}

	if err := query.Order("created_at DESC").Find(&alerts).Error; err != nil {
		c.JSON(500, GraphQLResponse{
			Errors: []GraphQLError{{Message: fmt.Sprintf("Failed to fetch safety alerts: %v", err)}},
		})
		return
	}

	// Convert to GraphQL format
	gqlAlerts := make([]map[string]interface{}, len(alerts))
	for i, alert := range alerts {
		gqlAlerts[i] = convertAlertToGraphQL(alert)
	}

	c.JSON(200, GraphQLResponse{
		Data: map[string]interface{}{
			"safetyAlerts": gqlAlerts,
		},
	})
}

func handleKB4StatisticsQuery(c *gin.Context, req GraphQLRequest, db *gorm.DB) {
	var totalAlerts int64
	db.Model(&SafetyAlert{}).Count(&totalAlerts)

	var criticalAlerts int64
	db.Model(&SafetyAlert{}).Where("severity = ?", "CRITICAL").Count(&criticalAlerts)

	var activeAlerts int64
	db.Model(&SafetyAlert{}).Where("override_status = ?", "active").Count(&activeAlerts)

	var patientsMonitored int64
	db.Model(&SafetyAlert{}).Distinct("patient_id").Count(&patientsMonitored)

	stats := map[string]interface{}{
		"totalAlerts":       totalAlerts,
		"criticalAlerts":    criticalAlerts,
		"activeAlerts":      activeAlerts,
		"resolvedAlerts":    totalAlerts - activeAlerts,
		"patientsMonitored": patientsMonitored,
		"lastUpdated":       time.Now().UTC().Format(time.RFC3339),
	}

	c.JSON(200, GraphQLResponse{
		Data: map[string]interface{}{
			"kb4Statistics": stats,
		},
	})
}

// Entity resolution functions
func resolveSafetyAlertEntity(alertId string, db *gorm.DB) map[string]interface{} {
	var alert SafetyAlert
	if err := db.Where("alert_id = ?", alertId).First(&alert).Error; err != nil {
		// Return minimal entity for demo
		return map[string]interface{}{
			"alertId":    alertId,
			"patientId":  "unknown",
			"severity":   "INFO",
			"action":     "PASS",
			"message":    "Alert not found in KB-4",
			"kb1RuleRefs": []string{},
			"overrideStatus": "active",
		}
	}

	return convertAlertToGraphQL(alert)
}

func resolveDrugRuleEntity(drugId string, repr map[string]interface{}, db *gorm.DB) map[string]interface{} {
	// Get safety alerts for this drug
	var alerts []SafetyAlert
	db.Where("drug_code = ?", drugId).Find(&alerts)

	// Convert to GraphQL format
	gqlAlerts := make([]map[string]interface{}, len(alerts))
	for i, alert := range alerts {
		gqlAlerts[i] = convertAlertToGraphQL(alert)
	}

	return map[string]interface{}{
		"drugId":       drugId,
		"version":      repr["version"],
		"safetyAlerts": gqlAlerts,
		"riskScore":    calculateRiskScore(alerts),
		"lastEvaluated": time.Now().UTC().Format(time.RFC3339),
	}
}

// Helper functions
func extractStringVariable(variables map[string]interface{}, key string) string {
	if val, ok := variables[key].(string); ok {
		return val
	}
	return ""
}

func convertAlertToGraphQL(alert SafetyAlert) map[string]interface{} {
	gqlAlert := map[string]interface{}{
		"alertId":           alert.AlertID,
		"patientId":         alert.PatientID,
		"drugCode":          alert.DrugCode,
		"ruleId":            alert.RuleID,
		"severity":          alert.Severity,
		"action":            alert.Action,
		"message":           alert.Message,
		"kb1RuleRefs":       alert.KB1RuleRefs,
		"kb3EvidenceRefs":   alert.KB3EvidenceRefs,
		"patientContext":    alert.PatientContext,
		"overrideStatus":    alert.OverrideStatus,
		"overrideReason":    alert.OverrideReason,
		"overrideBy":        alert.OverrideBy,
		"createdBy":         alert.CreatedBy,
		"createdAt":         alert.CreatedAt.Format(time.RFC3339),
		"updatedAt":         alert.UpdatedAt.Format(time.RFC3339),
	}

	if alert.OverrideTime != nil {
		gqlAlert["overrideTimestamp"] = alert.OverrideTime.Format(time.RFC3339)
	}

	return gqlAlert
}

func calculateRiskScore(alerts []SafetyAlert) float64 {
	if len(alerts) == 0 {
		return 0.0
	}

	score := 0.0
	for _, alert := range alerts {
		switch alert.Severity {
		case "CRITICAL":
			score += 10.0
		case "WARN":
			score += 5.0
		case "INFO":
			score += 1.0
		}
	}

	// Normalize to 0-100 scale
	return score / float64(len(alerts)) * 10
}

// =============================================================================
// SAFETY CHECK HANDLERS - Comprehensive Drug Safety Evaluation
// =============================================================================

// handleSafetyCheck performs comprehensive safety evaluation for a drug
func handleSafetyCheck() gin.HandlerFunc {
	return func(c *gin.Context) {
		var req safety.SafetyCheckRequest
		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{
				"error":   "Invalid request format",
				"details": err.Error(),
			})
			return
		}

		// Validate required fields
		if req.Drug.RxNormCode == "" && req.Drug.DrugName == "" {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "Either rxnormCode or drugName is required",
			})
			return
		}

		response := safetyChecker.Check(&req)
		c.JSON(http.StatusOK, response)
	}
}

// handleComprehensiveSafetyCheck performs all safety checks with detailed reporting
func handleComprehensiveSafetyCheck() gin.HandlerFunc {
	return func(c *gin.Context) {
		var req safety.SafetyCheckRequest
		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{
				"error":   "Invalid request format",
				"details": err.Error(),
			})
			return
		}

		// Force all check types for comprehensive evaluation
		req.CheckTypes = nil // Empty means all checks

		response := safetyChecker.Check(&req)

		// Add detailed breakdown
		result := gin.H{
			"safetyCheck":    response,
			"checkPerformed": []string{
				"BLACK_BOX_WARNING",
				"CONTRAINDICATION",
				"AGE_LIMIT",
				"DOSE_LIMIT",
				"PREGNANCY",
				"LACTATION",
				"HIGH_ALERT",
				"BEERS_CRITERIA",
				"ANTICHOLINERGIC",
				"LAB_REQUIRED",
			},
			"patientContext": req.Patient,
			"drugInfo":       req.Drug,
		}

		c.JSON(http.StatusOK, result)
	}
}

// handleGetBlackBoxWarning retrieves black box warning for a drug
// Uses governed knowledge first, falls back to hardcoded data
func handleGetBlackBoxWarning() gin.HandlerFunc {
	return func(c *gin.Context) {
		rxnorm := c.Query("rxnorm")
		drugName := c.Query("drugName")

		if rxnorm == "" && drugName == "" {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "Either rxnorm or drugName query parameter is required",
			})
			return
		}

		var warning *safety.BlackBoxWarning
		var found bool

		if rxnorm != "" {
			// Use safetyChecker which prefers governed knowledge
			warning, found = safetyChecker.GetBlackBoxWarning(rxnorm)
		} else {
			// Search by drug name - fallback to database for now
			db := safety.GetDatabase()
			warnings := db.GetAllBlackBoxWarnings()
			for _, w := range warnings {
				if strings.EqualFold(w.DrugName, drugName) {
					warning = w
					found = true
					break
				}
			}
		}

		if !found || warning == nil {
			c.JSON(http.StatusOK, gin.H{
				"found":   false,
				"message": "No black box warning found for this drug",
			})
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"found":   true,
			"warning": warning,
		})
	}
}

// handleListBlackBoxWarnings lists all drugs with black box warnings
func handleListBlackBoxWarnings() gin.HandlerFunc {
	return func(c *gin.Context) {
		db := safety.GetDatabase()
		warnings := db.GetAllBlackBoxWarnings()

		c.JSON(http.StatusOK, gin.H{
			"count":    len(warnings),
			"warnings": warnings,
		})
	}
}

// handleSearchBlackBoxWarnings searches black box warnings by risk category
func handleSearchBlackBoxWarnings() gin.HandlerFunc {
	return func(c *gin.Context) {
		category := c.Query("category")
		hasRems := c.Query("hasRems")

		db := safety.GetDatabase()
		warnings := db.GetAllBlackBoxWarnings()

		var filtered []*safety.BlackBoxWarning
		for _, w := range warnings {
			// Filter by category
			if category != "" {
				found := false
				for _, cat := range w.RiskCategories {
					if strings.Contains(strings.ToLower(cat), strings.ToLower(category)) {
						found = true
						break
					}
				}
				if !found {
					continue
				}
			}

			// Filter by REMS requirement
			if hasRems != "" {
				wantsRems := hasRems == "true" || hasRems == "1"
				if w.HasREMS != wantsRems {
					continue
				}
			}

			filtered = append(filtered, w)
		}

		c.JSON(http.StatusOK, gin.H{
			"count":    len(filtered),
			"filters":  gin.H{"category": category, "hasRems": hasRems},
			"warnings": filtered,
		})
	}
}

// handleGetContraindications retrieves contraindications for a drug
func handleGetContraindications() gin.HandlerFunc {
	return func(c *gin.Context) {
		rxnorm := c.Query("rxnorm")

		if rxnorm == "" {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "rxnorm query parameter is required",
			})
			return
		}

		db := safety.GetDatabase()
		contraindications := db.GetContraindications(rxnorm)

		c.JSON(http.StatusOK, gin.H{
			"rxnormCode":       rxnorm,
			"count":            len(contraindications),
			"contraindications": contraindications,
		})
	}
}

// handleCheckContraindications checks contraindications against patient diagnoses
func handleCheckContraindications() gin.HandlerFunc {
	return func(c *gin.Context) {
		var req struct {
			RxNormCode string            `json:"rxnormCode"`
			Diagnoses  []safety.Diagnosis `json:"diagnoses"`
		}

		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{
				"error":   "Invalid request format",
				"details": err.Error(),
			})
			return
		}

		db := safety.GetDatabase()
		contraindications := db.GetContraindications(req.RxNormCode)

		var matches []gin.H
		for _, ci := range contraindications {
			for _, diag := range req.Diagnoses {
				for _, ciCode := range ci.ConditionCodes {
					if strings.HasPrefix(diag.Code, ciCode) || ciCode == diag.Code {
						matches = append(matches, gin.H{
							"contraindication": ci,
							"matchedDiagnosis": diag,
							"severity":         ci.Severity,
						})
					}
				}
			}
		}

		c.JSON(http.StatusOK, gin.H{
			"rxnormCode":      req.RxNormCode,
			"hasContraindication": len(matches) > 0,
			"matchCount":      len(matches),
			"matches":         matches,
		})
	}
}

// handleGetDoseLimits retrieves dose limits for a drug
func handleGetDoseLimits() gin.HandlerFunc {
	return func(c *gin.Context) {
		rxnorm := c.Query("rxnorm")

		if rxnorm == "" {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "rxnorm query parameter is required",
			})
			return
		}

		db := safety.GetDatabase()
		limits := db.GetDoseLimit(rxnorm)

		if limits == nil {
			c.JSON(http.StatusOK, gin.H{
				"found":   false,
				"message": "No dose limits defined for this drug",
			})
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"found":  true,
			"limits": limits,
		})
	}
}

// handleGetAgeLimits retrieves age restrictions for a drug
func handleGetAgeLimits() gin.HandlerFunc {
	return func(c *gin.Context) {
		rxnorm := c.Query("rxnorm")

		if rxnorm == "" {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "rxnorm query parameter is required",
			})
			return
		}

		db := safety.GetDatabase()
		limits := db.GetAgeLimit(rxnorm)

		if limits == nil {
			c.JSON(http.StatusOK, gin.H{
				"found":   false,
				"message": "No age restrictions defined for this drug",
			})
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"found":  true,
			"limits": limits,
		})
	}
}

// handleValidateDose validates a proposed dose against limits
func handleValidateDose() gin.HandlerFunc {
	return func(c *gin.Context) {
		var req struct {
			Drug         safety.DrugInfo       `json:"drug"`
			ProposedDose float64               `json:"proposedDose"`
			DoseUnit     string                `json:"doseUnit"`
			Patient      safety.PatientContext `json:"patient"`
		}
		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{
				"error":   "Invalid request format",
				"details": err.Error(),
			})
			return
		}

		result := safetyChecker.ValidateDose(req.Drug, req.ProposedDose, req.DoseUnit, req.Patient)
		c.JSON(http.StatusOK, result)
	}
}

// handleGetPregnancySafety retrieves pregnancy safety information
// Uses governed knowledge first, falls back to hardcoded data
func handleGetPregnancySafety() gin.HandlerFunc {
	return func(c *gin.Context) {
		rxnorm := c.Query("rxnorm")

		if rxnorm == "" {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "rxnorm query parameter is required",
			})
			return
		}

		info, found := safetyChecker.GetPregnancySafety(rxnorm)

		if !found || info == nil {
			c.JSON(http.StatusOK, gin.H{
				"found":   false,
				"message": "No pregnancy safety information available",
			})
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"found": true,
			"info":  info,
		})
	}
}

// handleGetLactationSafety retrieves lactation safety information
// Uses governed knowledge first, falls back to hardcoded data
func handleGetLactationSafety() gin.HandlerFunc {
	return func(c *gin.Context) {
		rxnorm := c.Query("rxnorm")

		if rxnorm == "" {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "rxnorm query parameter is required",
			})
			return
		}

		info, found := safetyChecker.GetLactationSafety(rxnorm)

		if !found || info == nil {
			c.JSON(http.StatusOK, gin.H{
				"found":   false,
				"message": "No lactation safety information available",
			})
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"found": true,
			"info":  info,
		})
	}
}

// handleGetHighAlertStatus checks if a drug is high-alert
// Uses governed knowledge first, falls back to hardcoded data
func handleGetHighAlertStatus() gin.HandlerFunc {
	return func(c *gin.Context) {
		rxnorm := c.Query("rxnorm")

		if rxnorm == "" {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "rxnorm query parameter is required",
			})
			return
		}

		info, found := safetyChecker.GetHighAlertMedication(rxnorm)

		if !found || info == nil {
			c.JSON(http.StatusOK, gin.H{
				"isHighAlert": false,
				"message":     "Drug is not classified as high-alert",
			})
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"isHighAlert": true,
			"info":        info,
		})
	}
}

// handleListHighAlertMedications lists all high-alert medications
func handleListHighAlertMedications() gin.HandlerFunc {
	return func(c *gin.Context) {
		category := c.Query("category")

		db := safety.GetDatabase()
		medications := db.GetAllHighAlertMedications()

		var filtered []*safety.HighAlertMedication
		if category != "" {
			for _, med := range medications {
				if strings.EqualFold(string(med.Category), category) {
					filtered = append(filtered, med)
				}
			}
		} else {
			filtered = medications
		}

		// Group by category for summary
		categoryCounts := make(map[string]int)
		for _, med := range medications {
			categoryCounts[string(med.Category)]++
		}

		c.JSON(http.StatusOK, gin.H{
			"count":          len(filtered),
			"filter":         category,
			"categoryCounts": categoryCounts,
			"medications":    filtered,
		})
	}
}

// handleGetBeersEntry retrieves Beers Criteria entry for a drug
// Uses governed knowledge first, falls back to hardcoded data
func handleGetBeersEntry() gin.HandlerFunc {
	return func(c *gin.Context) {
		rxnorm := c.Query("rxnorm")

		if rxnorm == "" {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "rxnorm query parameter is required",
			})
			return
		}

		entry, found := safetyChecker.GetBeersEntry(rxnorm)

		if !found || entry == nil {
			c.JSON(http.StatusOK, gin.H{
				"found":   false,
				"message": "Drug not listed in Beers Criteria",
			})
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"found": true,
			"entry": entry,
		})
	}
}

// handleCheckBeersCriteria checks a medication list against Beers Criteria
func handleCheckBeersCriteria() gin.HandlerFunc {
	return func(c *gin.Context) {
		var req struct {
			Medications []safety.DrugInfo  `json:"medications"`
			AgeYears    float64            `json:"ageYears"`
			Diagnoses   []safety.Diagnosis `json:"diagnoses,omitempty"`
		}

		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{
				"error":   "Invalid request format",
				"details": err.Error(),
			})
			return
		}

		// Beers Criteria applies to patients ≥65 years
		if req.AgeYears < 65 {
			c.JSON(http.StatusOK, gin.H{
				"applicable": false,
				"message":    "Beers Criteria applies to patients 65 years and older",
				"patientAge": req.AgeYears,
			})
			return
		}

		alerts := safetyChecker.CheckBeers(req.Medications, req.AgeYears)
		c.JSON(http.StatusOK, gin.H{
			"applicable":     true,
			"patientAge":     req.AgeYears,
			"medicationCount": len(req.Medications),
			"alertCount":     len(alerts),
			"alerts":         alerts,
		})
	}
}

// handleGetAnticholinergicBurden retrieves ACB score for a drug
// Uses governed knowledge first, falls back to hardcoded data
func handleGetAnticholinergicBurden() gin.HandlerFunc {
	return func(c *gin.Context) {
		rxnorm := c.Query("rxnorm")

		if rxnorm == "" {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "rxnorm query parameter is required",
			})
			return
		}

		burden, found := safetyChecker.GetAnticholinergicBurden(rxnorm)

		if !found || burden == nil {
			c.JSON(http.StatusOK, gin.H{
				"found":    false,
				"acbScore": 0,
				"message":  "No anticholinergic burden data for this drug",
			})
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"found":  true,
			"burden": burden,
		})
	}
}

// handleCalculateAnticholinergicBurden calculates total ACB for medication list
func handleCalculateAnticholinergicBurden() gin.HandlerFunc {
	return func(c *gin.Context) {
		var req struct {
			Medications []safety.DrugInfo `json:"medications"`
		}

		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{
				"error":   "Invalid request format",
				"details": err.Error(),
			})
			return
		}

		result := safetyChecker.CalculateAnticholinergicBurden(req.Medications)
		c.JSON(http.StatusOK, result)
	}
}

// handleGetLabRequirements retrieves required lab monitoring for a drug
// Uses governed knowledge first, falls back to hardcoded data
func handleGetLabRequirements() gin.HandlerFunc {
	return func(c *gin.Context) {
		rxnorm := c.Query("rxnorm")

		if rxnorm == "" {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "rxnorm query parameter is required",
			})
			return
		}

		reqs, found := safetyChecker.GetLabRequirement(rxnorm)

		if !found || reqs == nil {
			c.JSON(http.StatusOK, gin.H{
				"found":   false,
				"message": "No specific lab requirements for this drug",
			})
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"found":        true,
			"requirements": reqs,
		})
	}
}

// =============================================================================
// EXPLAINABILITY HANDLERS - "Why did this alert fire?"
// =============================================================================

// handleExplainBlackBox explains why a black box warning fired for a drug
func handleExplainBlackBox() gin.HandlerFunc {
	return func(c *gin.Context) {
		rxnorm := c.Query("rxnorm")

		if rxnorm == "" {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "rxnorm query parameter is required",
			})
			return
		}

		explanation := alertExplainer.ExplainBlackBoxWarning(rxnorm)
		if explanation == nil {
			c.JSON(http.StatusOK, gin.H{
				"found":   false,
				"message": "No black box warning found for this drug",
			})
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"found":       true,
			"explanation": explanation,
		})
	}
}

// handleExplainAlert explains a specific safety alert by its ID
func handleExplainAlert() gin.HandlerFunc {
	return func(c *gin.Context) {
		alertID := c.Param("alertId")

		if alertID == "" {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "alertId path parameter is required",
			})
			return
		}

		// For now, return a placeholder - in production, this would look up the alert
		c.JSON(http.StatusOK, gin.H{
			"alertId": alertID,
			"message": "Alert explanation endpoint - provide alert details in POST /explain/check for full explanation",
			"usage":   "Use POST /v1/explain/check with drug and patient context for detailed explanations",
		})
	}
}

// handleExplainSafetyCheck performs a safety check and returns detailed explanations
func handleExplainSafetyCheck() gin.HandlerFunc {
	return func(c *gin.Context) {
		var req safety.SafetyCheckRequest
		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{
				"error":   "Invalid request format",
				"details": err.Error(),
			})
			return
		}

		// Validate required fields
		if req.Drug.RxNormCode == "" && req.Drug.DrugName == "" {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "Either rxnormCode or drugName is required in drug field",
			})
			return
		}

		// Run safety check
		result := safetyChecker.Check(&req)

		// Generate explanations for all alerts
		explanation := alertExplainer.ExplainSafetyCheckResult(result, &req.Patient)

		c.JSON(http.StatusOK, gin.H{
			"safetyCheck": result,
			"explanation": explanation,
			"auditInfo": gin.H{
				"requestId":   result.RequestID,
				"checkedAt":   result.CheckedAt,
				"explainedAt": explanation.GeneratedAt,
				"service":     serviceName,
				"version":     serviceVersion,
			},
		})
	}
}