#!/bin/bash

# Setup script for local PostgreSQL database for KB-Drug-Rules service
# This script works on Linux/macOS

set -e

echo "🗄️  Setting up local PostgreSQL for KB-Drug-Rules service..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
DB_NAME="kb_drug_rules"
DB_USER="kb_drug_rules_user"
DB_PASSWORD="kb_password"
POSTGRES_USER="postgres"

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if PostgreSQL is installed
check_postgres() {
    print_status "Checking PostgreSQL installation..."
    
    if command -v psql >/dev/null 2>&1; then
        PSQL_VERSION=$(psql --version | head -n1)
        print_success "PostgreSQL found: $PSQL_VERSION"
        return 0
    else
        print_error "PostgreSQL is not installed or not in PATH"
        echo ""
        echo "Please install PostgreSQL first:"
        echo "  Ubuntu/Debian: sudo apt-get install postgresql postgresql-contrib"
        echo "  CentOS/RHEL:   sudo yum install postgresql-server postgresql-contrib"
        echo "  macOS:         brew install postgresql"
        echo "  Windows:       Download from https://www.postgresql.org/download/windows/"
        return 1
    fi
}

# Check if PostgreSQL service is running
check_postgres_service() {
    print_status "Checking PostgreSQL service..."
    
    # Try to connect to PostgreSQL
    if pg_isready -h localhost -p 5432 >/dev/null 2>&1; then
        print_success "PostgreSQL service is running"
        return 0
    else
        print_warning "PostgreSQL service is not running"
        echo ""
        echo "Please start PostgreSQL service:"
        echo "  Ubuntu/Debian: sudo systemctl start postgresql"
        echo "  CentOS/RHEL:   sudo systemctl start postgresql"
        echo "  macOS:         brew services start postgresql"
        echo "  Windows:       Start PostgreSQL service from Services panel"
        echo ""
        read -p "Press Enter after starting PostgreSQL service..."
        
        # Check again
        if pg_isready -h localhost -p 5432 >/dev/null 2>&1; then
            print_success "PostgreSQL service is now running"
            return 0
        else
            print_error "PostgreSQL service is still not running"
            return 1
        fi
    fi
}

# Setup database
setup_database() {
    print_status "Setting up KB-Drug-Rules database..."
    
    # Get the directory of this script
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    SQL_FILE="$SCRIPT_DIR/setup-local-postgres.sql"
    
    if [ ! -f "$SQL_FILE" ]; then
        print_error "SQL setup file not found: $SQL_FILE"
        return 1
    fi
    
    # Try to run the SQL setup script
    print_status "Running database setup script..."
    
    # First, try with peer authentication (common on Linux)
    if sudo -u postgres psql -f "$SQL_FILE" >/dev/null 2>&1; then
        print_success "Database setup completed using peer authentication"
        return 0
    fi
    
    # If peer auth fails, try with password
    echo ""
    echo "Please enter the PostgreSQL superuser password (usually for user 'postgres'):"
    if psql -U postgres -h localhost -f "$SQL_FILE"; then
        print_success "Database setup completed using password authentication"
        return 0
    else
        print_error "Failed to setup database"
        return 1
    fi
}

# Test database connection
test_connection() {
    print_status "Testing database connection..."
    
    # Test connection with the new user
    export PGPASSWORD="$DB_PASSWORD"
    
    if psql -U "$DB_USER" -h localhost -d "$DB_NAME" -c "SELECT 'Connection successful!' as status;" >/dev/null 2>&1; then
        print_success "Database connection test passed"
        
        # Show sample data
        echo ""
        print_status "Sample data in database:"
        psql -U "$DB_USER" -h localhost -d "$DB_NAME" -c "SELECT drug_id, version, signature_valid FROM drug_rule_packs;"
        
        return 0
    else
        print_error "Database connection test failed"
        return 1
    fi
}

# Create environment file
create_env_file() {
    print_status "Creating environment configuration..."
    
    ENV_FILE="../.env.local"
    
    cat > "$ENV_FILE" << EOF
# Local PostgreSQL configuration for KB-Drug-Rules service
# Generated by setup-local-postgres.sh

# Server configuration
PORT=8081
DEBUG=true

# Database configuration
DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@localhost:5432/$DB_NAME

# Redis configuration (you'll need to install Redis separately)
REDIS_URL=redis://localhost:6379/0

# Security configuration
SIGNING_KEY_PATH=./keys/signing.key
JWT_SECRET=your-jwt-secret-key-here
REQUIRE_APPROVAL=false
REQUIRE_SIGNATURE=false

# Regional configuration
SUPPORTED_REGIONS=US,EU,CA,AU
DEFAULT_REGION=US

# Monitoring configuration
METRICS_ENABLED=true
TRACING_ENABLED=false
EOF

    print_success "Environment file created: $ENV_FILE"
    
    echo ""
    echo "Database connection details:"
    echo "  Host:     localhost"
    echo "  Port:     5432"
    echo "  Database: $DB_NAME"
    echo "  Username: $DB_USER"
    echo "  Password: $DB_PASSWORD"
}

# Main execution
main() {
    echo "🚀 KB-Drug-Rules PostgreSQL Setup"
    echo "=================================="
    echo ""
    
    # Run setup steps
    if ! check_postgres; then
        exit 1
    fi
    
    if ! check_postgres_service; then
        exit 1
    fi
    
    if ! setup_database; then
        exit 1
    fi
    
    if ! test_connection; then
        exit 1
    fi
    
    create_env_file
    
    echo ""
    echo "🎉 Setup completed successfully!"
    echo ""
    echo "Next steps:"
    echo "1. Install Redis (if not already installed):"
    echo "   Ubuntu/Debian: sudo apt-get install redis-server"
    echo "   macOS:         brew install redis"
    echo ""
    echo "2. Start the KB-Drug-Rules service:"
    echo "   cd ../kb-drug-rules"
    echo "   export \$(cat ../.env.local | xargs)"
    echo "   go run cmd/server/main.go"
    echo ""
    echo "3. Test the service:"
    echo "   curl http://localhost:8081/health"
    echo "   curl http://localhost:8081/v1/items/metformin"
    echo ""
    echo "4. Access database with:"
    echo "   psql -U $DB_USER -h localhost -d $DB_NAME"
    echo "   Password: $DB_PASSWORD"
}

# Run main function
main "$@"
