package orchestration

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-redis/redis/v8"
	"go.uber.org/zap"
)

// SLAManager manages Service Level Agreements for human review processes
type SLAManager struct {
	redis         *redis.Client
	notifier      NotificationService
	escalator     EscalationService
	logger        *zap.Logger
	slaConfig     *SLAConfiguration
}

// NotificationService defines interface for sending notifications
type NotificationService interface {
	SendImmediate(ctx context.Context, notification *SLANotification) error
	ScheduleAt(ctx context.Context, scheduledTime time.Time, notification *SLANotification) error
	CancelScheduled(ctx context.Context, notificationID string) error
}

// EscalationService defines interface for escalating overdue reviews
type EscalationService interface {
	EscalateReview(ctx context.Context, escalation *ReviewEscalation) error
	NotifySupervisor(ctx context.Context, reviewSLA *ReviewSLA) error
	CreateUrgentTicket(ctx context.Context, reviewSLA *ReviewSLA) error
}

// SLAConfiguration contains SLA management settings
type SLAConfiguration struct {
	// Standard human review SLA (2 hours per requirements)
	HumanReviewSLA         time.Duration `json:"human_review_sla"`

	// Escalation timelines
	FirstWarningOffset     time.Duration `json:"first_warning_offset"`     // 30 minutes before deadline
	SecondWarningOffset    time.Duration `json:"second_warning_offset"`    // 15 minutes before deadline
	EscalationOffset       time.Duration `json:"escalation_offset"`        // At deadline

	// Grace periods
	PostDeadlineGrace      time.Duration `json:"post_deadline_grace"`      // 15 minutes after deadline
	CriticalEscalation     time.Duration `json:"critical_escalation"`      // 1 hour after deadline

	// Retry configurations
	NotificationRetryCount int           `json:"notification_retry_count"`
	NotificationRetryDelay time.Duration `json:"notification_retry_delay"`
}

// ReviewSLA represents a human review SLA tracking entry
type ReviewSLA struct {
	ReviewID          string                 `json:"review_id"`
	WorkflowID        string                 `json:"workflow_id"`
	SessionID         string                 `json:"session_id,omitempty"`
	ReviewType        string                 `json:"review_type"` // CLINICAL_OVERRIDE, SAFETY_REVIEW, PEER_REVIEW
	RequiredLevel     string                 `json:"required_level"`
	AssignedReviewer  string                 `json:"assigned_reviewer,omitempty"`
	RequestedAt       time.Time              `json:"requested_at"`
	DeadlineAt        time.Time              `json:"deadline_at"`
	Status            ReviewSLAStatus        `json:"status"`
	Priority          ReviewPriority         `json:"priority"`

	// Escalation tracking
	EscalationLevel   int                    `json:"escalation_level"`
	LastNotifiedAt    *time.Time             `json:"last_notified_at,omitempty"`
	EscalatedAt       *time.Time             `json:"escalated_at,omitempty"`

	// Context for review
	Context           map[string]interface{} `json:"context"`
	ValidationFindings []ValidationFinding    `json:"validation_findings,omitempty"`

	// Resolution tracking
	ResolvedAt        *time.Time             `json:"resolved_at,omitempty"`
	ResolvedBy        string                 `json:"resolved_by,omitempty"`
	Resolution        string                 `json:"resolution,omitempty"`
	ResolutionNotes   string                 `json:"resolution_notes,omitempty"`

	CreatedAt         time.Time              `json:"created_at"`
	UpdatedAt         time.Time              `json:"updated_at"`
}

// SLANotification represents a scheduled notification
type SLANotification struct {
	NotificationID  string                 `json:"notification_id"`
	ReviewID        string                 `json:"review_id"`
	Type            NotificationType       `json:"type"`
	Priority        NotificationPriority   `json:"priority"`
	Recipients      []string               `json:"recipients"`
	Subject         string                 `json:"subject"`
	Message         string                 `json:"message"`
	ScheduledAt     time.Time              `json:"scheduled_at"`
	Context         map[string]interface{} `json:"context,omitempty"`
}

// ReviewEscalation represents an escalation event
type ReviewEscalation struct {
	EscalationID    string    `json:"escalation_id"`
	ReviewID        string    `json:"review_id"`
	EscalationType  string    `json:"escalation_type"`
	EscalatedTo     []string  `json:"escalated_to"`
	Reason          string    `json:"reason"`
	EscalatedAt     time.Time `json:"escalated_at"`
	AutoGenerated   bool      `json:"auto_generated"`
}

// Enums
type ReviewSLAStatus string

const (
	ReviewSLAStatusPending    ReviewSLAStatus = "PENDING"
	ReviewSLAStatusActive     ReviewSLAStatus = "ACTIVE"
	ReviewSLAStatusWarning    ReviewSLAStatus = "WARNING"
	ReviewSLAStatusOverdue    ReviewSLAStatus = "OVERDUE"
	ReviewSLAStatusEscalated  ReviewSLAStatus = "ESCALATED"
	ReviewSLAStatusResolved   ReviewSLAStatus = "RESOLVED"
	ReviewSLAStatusCancelled  ReviewSLAStatus = "CANCELLED"
)

type ReviewPriority string

const (
	ReviewPriorityLow      ReviewPriority = "LOW"
	ReviewPriorityNormal   ReviewPriority = "NORMAL"
	ReviewPriorityHigh     ReviewPriority = "HIGH"
	ReviewPriorityCritical ReviewPriority = "CRITICAL"
)

type NotificationType string

const (
	NotificationTypeAssignment    NotificationType = "ASSIGNMENT"
	NotificationTypeFirstWarning  NotificationType = "FIRST_WARNING"
	NotificationTypeSecondWarning NotificationType = "SECOND_WARNING"
	NotificationTypeDeadline      NotificationType = "DEADLINE"
	NotificationTypeOverdue       NotificationType = "OVERDUE"
	NotificationTypeEscalation    NotificationType = "ESCALATION"
)

type NotificationPriority string

const (
	NotificationPriorityNormal NotificationPriority = "NORMAL"
	NotificationPriorityHigh   NotificationPriority = "HIGH"
	NotificationPriorityUrgent NotificationPriority = "URGENT"
)

// NewSLAManager creates a new SLA Manager instance
func NewSLAManager(
	redis *redis.Client,
	notifier NotificationService,
	escalator EscalationService,
	logger *zap.Logger,
) *SLAManager {
	return &SLAManager{
		redis:     redis,
		notifier:  notifier,
		escalator: escalator,
		logger:    logger,
		slaConfig: DefaultSLAConfiguration(),
	}
}

// DefaultSLAConfiguration returns the default SLA configuration
func DefaultSLAConfiguration() *SLAConfiguration {
	return &SLAConfiguration{
		HumanReviewSLA:         2 * time.Hour,                // 2 hours per requirements
		FirstWarningOffset:     30 * time.Minute,             // 30 minutes before deadline
		SecondWarningOffset:    15 * time.Minute,             // 15 minutes before deadline
		EscalationOffset:       0 * time.Minute,              // At deadline
		PostDeadlineGrace:      15 * time.Minute,             // 15 minutes after deadline
		CriticalEscalation:     1 * time.Hour,                // 1 hour after deadline
		NotificationRetryCount: 3,
		NotificationRetryDelay: 5 * time.Minute,
	}
}

// StartSLATimer initiates SLA tracking for a human review request
func (s *SLAManager) StartSLATimer(
	ctx context.Context,
	workflowID string,
	reviewType string,
	requiredLevel string,
	assignedReviewer string,
	priority ReviewPriority,
	context map[string]interface{},
) (*ReviewSLA, error) {
	now := time.Now()
	reviewID := s.generateReviewID(workflowID, reviewType)

	// Calculate deadline based on review type and priority
	deadline := s.calculateDeadline(now, reviewType, priority)

	// Create ReviewSLA entry
	reviewSLA := &ReviewSLA{
		ReviewID:         reviewID,
		WorkflowID:       workflowID,
		ReviewType:       reviewType,
		RequiredLevel:    requiredLevel,
		AssignedReviewer: assignedReviewer,
		RequestedAt:      now,
		DeadlineAt:       deadline,
		Status:           ReviewSLAStatusPending,
		Priority:         priority,
		EscalationLevel:  0,
		Context:          context,
		CreatedAt:        now,
		UpdatedAt:        now,
	}

	s.logger.Info("Starting SLA timer for human review",
		zap.String("review_id", reviewID),
		zap.String("workflow_id", workflowID),
		zap.String("review_type", reviewType),
		zap.Time("deadline", deadline),
		zap.String("priority", string(priority)))

	// Store in Redis with expiration
	if err := s.storeReviewSLA(ctx, reviewSLA); err != nil {
		return nil, fmt.Errorf("failed to store review SLA: %w", err)
	}

	// Schedule notifications
	if err := s.scheduleNotifications(ctx, reviewSLA); err != nil {
		s.logger.Error("Failed to schedule notifications", zap.Error(err))
		// Don't fail the entire operation, continue without notifications
	}

	// Activate the SLA
	reviewSLA.Status = ReviewSLAStatusActive
	if err := s.updateReviewSLA(ctx, reviewSLA); err != nil {
		s.logger.Error("Failed to activate SLA", zap.Error(err))
	}

	return reviewSLA, nil
}

// ResolveSLA marks an SLA as resolved
func (s *SLAManager) ResolveSLA(
	ctx context.Context,
	reviewID string,
	resolvedBy string,
	resolution string,
	notes string,
) error {
	reviewSLA, err := s.getReviewSLA(ctx, reviewID)
	if err != nil {
		return fmt.Errorf("failed to get review SLA: %w", err)
	}

	now := time.Now()
	reviewSLA.Status = ReviewSLAStatusResolved
	reviewSLA.ResolvedAt = &now
	reviewSLA.ResolvedBy = resolvedBy
	reviewSLA.Resolution = resolution
	reviewSLA.ResolutionNotes = notes
	reviewSLA.UpdatedAt = now

	s.logger.Info("Resolving SLA",
		zap.String("review_id", reviewID),
		zap.String("resolved_by", resolvedBy),
		zap.String("resolution", resolution),
		zap.Duration("duration", now.Sub(reviewSLA.RequestedAt)))

	// Cancel scheduled notifications
	if err := s.cancelScheduledNotifications(ctx, reviewID); err != nil {
		s.logger.Warn("Failed to cancel scheduled notifications", zap.Error(err))
	}

	// Update stored SLA
	return s.updateReviewSLA(ctx, reviewSLA)
}

// CheckOverdueSLAs checks for and handles overdue SLAs
func (s *SLAManager) CheckOverdueSLAs(ctx context.Context) error {
	now := time.Now()

	// Get all active SLAs
	slas, err := s.getActiveSLAs(ctx)
	if err != nil {
		return fmt.Errorf("failed to get active SLAs: %w", err)
	}

	for _, sla := range slas {
		if now.After(sla.DeadlineAt) {
			if err := s.handleOverdueSLA(ctx, sla, now); err != nil {
				s.logger.Error("Failed to handle overdue SLA",
					zap.String("review_id", sla.ReviewID),
					zap.Error(err))
			}
		}
	}

	return nil
}

// GetSLAStatus returns the current status of an SLA
func (s *SLAManager) GetSLAStatus(ctx context.Context, reviewID string) (*ReviewSLA, error) {
	return s.getReviewSLA(ctx, reviewID)
}

// Helper methods

func (s *SLAManager) generateReviewID(workflowID, reviewType string) string {
	timestamp := time.Now().Unix()
	return fmt.Sprintf("review_%s_%s_%d", reviewType, workflowID[:8], timestamp)
}

func (s *SLAManager) calculateDeadline(requestTime time.Time, reviewType string, priority ReviewPriority) time.Time {
	baseSLA := s.slaConfig.HumanReviewSLA

	// Adjust based on priority
	switch priority {
	case ReviewPriorityCritical:
		baseSLA = baseSLA / 2  // Half the normal SLA for critical reviews
	case ReviewPriorityHigh:
		baseSLA = baseSLA * 3 / 4  // 75% of normal SLA for high priority
	case ReviewPriorityLow:
		baseSLA = baseSLA * 3 / 2  // 150% of normal SLA for low priority
	}

	// Adjust based on review type
	switch reviewType {
	case "CLINICAL_OVERRIDE":
		// Standard SLA applies
	case "SAFETY_REVIEW":
		baseSLA = baseSLA / 2  // Faster for safety reviews
	case "PEER_REVIEW":
		baseSLA = baseSLA * 2  // More time for peer reviews
	}

	return requestTime.Add(baseSLA)
}

func (s *SLAManager) scheduleNotifications(ctx context.Context, reviewSLA *ReviewSLA) error {
	notifications := s.createNotificationSchedule(reviewSLA)

	for _, notification := range notifications {
		if err := s.notifier.ScheduleAt(ctx, notification.ScheduledAt, notification); err != nil {
			s.logger.Error("Failed to schedule notification",
				zap.String("notification_id", notification.NotificationID),
				zap.Error(err))
			// Continue with other notifications
		}
	}

	return nil
}

func (s *SLAManager) createNotificationSchedule(reviewSLA *ReviewSLA) []*SLANotification {
	notifications := make([]*SLANotification, 0)

	// Assignment notification (immediate)
	notifications = append(notifications, &SLANotification{
		NotificationID: fmt.Sprintf("%s_assignment", reviewSLA.ReviewID),
		ReviewID:       reviewSLA.ReviewID,
		Type:           NotificationTypeAssignment,
		Priority:       NotificationPriorityNormal,
		Recipients:     []string{reviewSLA.AssignedReviewer},
		Subject:        fmt.Sprintf("Clinical Review Required: %s", reviewSLA.ReviewType),
		Message:        s.generateAssignmentMessage(reviewSLA),
		ScheduledAt:    reviewSLA.RequestedAt,
	})

	// First warning (30 minutes before deadline)
	if s.slaConfig.FirstWarningOffset > 0 {
		warningTime := reviewSLA.DeadlineAt.Add(-s.slaConfig.FirstWarningOffset)
		if warningTime.After(time.Now()) {
			notifications = append(notifications, &SLANotification{
				NotificationID: fmt.Sprintf("%s_warning_1", reviewSLA.ReviewID),
				ReviewID:       reviewSLA.ReviewID,
				Type:           NotificationTypeFirstWarning,
				Priority:       NotificationPriorityHigh,
				Recipients:     []string{reviewSLA.AssignedReviewer},
				Subject:        fmt.Sprintf("Review Deadline Approaching: %s", reviewSLA.ReviewType),
				Message:        s.generateWarningMessage(reviewSLA, s.slaConfig.FirstWarningOffset),
				ScheduledAt:    warningTime,
			})
		}
	}

	// Second warning (15 minutes before deadline)
	if s.slaConfig.SecondWarningOffset > 0 {
		finalWarningTime := reviewSLA.DeadlineAt.Add(-s.slaConfig.SecondWarningOffset)
		if finalWarningTime.After(time.Now()) {
			notifications = append(notifications, &SLANotification{
				NotificationID: fmt.Sprintf("%s_warning_2", reviewSLA.ReviewID),
				ReviewID:       reviewSLA.ReviewID,
				Type:           NotificationTypeSecondWarning,
				Priority:       NotificationPriorityUrgent,
				Recipients:     []string{reviewSLA.AssignedReviewer},
				Subject:        fmt.Sprintf("URGENT: Review Deadline Imminent: %s", reviewSLA.ReviewType),
				Message:        s.generateFinalWarningMessage(reviewSLA, s.slaConfig.SecondWarningOffset),
				ScheduledAt:    finalWarningTime,
			})
		}
	}

	// Deadline notification
	notifications = append(notifications, &SLANotification{
		NotificationID: fmt.Sprintf("%s_deadline", reviewSLA.ReviewID),
		ReviewID:       reviewSLA.ReviewID,
		Type:           NotificationTypeDeadline,
		Priority:       NotificationPriorityUrgent,
		Recipients:     []string{reviewSLA.AssignedReviewer},
		Subject:        fmt.Sprintf("DEADLINE REACHED: %s", reviewSLA.ReviewType),
		Message:        s.generateDeadlineMessage(reviewSLA),
		ScheduledAt:    reviewSLA.DeadlineAt,
	})

	return notifications
}

func (s *SLAManager) handleOverdueSLA(ctx context.Context, sla *ReviewSLA, currentTime time.Time) error {
	overdueMinutes := int(currentTime.Sub(sla.DeadlineAt).Minutes())

	s.logger.Warn("SLA overdue",
		zap.String("review_id", sla.ReviewID),
		zap.Int("overdue_minutes", overdueMinutes))

	// Update status
	sla.Status = ReviewSLAStatusOverdue
	sla.UpdatedAt = currentTime

	// Escalate if past grace period
	gracePeriodEnd := sla.DeadlineAt.Add(s.slaConfig.PostDeadlineGrace)
	if currentTime.After(gracePeriodEnd) {
		return s.escalateReview(ctx, sla, currentTime)
	}

	// Send overdue notification
	overdueNotification := &SLANotification{
		NotificationID: fmt.Sprintf("%s_overdue_%d", sla.ReviewID, overdueMinutes),
		ReviewID:       sla.ReviewID,
		Type:           NotificationTypeOverdue,
		Priority:       NotificationPriorityUrgent,
		Recipients:     []string{sla.AssignedReviewer},
		Subject:        fmt.Sprintf("OVERDUE: Clinical Review Required: %s", sla.ReviewType),
		Message:        s.generateOverdueMessage(sla, overdueMinutes),
		ScheduledAt:    currentTime,
	}

	if err := s.notifier.SendImmediate(ctx, overdueNotification); err != nil {
		return fmt.Errorf("failed to send overdue notification: %w", err)
	}

	return s.updateReviewSLA(ctx, sla)
}

func (s *SLAManager) escalateReview(ctx context.Context, sla *ReviewSLA, currentTime time.Time) error {
	sla.Status = ReviewSLAStatusEscalated
	sla.EscalationLevel++
	now := currentTime
	sla.EscalatedAt = &now
	sla.UpdatedAt = currentTime

	escalation := &ReviewEscalation{
		EscalationID:   fmt.Sprintf("esc_%s_%d", sla.ReviewID, sla.EscalationLevel),
		ReviewID:       sla.ReviewID,
		EscalationType: "SLA_BREACH",
		EscalatedTo:    s.determineEscalationTargets(sla),
		Reason:         fmt.Sprintf("Review SLA exceeded by %v", currentTime.Sub(sla.DeadlineAt)),
		EscalatedAt:    currentTime,
		AutoGenerated:  true,
	}

	s.logger.Error("Escalating overdue review",
		zap.String("review_id", sla.ReviewID),
		zap.Strings("escalated_to", escalation.EscalatedTo))

	// Execute escalation
	if err := s.escalator.EscalateReview(ctx, escalation); err != nil {
		return fmt.Errorf("escalation failed: %w", err)
	}

	return s.updateReviewSLA(ctx, sla)
}

// Redis operations

func (s *SLAManager) storeReviewSLA(ctx context.Context, sla *ReviewSLA) error {
	key := fmt.Sprintf("sla:review:%s", sla.ReviewID)
	data, err := json.Marshal(sla)
	if err != nil {
		return err
	}

	// Store with expiration (24 hours after deadline)
	expiration := time.Until(sla.DeadlineAt.Add(24 * time.Hour))
	return s.redis.Set(ctx, key, data, expiration).Err()
}

func (s *SLAManager) getReviewSLA(ctx context.Context, reviewID string) (*ReviewSLA, error) {
	key := fmt.Sprintf("sla:review:%s", reviewID)
	data, err := s.redis.Get(ctx, key).Result()
	if err != nil {
		return nil, err
	}

	var sla ReviewSLA
	if err := json.Unmarshal([]byte(data), &sla); err != nil {
		return nil, err
	}

	return &sla, nil
}

func (s *SLAManager) updateReviewSLA(ctx context.Context, sla *ReviewSLA) error {
	sla.UpdatedAt = time.Now()
	return s.storeReviewSLA(ctx, sla)
}

func (s *SLAManager) getActiveSLAs(ctx context.Context) ([]*ReviewSLA, error) {
	pattern := "sla:review:*"
	keys, err := s.redis.Keys(ctx, pattern).Result()
	if err != nil {
		return nil, err
	}

	slas := make([]*ReviewSLA, 0, len(keys))
	for _, key := range keys {
		data, err := s.redis.Get(ctx, key).Result()
		if err != nil {
			continue // Skip invalid entries
		}

		var sla ReviewSLA
		if err := json.Unmarshal([]byte(data), &sla); err != nil {
			continue // Skip invalid entries
		}

		// Only include active SLAs
		if sla.Status == ReviewSLAStatusActive || sla.Status == ReviewSLAStatusWarning || sla.Status == ReviewSLAStatusOverdue {
			slas = append(slas, &sla)
		}
	}

	return slas, nil
}

func (s *SLAManager) cancelScheduledNotifications(ctx context.Context, reviewID string) error {
	// Cancel various notification types
	notificationIDs := []string{
		fmt.Sprintf("%s_assignment", reviewID),
		fmt.Sprintf("%s_warning_1", reviewID),
		fmt.Sprintf("%s_warning_2", reviewID),
		fmt.Sprintf("%s_deadline", reviewID),
	}

	for _, notificationID := range notificationIDs {
		if err := s.notifier.CancelScheduled(ctx, notificationID); err != nil {
			s.logger.Debug("Could not cancel notification (may not exist)",
				zap.String("notification_id", notificationID),
				zap.Error(err))
		}
	}

	return nil
}

// Message generation helpers

func (s *SLAManager) generateAssignmentMessage(sla *ReviewSLA) string {
	return fmt.Sprintf("You have been assigned a clinical review for workflow %s. "+
		"Review type: %s. Priority: %s. Deadline: %s. "+
		"Please complete your review before the deadline to ensure patient safety.",
		sla.WorkflowID, sla.ReviewType, string(sla.Priority),
		sla.DeadlineAt.Format("2006-01-02 15:04:05"))
}

func (s *SLAManager) generateWarningMessage(sla *ReviewSLA, timeRemaining time.Duration) string {
	return fmt.Sprintf("Reminder: Your clinical review for workflow %s is due in %v. "+
		"Review type: %s. Priority: %s. "+
		"Please complete your review to avoid escalation.",
		sla.WorkflowID, timeRemaining, sla.ReviewType, string(sla.Priority))
}

func (s *SLAManager) generateFinalWarningMessage(sla *ReviewSLA, timeRemaining time.Duration) string {
	return fmt.Sprintf("URGENT: Your clinical review for workflow %s is due in %v. "+
		"This is your final warning before escalation. "+
		"Review type: %s. Priority: %s.",
		sla.WorkflowID, timeRemaining, sla.ReviewType, string(sla.Priority))
}

func (s *SLAManager) generateDeadlineMessage(sla *ReviewSLA) string {
	return fmt.Sprintf("DEADLINE REACHED: Clinical review for workflow %s is now overdue. "+
		"Immediate action required. Review type: %s. "+
		"This review will be escalated if not completed within the grace period.",
		sla.WorkflowID, sla.ReviewType)
}

func (s *SLAManager) generateOverdueMessage(sla *ReviewSLA, overdueMinutes int) string {
	return fmt.Sprintf("OVERDUE: Clinical review for workflow %s is %d minutes overdue. "+
		"Escalation process initiated. Review type: %s. "+
		"Complete immediately to minimize disruption.",
		sla.WorkflowID, overdueMinutes, sla.ReviewType)
}

func (s *SLAManager) determineEscalationTargets(sla *ReviewSLA) []string {
	// Determine who to escalate to based on review type and level
	switch sla.RequiredLevel {
	case "CLINICAL_JUDGMENT":
		return []string{"peer_clinician", "supervising_physician"}
	case "PEER_REVIEW":
		return []string{"department_chief", "medical_director"}
	case "SUPERVISORY":
		return []string{"medical_director", "chief_medical_officer"}
	case "EMERGENCY":
		return []string{"chief_medical_officer", "patient_safety_officer"}
	default:
		return []string{"supervising_physician"}
	}
}