package com.cardiofit.flink.cds.population;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for CareGap
 * Phase 8 Module 4 - Population Health Module
 *
 * Test Coverage:
 * - Care gap creation and initialization
 * - Days overdue calculation
 * - Intervention attempt tracking
 * - Gap closure with different statuses
 * - Severity and priority management
 * - Clinical context tracking
 *
 * @author CardioFit Testing Team
 * @version 1.0.0
 * @since Phase 8
 */
@DisplayName("CareGap Tests")
class CareGapTest {

    private CareGap careGap;
    private static final String TEST_PATIENT_ID = "PATIENT-12345";
    private static final CareGap.GapType TEST_GAP_TYPE = CareGap.GapType.PREVENTIVE_SCREENING;
    private static final String TEST_GAP_NAME = "Colonoscopy Screening";

    @BeforeEach
    void setUp() {
        careGap = new CareGap(TEST_PATIENT_ID, TEST_GAP_TYPE, TEST_GAP_NAME);
    }

    @Nested
    @DisplayName("Care Gap Creation Tests")
    class CareGapCreationTests {

        @Test
        @DisplayName("Should create care gap with required fields")
        void testCareGapCreation() {
            assertNotNull(careGap);
            assertEquals(TEST_PATIENT_ID, careGap.getPatientId());
            assertEquals(TEST_GAP_TYPE, careGap.getGapType());
            assertEquals(TEST_GAP_NAME, careGap.getGapName());
            assertEquals(CareGap.GapStatus.IDENTIFIED, careGap.getStatus());
            assertNotNull(careGap.getIdentifiedAt());
        }

        @Test
        @DisplayName("Should auto-generate unique gap ID")
        void testAutoGeneratedGapId() throws InterruptedException {
            assertNotNull(careGap.getGapId());
            assertTrue(careGap.getGapId().startsWith("GAP-"));

            Thread.sleep(1); // Ensure different timestamp
            CareGap gap2 = new CareGap(TEST_PATIENT_ID, TEST_GAP_TYPE, "Mammography Screening");
            assertNotEquals(careGap.getGapId(), gap2.getGapId());
        }

        @Test
        @DisplayName("Should initialize empty interventions list")
        void testInterventionsInitialization() {
            assertNotNull(careGap.getInterventions());
            assertEquals(0, careGap.getInterventions().size());
        }

        @Test
        @DisplayName("Should support all gap types")
        void testAllGapTypes() {
            CareGap.GapType[] types = CareGap.GapType.values();

            assertEquals(10, types.length);
            assertTrue(containsGapType(types, CareGap.GapType.PREVENTIVE_SCREENING));
            assertTrue(containsGapType(types, CareGap.GapType.CHRONIC_DISEASE_MONITORING));
            assertTrue(containsGapType(types, CareGap.GapType.MEDICATION_ADHERENCE));
            assertTrue(containsGapType(types, CareGap.GapType.IMMUNIZATION));
            assertTrue(containsGapType(types, CareGap.GapType.DIAGNOSTIC_TESTING));
            assertTrue(containsGapType(types, CareGap.GapType.FOLLOW_UP_APPOINTMENT));
            assertTrue(containsGapType(types, CareGap.GapType.SPECIALIST_REFERRAL));
            assertTrue(containsGapType(types, CareGap.GapType.CARE_COORDINATION));
            assertTrue(containsGapType(types, CareGap.GapType.PATIENT_EDUCATION));
            assertTrue(containsGapType(types, CareGap.GapType.LIFESTYLE_MODIFICATION));
        }

        @Test
        @DisplayName("Should support all gap categories")
        void testAllGapCategories() {
            CareGap.GapCategory[] categories = CareGap.GapCategory.values();

            assertEquals(6, categories.length);
            assertTrue(containsGapCategory(categories, CareGap.GapCategory.PREVENTIVE));
            assertTrue(containsGapCategory(categories, CareGap.GapCategory.CHRONIC_MANAGEMENT));
            assertTrue(containsGapCategory(categories, CareGap.GapCategory.ACUTE_CARE));
            assertTrue(containsGapCategory(categories, CareGap.GapCategory.MEDICATION));
            assertTrue(containsGapCategory(categories, CareGap.GapCategory.BEHAVIORAL_HEALTH));
            assertTrue(containsGapCategory(categories, CareGap.GapCategory.SOCIAL_DETERMINANTS));
        }

        @Test
        @DisplayName("Should support all severity levels")
        void testAllSeverityLevels() {
            CareGap.GapSeverity[] severities = CareGap.GapSeverity.values();

            assertEquals(4, severities.length);
            assertTrue(containsSeverity(severities, CareGap.GapSeverity.LOW));
            assertTrue(containsSeverity(severities, CareGap.GapSeverity.MODERATE));
            assertTrue(containsSeverity(severities, CareGap.GapSeverity.HIGH));
            assertTrue(containsSeverity(severities, CareGap.GapSeverity.CRITICAL));

            // Test severity levels
            assertEquals(1, CareGap.GapSeverity.LOW.getLevel());
            assertEquals(4, CareGap.GapSeverity.CRITICAL.getLevel());
        }

        @Test
        @DisplayName("Should support all gap statuses")
        void testAllGapStatuses() {
            CareGap.GapStatus[] statuses = CareGap.GapStatus.values();

            assertEquals(8, statuses.length);
            assertTrue(containsStatus(statuses, CareGap.GapStatus.IDENTIFIED));
            assertTrue(containsStatus(statuses, CareGap.GapStatus.NOTIFIED));
            assertTrue(containsStatus(statuses, CareGap.GapStatus.INTERVENTION_SENT));
            assertTrue(containsStatus(statuses, CareGap.GapStatus.IN_PROGRESS));
            assertTrue(containsStatus(statuses, CareGap.GapStatus.CLOSED_COMPLETED));
            assertTrue(containsStatus(statuses, CareGap.GapStatus.CLOSED_INAPPROPRIATE));
            assertTrue(containsStatus(statuses, CareGap.GapStatus.CLOSED_REFUSED));
            assertTrue(containsStatus(statuses, CareGap.GapStatus.CLOSED_EXPIRED));
        }

        private boolean containsGapType(CareGap.GapType[] types, CareGap.GapType target) {
            for (CareGap.GapType type : types) {
                if (type == target) return true;
            }
            return false;
        }

        private boolean containsGapCategory(CareGap.GapCategory[] categories, CareGap.GapCategory target) {
            for (CareGap.GapCategory category : categories) {
                if (category == target) return true;
            }
            return false;
        }

        private boolean containsSeverity(CareGap.GapSeverity[] severities, CareGap.GapSeverity target) {
            for (CareGap.GapSeverity severity : severities) {
                if (severity == target) return true;
            }
            return false;
        }

        private boolean containsStatus(CareGap.GapStatus[] statuses, CareGap.GapStatus target) {
            for (CareGap.GapStatus status : statuses) {
                if (status == target) return true;
            }
            return false;
        }
    }

    @Nested
    @DisplayName("Days Overdue Calculation Tests")
    class DaysOverdueTests {

        @Test
        @DisplayName("Should calculate days overdue for past due date")
        void testCalculateDaysOverdue() {
            LocalDate pastDate = LocalDate.now().minusDays(30);
            careGap.setDueDate(pastDate);

            careGap.calculateDaysOverdue();

            assertEquals(30, careGap.getDaysOverdue());
            assertNotNull(careGap.getOverdueDate());
            assertEquals(pastDate.plusDays(1), careGap.getOverdueDate());
        }

        @Test
        @DisplayName("Should return zero days overdue for future due date")
        void testZeroDaysOverdueForFuture() {
            LocalDate futureDate = LocalDate.now().plusDays(10);
            careGap.setDueDate(futureDate);

            careGap.calculateDaysOverdue();

            assertEquals(0, careGap.getDaysOverdue());
        }

        @Test
        @DisplayName("Should detect if gap is overdue")
        void testIsOverdue() {
            LocalDate pastDate = LocalDate.now().minusDays(15);
            careGap.setDueDate(pastDate);

            assertTrue(careGap.isOverdue());
        }

        @Test
        @DisplayName("Should detect if gap is not overdue")
        void testIsNotOverdue() {
            LocalDate futureDate = LocalDate.now().plusDays(15);
            careGap.setDueDate(futureDate);

            assertFalse(careGap.isOverdue());
        }

        @Test
        @DisplayName("Should handle null due date")
        void testNullDueDate() {
            careGap.setDueDate(null);

            careGap.calculateDaysOverdue();

            assertEquals(0, careGap.getDaysOverdue());
            assertFalse(careGap.isOverdue());
        }
    }

    @Nested
    @DisplayName("Intervention Tracking Tests")
    class InterventionTrackingTests {

        @Test
        @DisplayName("Should add intervention attempt")
        void testAddIntervention() {
            careGap.addIntervention("Phone call", "Left voicemail");

            assertEquals(1, careGap.getInterventions().size());
            assertEquals(CareGap.GapStatus.INTERVENTION_SENT, careGap.getStatus());

            CareGap.InterventionAttempt intervention = careGap.getInterventions().get(0);
            assertEquals("Phone call", intervention.getInterventionType());
            assertEquals("Left voicemail", intervention.getOutcome());
            assertNotNull(intervention.getAttemptDate());
        }

        @Test
        @DisplayName("Should track multiple intervention attempts")
        void testMultipleInterventions() {
            careGap.addIntervention("Phone call", "Left voicemail");
            careGap.addIntervention("Letter", "Mailed to home address");
            careGap.addIntervention("Portal message", "Message sent");

            assertEquals(3, careGap.getInterventions().size());
        }

        @Test
        @DisplayName("Should create intervention attempt with constructor")
        void testInterventionAttemptCreation() {
            CareGap.InterventionAttempt intervention = new CareGap.InterventionAttempt(
                "Patient portal reminder",
                "Message read"
            );

            assertEquals("Patient portal reminder", intervention.getInterventionType());
            assertEquals("Message read", intervention.getOutcome());
            assertNotNull(intervention.getAttemptDate());
        }

        @Test
        @DisplayName("Should set intervention notes")
        void testInterventionNotes() {
            CareGap.InterventionAttempt intervention = new CareGap.InterventionAttempt();
            intervention.setInterventionType("Phone call");
            intervention.setOutcome("Spoke with patient");
            intervention.setNotes("Patient agreed to schedule appointment next week");

            assertEquals("Phone call", intervention.getInterventionType());
            assertEquals("Spoke with patient", intervention.getOutcome());
            assertEquals("Patient agreed to schedule appointment next week", intervention.getNotes());
        }
    }

    @Nested
    @DisplayName("Gap Closure Tests")
    class GapClosureTests {

        @Test
        @DisplayName("Should close gap as completed")
        void testCloseGapCompleted() {
            careGap.closeGap(
                CareGap.GapStatus.CLOSED_COMPLETED,
                "Colonoscopy performed on 2024-01-15"
            );

            assertEquals(CareGap.GapStatus.CLOSED_COMPLETED, careGap.getStatus());
            assertEquals("Colonoscopy performed on 2024-01-15", careGap.getClosureReason());
            assertNotNull(careGap.getClosedAt());
        }

        @Test
        @DisplayName("Should close gap as inappropriate")
        void testCloseGapInappropriate() {
            careGap.closeGap(
                CareGap.GapStatus.CLOSED_INAPPROPRIATE,
                "Patient had colonoscopy 2 years ago, not in EHR"
            );

            assertEquals(CareGap.GapStatus.CLOSED_INAPPROPRIATE, careGap.getStatus());
            assertEquals("Patient had colonoscopy 2 years ago, not in EHR", careGap.getClosureReason());
        }

        @Test
        @DisplayName("Should close gap as refused")
        void testCloseGapRefused() {
            careGap.closeGap(
                CareGap.GapStatus.CLOSED_REFUSED,
                "Patient declined colonoscopy after informed discussion"
            );

            assertEquals(CareGap.GapStatus.CLOSED_REFUSED, careGap.getStatus());
            assertEquals("Patient declined colonoscopy after informed discussion", careGap.getClosureReason());
        }

        @Test
        @DisplayName("Should close gap as expired")
        void testCloseGapExpired() {
            careGap.closeGap(
                CareGap.GapStatus.CLOSED_EXPIRED,
                "Patient aged out of screening recommendation"
            );

            assertEquals(CareGap.GapStatus.CLOSED_EXPIRED, careGap.getStatus());
            assertEquals("Patient aged out of screening recommendation", careGap.getClosureReason());
        }

        @Test
        @DisplayName("Should reject invalid closure status")
        void testInvalidClosureStatus() {
            assertThrows(IllegalArgumentException.class, () -> {
                careGap.closeGap(CareGap.GapStatus.IDENTIFIED, "Invalid status");
            });
        }

        @Test
        @DisplayName("Should detect if gap is open")
        void testIsOpen() {
            assertTrue(careGap.isOpen());

            careGap.setStatus(CareGap.GapStatus.INTERVENTION_SENT);
            assertTrue(careGap.isOpen());

            careGap.setStatus(CareGap.GapStatus.IN_PROGRESS);
            assertTrue(careGap.isOpen());

            careGap.closeGap(CareGap.GapStatus.CLOSED_COMPLETED, "Completed");
            assertFalse(careGap.isOpen());
        }
    }

    @Nested
    @DisplayName("Priority and Severity Tests")
    class PrioritySeverityTests {

        @Test
        @DisplayName("Should set priority within valid range")
        void testSetPriority() {
            careGap.setPriority(8);
            assertEquals(8, careGap.getPriority());
        }

        @Test
        @DisplayName("Should clamp priority to minimum of 1")
        void testPriorityMinimumClamp() {
            careGap.setPriority(-5);
            assertEquals(1, careGap.getPriority());
        }

        @Test
        @DisplayName("Should clamp priority to maximum of 10")
        void testPriorityMaximumClamp() {
            careGap.setPriority(15);
            assertEquals(10, careGap.getPriority());
        }

        @Test
        @DisplayName("Should set severity level")
        void testSetSeverity() {
            careGap.setSeverity(CareGap.GapSeverity.HIGH);
            assertEquals(CareGap.GapSeverity.HIGH, careGap.getSeverity());
            assertEquals(3, careGap.getSeverity().getLevel());
        }

        @Test
        @DisplayName("Should mark gap as urgent")
        void testSetUrgent() {
            careGap.setUrgent(true);
            assertTrue(careGap.isUrgent());
        }
    }

    @Nested
    @DisplayName("Clinical Context Tests")
    class ClinicalContextTests {

        @Test
        @DisplayName("Should set clinical reason and recommended action")
        void testClinicalContext() {
            careGap.setClinicalReason("Colorectal cancer screening reduces mortality by 30%");
            careGap.setRecommendedAction("Schedule colonoscopy with gastroenterology");

            assertEquals("Colorectal cancer screening reduces mortality by 30%", careGap.getClinicalReason());
            assertEquals("Schedule colonoscopy with gastroenterology", careGap.getRecommendedAction());
        }

        @Test
        @DisplayName("Should set guideline reference and quality measure ID")
        void testGuidelineContext() {
            careGap.setGuidelineReference("USPSTF 2021 Recommendations");
            careGap.setQualityMeasureId("HEDIS-COL");
            careGap.setEvidenceLevel("A");

            assertEquals("USPSTF 2021 Recommendations", careGap.getGuidelineReference());
            assertEquals("HEDIS-COL", careGap.getQualityMeasureId());
            assertEquals("A", careGap.getEvidenceLevel());
        }

        @Test
        @DisplayName("Should set related clinical codes")
        void testRelatedCodes() {
            careGap.setRelatedCondition("E11.9"); // Type 2 Diabetes
            careGap.setRelatedMedication("Metformin");
            careGap.setRelatedProcedure("45378"); // CPT colonoscopy
            careGap.setRelatedLab("4548-4"); // LOINC HbA1c

            assertEquals("E11.9", careGap.getRelatedCondition());
            assertEquals("Metformin", careGap.getRelatedMedication());
            assertEquals("45378", careGap.getRelatedProcedure());
            assertEquals("4548-4", careGap.getRelatedLab());
        }

        @Test
        @DisplayName("Should track quality measure impact")
        void testQualityMeasureImpact() {
            careGap.setImpactsQualityMeasure(true);
            careGap.setFinancialImpact(250.00);

            assertTrue(careGap.isImpactsQualityMeasure());
            assertEquals(250.00, careGap.getFinancialImpact(), 0.01);
        }
    }

    @Nested
    @DisplayName("toString Tests")
    class ToStringTests {

        @Test
        @DisplayName("Should generate meaningful string representation")
        void testToString() {
            careGap.setSeverity(CareGap.GapSeverity.MODERATE);
            careGap.setDueDate(LocalDate.now().minusDays(20));
            careGap.calculateDaysOverdue();

            String str = careGap.toString();

            assertTrue(str.contains(TEST_PATIENT_ID));
            assertTrue(str.contains("PREVENTIVE_SCREENING"));
            assertTrue(str.contains("MODERATE"));
            assertTrue(str.contains("20")); // days overdue
            assertTrue(str.contains("IDENTIFIED"));
        }
    }
}
