package com.cardiofit.flink.cds.population;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for PatientCohort
 * Phase 8 Module 4 - Population Health Module
 *
 * Test Coverage:
 * - Cohort creation and initialization
 * - Patient add/remove operations
 * - Inclusion/exclusion criteria management
 * - Risk distribution tracking
 * - Quality metric tracking
 * - Demographic profiling
 * - Aggregate calculations
 *
 * @author CardioFit Testing Team
 * @version 1.0.0
 * @since Phase 8
 */
@DisplayName("PatientCohort Tests")
class PatientCohortTest {

    private PatientCohort cohort;
    private static final String TEST_COHORT_NAME = "Diabetes Management Cohort";
    private static final PatientCohort.CohortType TEST_COHORT_TYPE = PatientCohort.CohortType.DISEASE_BASED;

    @BeforeEach
    void setUp() {
        cohort = new PatientCohort(TEST_COHORT_NAME, TEST_COHORT_TYPE);
    }

    @Nested
    @DisplayName("Cohort Creation Tests")
    class CohortCreationTests {

        @Test
        @DisplayName("Should create cohort with required fields")
        void testCohortCreation() {
            assertNotNull(cohort);
            assertEquals(TEST_COHORT_NAME, cohort.getCohortName());
            assertEquals(TEST_COHORT_TYPE, cohort.getCohortType());
            assertTrue(cohort.isActive());
            assertNotNull(cohort.getCreatedAt());
            assertNotNull(cohort.getLastUpdated());
        }

        @Test
        @DisplayName("Should auto-generate unique cohort ID")
        void testAutoGeneratedCohortId() throws InterruptedException {
            assertNotNull(cohort.getCohortId());
            assertTrue(cohort.getCohortId().startsWith("COHORT-"));

            Thread.sleep(1); // Ensure different timestamp
            PatientCohort cohort2 = new PatientCohort("Hypertension Cohort", PatientCohort.CohortType.DISEASE_BASED);
            assertNotEquals(cohort.getCohortId(), cohort2.getCohortId());
        }

        @Test
        @DisplayName("Should initialize empty collections")
        void testCollectionInitialization() {
            assertNotNull(cohort.getPatientIds());
            assertNotNull(cohort.getInclusionCriteria());
            assertNotNull(cohort.getExclusionCriteria());
            assertNotNull(cohort.getRiskDistribution());
            assertNotNull(cohort.getConditionDistribution());
            assertNotNull(cohort.getMedicationDistribution());
            assertNotNull(cohort.getQualityMetrics());
            assertNotNull(cohort.getDemographics());

            assertEquals(0, cohort.getTotalPatients());
            assertEquals(0, cohort.getPatientIds().size());
            assertEquals(0, cohort.getCareGapsIdentified());
        }

        @Test
        @DisplayName("Should support all cohort types")
        void testAllCohortTypes() {
            PatientCohort.CohortType[] types = PatientCohort.CohortType.values();

            assertEquals(9, types.length);
            assertTrue(containsCohortType(types, PatientCohort.CohortType.DISEASE_BASED));
            assertTrue(containsCohortType(types, PatientCohort.CohortType.RISK_BASED));
            assertTrue(containsCohortType(types, PatientCohort.CohortType.GEOGRAPHIC));
            assertTrue(containsCohortType(types, PatientCohort.CohortType.DEMOGRAPHIC));
            assertTrue(containsCohortType(types, PatientCohort.CohortType.QUALITY_MEASURE));
            assertTrue(containsCohortType(types, PatientCohort.CohortType.CARE_GAP));
            assertTrue(containsCohortType(types, PatientCohort.CohortType.INSURANCE));
            assertTrue(containsCohortType(types, PatientCohort.CohortType.PROVIDER));
            assertTrue(containsCohortType(types, PatientCohort.CohortType.CUSTOM));
        }

        @Test
        @DisplayName("Should support all risk levels")
        void testAllRiskLevels() {
            PatientCohort.RiskLevel[] levels = PatientCohort.RiskLevel.values();

            assertEquals(5, levels.length);
            assertTrue(containsRiskLevel(levels, PatientCohort.RiskLevel.VERY_LOW));
            assertTrue(containsRiskLevel(levels, PatientCohort.RiskLevel.LOW));
            assertTrue(containsRiskLevel(levels, PatientCohort.RiskLevel.MODERATE));
            assertTrue(containsRiskLevel(levels, PatientCohort.RiskLevel.HIGH));
            assertTrue(containsRiskLevel(levels, PatientCohort.RiskLevel.VERY_HIGH));

            // Test priority ordering
            assertEquals(0, PatientCohort.RiskLevel.VERY_LOW.getPriority());
            assertEquals(4, PatientCohort.RiskLevel.VERY_HIGH.getPriority());
        }

        private boolean containsCohortType(PatientCohort.CohortType[] types, PatientCohort.CohortType target) {
            for (PatientCohort.CohortType type : types) {
                if (type == target) return true;
            }
            return false;
        }

        private boolean containsRiskLevel(PatientCohort.RiskLevel[] levels, PatientCohort.RiskLevel target) {
            for (PatientCohort.RiskLevel level : levels) {
                if (level == target) return true;
            }
            return false;
        }
    }

    @Nested
    @DisplayName("Patient Management Tests")
    class PatientManagementTests {

        @Test
        @DisplayName("Should add patient to cohort")
        void testAddPatient() throws InterruptedException {
            LocalDateTime beforeAdd = cohort.getLastUpdated();
            Thread.sleep(10);

            cohort.addPatient("PATIENT-001");

            assertEquals(1, cohort.getTotalPatients());
            assertTrue(cohort.getPatientIds().contains("PATIENT-001"));
            assertTrue(cohort.getLastUpdated().isAfter(beforeAdd));
        }

        @Test
        @DisplayName("Should add multiple patients")
        void testAddMultiplePatients() {
            cohort.addPatient("PATIENT-001");
            cohort.addPatient("PATIENT-002");
            cohort.addPatient("PATIENT-003");

            assertEquals(3, cohort.getTotalPatients());
            assertTrue(cohort.getPatientIds().contains("PATIENT-001"));
            assertTrue(cohort.getPatientIds().contains("PATIENT-002"));
            assertTrue(cohort.getPatientIds().contains("PATIENT-003"));
        }

        @Test
        @DisplayName("Should prevent duplicate patient IDs")
        void testNoDuplicatePatients() {
            cohort.addPatient("PATIENT-001");
            cohort.addPatient("PATIENT-001"); // Duplicate

            assertEquals(1, cohort.getTotalPatients());
        }

        @Test
        @DisplayName("Should remove patient from cohort")
        void testRemovePatient() throws InterruptedException {
            cohort.addPatient("PATIENT-001");
            cohort.addPatient("PATIENT-002");

            LocalDateTime beforeRemove = cohort.getLastUpdated();
            Thread.sleep(10);

            cohort.removePatient("PATIENT-001");

            assertEquals(1, cohort.getTotalPatients());
            assertFalse(cohort.getPatientIds().contains("PATIENT-001"));
            assertTrue(cohort.getPatientIds().contains("PATIENT-002"));
            assertTrue(cohort.getLastUpdated().isAfter(beforeRemove));
        }

        @Test
        @DisplayName("Should handle removing non-existent patient")
        void testRemoveNonExistentPatient() {
            cohort.addPatient("PATIENT-001");

            cohort.removePatient("PATIENT-999"); // Doesn't exist

            assertEquals(1, cohort.getTotalPatients());
        }
    }

    @Nested
    @DisplayName("Criteria Management Tests")
    class CriteriaManagementTests {

        @Test
        @DisplayName("Should add inclusion criteria")
        void testAddInclusionCriteria() {
            PatientCohort.CriteriaRule rule = new PatientCohort.CriteriaRule(
                PatientCohort.CriteriaRule.CriteriaType.DIAGNOSIS,
                "ICD-10",
                "=",
                "E11.9"
            );
            rule.setDescription("Type 2 Diabetes Mellitus");

            cohort.addInclusionCriteria(rule);

            assertEquals(1, cohort.getInclusionCriteria().size());
            assertEquals("Type 2 Diabetes Mellitus", cohort.getInclusionCriteria().get(0).getDescription());
        }

        @Test
        @DisplayName("Should add exclusion criteria")
        void testAddExclusionCriteria() {
            PatientCohort.CriteriaRule rule = new PatientCohort.CriteriaRule(
                PatientCohort.CriteriaRule.CriteriaType.AGE,
                "age",
                "<",
                18
            );
            rule.setDescription("Exclude pediatric patients");

            cohort.addExclusionCriteria(rule);

            assertEquals(1, cohort.getExclusionCriteria().size());
            assertEquals("Exclude pediatric patients", cohort.getExclusionCriteria().get(0).getDescription());
        }

        @Test
        @DisplayName("Should support all criteria types")
        void testAllCriteriaTypes() {
            PatientCohort.CriteriaRule.CriteriaType[] types = PatientCohort.CriteriaRule.CriteriaType.values();

            assertEquals(10, types.length);
            assertTrue(containsCriteriaType(types, PatientCohort.CriteriaRule.CriteriaType.AGE));
            assertTrue(containsCriteriaType(types, PatientCohort.CriteriaRule.CriteriaType.GENDER));
            assertTrue(containsCriteriaType(types, PatientCohort.CriteriaRule.CriteriaType.DIAGNOSIS));
            assertTrue(containsCriteriaType(types, PatientCohort.CriteriaRule.CriteriaType.MEDICATION));
            assertTrue(containsCriteriaType(types, PatientCohort.CriteriaRule.CriteriaType.LAB_VALUE));
            assertTrue(containsCriteriaType(types, PatientCohort.CriteriaRule.CriteriaType.RISK_SCORE));
            assertTrue(containsCriteriaType(types, PatientCohort.CriteriaRule.CriteriaType.VITAL_SIGN));
            assertTrue(containsCriteriaType(types, PatientCohort.CriteriaRule.CriteriaType.INSURANCE));
            assertTrue(containsCriteriaType(types, PatientCohort.CriteriaRule.CriteriaType.GEOGRAPHIC));
            assertTrue(containsCriteriaType(types, PatientCohort.CriteriaRule.CriteriaType.CUSTOM));
        }

        @Test
        @DisplayName("Should create criteria rule with operator and value")
        void testCriteriaRuleCreation() {
            PatientCohort.CriteriaRule rule = new PatientCohort.CriteriaRule(
                PatientCohort.CriteriaRule.CriteriaType.LAB_VALUE,
                "HbA1c",
                ">",
                8.0
            );

            assertEquals(PatientCohort.CriteriaRule.CriteriaType.LAB_VALUE, rule.getCriteriaType());
            assertEquals("HbA1c", rule.getParameter());
            assertEquals(">", rule.getOperator());
            assertEquals(8.0, rule.getValue());
        }

        @Test
        @DisplayName("Should support BETWEEN operator with second value")
        void testBetweenOperator() {
            PatientCohort.CriteriaRule rule = new PatientCohort.CriteriaRule();
            rule.setCriteriaType(PatientCohort.CriteriaRule.CriteriaType.AGE);
            rule.setParameter("age");
            rule.setOperator("BETWEEN");
            rule.setValue(50);
            rule.setSecondValue(75);

            assertEquals("BETWEEN", rule.getOperator());
            assertEquals(50, rule.getValue());
            assertEquals(75, rule.getSecondValue());
        }

        private boolean containsCriteriaType(PatientCohort.CriteriaRule.CriteriaType[] types,
                                             PatientCohort.CriteriaRule.CriteriaType target) {
            for (PatientCohort.CriteriaRule.CriteriaType type : types) {
                if (type == target) return true;
            }
            return false;
        }
    }

    @Nested
    @DisplayName("Risk Distribution Tests")
    class RiskDistributionTests {

        @Test
        @DisplayName("Should update risk distribution")
        void testUpdateRiskDistribution() throws InterruptedException {
            LocalDateTime before = cohort.getLastUpdated();
            Thread.sleep(10);

            cohort.updateRiskDistribution(PatientCohort.RiskLevel.HIGH, 25);
            cohort.updateRiskDistribution(PatientCohort.RiskLevel.MODERATE, 50);
            cohort.updateRiskDistribution(PatientCohort.RiskLevel.LOW, 100);

            assertEquals(3, cohort.getRiskDistribution().size());
            assertEquals(25, cohort.getRiskDistribution().get(PatientCohort.RiskLevel.HIGH));
            assertEquals(50, cohort.getRiskDistribution().get(PatientCohort.RiskLevel.MODERATE));
            assertEquals(100, cohort.getRiskDistribution().get(PatientCohort.RiskLevel.LOW));
            assertTrue(cohort.getLastUpdated().isAfter(before));
        }

        @Test
        @DisplayName("Should calculate high-risk patient count")
        void testGetHighRiskPatientCount() {
            cohort.updateRiskDistribution(PatientCohort.RiskLevel.VERY_LOW, 50);
            cohort.updateRiskDistribution(PatientCohort.RiskLevel.LOW, 100);
            cohort.updateRiskDistribution(PatientCohort.RiskLevel.MODERATE, 75);
            cohort.updateRiskDistribution(PatientCohort.RiskLevel.HIGH, 30);
            cohort.updateRiskDistribution(PatientCohort.RiskLevel.VERY_HIGH, 10);

            // HIGH + VERY_HIGH = 30 + 10 = 40
            assertEquals(40, cohort.getHighRiskPatientCount());
        }

        @Test
        @DisplayName("Should return zero high-risk count when none present")
        void testZeroHighRiskCount() {
            cohort.updateRiskDistribution(PatientCohort.RiskLevel.VERY_LOW, 50);
            cohort.updateRiskDistribution(PatientCohort.RiskLevel.LOW, 100);

            assertEquals(0, cohort.getHighRiskPatientCount());
        }

        @Test
        @DisplayName("Should set average risk score")
        void testAverageRiskScore() {
            cohort.setAverageRiskScore(0.65);

            assertEquals(0.65, cohort.getAverageRiskScore(), 0.001);
        }
    }

    @Nested
    @DisplayName("Quality Metrics Tests")
    class QualityMetricsTests {

        @Test
        @DisplayName("Should update quality metrics")
        void testUpdateQualityMetric() throws InterruptedException {
            LocalDateTime before = cohort.getLastUpdated();
            Thread.sleep(10);

            cohort.updateQualityMetric("HEDIS-CDC-HbA1c", 75.5);
            cohort.updateQualityMetric("HEDIS-BCS", 82.3);

            assertEquals(2, cohort.getQualityMetrics().size());
            assertEquals(75.5, cohort.getQualityMetrics().get("HEDIS-CDC-HbA1c"), 0.001);
            assertEquals(82.3, cohort.getQualityMetrics().get("HEDIS-BCS"), 0.001);
            assertTrue(cohort.getLastUpdated().isAfter(before));
        }

        @Test
        @DisplayName("Should calculate overall quality compliance")
        void testGetOverallQualityCompliance() {
            cohort.updateQualityMetric("HEDIS-CDC-HbA1c", 75.0);
            cohort.updateQualityMetric("HEDIS-BCS", 85.0);
            cohort.updateQualityMetric("HEDIS-COL", 70.0);

            // Average = (75 + 85 + 70) / 3 = 76.67
            assertEquals(76.67, cohort.getOverallQualityCompliance(), 0.01);
        }

        @Test
        @DisplayName("Should return zero compliance for no metrics")
        void testZeroComplianceForNoMetrics() {
            assertEquals(0.0, cohort.getOverallQualityCompliance(), 0.001);
        }

        @Test
        @DisplayName("Should track care gaps identified")
        void testCareGapsTracking() {
            cohort.setCareGapsIdentified(42);

            assertEquals(42, cohort.getCareGapsIdentified());
        }
    }

    @Nested
    @DisplayName("Demographic Profile Tests")
    class DemographicProfileTests {

        @Test
        @DisplayName("Should update demographic profile")
        void testDemographicProfileUpdate() {
            PatientCohort.DemographicProfile demographics = cohort.getDemographics();

            demographics.setAverageAge(62.5);
            demographics.setMaleCount(120);
            demographics.setFemaleCount(145);
            demographics.setOtherGenderCount(5);

            assertEquals(62.5, demographics.getAverageAge(), 0.001);
            assertEquals(120, demographics.getMaleCount());
            assertEquals(145, demographics.getFemaleCount());
            assertEquals(5, demographics.getOtherGenderCount());
        }

        @Test
        @DisplayName("Should track age range distribution")
        void testAgeRangeDistribution() {
            PatientCohort.DemographicProfile demographics = cohort.getDemographics();

            demographics.getAgeRangeDistribution().put("18-34", 25);
            demographics.getAgeRangeDistribution().put("35-54", 80);
            demographics.getAgeRangeDistribution().put("55-74", 150);
            demographics.getAgeRangeDistribution().put("75+", 45);

            assertEquals(4, demographics.getAgeRangeDistribution().size());
            assertEquals(150, demographics.getAgeRangeDistribution().get("55-74"));
        }

        @Test
        @DisplayName("Should track ethnicity distribution")
        void testEthnicityDistribution() {
            PatientCohort.DemographicProfile demographics = cohort.getDemographics();

            demographics.getEthnicityDistribution().put("Hispanic", 60);
            demographics.getEthnicityDistribution().put("Non-Hispanic", 240);

            assertEquals(2, demographics.getEthnicityDistribution().size());
            assertEquals(60, demographics.getEthnicityDistribution().get("Hispanic"));
        }

        @Test
        @DisplayName("Should track race distribution")
        void testRaceDistribution() {
            PatientCohort.DemographicProfile demographics = cohort.getDemographics();

            demographics.getRaceDistribution().put("White", 180);
            demographics.getRaceDistribution().put("Black", 70);
            demographics.getRaceDistribution().put("Asian", 30);
            demographics.getRaceDistribution().put("Other", 20);

            assertEquals(4, demographics.getRaceDistribution().size());
            assertEquals(180, demographics.getRaceDistribution().get("White"));
        }
    }

    @Nested
    @DisplayName("Condition and Medication Distribution Tests")
    class DistributionTests {

        @Test
        @DisplayName("Should update condition distribution")
        void testUpdateConditionDistribution() throws InterruptedException {
            LocalDateTime before = cohort.getLastUpdated();
            Thread.sleep(10);

            cohort.updateConditionDistribution("E11.9", 150); // Type 2 Diabetes
            cohort.updateConditionDistribution("I10", 120);   // Hypertension
            cohort.updateConditionDistribution("E78.5", 80);  // Hyperlipidemia

            assertEquals(3, cohort.getConditionDistribution().size());
            assertEquals(150, cohort.getConditionDistribution().get("E11.9"));
            assertTrue(cohort.getLastUpdated().isAfter(before));
        }

        @Test
        @DisplayName("Should update medication distribution")
        void testUpdateMedicationDistribution() {
            Map<String, Integer> medications = new HashMap<>();
            medications.put("Metformin", 140);
            medications.put("ACE Inhibitors", 110);
            medications.put("Statins", 90);

            cohort.setMedicationDistribution(medications);

            assertEquals(3, cohort.getMedicationDistribution().size());
            assertEquals(140, cohort.getMedicationDistribution().get("Metformin"));
        }
    }

    @Nested
    @DisplayName("toString Tests")
    class ToStringTests {

        @Test
        @DisplayName("Should generate meaningful string representation")
        void testToString() {
            cohort.addPatient("PATIENT-001");
            cohort.addPatient("PATIENT-002");
            cohort.setAverageRiskScore(0.55);
            cohort.setCareGapsIdentified(12);

            String str = cohort.toString();

            assertTrue(str.contains("Diabetes Management Cohort"));
            assertTrue(str.contains("DISEASE_BASED"));
            assertTrue(str.contains("patients=2"));
            assertTrue(str.contains("0.55"));
            assertTrue(str.contains("careGaps=12"));
        }
    }
}
