package com.cardiofit.flink.cds.population;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for QualityMeasure
 * Phase 8 Module 4 - Population Health Module
 *
 * Test Coverage:
 * - Quality measure creation and initialization
 * - Numerator/denominator/exclusion/exception logic
 * - Compliance rate calculation
 * - Performance level determination
 * - Measure criterion creation and management
 * - Stratification tracking
 *
 * @author CardioFit Testing Team
 * @version 1.0.0
 * @since Phase 8
 */
@DisplayName("QualityMeasure Tests")
class QualityMeasureTest {

    private QualityMeasure measure;
    private static final String TEST_MEASURE_NAME = "Diabetes HbA1c Testing";
    private static final QualityMeasure.MeasureType TEST_MEASURE_TYPE = QualityMeasure.MeasureType.PROCESS;
    private static final QualityMeasure.MeasureSource TEST_SOURCE = QualityMeasure.MeasureSource.HEDIS;

    @BeforeEach
    void setUp() {
        measure = new QualityMeasure(TEST_MEASURE_NAME, TEST_MEASURE_TYPE, TEST_SOURCE);
    }

    @Nested
    @DisplayName("Quality Measure Creation Tests")
    class QualityMeasureCreationTests {

        @Test
        @DisplayName("Should create measure with required fields")
        void testMeasureCreation() {
            assertNotNull(measure);
            assertEquals(TEST_MEASURE_NAME, measure.getMeasureName());
            assertEquals(TEST_MEASURE_TYPE, measure.getMeasureType());
            assertEquals(TEST_SOURCE, measure.getSource());
            assertNotNull(measure.getLastCalculated());
            assertTrue(measure.isActive());
        }

        @Test
        @DisplayName("Should auto-generate unique measure ID")
        void testAutoGeneratedMeasureId() throws InterruptedException {
            assertNotNull(measure.getMeasureId());
            assertTrue(measure.getMeasureId().startsWith("QM-"));

            Thread.sleep(1); // Ensure different timestamp
            QualityMeasure measure2 = new QualityMeasure("Blood Pressure Control",
                                                         QualityMeasure.MeasureType.OUTCOME,
                                                         QualityMeasure.MeasureSource.CMS);
            assertNotEquals(measure.getMeasureId(), measure2.getMeasureId());
        }

        @Test
        @DisplayName("Should initialize empty criterion lists")
        void testCriterionListsInitialization() {
            assertNotNull(measure.getNumeratorCriteria());
            assertNotNull(measure.getDenominatorCriteria());
            assertNotNull(measure.getExclusionCriteria());
            assertNotNull(measure.getExceptionCriteria());

            assertEquals(0, measure.getNumeratorCriteria().size());
            assertEquals(0, measure.getDenominatorCriteria().size());
            assertEquals(0, measure.getExclusionCriteria().size());
            assertEquals(0, measure.getExceptionCriteria().size());
        }

        @Test
        @DisplayName("Should support all measure types")
        void testAllMeasureTypes() {
            QualityMeasure.MeasureType[] types = QualityMeasure.MeasureType.values();

            assertEquals(6, types.length);
            assertTrue(containsMeasureType(types, QualityMeasure.MeasureType.PROCESS));
            assertTrue(containsMeasureType(types, QualityMeasure.MeasureType.OUTCOME));
            assertTrue(containsMeasureType(types, QualityMeasure.MeasureType.STRUCTURE));
            assertTrue(containsMeasureType(types, QualityMeasure.MeasureType.PATIENT_EXPERIENCE));
            assertTrue(containsMeasureType(types, QualityMeasure.MeasureType.EFFICIENCY));
            assertTrue(containsMeasureType(types, QualityMeasure.MeasureType.COMPOSITE));
        }

        @Test
        @DisplayName("Should support all measure sources")
        void testAllMeasureSources() {
            QualityMeasure.MeasureSource[] sources = QualityMeasure.MeasureSource.values();

            assertEquals(6, sources.length);
            assertTrue(containsMeasureSource(sources, QualityMeasure.MeasureSource.HEDIS));
            assertTrue(containsMeasureSource(sources, QualityMeasure.MeasureSource.CMS));
            assertTrue(containsMeasureSource(sources, QualityMeasure.MeasureSource.NQF));
            assertTrue(containsMeasureSource(sources, QualityMeasure.MeasureSource.TJC));
            assertTrue(containsMeasureSource(sources, QualityMeasure.MeasureSource.NCQA));
            assertTrue(containsMeasureSource(sources, QualityMeasure.MeasureSource.CUSTOM));
        }

        @Test
        @DisplayName("Should support all performance levels")
        void testAllPerformanceLevels() {
            QualityMeasure.PerformanceLevel[] levels = QualityMeasure.PerformanceLevel.values();

            assertEquals(4, levels.length);
            assertTrue(containsPerformanceLevel(levels, QualityMeasure.PerformanceLevel.NEEDS_IMPROVEMENT));
            assertTrue(containsPerformanceLevel(levels, QualityMeasure.PerformanceLevel.MEETS_TARGET));
            assertTrue(containsPerformanceLevel(levels, QualityMeasure.PerformanceLevel.EXCEEDS_TARGET));
            assertTrue(containsPerformanceLevel(levels, QualityMeasure.PerformanceLevel.TOP_DECILE));

            // Test rank ordering
            assertEquals(1, QualityMeasure.PerformanceLevel.NEEDS_IMPROVEMENT.getRank());
            assertEquals(4, QualityMeasure.PerformanceLevel.TOP_DECILE.getRank());

            // Test colors
            assertEquals("red", QualityMeasure.PerformanceLevel.NEEDS_IMPROVEMENT.getColor());
            assertEquals("blue", QualityMeasure.PerformanceLevel.TOP_DECILE.getColor());
        }

        private boolean containsMeasureType(QualityMeasure.MeasureType[] types, QualityMeasure.MeasureType target) {
            for (QualityMeasure.MeasureType type : types) {
                if (type == target) return true;
            }
            return false;
        }

        private boolean containsMeasureSource(QualityMeasure.MeasureSource[] sources, QualityMeasure.MeasureSource target) {
            for (QualityMeasure.MeasureSource source : sources) {
                if (source == target) return true;
            }
            return false;
        }

        private boolean containsPerformanceLevel(QualityMeasure.PerformanceLevel[] levels, QualityMeasure.PerformanceLevel target) {
            for (QualityMeasure.PerformanceLevel level : levels) {
                if (level == target) return true;
            }
            return false;
        }
    }

    @Nested
    @DisplayName("Measure Criterion Tests")
    class MeasureCriterionTests {

        @Test
        @DisplayName("Should create measure criterion")
        void testCriterionCreation() {
            QualityMeasure.MeasureCriterion criterion = new QualityMeasure.MeasureCriterion(
                QualityMeasure.MeasureCriterion.CriterionType.LAB_VALUE,
                "LOINC"
            );

            criterion.setDescription("HbA1c > 9%");
            criterion.setOperator(">");
            criterion.setValue(9.0);
            criterion.addCode("4548-4"); // LOINC HbA1c

            assertEquals(QualityMeasure.MeasureCriterion.CriterionType.LAB_VALUE, criterion.getCriterionType());
            assertEquals("LOINC", criterion.getCodeSystem());
            assertEquals("HbA1c > 9%", criterion.getDescription());
            assertEquals(">", criterion.getOperator());
            assertEquals(9.0, criterion.getValue());
            assertEquals(1, criterion.getCodes().size());
            assertTrue(criterion.getCodes().contains("4548-4"));
        }

        @Test
        @DisplayName("Should support all criterion types")
        void testAllCriterionTypes() {
            QualityMeasure.MeasureCriterion.CriterionType[] types = QualityMeasure.MeasureCriterion.CriterionType.values();

            assertEquals(10, types.length);
            assertTrue(containsCriterionType(types, QualityMeasure.MeasureCriterion.CriterionType.DIAGNOSIS));
            assertTrue(containsCriterionType(types, QualityMeasure.MeasureCriterion.CriterionType.PROCEDURE));
            assertTrue(containsCriterionType(types, QualityMeasure.MeasureCriterion.CriterionType.LAB_VALUE));
            assertTrue(containsCriterionType(types, QualityMeasure.MeasureCriterion.CriterionType.MEDICATION));
            assertTrue(containsCriterionType(types, QualityMeasure.MeasureCriterion.CriterionType.VITAL_SIGN));
            assertTrue(containsCriterionType(types, QualityMeasure.MeasureCriterion.CriterionType.AGE_RANGE));
            assertTrue(containsCriterionType(types, QualityMeasure.MeasureCriterion.CriterionType.GENDER));
            assertTrue(containsCriterionType(types, QualityMeasure.MeasureCriterion.CriterionType.ENCOUNTER_TYPE));
            assertTrue(containsCriterionType(types, QualityMeasure.MeasureCriterion.CriterionType.OBSERVATION));
            assertTrue(containsCriterionType(types, QualityMeasure.MeasureCriterion.CriterionType.CUSTOM));
        }

        @Test
        @DisplayName("Should support BETWEEN operator with second value")
        void testBetweenOperator() {
            QualityMeasure.MeasureCriterion criterion = new QualityMeasure.MeasureCriterion();
            criterion.setCriterionType(QualityMeasure.MeasureCriterion.CriterionType.AGE_RANGE);
            criterion.setDescription("Age between 50 and 75");
            criterion.setOperator("BETWEEN");
            criterion.setValue(50);
            criterion.setSecondValue(75);

            assertEquals(QualityMeasure.MeasureCriterion.CriterionType.AGE_RANGE, criterion.getCriterionType());
            assertEquals("BETWEEN", criterion.getOperator());
            assertEquals(50, criterion.getValue());
            assertEquals(75, criterion.getSecondValue());
        }

        @Test
        @DisplayName("Should set timeframe for criterion")
        void testCriterionTimeframe() {
            QualityMeasure.MeasureCriterion criterion = new QualityMeasure.MeasureCriterion();
            criterion.setTimeframe("past 12 months");

            assertEquals("past 12 months", criterion.getTimeframe());
        }

        private boolean containsCriterionType(QualityMeasure.MeasureCriterion.CriterionType[] types,
                                              QualityMeasure.MeasureCriterion.CriterionType target) {
            for (QualityMeasure.MeasureCriterion.CriterionType type : types) {
                if (type == target) return true;
            }
            return false;
        }
    }

    @Nested
    @DisplayName("Criterion Management Tests")
    class CriterionManagementTests {

        @Test
        @DisplayName("Should add numerator criterion")
        void testAddNumeratorCriterion() {
            QualityMeasure.MeasureCriterion criterion = new QualityMeasure.MeasureCriterion(
                QualityMeasure.MeasureCriterion.CriterionType.LAB_VALUE,
                "LOINC"
            );
            criterion.setDescription("HbA1c tested in past year");

            measure.addNumeratorCriterion(criterion);

            assertEquals(1, measure.getNumeratorCriteria().size());
            assertEquals("HbA1c tested in past year", measure.getNumeratorCriteria().get(0).getDescription());
        }

        @Test
        @DisplayName("Should add denominator criterion")
        void testAddDenominatorCriterion() {
            QualityMeasure.MeasureCriterion criterion = new QualityMeasure.MeasureCriterion(
                QualityMeasure.MeasureCriterion.CriterionType.DIAGNOSIS,
                "ICD-10"
            );
            criterion.setDescription("Type 2 Diabetes diagnosis");
            criterion.addCode("E11.9");

            measure.addDenominatorCriterion(criterion);

            assertEquals(1, measure.getDenominatorCriteria().size());
            assertEquals("Type 2 Diabetes diagnosis", measure.getDenominatorCriteria().get(0).getDescription());
        }

        @Test
        @DisplayName("Should add exclusion criterion")
        void testAddExclusionCriterion() {
            QualityMeasure.MeasureCriterion criterion = new QualityMeasure.MeasureCriterion(
                QualityMeasure.MeasureCriterion.CriterionType.AGE_RANGE,
                "age"
            );
            criterion.setDescription("Exclude patients under 18");
            criterion.setOperator("<");
            criterion.setValue(18);

            measure.addExclusionCriterion(criterion);

            assertEquals(1, measure.getExclusionCriteria().size());
        }

        @Test
        @DisplayName("Should add exception criterion")
        void testAddExceptionCriterion() {
            QualityMeasure.MeasureCriterion criterion = new QualityMeasure.MeasureCriterion(
                QualityMeasure.MeasureCriterion.CriterionType.DIAGNOSIS,
                "ICD-10"
            );
            criterion.setDescription("Terminal illness exception");
            criterion.addCode("Z51.5");

            measure.addExceptionCriterion(criterion);

            assertEquals(1, measure.getExceptionCriteria().size());
        }
    }

    @Nested
    @DisplayName("Compliance Rate Calculation Tests")
    class ComplianceRateTests {

        @Test
        @DisplayName("Should calculate 100% compliance rate")
        void testPerfectCompliance() {
            measure.setDenominatorCount(100);
            measure.setNumeratorCount(100);
            measure.setExclusionCount(0);
            measure.setExceptionCount(0);

            measure.calculateComplianceRate();

            assertEquals(100.0, measure.getComplianceRate(), 0.001);
        }

        @Test
        @DisplayName("Should calculate 75% compliance rate")
        void testPartialCompliance() {
            measure.setDenominatorCount(100);
            measure.setNumeratorCount(75);
            measure.setExclusionCount(0);
            measure.setExceptionCount(0);

            measure.calculateComplianceRate();

            assertEquals(75.0, measure.getComplianceRate(), 0.001);
        }

        @Test
        @DisplayName("Should adjust denominator for exclusions")
        void testExclusionAdjustment() {
            measure.setDenominatorCount(100);
            measure.setNumeratorCount(80);
            measure.setExclusionCount(10);
            measure.setExceptionCount(0);

            measure.calculateComplianceRate();

            // 80 / (100 - 10) = 88.89%
            assertEquals(88.89, measure.getComplianceRate(), 0.01);
        }

        @Test
        @DisplayName("Should adjust denominator for exceptions")
        void testExceptionAdjustment() {
            measure.setDenominatorCount(100);
            measure.setNumeratorCount(75);
            measure.setExclusionCount(5);
            measure.setExceptionCount(5);

            measure.calculateComplianceRate();

            // 75 / (100 - 5 - 5) = 83.33%
            assertEquals(83.33, measure.getComplianceRate(), 0.01);
        }

        @Test
        @DisplayName("Should return zero for zero adjusted denominator")
        void testZeroAdjustedDenominator() {
            measure.setDenominatorCount(10);
            measure.setNumeratorCount(5);
            measure.setExclusionCount(10);
            measure.setExceptionCount(0);

            measure.calculateComplianceRate();

            assertEquals(0.0, measure.getComplianceRate(), 0.001);
        }
    }

    @Nested
    @DisplayName("Performance Level Tests")
    class PerformanceLevelTests {

        @Test
        @DisplayName("Should determine TOP_DECILE performance level")
        void testTopDecilePerformance() {
            measure.setTargetRate(75.0);
            measure.setTopDecileBenchmark(90.0);
            measure.setDenominatorCount(100);
            measure.setNumeratorCount(92);

            measure.calculateComplianceRate();

            assertEquals(92.0, measure.getComplianceRate(), 0.001);
            assertEquals(QualityMeasure.PerformanceLevel.TOP_DECILE, measure.getPerformanceLevel());
        }

        @Test
        @DisplayName("Should determine EXCEEDS_TARGET performance level")
        void testExceedsTargetPerformance() {
            measure.setTargetRate(75.0);
            measure.setTopDecileBenchmark(90.0);
            measure.setDenominatorCount(100);
            measure.setNumeratorCount(82); // 82% >= 75% + 5%

            measure.calculateComplianceRate();

            assertEquals(82.0, measure.getComplianceRate(), 0.001);
            assertEquals(QualityMeasure.PerformanceLevel.EXCEEDS_TARGET, measure.getPerformanceLevel());
        }

        @Test
        @DisplayName("Should determine MEETS_TARGET performance level")
        void testMeetsTargetPerformance() {
            measure.setTargetRate(75.0);
            measure.setDenominatorCount(100);
            measure.setNumeratorCount(76);

            measure.calculateComplianceRate();

            assertEquals(76.0, measure.getComplianceRate(), 0.001);
            assertEquals(QualityMeasure.PerformanceLevel.MEETS_TARGET, measure.getPerformanceLevel());
        }

        @Test
        @DisplayName("Should determine NEEDS_IMPROVEMENT performance level")
        void testNeedsImprovementPerformance() {
            measure.setTargetRate(75.0);
            measure.setDenominatorCount(100);
            measure.setNumeratorCount(65);

            measure.calculateComplianceRate();

            assertEquals(65.0, measure.getComplianceRate(), 0.001);
            assertEquals(QualityMeasure.PerformanceLevel.NEEDS_IMPROVEMENT, measure.getPerformanceLevel());
        }
    }

    @Nested
    @DisplayName("Gap and Passing Tests")
    class GapPassingTests {

        @Test
        @DisplayName("Should calculate gap from target")
        void testGetGapFromTarget() {
            measure.setTargetRate(80.0);
            measure.setDenominatorCount(100);
            measure.setNumeratorCount(70);

            measure.calculateComplianceRate();

            // Target 80%, actual 70%, gap = 10%
            assertEquals(10.0, measure.getGapFromTarget(), 0.001);
        }

        @Test
        @DisplayName("Should return negative gap when exceeding target")
        void testNegativeGap() {
            measure.setTargetRate(75.0);
            measure.setDenominatorCount(100);
            measure.setNumeratorCount(85);

            measure.calculateComplianceRate();

            // Target 75%, actual 85%, gap = -10%
            assertEquals(-10.0, measure.getGapFromTarget(), 0.001);
        }

        @Test
        @DisplayName("Should detect if measure is passing")
        void testIsPassing() {
            measure.setTargetRate(75.0);
            measure.setDenominatorCount(100);
            measure.setNumeratorCount(80);

            measure.calculateComplianceRate();

            assertTrue(measure.isPassing());
        }

        @Test
        @DisplayName("Should detect if measure is not passing")
        void testIsNotPassing() {
            measure.setTargetRate(75.0);
            measure.setDenominatorCount(100);
            measure.setNumeratorCount(70);

            measure.calculateComplianceRate();

            assertFalse(measure.isPassing());
        }
    }

    @Nested
    @DisplayName("Stratification and Metadata Tests")
    class StratificationMetadataTests {

        @Test
        @DisplayName("Should add stratification results")
        void testAddStratification() {
            measure.addStratification("Age 50-64", 78.5);
            measure.addStratification("Age 65+", 82.3);
            measure.addStratification("Male", 75.8);
            measure.addStratification("Female", 81.2);

            assertEquals(4, measure.getStratificationResults().size());
            assertEquals(78.5, measure.getStratificationResults().get("Age 50-64"), 0.001);
            assertEquals(82.3, measure.getStratificationResults().get("Age 65+"), 0.001);
        }

        @Test
        @DisplayName("Should set measure specification identifiers")
        void testMeasureSpecification() {
            measure.setVersion("HEDIS 2023");
            measure.setNqfNumber("0059");
            measure.setCmsId("CMS122v10");
            measure.setHedisCode("CDC");

            assertEquals("HEDIS 2023", measure.getVersion());
            assertEquals("0059", measure.getNqfNumber());
            assertEquals("CMS122v10", measure.getCmsId());
            assertEquals("CDC", measure.getHedisCode());
        }

        @Test
        @DisplayName("Should set measurement period")
        void testMeasurementPeriod() {
            LocalDate startDate = LocalDate.of(2023, 1, 1);
            LocalDate endDate = LocalDate.of(2023, 12, 31);

            measure.setMeasurementStartDate(startDate);
            measure.setMeasurementEndDate(endDate);
            measure.setMeasurementPeriodDays(365);

            assertEquals(startDate, measure.getMeasurementStartDate());
            assertEquals(endDate, measure.getMeasurementEndDate());
            assertEquals(365, measure.getMeasurementPeriodDays());
        }

        @Test
        @DisplayName("Should set benchmarks and targets")
        void testBenchmarksAndTargets() {
            measure.setTargetRate(75.0);
            measure.setNationalBenchmark(72.5);
            measure.setTopDecileBenchmark(90.0);

            assertEquals(75.0, measure.getTargetRate(), 0.001);
            assertEquals(72.5, measure.getNationalBenchmark(), 0.001);
            assertEquals(90.0, measure.getTopDecileBenchmark(), 0.001);
        }

        @Test
        @DisplayName("Should set clinical context")
        void testClinicalContext() {
            measure.setClinicalDomain("Diabetes");
            measure.setRelatedGuideline("ADA 2023 Standards of Care");
            measure.setCoreSet(true);
            measure.setStarRating(true);

            assertEquals("Diabetes", measure.getClinicalDomain());
            assertEquals("ADA 2023 Standards of Care", measure.getRelatedGuideline());
            assertTrue(measure.isCoreSet());
            assertTrue(measure.isStarRating());
        }

        @Test
        @DisplayName("Should set calculated by and audit info")
        void testAuditInfo() {
            measure.setCalculatedBy("PopulationHealthService");

            assertEquals("PopulationHealthService", measure.getCalculatedBy());
            assertNotNull(measure.getLastCalculated());
        }
    }

    @Nested
    @DisplayName("toString Tests")
    class ToStringTests {

        @Test
        @DisplayName("Should generate meaningful string representation")
        void testToString() {
            measure.setTargetRate(75.0);
            measure.setDenominatorCount(100);
            measure.setNumeratorCount(82);
            measure.calculateComplianceRate();

            String str = measure.toString();

            assertTrue(str.contains("Diabetes HbA1c Testing"));
            assertTrue(str.contains("PROCESS"));
            assertTrue(str.contains("82.0")); // compliance
            assertTrue(str.contains("75.0")); // target
            assertTrue(str.contains("EXCEEDS_TARGET"));
        }
    }
}
