# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import outbox_pb2 as outbox__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in outbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GlobalOutboxServiceStub(object):
    """Global Outbox Service for centralized event publishing
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishEvent = channel.unary_unary(
                '/clinical_hub.outbox.v1.GlobalOutboxService/PublishEvent',
                request_serializer=outbox__pb2.PublishEventRequest.SerializeToString,
                response_deserializer=outbox__pb2.PublishEventResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/clinical_hub.outbox.v1.GlobalOutboxService/HealthCheck',
                request_serializer=outbox__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=outbox__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetOutboxStats = channel.unary_unary(
                '/clinical_hub.outbox.v1.GlobalOutboxService/GetOutboxStats',
                request_serializer=outbox__pb2.OutboxStatsRequest.SerializeToString,
                response_deserializer=outbox__pb2.OutboxStatsResponse.FromString,
                _registered_method=True)
        self.GetEventsByCorrelation = channel.unary_unary(
                '/clinical_hub.outbox.v1.GlobalOutboxService/GetEventsByCorrelation',
                request_serializer=outbox__pb2.GetEventsByCorrelationRequest.SerializeToString,
                response_deserializer=outbox__pb2.GetEventsByCorrelationResponse.FromString,
                _registered_method=True)


class GlobalOutboxServiceServicer(object):
    """Global Outbox Service for centralized event publishing
    """

    def PublishEvent(self, request, context):
        """Publish an event to the outbox for guaranteed delivery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for service monitoring
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOutboxStats(self, request, context):
        """Get outbox statistics for monitoring and debugging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventsByCorrelation(self, request, context):
        """Get events by correlation ID for debugging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlobalOutboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=outbox__pb2.PublishEventRequest.FromString,
                    response_serializer=outbox__pb2.PublishEventResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=outbox__pb2.HealthCheckRequest.FromString,
                    response_serializer=outbox__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetOutboxStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOutboxStats,
                    request_deserializer=outbox__pb2.OutboxStatsRequest.FromString,
                    response_serializer=outbox__pb2.OutboxStatsResponse.SerializeToString,
            ),
            'GetEventsByCorrelation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventsByCorrelation,
                    request_deserializer=outbox__pb2.GetEventsByCorrelationRequest.FromString,
                    response_serializer=outbox__pb2.GetEventsByCorrelationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clinical_hub.outbox.v1.GlobalOutboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('clinical_hub.outbox.v1.GlobalOutboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GlobalOutboxService(object):
    """Global Outbox Service for centralized event publishing
    """

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clinical_hub.outbox.v1.GlobalOutboxService/PublishEvent',
            outbox__pb2.PublishEventRequest.SerializeToString,
            outbox__pb2.PublishEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clinical_hub.outbox.v1.GlobalOutboxService/HealthCheck',
            outbox__pb2.HealthCheckRequest.SerializeToString,
            outbox__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOutboxStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clinical_hub.outbox.v1.GlobalOutboxService/GetOutboxStats',
            outbox__pb2.OutboxStatsRequest.SerializeToString,
            outbox__pb2.OutboxStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventsByCorrelation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clinical_hub.outbox.v1.GlobalOutboxService/GetEventsByCorrelation',
            outbox__pb2.GetEventsByCorrelationRequest.SerializeToString,
            outbox__pb2.GetEventsByCorrelationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
