"""
Test RDF parsing and conversion to Neo4j
"""

import asyncio
import sys
import os
from pathlib import Path

# Add the src directory to the Python path
sys.path.insert(0, str(Path(__file__).parent / "src"))

from core.neo4j_client import Neo4jCloudClient
from core.neo4j_ingester_adapter import Neo4jIngesterAdapter
from core.config import settings
import structlog

# Configure structured logging
structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.dev.ConsoleRenderer()
    ],
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)

logger = structlog.get_logger(__name__)


async def test_rdf_parsing():
    """Test RDF parsing with actual RxNorm format"""
    
    logger.info("Starting RDF parsing test...")
    
    # Sample RDF in the format generated by RxNorm ingester
    sample_rdf = """
<http://example.org/rxnorm/Drug/123456> a cae:Drug ;
    cae:hasRxCUI "123456" ;
    rdfs:label "Aspirin" ;
    cae:hasTermType "IN" ;
    cae:hasSource "RxNorm" ;
    cae:lastUpdated "2024-01-01T00:00:00" .

<http://example.org/rxnorm/Drug/789012> a cae:Drug ;
    cae:hasRxCUI "789012" ;
    rdfs:label "Ibuprofen" ;
    cae:hasTermType "IN" ;
    cae:hasSource "RxNorm" ;
    cae:lastUpdated "2024-01-01T00:00:00" .

<http://example.org/rxnorm/Drug/123456> cae:hasIngredient <http://example.org/rxnorm/Drug/789012> .
"""
    
    logger.info("Sample RDF:", rdf=sample_rdf[:200])
    
    # Create Neo4j client and adapter
    neo4j_client = Neo4jCloudClient()
    adapter = Neo4jIngesterAdapter(neo4j_client)
    
    try:
        # Connect to Neo4j
        logger.info("Connecting to Neo4j...")
        connected = await neo4j_client.connect()
        if not connected:
            logger.error("Failed to connect to Neo4j")
            return
        
        logger.info("Connected to Neo4j successfully")
        
        # Test RDF parsing
        logger.info("Testing RDF parsing...")
        cypher_statements = await adapter._convert_rdf_to_cypher(sample_rdf)
        
        logger.info("Generated Cypher statements", count=len(cypher_statements))
        for i, stmt in enumerate(cypher_statements):
            if isinstance(stmt, tuple):
                query, params = stmt
                logger.info(f"Statement {i+1}", query=query, params=params)
            else:
                logger.info(f"Statement {i+1}", query=stmt)
        
        # Try to execute the statements
        if cypher_statements:
            logger.info("Executing Cypher statements...")
            await adapter._execute_cypher_batch(cypher_statements)
            
            # Verify the data
            logger.info("Verifying data in Neo4j...")
            result = await neo4j_client.execute_cypher(
                "MATCH (n) RETURN labels(n) as labels, n LIMIT 10"
            )
            
            logger.info("Nodes in database:")
            for record in result:
                logger.info("Node", labels=record['labels'], properties=dict(record['n']))
        else:
            logger.warning("No Cypher statements generated from RDF")
        
    except Exception as e:
        logger.error("Test failed", error=str(e), exc_info=True)
    finally:
        logger.info("Disconnecting from Neo4j...")
        await neo4j_client.disconnect()
        logger.info("Test completed")


if __name__ == "__main__":
    asyncio.run(test_rdf_parsing())
