// Package ordersets provides clinical order set templates for KB-12
// admission_ordersets_cardiac.go - Cardiac admission order sets
// Templates: CHF Exacerbation, Acute MI/STEMI, Chest Pain Evaluation
package ordersets

import (
	"time"

	"github.com/google/uuid"
	"kb-12-ordersets-careplans/internal/models"
)

// GetCHFExacerbationOrderSet returns the CHF Exacerbation admission order set
// Based on ACC/AHA Heart Failure Guidelines 2022
func GetCHFExacerbationOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-CARD-001",
		TemplateID:  "OS-CARD-001",
		Name:        "CHF Exacerbation Admission",
		Description: "Comprehensive order set for acute decompensated heart failure admission",
		Version:     "2.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "Cardiac",
		Specialty:   "Cardiology",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Cardiology Clinical Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level A",
		References: []string{
			"2022 ACC/AHA/HFSA Heart Failure Guidelines",
			"ESC Guidelines for HF 2021",
		},
		ICDCodes: []string{"I50.9", "I50.1", "I50.21", "I50.23", "I50.31", "I50.33"},
		SNOMEDCodes: []string{"84114007", "195111005", "10091002"},
		Orders: getCHFOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:          "TC-CHF-001",
				Name:        "Initial Diuretic Administration",
				Description: "IV diuretic within 1 hour of admission",
				Type:        "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes: 60,
				Priority:    "high",
				Rationale:   "Early diuresis improves outcomes in ADHF",
			},
			{
				ID:          "TC-CHF-002",
				Name:        "BNP/NT-proBNP Draw",
				Description: "Natriuretic peptide level within 2 hours",
				Type:        "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes: 120,
				Priority:    "high",
				Rationale:   "Establishes baseline and confirms diagnosis",
			},
		},
		Metadata: map[string]interface{}{
			"expected_los":       "3-5 days",
			"discharge_criteria": []string{"euvolemic", "stable oral diuretics", "stable weight"},
			"escalation_triggers": []string{"cardiogenic shock", "respiratory failure", "renal failure"},
		},
	}
}

func getCHFOrders() []models.Order {
	return []models.Order{
		// === ADMISSION ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Admit to Cardiology/Heart Failure Service",
			Description: "Telemetry bed preferred",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
		},
		{
			ID:          uuid.New().String(),
			Type:        "diet",
			Category:    "Nursing",
			Name:        "Cardiac Diet - Sodium Restricted",
			Description: "2g sodium restriction, fluid restriction if hyponatremic",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
		},
		{
			ID:          uuid.New().String(),
			Type:        "activity",
			Category:    "Nursing",
			Name:        "Activity as Tolerated",
			Description: "Bed rest if hemodynamically unstable, otherwise up ad lib",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Nursing",
			Name:        "Daily Weights",
			Description: "Weigh patient every morning before breakfast",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "daily",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Nursing",
			Name:        "Strict Intake and Output",
			Description: "Document all fluid intake and urine output",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Continuous Telemetry Monitoring",
			Description: "Monitor for arrhythmias",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
		},
		// === MEDICATIONS - DIURETICS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Diuretics",
			Name:        "Furosemide IV",
			Description: "Loop diuretic for volume overload",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "4603",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "q12h",
			Duration:    "until euvolemic",
			Instructions: "Increase to 80mg IV if inadequate response. Consider continuous infusion if refractory.",
			WeightBased: false,
			MaxDose:     "600 mg/day",
			Conditions: []models.OrderCondition{
				{Type: "renal_adjustment", Parameter: "eGFR", Operator: "<", Value: "30", Action: "Double dose may be needed"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Diuretics",
			Name:        "Metolazone",
			Description: "Thiazide-like diuretic for diuretic resistance",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "6916",
			Dose:        "2.5-5",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "daily",
			Duration:    "PRN",
			Instructions: "Give 30 minutes before loop diuretic if diuretic resistance",
			Conditions: []models.OrderCondition{
				{Type: "clinical", Parameter: "diuretic_response", Operator: "=", Value: "inadequate", Action: "Add metolazone"},
			},
		},
		// === MEDICATIONS - HEART FAILURE THERAPIES ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "ACE Inhibitors",
			Name:        "Lisinopril",
			Description: "ACE inhibitor for HFrEF",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "29046",
			Dose:        "2.5-5",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "daily",
			Duration:    "ongoing",
			Instructions: "Titrate to target dose 20-40mg daily as tolerated",
			Conditions: []models.OrderCondition{
				{Type: "contraindication", Parameter: "K", Operator: ">", Value: "5.5", Action: "Hold if hyperkalemic"},
				{Type: "contraindication", Parameter: "SBP", Operator: "<", Value: "90", Action: "Hold if hypotensive"},
				{Type: "renal_adjustment", Parameter: "eGFR", Operator: "<", Value: "30", Action: "Start at 2.5mg"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "ARNi",
			Name:        "Sacubitril-Valsartan",
			Description: "ARNI for HFrEF - preferred over ACE-I if tolerated",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "1656354",
			Dose:        "24/26-49/51",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "BID",
			Duration:    "ongoing",
			Instructions: "36hr washout from ACE-I required. Target 97/103mg BID.",
			Conditions: []models.OrderCondition{
				{Type: "contraindication", Parameter: "ACE_I_use", Operator: "=", Value: "within_36h", Action: "Do not use"},
				{Type: "contraindication", Parameter: "angioedema_history", Operator: "=", Value: "true", Action: "Contraindicated"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Beta Blockers",
			Name:        "Carvedilol",
			Description: "Beta blocker for HFrEF",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "20352",
			Dose:        "3.125",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "BID",
			Duration:    "ongoing",
			Instructions: "Start low, titrate slowly to 25mg BID. Hold if decompensated.",
			Conditions: []models.OrderCondition{
				{Type: "clinical", Parameter: "volume_status", Operator: "=", Value: "overloaded", Action: "Hold until euvolemic"},
				{Type: "contraindication", Parameter: "HR", Operator: "<", Value: "60", Action: "Hold if bradycardic"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "MRA",
			Name:        "Spironolactone",
			Description: "Mineralocorticoid receptor antagonist for HFrEF",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "9997",
			Dose:        "12.5-25",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "daily",
			Duration:    "ongoing",
			Instructions: "Monitor potassium closely. Target 25-50mg daily.",
			Conditions: []models.OrderCondition{
				{Type: "contraindication", Parameter: "K", Operator: ">", Value: "5.0", Action: "Hold if K > 5.0"},
				{Type: "contraindication", Parameter: "eGFR", Operator: "<", Value: "30", Action: "Use with caution"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "SGLT2i",
			Name:        "Dapagliflozin",
			Description: "SGLT2 inhibitor for HFrEF/HFpEF",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "1488564",
			Dose:        "10",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "daily",
			Duration:    "ongoing",
			Instructions: "Benefits regardless of diabetes status. Monitor for UTI/DKA.",
			Conditions: []models.OrderCondition{
				{Type: "contraindication", Parameter: "eGFR", Operator: "<", Value: "20", Action: "Not recommended"},
				{Type: "warning", Parameter: "diabetes", Operator: "=", Value: "type1", Action: "Caution - DKA risk"},
			},
		},
		// === MEDICATIONS - SUPPORTIVE ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Enoxaparin",
			Description: "DVT prophylaxis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "67108",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "SubQ",
			Frequency:   "daily",
			Duration:    "during hospitalization",
			Instructions: "Reduce to 30mg daily if CrCl < 30",
			WeightBased: false,
			Conditions: []models.OrderCondition{
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "30", Action: "Reduce to 30mg daily"},
				{Type: "contraindication", Parameter: "active_bleeding", Operator: "=", Value: "true", Action: "Hold"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Electrolytes",
			Name:        "Potassium Chloride",
			Description: "Potassium replacement PRN",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "8591",
			Dose:        "20-40",
			DoseUnit:    "mEq",
			Route:       "PO/IV",
			Frequency:   "PRN",
			Instructions: "Replace to maintain K 4.0-5.0 mEq/L",
			Conditions: []models.OrderCondition{
				{Type: "lab", Parameter: "K", Operator: "<", Value: "3.5", Action: "Replace 40 mEq"},
				{Type: "lab", Parameter: "K", Operator: "<", Value: "4.0", Action: "Replace 20 mEq"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Electrolytes",
			Name:        "Magnesium Sulfate",
			Description: "Magnesium replacement PRN",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "6585",
			Dose:        "2",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "PRN",
			Instructions: "Replace to maintain Mg > 2.0 mg/dL",
			Conditions: []models.OrderCondition{
				{Type: "lab", Parameter: "Mg", Operator: "<", Value: "1.8", Action: "Replace 2g IV"},
			},
		},
		// === LABORATORY ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Basic Metabolic Panel",
			Description: "Monitor renal function and electrolytes",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "51990-0",
			Frequency:   "daily",
			Instructions: "BMP daily while on IV diuretics",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Cardiac",
			Name:        "BNP",
			Description: "B-type natriuretic peptide",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "30934-4",
			Frequency:   "admission, discharge",
			Instructions: "Baseline and pre-discharge for prognostication",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Cardiac",
			Name:        "Troponin I",
			Description: "Cardiac troponin to evaluate for ischemia",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "10839-9",
			Frequency:   "admission",
			Instructions: "Single troponin unless chest pain/ischemic symptoms",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count",
			Description: "Evaluate for anemia, infection",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
			Frequency:   "admission",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hepatic",
			Name:        "Hepatic Function Panel",
			Description: "Evaluate hepatic congestion",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "24325-3",
			Frequency:   "admission",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Thyroid",
			Name:        "TSH",
			Description: "Thyroid function - reversible cause of HF",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "3016-3",
			Frequency:   "admission",
			Instructions: "If not done in past 12 months",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Iron Studies",
			Name:        "Iron Studies",
			Description: "Ferritin and TSAT for iron deficiency evaluation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "2498-4",
			Frequency:   "admission",
			Instructions: "IV iron if ferritin <100 or TSAT <20% with ferritin 100-300",
		},
		// === IMAGING/DIAGNOSTICS ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "Chest X-Ray PA and Lateral",
			Description: "Evaluate pulmonary congestion, cardiomegaly",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "71046",
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Cardiology",
			Name:        "Transthoracic Echocardiogram",
			Description: "Assess LVEF, wall motion, valves",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "93306",
			Instructions: "If no echo in past 12 months or clinical change",
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Cardiology",
			Name:        "12-Lead ECG",
			Description: "Evaluate rhythm, ischemia, conduction",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "93000",
		},
		// === CONSULTS ===
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Cardiology Consult",
			Description: "Heart failure specialist evaluation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consider for new HF diagnosis, refractory symptoms, device evaluation",
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Ancillary",
			Name:        "Dietary Consult",
			Description: "Sodium and fluid restriction education",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Ancillary",
			Name:        "Physical Therapy",
			Description: "Mobility and exercise assessment",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "If prolonged immobility or deconditioning",
		},
	}
}

// GetAcuteMIOrderSet returns the Acute MI/STEMI admission order set
// Based on ACC/AHA STEMI Guidelines 2021
func GetAcuteMIOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-CARD-002",
		TemplateID:  "OS-CARD-002",
		Name:        "Acute MI/STEMI Admission",
		Description: "Time-critical order set for ST-elevation myocardial infarction",
		Version:     "2.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "Cardiac",
		Specialty:   "Cardiology",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Interventional Cardiology Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level A",
		References: []string{
			"2021 ACC/AHA/SCAI STEMI Guidelines",
			"ESC STEMI Guidelines 2023",
		},
		ICDCodes: []string{"I21.0", "I21.1", "I21.2", "I21.3", "I21.4"},
		SNOMEDCodes: []string{"401303003", "401314000", "57054005"},
		Orders: getAcuteMIOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:          "TC-STEMI-001",
				Name:        "ECG Within 10 Minutes",
				Description: "12-lead ECG must be obtained within 10 minutes of arrival",
				Type:        "deadline",
				ReferenceEvent: "arrival",
				OffsetMinutes: 10,
				Priority:    "critical",
				Rationale:   "ACC/AHA Class I recommendation for rapid STEMI diagnosis",
				Regulatory:  true,
			},
			{
				ID:          "TC-STEMI-002",
				Name:        "Door-to-Balloon Time",
				Description: "PCI must be performed within 90 minutes of arrival",
				Type:        "deadline",
				ReferenceEvent: "arrival",
				OffsetMinutes: 90,
				Priority:    "critical",
				Rationale:   "ACC/AHA Class I - door-to-balloon <90min",
				Regulatory:  true,
			},
			{
				ID:          "TC-STEMI-003",
				Name:        "Aspirin Administration",
				Description: "Aspirin must be given within 30 minutes of arrival",
				Type:        "deadline",
				ReferenceEvent: "arrival",
				OffsetMinutes: 30,
				Priority:    "critical",
				Rationale:   "Immediate antiplatelet therapy reduces mortality",
			},
			{
				ID:          "TC-STEMI-004",
				Name:        "P2Y12 Inhibitor Loading",
				Description: "P2Y12 inhibitor load before or at time of PCI",
				Type:        "deadline",
				ReferenceEvent: "pci_start",
				OffsetMinutes: 0,
				Priority:    "high",
				Rationale:   "DAPT required for PCI",
			},
		},
		Metadata: map[string]interface{}{
			"cath_lab_activation":   true,
			"time_critical":         true,
			"quality_metrics":       []string{"door_to_ecg", "door_to_balloon", "aspirin_timing"},
			"escalation_triggers":   []string{"cardiogenic shock", "cardiac arrest", "mechanical complication"},
		},
	}
}

func getAcuteMIOrders() []models.Order {
	return []models.Order{
		// === IMMEDIATE ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "alert",
			Category:    "Critical",
			Name:        "STEMI Alert - Activate Cath Lab",
			Description: "Immediate cath lab activation for primary PCI",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Call cath lab team immediately. Target door-to-balloon <90 min.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Admit to CCU/Cardiac ICU",
			Description: "Intensive cardiac monitoring required",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Cardiology",
			Name:        "STAT 12-Lead ECG",
			Description: "Immediate ECG within 10 minutes of arrival",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "93000",
			Instructions: "Serial ECGs q15-30min until cath lab or if symptoms change",
		},
		// === MEDICATIONS - ANTIPLATELET ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antiplatelet",
			Name:        "Aspirin",
			Description: "Non-enteric coated aspirin - chewed",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "1191",
			Dose:        "325",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "once",
			Instructions: "Chew immediately unless already given by EMS. 81mg daily thereafter.",
			Conditions: []models.OrderCondition{
				{Type: "contraindication", Parameter: "aspirin_allergy", Operator: "=", Value: "true", Action: "Use alternative antiplatelet"},
				{Type: "warning", Parameter: "active_bleeding", Operator: "=", Value: "true", Action: "Assess risk/benefit"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antiplatelet",
			Name:        "Ticagrelor",
			Description: "P2Y12 inhibitor - preferred for STEMI",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "1116632",
			Dose:        "180",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "once (loading dose)",
			Instructions: "Give before or at PCI. Maintenance 90mg BID x12 months.",
			Conditions: []models.OrderCondition{
				{Type: "alternative", Parameter: "ticagrelor_contraindicated", Operator: "=", Value: "true", Action: "Use Prasugrel or Clopidogrel"},
				{Type: "contraindication", Parameter: "prior_stroke", Operator: "=", Value: "hemorrhagic", Action: "Contraindicated - use Clopidogrel"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antiplatelet",
			Name:        "Prasugrel (Alternative)",
			Description: "P2Y12 inhibitor - alternative to ticagrelor",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "855812",
			Dose:        "60",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "once (loading dose)",
			Instructions: "Alternative if ticagrelor unavailable. Maintenance 10mg daily.",
			Conditions: []models.OrderCondition{
				{Type: "contraindication", Parameter: "prior_stroke_tia", Operator: "=", Value: "true", Action: "Contraindicated"},
				{Type: "contraindication", Parameter: "age", Operator: ">=", Value: "75", Action: "Generally not recommended"},
				{Type: "contraindication", Parameter: "weight", Operator: "<", Value: "60", Action: "Consider 5mg maintenance"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antiplatelet",
			Name:        "Clopidogrel (Alternative)",
			Description: "P2Y12 inhibitor - if ticagrelor/prasugrel contraindicated",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "32968",
			Dose:        "600",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "once (loading dose)",
			Instructions: "Use if ticagrelor and prasugrel contraindicated. Maintenance 75mg daily.",
		},
		// === MEDICATIONS - ANTICOAGULATION ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Unfractionated Heparin",
			Description: "UFH bolus and infusion for PCI",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "5224",
			Dose:        "70-100",
			DoseUnit:    "units/kg",
			Route:       "IV",
			Frequency:   "bolus",
			Instructions: "Target ACT 250-300s for PCI. Additional heparin per cath lab protocol.",
			WeightBased: true,
			MaxDose:     "10000 units",
			Conditions: []models.OrderCondition{
				{Type: "monitoring", Parameter: "ACT", Operator: "<", Value: "250", Action: "Additional heparin needed"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Bivalirudin (Alternative)",
			Description: "Direct thrombin inhibitor - alternative to heparin",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "68587",
			Dose:        "0.75",
			DoseUnit:    "mg/kg",
			Route:       "IV",
			Frequency:   "bolus then 1.75 mg/kg/hr infusion",
			Instructions: "Alternative for HIT or high bleeding risk. Per cath lab protocol.",
			WeightBased: true,
		},
		// === MEDICATIONS - SUPPORTIVE ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antianginal",
			Name:        "Nitroglycerin",
			Description: "Sublingual NTG for chest pain",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "4917",
			Dose:        "0.4",
			DoseUnit:    "mg",
			Route:       "SL",
			Frequency:   "q5min PRN",
			Instructions: "May repeat x3 doses. Hold if SBP <90 or RV infarct.",
			MaxDose:     "3 doses",
			Conditions: []models.OrderCondition{
				{Type: "contraindication", Parameter: "SBP", Operator: "<", Value: "90", Action: "Hold"},
				{Type: "contraindication", Parameter: "PDE5_inhibitor", Operator: "=", Value: "within_24h", Action: "Contraindicated"},
				{Type: "contraindication", Parameter: "RV_infarct", Operator: "=", Value: "true", Action: "Contraindicated"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Analgesic",
			Name:        "Morphine",
			Description: "Pain control for ongoing chest pain",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "7052",
			Dose:        "2-4",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "q5-15min PRN",
			Instructions: "For ongoing chest pain despite NTG. Use with caution - may worsen outcomes.",
			MaxDose:     "10 mg",
			Conditions: []models.OrderCondition{
				{Type: "warning", Parameter: "hypotension", Operator: "=", Value: "true", Action: "Use with extreme caution"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Beta Blocker",
			Name:        "Metoprolol",
			Description: "Beta blocker - initiate within 24h if stable",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "6918",
			Dose:        "12.5-25",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "BID-TID",
			Instructions: "Initiate within 24h if hemodynamically stable. Titrate to target HR 50-60.",
			Conditions: []models.OrderCondition{
				{Type: "contraindication", Parameter: "HR", Operator: "<", Value: "60", Action: "Hold"},
				{Type: "contraindication", Parameter: "SBP", Operator: "<", Value: "100", Action: "Hold"},
				{Type: "contraindication", Parameter: "cardiogenic_shock", Operator: "=", Value: "true", Action: "Contraindicated"},
				{Type: "contraindication", Parameter: "acute_HF", Operator: "=", Value: "severe", Action: "Defer initiation"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Statin",
			Name:        "Atorvastatin",
			Description: "High-intensity statin therapy",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "83367",
			Dose:        "80",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "daily",
			Duration:    "indefinite",
			Instructions: "High-intensity statin for all STEMI patients",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "ACE Inhibitor",
			Name:        "Lisinopril",
			Description: "ACE inhibitor - initiate within 24h",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "29046",
			Dose:        "2.5-5",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "daily",
			Instructions: "Initiate within 24h. Titrate as tolerated. Especially if EF <40%, anterior MI.",
			Conditions: []models.OrderCondition{
				{Type: "contraindication", Parameter: "SBP", Operator: "<", Value: "100", Action: "Defer until stable"},
				{Type: "contraindication", Parameter: "K", Operator: ">", Value: "5.5", Action: "Hold"},
			},
		},
		// === LABORATORY ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Cardiac",
			Name:        "Troponin I - Serial",
			Description: "Serial troponins to assess infarct size",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "10839-9",
			Frequency:   "q6h x 3",
			Instructions: "Baseline, 6h, 12h. Peak troponin correlates with infarct size.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Basic Metabolic Panel",
			Description: "Renal function, electrolytes",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "51990-0",
			Frequency:   "q12h x 48h",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count",
			Description: "Baseline CBC, monitor for bleeding",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
			Frequency:   "daily x 3 days",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Coagulation",
			Name:        "PT/INR, PTT",
			Description: "Coagulation studies",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "5902-2",
			Frequency:   "baseline",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Lipid",
			Name:        "Lipid Panel",
			Description: "Baseline lipids within 24h",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "24331-1",
			Frequency:   "once",
			Instructions: "Draw within 24h before values affected by acute stress",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Metabolic",
			Name:        "Hemoglobin A1c",
			Description: "Screen for diabetes",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "4548-4",
			Frequency:   "once",
		},
		// === IMAGING ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "Portable Chest X-Ray",
			Description: "Evaluate for pulmonary edema, cardiomegaly",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "71045",
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Cardiology",
			Name:        "Transthoracic Echocardiogram",
			Description: "Assess LV function, wall motion, complications",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "93306",
			Instructions: "Within 24-48h post-PCI to assess LVEF and complications",
		},
		// === NURSING ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Continuous Telemetry",
			Description: "Continuous cardiac monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Monitor for arrhythmias minimum 48h",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Vital Signs",
			Description: "Frequent vital sign monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q15min x 4h, then q1h x 24h, then q4h",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Vascular",
			Name:        "Access Site Monitoring",
			Description: "Monitor femoral/radial access site",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Check for hematoma, bleeding, pulse q15min x 4h post-cath",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Activity",
			Name:        "Bed Rest",
			Description: "Activity restriction post-PCI",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Bed rest 2-4h post-radial, 6h post-femoral access",
		},
	}
}

// GetChestPainOrderSet returns the Chest Pain Evaluation admission order set
// For risk stratification and workup of undifferentiated chest pain
func GetChestPainOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-CARD-003",
		TemplateID:  "OS-CARD-003",
		Name:        "Chest Pain Evaluation Admission",
		Description: "Order set for risk stratification and evaluation of undifferentiated chest pain",
		Version:     "2.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "Cardiac",
		Specialty:   "Cardiology",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Cardiology Clinical Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level B",
		References: []string{
			"2021 ACC/AHA Chest Pain Guidelines",
			"HEART Score Validation Studies",
		},
		ICDCodes: []string{"R07.9", "R07.89", "I20.9", "I25.10"},
		SNOMEDCodes: []string{"29857009", "194828000"},
		Orders: getChestPainOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:          "TC-CP-001",
				Name:        "Initial ECG",
				Description: "ECG within 10 minutes of arrival",
				Type:        "deadline",
				ReferenceEvent: "arrival",
				OffsetMinutes: 10,
				Priority:    "high",
				Rationale:   "Rapid identification of STEMI or ischemia",
			},
			{
				ID:          "TC-CP-002",
				Name:        "Initial Troponin",
				Description: "First troponin within 30 minutes",
				Type:        "deadline",
				ReferenceEvent: "arrival",
				OffsetMinutes: 30,
				Priority:    "high",
				Rationale:   "Early rule-out/rule-in of MI",
			},
			{
				ID:          "TC-CP-003",
				Name:        "Serial Troponin",
				Description: "Second troponin at 3 hours with high-sensitivity assay",
				Type:        "deadline",
				ReferenceEvent: "first_troponin",
				OffsetMinutes: 180,
				Priority:    "high",
				Rationale:   "0/3h rule-out protocol with hs-cTn",
			},
		},
		Metadata: map[string]interface{}{
			"risk_scores":         []string{"HEART", "TIMI", "GRACE"},
			"disposition_options": []string{"discharge", "observation", "admission", "cath_lab"},
		},
	}
}

func getChestPainOrders() []models.Order {
	return []models.Order{
		// === IMMEDIATE EVALUATION ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Cardiology",
			Name:        "STAT 12-Lead ECG",
			Description: "Immediate ECG for ischemia evaluation",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "93000",
			Instructions: "Within 10 minutes. Compare to prior if available.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Observation Status - Chest Pain",
			Description: "Place in observation for cardiac workup",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Telemetry bed required",
		},
		// === MEDICATIONS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antiplatelet",
			Name:        "Aspirin",
			Description: "Aspirin for suspected ACS",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "1191",
			Dose:        "325",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "once",
			Instructions: "Give if ACS suspected and no contraindications",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "ACS_suspected", Operator: "=", Value: "true", Action: "Administer"},
				{Type: "contraindication", Parameter: "active_bleeding", Operator: "=", Value: "true", Action: "Hold"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antianginal",
			Name:        "Nitroglycerin SL",
			Description: "PRN for chest pain",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "4917",
			Dose:        "0.4",
			DoseUnit:    "mg",
			Route:       "SL",
			Frequency:   "q5min PRN",
			MaxDose:     "3 doses",
			Conditions: []models.OrderCondition{
				{Type: "contraindication", Parameter: "SBP", Operator: "<", Value: "90", Action: "Hold"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Enoxaparin",
			Description: "DVT prophylaxis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "67108",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "SubQ",
			Frequency:   "daily",
			Instructions: "Reduce to 30mg if CrCl <30",
		},
		// === SERIAL TROPONINS ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Cardiac",
			Name:        "High-Sensitivity Troponin I - Serial",
			Description: "Serial hs-cTnI for 0/3h protocol",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "89579-7",
			Frequency:   "0h, 3h",
			Instructions: "0/3h rule-out protocol. If negative x2, consider discharge vs stress test.",
		},
		// === BASIC LABS ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Basic Metabolic Panel",
			Description: "Electrolytes and renal function",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "51990-0",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count",
			Description: "Evaluate for anemia",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Cardiac",
			Name:        "BNP",
			Description: "Evaluate for heart failure",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "30934-4",
			Instructions: "If heart failure suspected",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Coagulation",
			Name:        "D-Dimer",
			Description: "PE evaluation if clinically indicated",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "48066-5",
			Instructions: "Order if PE is in differential (use Wells score)",
		},
		// === IMAGING ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "Chest X-Ray PA and Lateral",
			Description: "Evaluate for pulmonary/mediastinal pathology",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "71046",
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Cardiology",
			Name:        "Exercise Stress Test",
			Description: "Functional testing if troponins negative",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "93015",
			Instructions: "If troponins negative x2 and able to exercise. Alternative: pharmacologic stress.",
			Conditions: []models.OrderCondition{
				{Type: "prerequisite", Parameter: "troponin", Operator: "=", Value: "negative_x2", Action: "Order stress test"},
				{Type: "prerequisite", Parameter: "ecg_interpretable", Operator: "=", Value: "true", Action: "Exercise ETT"},
				{Type: "alternative", Parameter: "unable_to_exercise", Operator: "=", Value: "true", Action: "Pharmacologic stress"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Cardiology",
			Name:        "Coronary CT Angiography",
			Description: "Anatomic evaluation of coronary arteries",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "75574",
			Instructions: "Alternative to stress testing for low-intermediate risk patients",
			Conditions: []models.OrderCondition{
				{Type: "contraindication", Parameter: "renal_function", Operator: "<", Value: "30", Action: "Avoid contrast"},
				{Type: "contraindication", Parameter: "HR", Operator: ">", Value: "100", Action: "Beta-blocker may be needed"},
			},
		},
		// === NURSING ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Continuous Telemetry",
			Description: "Cardiac rhythm monitoring",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Vital Signs",
			Description: "Regular vital sign monitoring",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q4h",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Assessment",
			Name:        "Pain Assessment",
			Description: "Document chest pain characteristics",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Document location, quality, severity, radiation, duration, associated symptoms",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Protocol",
			Name:        "HEART Score Calculation",
			Description: "Calculate HEART score for risk stratification",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Calculate HEART score: History, ECG, Age, Risk factors, Troponin (0-10 points)",
		},
	}
}

// GetSTEMIAdmissionOrderSet returns the STEMI Admission order set
// Based on ACC/AHA STEMI Guidelines 2021 - Post-PCI Admission Management
func GetSTEMIAdmissionOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-ADM-005",
		TemplateID:  "OS-ADM-005",
		Name:        "STEMI Post-PCI Admission",
		Description: "STEMI admission order set for post-PCI management including antiplatelet therapy, monitoring, and secondary prevention per ACC/AHA guidelines",
		Version:     "2024.1",
		Category:    models.CategoryAdmission,
		Subcategory: "Cardiac",
		Specialty:   "Cardiology",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Interventional Cardiology Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level A",
		References: []string{
			"2021 ACC/AHA/SCAI Coronary Revascularization Guidelines",
			"2013 ACCF/AHA STEMI Guidelines (updated 2017)",
			"ESC STEMI Guidelines 2017",
		},
		ICDCodes: []string{"I21.0", "I21.1", "I21.2", "I21.3", "I21.4"},
		SNOMEDCodes: []string{"401303003", "401314000", "233824008"},
		Orders: getSTEMIAdmissionOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:          "TC-STEMI-ADM-001",
				Name:        "Door-to-Balloon Time",
				Description: "First balloon inflation within 90 minutes of first medical contact",
				Type:        "door-to-balloon",
				ReferenceEvent: "first_medical_contact",
				OffsetMinutes: 90,
				Deadline:    90 * time.Minute,
				Priority:    "critical",
				Rationale:   "ACC/AHA Class I recommendation for primary PCI in STEMI",
			},
			{
				ID:          "TC-STEMI-ADM-002",
				Name:        "Post-PCI Monitoring",
				Description: "Continuous cardiac monitoring for minimum 24 hours post-PCI",
				Type:        "monitoring",
				ReferenceEvent: "pci_completion",
				OffsetMinutes: 1440,
				Priority:    "high",
				Rationale:   "Early detection of reperfusion arrhythmias and re-occlusion",
			},
			{
				ID:          "TC-STEMI-ADM-003",
				Name:        "Echocardiogram",
				Description: "TTE to assess LV function within 48 hours",
				Type:        "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes: 2880,
				Priority:    "high",
				Rationale:   "Establishes baseline LVEF for risk stratification and therapy decisions",
			},
		},
		Metadata: map[string]interface{}{
			"kb1_drug_check":       true,
			"kb3_temporal_enabled": true,
			"kb6_formulary_check":  true,
			"kb7_snomed_validated": true,
			"quality_measures":     []string{"ACC_D2B", "STEMI_ANTIPLATELET", "STEMI_BETA_BLOCKER"},
			"target_los_hours":     72,
			"ccu_admission":        true,
		},
		Active: true,
	}
}

// getSTEMIAdmissionOrders returns orders for STEMI post-PCI admission
func getSTEMIAdmissionOrders() []models.Order {
	return []models.Order{
		// Admission and Monitoring
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Admission",
			Name:        "Admit to CCU/ICU",
			Description: "Cardiac Care Unit admission for post-STEMI monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "CCU/ICU level of care. Continuous telemetry monitoring. 1:1 or 1:2 nursing ratio.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Continuous Cardiac Monitoring",
			Description: "Continuous ECG and hemodynamic monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Continuous telemetry. VS q15min x4, then q1h x4, then q4h. Notify MD for: SBP <90 or >180, HR <50 or >120, new ST changes, arrhythmias.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Access Site Assessment",
			Description: "Monitor arterial access site post-catheterization",
			Priority:    "urgent",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Assess femoral/radial site q15min x4, then q1h x4, then q4h. Check for hematoma, bleeding, pseudoaneurysm signs. Maintain pressure dressing as per cath lab protocol.",
		},
		// Antiplatelet Therapy (DAPT)
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antiplatelet",
			Name:        "Aspirin 81mg Daily",
			Description: "Lifelong aspirin therapy post-STEMI/PCI",
			Priority:    "urgent",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Aspirin 81mg PO daily. Continue indefinitely unless contraindicated. (Class I, Level A)",
			DrugCode:    "aspirin-81mg",
			RxNormCode:  "212033",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antiplatelet",
			Name:        "P2Y12 Inhibitor (DAPT)",
			Description: "Dual antiplatelet therapy with P2Y12 inhibitor",
			Priority:    "urgent",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Select one: Ticagrelor 90mg PO BID (preferred) OR Prasugrel 10mg PO daily (if <75y, >60kg, no prior stroke) OR Clopidogrel 75mg PO daily (if P2Y12 alternatives CI). Continue minimum 12 months. (Class I, Level A)",
			DrugCode:    "p2y12-inhibitor",
			RxNormCode:  "855320",
		},
		// Anticoagulation
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "UFH or LMWH Post-PCI",
			Description: "Short-term anticoagulation post-PCI",
			Priority:    "urgent",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Enoxaparin 40mg SQ daily for VTE prophylaxis OR continue UFH if started in cath lab per protocol. D/C anticoagulation when ambulating unless other indication.",
			DrugCode:    "enoxaparin-40mg",
			RxNormCode:  "854228",
		},
		// Beta Blocker
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Rate Control",
			Name:        "Beta Blocker",
			Description: "Oral beta blocker within 24 hours post-STEMI",
			Priority:    "urgent",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Start Metoprolol succinate 25mg PO daily OR Carvedilol 3.125mg PO BID. Titrate to HR 55-65 if tolerated. Hold if: SBP <100, HR <55, 2nd/3rd degree AV block, active decompensated HF. (Class I, Level B)",
			DrugCode:    "metoprolol-succinate-25mg",
			RxNormCode:  "866511",
		},
		// Statin
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Lipid",
			Name:        "High-Intensity Statin",
			Description: "High-intensity statin therapy post-ACS",
			Priority:    "urgent",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Atorvastatin 80mg PO at bedtime OR Rosuvastatin 40mg PO at bedtime. Start regardless of baseline LDL. (Class I, Level A)",
			DrugCode:    "atorvastatin-80mg",
			RxNormCode:  "617314",
		},
		// ACE Inhibitor
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Cardiac",
			Name:        "ACE Inhibitor or ARB",
			Description: "RAAS blockade for ventricular remodeling prevention",
			Priority:    "urgent",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Start Lisinopril 2.5-5mg PO daily OR Losartan 25mg PO daily if ACEi intolerant. Initiate within 24h if LVEF <40% or anterior MI. Hold if SBP <100 or Cr >3.0. (Class I, Level A for EF<40%)",
			DrugCode:    "lisinopril-5mg",
			RxNormCode:  "314076",
		},
		// Labs
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Labs",
			Name:        "Serial Troponins",
			Description: "Serial troponin to assess peak and trend",
			Priority:    "urgent",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Troponin T or I q6h x3 to establish peak. Peak troponin correlates with infarct size.",
			LOINCCode:   "10839-9",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Labs",
			Name:        "CBC, BMP, Lipid Panel",
			Description: "Baseline laboratory assessment",
			Priority:    "urgent",
			Status:      "active",
			IsRequired:  true,
			Instructions: "CBC, comprehensive metabolic panel, fasting lipid panel in AM. BNP/NT-proBNP if HF suspected.",
			LOINCCode:   "24323-8",
		},
		// Imaging
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Imaging",
			Name:        "Transthoracic Echocardiogram",
			Description: "Assess LV function and wall motion abnormalities",
			Priority:    "urgent",
			Status:      "active",
			IsRequired:  true,
			Instructions: "TTE within 48 hours of admission. Assess LVEF, regional wall motion, RV function, valvular pathology, mechanical complications (VSD, free wall rupture, papillary muscle rupture).",
		},
		// Nursing/Education
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Education",
			Name:        "Cardiac Rehab Referral",
			Description: "Refer to outpatient cardiac rehabilitation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Place cardiac rehab referral. Discuss importance of completing Phase II cardiac rehab (Class I recommendation). Exercise improves outcomes post-MI.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Education",
			Name:        "Discharge Education",
			Description: "STEMI discharge education and warning signs",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Educate patient/family: DAPT importance (no missed doses), warning signs (chest pain, SOB, palpitations), activity restrictions, dietary modifications (low sodium, heart-healthy diet), smoking cessation, follow-up appointments.",
		},
	}
}

// GetCardiacAdmissionOrderSets returns all cardiac admission order sets
func GetCardiacAdmissionOrderSets() []*models.OrderSetTemplate {
	return []*models.OrderSetTemplate{
		GetCHFExacerbationOrderSet(),
		GetAcuteMIOrderSet(),
		GetChestPainOrderSet(),
		GetSTEMIAdmissionOrderSet(),
	}
}
