// Package ordersets provides clinical order set templates for KB-12
// admission_ordersets_neuro.go - Neurological admission order sets
// Templates: Acute Stroke (tPA/Thrombectomy), Syncope Workup
package ordersets

import (
	"time"

	"github.com/google/uuid"
	"kb-12-ordersets-careplans/internal/models"
)

// GetAcuteStrokeOrderSet returns the Acute Stroke admission order set
// Based on AHA/ASA Stroke Guidelines 2019
func GetAcuteStrokeOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-NEURO-001",
		TemplateID:  "OS-NEURO-001",
		Name:        "Acute Ischemic Stroke Admission",
		Description: "Time-critical order set for acute ischemic stroke with tPA and thrombectomy pathways",
		Version:     "2.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "Neurological",
		Specialty:   "Neurology",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Stroke/Neurology Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level A",
		References: []string{
			"AHA/ASA Acute Ischemic Stroke Guidelines 2019",
			"AHA Get With The Guidelines - Stroke",
			"DAWN and DEFUSE-3 Extended Window Criteria",
		},
		ICDCodes: []string{"I63.9", "I63.50", "I63.30", "I63.40", "G45.9"},
		SNOMEDCodes: []string{"422504002", "230690007", "195189003"},
		Orders: getAcuteStrokeOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:             "TC-STROKE-001",
				Name:           "Door-to-CT",
				Description:    "Non-contrast CT within 25 minutes of arrival",
				Type:           "deadline",
				ReferenceEvent: "arrival",
				OffsetMinutes:  25,
				Priority:       "critical",
				Rationale:      "AHA Target: Door-to-imaging <25 minutes",
				Regulatory:     true,
			},
			{
				ID:             "TC-STROKE-002",
				Name:           "Door-to-Needle (tPA)",
				Description:    "tPA administration within 60 minutes of arrival",
				Type:           "deadline",
				ReferenceEvent: "arrival",
				OffsetMinutes:  60,
				Priority:       "critical",
				Rationale:      "AHA Target: Door-to-needle <60 minutes. Every 15 min delay reduces benefit.",
				Regulatory:     true,
			},
			{
				ID:             "TC-STROKE-003",
				Name:           "Door-to-Groin (Thrombectomy)",
				Description:    "Arterial puncture within 90 minutes for LVO",
				Type:           "deadline",
				ReferenceEvent: "arrival",
				OffsetMinutes:  90,
				Priority:       "critical",
				Rationale:      "AHA Target: Door-to-puncture <90 minutes for thrombectomy-eligible patients",
				Regulatory:     true,
			},
			{
				ID:             "TC-STROKE-004",
				Name:           "tPA Window",
				Description:    "tPA eligibility within 4.5 hours of symptom onset",
				Type:           "deadline",
				ReferenceEvent: "symptom_onset",
				OffsetMinutes:  270,
				Priority:       "critical",
				Rationale:      "Standard tPA window is 4.5 hours from last known well",
			},
			{
				ID:             "TC-STROKE-005",
				Name:           "Extended Thrombectomy Window",
				Description:    "Thrombectomy eligibility up to 24 hours with imaging selection",
				Type:           "deadline",
				ReferenceEvent: "symptom_onset",
				OffsetMinutes:  1440,
				Priority:       "high",
				Rationale:      "DAWN/DEFUSE-3: Extended window with perfusion imaging selection",
			},
			{
				ID:             "TC-STROKE-006",
				Name:           "Dysphagia Screen",
				Description:    "Swallow screen before any oral intake",
				Type:           "prerequisite",
				ReferenceEvent: "first_oral_intake",
				OffsetMinutes:  0,
				Priority:       "high",
				Rationale:      "Prevents aspiration pneumonia",
			},
		},
		Metadata: map[string]interface{}{
			"stroke_code":         true,
			"time_critical":       true,
			"quality_metrics":     []string{"door_to_ct", "door_to_needle", "door_to_groin", "dysphagia_screen"},
			"lvo_criteria":        []string{"NIHSS>=6", "proximal_occlusion", "good_ASPECTS"},
			"tpa_contraindications": []string{"active_bleeding", "recent_surgery", "coagulopathy", "recent_stroke"},
		},
	}
}

func getAcuteStrokeOrders() []models.Order {
	return []models.Order{
		// === IMMEDIATE CRITICAL ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "alert",
			Category:    "Critical",
			Name:        "STROKE CODE - Activate Stroke Team",
			Description: "Immediate stroke team activation",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Document: Last known well time, NIHSS score, symptom onset. Activate stroke pager/team.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Admit to Stroke Unit/Neuro ICU",
			Description: "Specialized stroke care unit",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Neuro ICU if: tPA administered, thrombectomy, NIHSS ≥15, hemorrhagic transformation risk",
		},
		// === IMMEDIATE IMAGING ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "STAT Non-Contrast CT Head",
			Description: "Rule out hemorrhage - within 25 minutes",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "70450",
			Instructions: "MUST be completed within 25 minutes of arrival. Rule out hemorrhage before thrombolytics.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "CT Angiography Head and Neck",
			Description: "Evaluate for large vessel occlusion",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "70496",
			Instructions: "Concurrent with non-contrast CT. Identify LVO for thrombectomy candidacy.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "CT Perfusion",
			Description: "Perfusion imaging for extended window patients",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "70498",
			Instructions: "Required if: >6h from LKW, wake-up stroke, or unclear onset time. Guides extended window treatment.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "time_from_LKW", Operator: ">", Value: "6", Action: "CT Perfusion required"},
				{Type: "indication", Parameter: "wake_up_stroke", Operator: "=", Value: "true", Action: "CT Perfusion required"},
			},
		},
		// === THROMBOLYTIC THERAPY ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Thrombolytic",
			Name:        "Alteplase (tPA)",
			Description: "IV thrombolysis for acute ischemic stroke",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "8410",
			Dose:        "0.9",
			DoseUnit:    "mg/kg",
			Route:       "IV",
			Frequency:   "10% bolus, 90% infusion over 60 min",
			Instructions: "Max dose 90mg. 10% as IV bolus, remainder as infusion over 60 min. Door-to-needle <60 min goal.",
			WeightBased: true,
			MaxDose:     "90 mg",
			Conditions: []models.OrderCondition{
				{Type: "prerequisite", Parameter: "CT_hemorrhage", Operator: "=", Value: "negative", Action: "Must rule out hemorrhage"},
				{Type: "prerequisite", Parameter: "time_from_LKW", Operator: "<=", Value: "4.5h", Action: "Within standard window"},
				{Type: "contraindication", Parameter: "BP", Operator: ">", Value: "185/110", Action: "Lower BP before tPA"},
				{Type: "contraindication", Parameter: "INR", Operator: ">", Value: "1.7", Action: "Contraindicated"},
				{Type: "contraindication", Parameter: "platelets", Operator: "<", Value: "100000", Action: "Contraindicated"},
				{Type: "contraindication", Parameter: "glucose", Operator: "<", Value: "50", Action: "Correct hypoglycemia first"},
				{Type: "contraindication", Parameter: "recent_surgery", Operator: "=", Value: "14_days", Action: "Relative contraindication"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Thrombolytic",
			Name:        "Tenecteplase (Alternative)",
			Description: "Alternative thrombolytic with single bolus dosing",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "238709",
			Dose:        "0.25",
			DoseUnit:    "mg/kg",
			Route:       "IV",
			Frequency:   "single bolus",
			Instructions: "Max 25mg. Single IV bolus. May be preferred for transfer to thrombectomy center.",
			WeightBased: true,
			MaxDose:     "25 mg",
		},
		// === BLOOD PRESSURE MANAGEMENT ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antihypertensive",
			Name:        "Labetalol IV",
			Description: "BP control before/during thrombolysis",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "6135",
			Dose:        "10-20",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "q10-20min PRN",
			MaxDose:     "300 mg",
			Instructions: "Pre-tPA: Lower BP to <185/110. Post-tPA: Maintain <180/105 for 24h.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "BP", Operator: ">", Value: "185/110", Action: "Pre-tPA BP control"},
				{Type: "indication", Parameter: "post_tPA_BP", Operator: ">", Value: "180/105", Action: "Post-tPA BP control"},
				{Type: "contraindication", Parameter: "bradycardia", Operator: "=", Value: "true", Action: "Use nicardipine instead"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antihypertensive",
			Name:        "Nicardipine Infusion",
			Description: "Continuous BP control",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "7443",
			Dose:        "5-15",
			DoseUnit:    "mg/hr",
			Route:       "IV continuous",
			Frequency:   "titrate to BP goal",
			Instructions: "Start 5 mg/hr, titrate by 2.5 mg/hr q5-15min to goal. Alternative to labetalol.",
		},
		// === ANTITHROMBOTIC THERAPY ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antiplatelet",
			Name:        "Aspirin",
			Description: "Antiplatelet therapy after tPA or if tPA not given",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "1191",
			Dose:        "325",
			DoseUnit:    "mg",
			Route:       "PO/PR",
			Frequency:   "daily",
			Instructions: "If tPA given: Start 24h after tPA, after repeat CT shows no hemorrhage. If no tPA: Give within 48h.",
			Conditions: []models.OrderCondition{
				{Type: "timing", Parameter: "tPA_given", Operator: "=", Value: "true", Action: "Start 24h after tPA, after CT"},
				{Type: "timing", Parameter: "tPA_given", Operator: "=", Value: "false", Action: "Give within 48h of stroke"},
				{Type: "contraindication", Parameter: "aspirin_allergy", Operator: "=", Value: "true", Action: "Use clopidogrel"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antiplatelet",
			Name:        "Clopidogrel",
			Description: "Dual antiplatelet for minor stroke/TIA",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "32968",
			Dose:        "300",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "loading dose, then 75mg daily",
			Instructions: "DAPT (ASA+clopidogrel) for 21 days for minor stroke/TIA (NIHSS ≤3). Then ASA monotherapy.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "NIHSS", Operator: "<=", Value: "3", Action: "Consider DAPT x 21 days"},
				{Type: "indication", Parameter: "high_risk_TIA", Operator: "=", Value: "true", Action: "Consider DAPT x 21 days"},
			},
		},
		// === DVT PROPHYLAXIS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Enoxaparin DVT Prophylaxis",
			Description: "DVT prevention",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "67108",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "SubQ",
			Frequency:   "daily",
			Instructions: "Start when hemorrhage excluded. If immobile, start within 24h if no tPA, 24-48h post-tPA.",
			Conditions: []models.OrderCondition{
				{Type: "timing", Parameter: "tPA_given", Operator: "=", Value: "true", Action: "Start 24-48h post-tPA after CT"},
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "30", Action: "Reduce to 30mg daily"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Prevention",
			Name:        "Sequential Compression Devices",
			Description: "Mechanical DVT prophylaxis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Apply immediately if immobile. Use in addition to pharmacologic prophylaxis when safe.",
		},
		// === SUPPORTIVE MEDICATIONS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Statin",
			Name:        "Atorvastatin",
			Description: "High-intensity statin therapy",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "83367",
			Dose:        "80",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "daily",
			Instructions: "High-intensity statin for all ischemic stroke/TIA patients.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Neuroprotective",
			Name:        "Acetaminophen PRN",
			Description: "Fever control",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "161",
			Dose:        "650",
			DoseUnit:    "mg",
			Route:       "PO/PR",
			Frequency:   "q4-6h PRN",
			Instructions: "For temperature >37.5°C. Fever associated with worse outcomes.",
		},
		// === LABORATORY ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "STAT Glucose",
			Description: "Rule out hypoglycemia mimicking stroke",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "2345-7",
			Instructions: "ONLY lab required before tPA. Correct if <50 or >400.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count",
			Description: "Platelet count for tPA eligibility",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
			Instructions: "Do NOT delay tPA for results unless known coagulopathy. Plt <100K is contraindication.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Coagulation",
			Name:        "PT/INR, PTT",
			Description: "Coagulation studies",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "5902-2",
			Instructions: "Do NOT delay tPA for results unless on anticoagulation. INR >1.7 is contraindication.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Basic Metabolic Panel",
			Description: "Electrolytes and renal function",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "51990-0",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Cardiac",
			Name:        "Troponin",
			Description: "Evaluate for concurrent MI",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "10839-9",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Lipid",
			Name:        "Lipid Panel",
			Description: "Baseline lipids for secondary prevention",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "24331-1",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Metabolic",
			Name:        "Hemoglobin A1c",
			Description: "Screen for diabetes",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "4548-4",
		},
		// === ADDITIONAL IMAGING ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Cardiology",
			Name:        "Transthoracic Echocardiogram",
			Description: "Evaluate for cardioembolic source",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "93306",
			Instructions: "Evaluate for thrombus, PFO, valvular disease. Consider TEE if high suspicion for cardioembolic.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Cardiology",
			Name:        "MRI Brain with DWI",
			Description: "Confirm infarct, evaluate extent",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "70553",
			Instructions: "When stable. DWI most sensitive for acute infarct. Helps with prognosis and management.",
		},
		// === NURSING ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Neuro Checks - NIHSS",
			Description: "Serial neurological assessments",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q15min x 2h, q30min x 6h, q1h x 16h, then q4h",
			Instructions: "NIHSS score at baseline and with any change. Alert MD for NIHSS increase ≥2 points.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Blood Pressure Monitoring",
			Description: "Frequent BP monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q15min x 2h, q30min x 6h, then q1h x 16h",
			Instructions: "Post-tPA: Maintain BP <180/105 for 24h. Call MD if BP exceeds threshold.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Assessment",
			Name:        "Dysphagia Screen",
			Description: "Swallow assessment before oral intake",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "NPO until passed bedside swallow screen. Formal SLP evaluation if screen fails.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Positioning",
			Name:        "Head of Bed Positioning",
			Description: "Optimize cerebral perfusion",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "HOB flat for LVO/hypoperfusion. HOB 30° if aspiration risk or elevated ICP signs.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Continuous Cardiac Telemetry",
			Description: "Arrhythmia monitoring",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Minimum 24h monitoring for AFib detection. Consider extended monitoring for cryptogenic stroke.",
		},
		// === CONSULTS ===
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Neurology/Stroke Consult",
			Description: "Stroke specialist evaluation",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Neurointerventional (if LVO)",
			Description: "Thrombectomy evaluation",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Activate for LVO identified on CTA. Door-to-groin goal <90 min.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Ancillary",
			Name:        "Speech-Language Pathology",
			Description: "Formal swallow and speech evaluation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Ancillary",
			Name:        "Physical and Occupational Therapy",
			Description: "Early mobilization and rehab assessment",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
		},
	}
}

// GetSyncopeOrderSet returns the Syncope Workup admission order set
func GetSyncopeOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-NEURO-002",
		TemplateID:  "OS-NEURO-002",
		Name:        "Syncope Workup Admission",
		Description: "Comprehensive order set for syncope evaluation and risk stratification",
		Version:     "2.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "Neurological",
		Specialty:   "Cardiology/Neurology",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Cardiology/Neurology Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level B",
		References: []string{
			"2017 ACC/AHA/HRS Syncope Guidelines",
			"ESC Syncope Guidelines 2018",
			"San Francisco Syncope Rule",
		},
		ICDCodes: []string{"R55", "R42", "I45.9", "G90.9"},
		SNOMEDCodes: []string{"271594007", "272030005"},
		Orders: getSyncopeOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:             "TC-SYNC-001",
				Name:           "ECG",
				Description:    "12-lead ECG within 30 minutes",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  30,
				Priority:       "high",
				Rationale:      "Rule out arrhythmia as cause",
			},
			{
				ID:             "TC-SYNC-002",
				Name:           "Orthostatic Vitals",
				Description:    "Orthostatic blood pressure within 2 hours",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  120,
				Priority:       "high",
				Rationale:      "Common cause of syncope, easily treatable",
			},
		},
		Metadata: map[string]interface{}{
			"risk_scores":         []string{"San Francisco Syncope Rule", "OESIL", "EGSYS", "Canadian Syncope Risk Score"},
			"high_risk_features":  []string{"abnormal_ECG", "CHF_history", "low_hematocrit", "shortness_breath", "SBP<90"},
			"etiology_categories": []string{"cardiac", "neurally_mediated", "orthostatic", "unknown"},
		},
	}
}

func getSyncopeOrders() []models.Order {
	return []models.Order{
		// === ADMISSION ===
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Admit to Observation/Telemetry",
			Description: "Cardiac monitoring for syncope evaluation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Telemetry for arrhythmia detection. Consider ICU if hemodynamically unstable.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "diet",
			Category:    "Nursing",
			Name:        "Regular Diet",
			Description: "Advance as tolerated",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Adequate hydration encouraged. Salt supplementation if orthostatic hypotension.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "activity",
			Category:    "Nursing",
			Name:        "Fall Precautions",
			Description: "Prevent recurrent falls",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Bed alarm, non-skid socks, call light within reach. Assist with ambulation.",
		},
		// === DIAGNOSTIC STUDIES ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Cardiology",
			Name:        "12-Lead ECG",
			Description: "Evaluate for arrhythmia, conduction abnormalities",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "93000",
			Instructions: "Look for: prolonged QT, Brugada, WPW, heart block, ischemia, prior MI",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Continuous Telemetry",
			Description: "Cardiac rhythm monitoring",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Minimum 24-48h continuous monitoring. Capture and save any symptomatic events.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Cardiology",
			Name:        "Transthoracic Echocardiogram",
			Description: "Evaluate for structural heart disease",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "93306",
			Instructions: "Evaluate: LV function, valvular disease, HOCM, RV strain (PE)",
		},
		// === ORTHOSTATIC EVALUATION ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Assessment",
			Name:        "Orthostatic Vital Signs",
			Description: "Supine and standing BP/HR",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Supine x 5min, then immediate standing, 1min, 3min. Positive if: SBP drop ≥20, DBP drop ≥10, or symptoms.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "procedure",
			Category:    "Cardiology",
			Name:        "Tilt Table Test",
			Description: "Provocative testing for vasovagal syncope",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consider if: recurrent syncope, unclear etiology, suspected neurally-mediated mechanism.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "recurrent_syncope", Operator: "=", Value: "true", Action: "Consider tilt table"},
				{Type: "indication", Parameter: "etiology", Operator: "=", Value: "unclear", Action: "Consider tilt table"},
			},
		},
		// === LABORATORY ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Basic Metabolic Panel",
			Description: "Electrolytes, renal function, glucose",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "51990-0",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count",
			Description: "Evaluate for anemia, infection",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
			Instructions: "Anemia is San Francisco Syncope Rule criterion (Hct <30%)",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Cardiac",
			Name:        "Troponin",
			Description: "Evaluate for cardiac ischemia",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "10839-9",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Cardiac",
			Name:        "BNP",
			Description: "Evaluate for heart failure",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "30934-4",
			Instructions: "CHF history is San Francisco Syncope Rule criterion",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Endocrine",
			Name:        "TSH",
			Description: "Thyroid function",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "3016-3",
		},
		// === MEDICATIONS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Enoxaparin DVT Prophylaxis",
			Description: "DVT prevention if immobile",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "67108",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "SubQ",
			Frequency:   "daily",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Supportive",
			Name:        "IV Fluids",
			Description: "Fluid resuscitation if dehydrated",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "313002",
			Dose:        "1000",
			DoseUnit:    "mL",
			Route:       "IV",
			Frequency:   "bolus, then 100-125 mL/hr",
			Instructions: "If orthostatic hypotension or dehydration contributing",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Orthostatic",
			Name:        "Fludrocortisone",
			Description: "For orthostatic hypotension",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "4206",
			Dose:        "0.1",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "daily",
			Instructions: "Consider if confirmed orthostatic hypotension. Volume expansion via sodium retention.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "orthostatic_hypotension", Operator: "=", Value: "confirmed", Action: "Consider fludrocortisone"},
				{Type: "contraindication", Parameter: "CHF", Operator: "=", Value: "true", Action: "Use with caution"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Orthostatic",
			Name:        "Midodrine",
			Description: "Alpha-agonist for orthostatic hypotension",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "6960",
			Dose:        "2.5-10",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "TID",
			Instructions: "Give upon awakening, midday, and afternoon. Avoid evening dose (supine HTN).",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "orthostatic_hypotension", Operator: "=", Value: "confirmed", Action: "Consider midodrine"},
				{Type: "contraindication", Parameter: "supine_hypertension", Operator: "=", Value: "true", Action: "Avoid"},
			},
		},
		// === ADDITIONAL IMAGING ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "CT Head without Contrast",
			Description: "If head trauma or neurological symptoms",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "70450",
			Instructions: "Order if: witnessed head trauma, focal neurological findings, prolonged confusion",
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Vascular",
			Name:        "Carotid Duplex Ultrasound",
			Description: "Carotid stenosis evaluation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "93880",
			Instructions: "Consider if focal neurological symptoms or carotid bruit",
		},
		// === NURSING ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Vital Signs",
			Description: "Regular vital sign monitoring",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q4h",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Assessment",
			Name:        "Syncope History Documentation",
			Description: "Detailed syncope event documentation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Document: prodrome, position, triggers, duration, post-event symptoms, witnesses",
		},
		// === CONSULTS ===
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Cardiology Consult",
			Description: "Cardiac syncope evaluation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consult if: abnormal ECG, structural heart disease, suspected arrhythmia, family history of sudden death",
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Electrophysiology Consult",
			Description: "EP study or device evaluation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consider for: recurrent unexplained syncope, suspected arrhythmia, ILR placement consideration",
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Neurology Consult",
			Description: "Neurological syncope evaluation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consult if: seizure suspected, autonomic dysfunction, unexplained neurological symptoms",
		},
	}
}

// GetNeuroAdmissionOrderSets returns all neurological admission order sets
func GetNeuroAdmissionOrderSets() []*models.OrderSetTemplate {
	return []*models.OrderSetTemplate{
		GetAcuteStrokeOrderSet(),
		GetSyncopeOrderSet(),
	}
}
