// Package ordersets provides clinical order set templates for KB-12
// admission_ordersets_gi.go - Gastrointestinal admission order sets
// Templates: GI Bleeding (Upper/Lower), Acute Pancreatitis
package ordersets

import (
	"time"

	"github.com/google/uuid"
	"kb-12-ordersets-careplans/internal/models"
)

// GetGIBleedingOrderSet returns the GI Bleeding admission order set
// Based on ACG/ASGE Guidelines
func GetGIBleedingOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-GI-001",
		TemplateID:  "OS-GI-001",
		Name:        "GI Bleeding Admission",
		Description: "Order set for acute upper and lower GI bleeding management",
		Version:     "2.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "Gastrointestinal",
		Specialty:   "Gastroenterology",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Gastroenterology Clinical Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level A",
		References: []string{
			"ACG Upper GI Bleeding Guidelines 2021",
			"ACG Lower GI Bleeding Guidelines 2016",
			"Glasgow-Blatchford Score",
			"Rockall Score",
		},
		ICDCodes: []string{"K92.2", "K92.0", "K92.1", "K25.4", "K26.4", "K27.4"},
		SNOMEDCodes: []string{"74474003", "37372002", "12063002"},
		Orders: getGIBleedingOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:             "TC-GIB-001",
				Name:           "Type and Screen",
				Description:    "Blood bank sample within 30 minutes",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  30,
				Priority:       "critical",
				Rationale:      "Ensure blood products available if needed",
			},
			{
				ID:             "TC-GIB-002",
				Name:           "IV Access and Resuscitation",
				Description:    "Two large-bore IVs and fluid resuscitation within 30 minutes",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  30,
				Priority:       "critical",
				Rationale:      "Rapid volume resuscitation critical for hemodynamic stability",
			},
			{
				ID:             "TC-GIB-003",
				Name:           "EGD for High-Risk UGIB",
				Description:    "Upper endoscopy within 24 hours for high-risk UGIB",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  1440,
				Priority:       "high",
				Rationale:      "ACG recommends EGD within 24h. Urgent (<12h) if hemodynamic instability.",
			},
			{
				ID:             "TC-GIB-004",
				Name:           "PPI Initiation",
				Description:    "IV PPI bolus within 1 hour for suspected UGIB",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  60,
				Priority:       "high",
				Rationale:      "PPI reduces rebleeding and need for intervention",
			},
		},
		Metadata: map[string]interface{}{
			"risk_scores":          []string{"Glasgow-Blatchford", "Rockall", "AIMS65"},
			"transfusion_threshold": "Hgb <7 g/dL (restrictive) or <9 g/dL if symptomatic/CAD",
			"high_risk_features":   []string{"hemodynamic_instability", "active_hematemesis", "hematochezia", "anticoagulation"},
		},
	}
}

func getGIBleedingOrders() []models.Order {
	return []models.Order{
		// === ADMISSION ===
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Admit to Medicine/GI Service",
			Description: "Level of care based on severity",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "ICU if: hemodynamic instability, massive hemorrhage, ongoing transfusion requirement",
		},
		{
			ID:          uuid.New().String(),
			Type:        "diet",
			Category:    "Nursing",
			Name:        "NPO",
			Description: "Nothing by mouth pending endoscopy",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "NPO until post-endoscopy and stable. Clear liquids after if successful hemostasis.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Access",
			Name:        "Two Large-Bore IV Access",
			Description: "18G or larger peripheral IVs",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Place 2 large-bore (18G or larger) peripheral IVs. Central line if unable.",
		},
		// === RESUSCITATION ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "IV Fluids",
			Name:        "Lactated Ringer's Bolus",
			Description: "Volume resuscitation",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "313965",
			Dose:        "1000-2000",
			DoseUnit:    "mL",
			Route:       "IV",
			Frequency:   "bolus, repeat PRN",
			Instructions: "Rapid infusion for hemodynamic instability. Reassess after each liter.",
		},
		// === BLOOD PRODUCTS ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Blood Bank",
			Name:        "Type and Screen",
			Description: "Blood bank sample for potential transfusion",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "882-1",
			Instructions: "MUST be drawn immediately. Type and crossmatch if transfusion anticipated.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Blood Products",
			Name:        "Packed Red Blood Cells",
			Description: "RBC transfusion per protocol",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "1000",
			Dose:        "1-2",
			DoseUnit:    "units",
			Route:       "IV",
			Frequency:   "PRN",
			Instructions: "Transfuse for Hgb <7 (restrictive) or <9 if CAD/symptomatic. Massive transfusion protocol if needed.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "hemoglobin", Operator: "<", Value: "7", Action: "Transfuse pRBC"},
				{Type: "indication", Parameter: "hemoglobin", Operator: "<", Value: "9", Action: "Transfuse if CAD or symptomatic"},
				{Type: "indication", Parameter: "active_bleeding", Operator: "=", Value: "massive", Action: "Activate MTP"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Blood Products",
			Name:        "Fresh Frozen Plasma",
			Description: "FFP for coagulopathy",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "1001",
			Dose:        "2-4",
			DoseUnit:    "units",
			Route:       "IV",
			Frequency:   "PRN",
			Instructions: "Give if INR >1.5-2.0 with active bleeding. Part of MTP if activated.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "INR", Operator: ">", Value: "1.5", Action: "Consider FFP"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Blood Products",
			Name:        "Platelets",
			Description: "Platelet transfusion for thrombocytopenia",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "1002",
			Dose:        "1",
			DoseUnit:    "unit (apheresis)",
			Route:       "IV",
			Frequency:   "PRN",
			Instructions: "Transfuse if platelets <50K with active bleeding. <100K before invasive procedure.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "platelets", Operator: "<", Value: "50000", Action: "Transfuse with active bleeding"},
			},
		},
		// === ACID SUPPRESSION ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "PPI",
			Name:        "Pantoprazole IV Bolus + Infusion",
			Description: "High-dose IV PPI for UGIB",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "40790",
			Dose:        "80",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "bolus, then 8 mg/hr infusion",
			Instructions: "80mg IV bolus, then 8 mg/hr continuous infusion until endoscopy. High-risk stigmata: continue 72h.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "PPI",
			Name:        "Pantoprazole IV BID",
			Description: "Intermittent IV PPI alternative",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "40790",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "BID",
			Instructions: "Alternative to continuous infusion for low-risk stigmata post-endoscopy.",
		},
		// === VARICEAL BLEEDING ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Vasoactive",
			Name:        "Octreotide",
			Description: "Splanchnic vasoconstrictor for variceal bleeding",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "7646",
			Dose:        "50",
			DoseUnit:    "mcg",
			Route:       "IV",
			Frequency:   "bolus, then 50 mcg/hr x 3-5 days",
			Instructions: "If variceal bleed suspected (cirrhosis, known varices). Start before endoscopy.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "cirrhosis", Operator: "=", Value: "true", Action: "Start octreotide"},
				{Type: "indication", Parameter: "variceal_bleed_suspected", Operator: "=", Value: "true", Action: "Start octreotide"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Ceftriaxone",
			Description: "Antibiotic prophylaxis for variceal bleeding",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "2193",
			Dose:        "1",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "daily x 7 days",
			Instructions: "Required for cirrhotic patients with GI bleed. Reduces SBP and mortality.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "cirrhosis", Operator: "=", Value: "true", Action: "Start prophylactic antibiotics"},
			},
		},
		// === ANTICOAGULATION REVERSAL ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Reversal",
			Name:        "Vitamin K",
			Description: "Warfarin reversal",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "11256",
			Dose:        "10",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "once",
			Instructions: "For warfarin-associated bleeding. Give IV slowly. Onset 6-12h, so give with FFP/PCC for immediate reversal.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "warfarin", Operator: "=", Value: "true", Action: "Give vitamin K"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Reversal",
			Name:        "4-Factor PCC (Kcentra)",
			Description: "Rapid warfarin reversal",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "1313092",
			Dose:        "25-50",
			DoseUnit:    "units/kg",
			Route:       "IV",
			Frequency:   "once",
			Instructions: "For life-threatening warfarin-associated bleed. Dose based on INR and weight.",
			WeightBased: true,
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "warfarin_bleed", Operator: "=", Value: "life_threatening", Action: "Give PCC"},
				{Type: "dosing", Parameter: "INR", Operator: "between", Value: "2-4", Action: "25 units/kg"},
				{Type: "dosing", Parameter: "INR", Operator: ">", Value: "4", Action: "50 units/kg"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Reversal",
			Name:        "Idarucizumab",
			Description: "Dabigatran reversal agent",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "1735342",
			Dose:        "5",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "once",
			Instructions: "For life-threatening bleed on dabigatran. Give as 2 x 2.5g boluses.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "dabigatran", Operator: "=", Value: "true", Action: "Give idarucizumab"},
			},
		},
		// === LABORATORY ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count - Serial",
			Description: "Monitor hemoglobin",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
			Frequency:   "q6h x 24h, then q12h",
			Instructions: "Serial Hgb to monitor for ongoing blood loss. May lag true blood loss.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Basic Metabolic Panel",
			Description: "Electrolytes and renal function",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "51990-0",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Coagulation",
			Name:        "PT/INR, PTT",
			Description: "Coagulation studies",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "5902-2",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hepatic",
			Name:        "Hepatic Function Panel",
			Description: "Liver function if cirrhosis suspected",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "24325-3",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Lactate",
			Description: "Marker of hypoperfusion",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "2524-7",
			Instructions: "If hemodynamic instability or shock",
		},
		// === NURSING ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Vital Signs",
			Description: "Frequent monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q15min x 4, then q1h until stable",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Strict Intake and Output",
			Description: "Fluid balance monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Record all blood products, IV fluids, urine output",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Assessment",
			Name:        "Stool Description",
			Description: "Characterize bleeding",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Document: melena, hematochezia, bright red blood, maroon. Notify MD of changes.",
		},
		// === CONSULTS ===
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "GI Consult - Urgent",
			Description: "Endoscopy evaluation",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Urgent GI consult for endoscopy planning. EGD within 24h, earlier if unstable.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Interventional Radiology",
			Description: "Angiography for refractory bleeding",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consider if: endoscopy fails, bleeding source not identified, hemodynamically unstable",
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Surgery Consult",
			Description: "Surgical evaluation for refractory bleeding",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consider for: massive hemorrhage, failed endoscopic/IR therapy, perforation",
		},
	}
}

// GetPancreatitisOrderSet returns the Acute Pancreatitis admission order set
// Based on ACG Guidelines
func GetPancreatitisOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-GI-002",
		TemplateID:  "OS-GI-002",
		Name:        "Acute Pancreatitis Admission",
		Description: "Order set for acute pancreatitis management per ACG guidelines",
		Version:     "2.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "Gastrointestinal",
		Specialty:   "Gastroenterology",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Gastroenterology Clinical Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level B",
		References: []string{
			"ACG Acute Pancreatitis Guidelines 2013",
			"AGA Pancreatitis Guidelines 2018",
			"Revised Atlanta Classification",
			"BISAP Score",
		},
		ICDCodes: []string{"K85.9", "K85.1", "K85.2", "K85.3", "K85.0"},
		SNOMEDCodes: []string{"197456007", "235494005"},
		Orders: getPancreatitisOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:             "TC-PANC-001",
				Name:           "Aggressive IV Fluids",
				Description:    "Goal-directed fluid resuscitation in first 12-24 hours",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  720,
				Priority:       "critical",
				Rationale:      "Early aggressive hydration improves outcomes",
			},
			{
				ID:             "TC-PANC-002",
				Name:           "Etiology Workup",
				Description:    "Determine etiology within 24 hours",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  1440,
				Priority:       "high",
				Rationale:      "Gallstone pancreatitis requires ERCP consideration",
			},
			{
				ID:             "TC-PANC-003",
				Name:           "ERCP for Cholangitis",
				Description:    "Urgent ERCP within 24h if cholangitis",
				Type:           "deadline",
				ReferenceEvent: "cholangitis_identified",
				OffsetMinutes:  1440,
				Priority:       "critical",
				Rationale:      "Biliary obstruction with infection requires urgent decompression",
			},
		},
		Metadata: map[string]interface{}{
			"severity_scores":   []string{"BISAP", "Ranson", "APACHE-II", "Revised Atlanta"},
			"etiology":          []string{"gallstones", "alcohol", "hypertriglyceridemia", "post-ERCP", "medications", "idiopathic"},
			"complications":     []string{"necrosis", "pseudocyst", "WOPN", "splenic_vein_thrombosis", "ARDS", "AKI"},
			"nutrition_timing":  "Early enteral feeding (within 24-48h) if tolerated",
		},
	}
}

func getPancreatitisOrders() []models.Order {
	return []models.Order{
		// === ADMISSION ===
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Admit to Medicine/GI Service",
			Description: "Level of care based on severity",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "ICU if: organ failure (SIRS, hypotension, AKI, ARDS), severe per Atlanta criteria",
		},
		{
			ID:          uuid.New().String(),
			Type:        "diet",
			Category:    "Nursing",
			Name:        "NPO Initially",
			Description: "Bowel rest initially",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "NPO initially. Advance to low-fat solid diet as tolerated (not clear liquids first). Early feeding encouraged.",
		},
		// === AGGRESSIVE IV FLUIDS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "IV Fluids",
			Name:        "Lactated Ringer's - Aggressive Hydration",
			Description: "Goal-directed fluid resuscitation",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "313965",
			Dose:        "250-500",
			DoseUnit:    "mL/hr",
			Route:       "IV",
			Frequency:   "continuous",
			Instructions: "Goal: UOP 0.5 mL/kg/hr, HR <120, MAP >65. LR preferred over NS. Bolus 1L then 250-500 mL/hr x 12-24h.",
			Conditions: []models.OrderCondition{
				{Type: "goal", Parameter: "UOP", Operator: "target", Value: "0.5 mL/kg/hr", Action: "Adjust rate"},
				{Type: "warning", Parameter: "CHF", Operator: "=", Value: "severe", Action: "Lower rate, reassess frequently"},
				{Type: "warning", Parameter: "CKD", Operator: "=", Value: "severe", Action: "Lower rate, reassess frequently"},
			},
		},
		// === PAIN CONTROL ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Analgesic",
			Name:        "Hydromorphone",
			Description: "Pain control for pancreatitis",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "3423",
			Dose:        "0.5-2",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "q3-4h PRN",
			Instructions: "Pain control is essential. No evidence morphine worsens outcomes. PCA may be needed.",
			Conditions: []models.OrderCondition{
				{Type: "alternative", Parameter: "renal_impairment", Operator: "=", Value: "severe", Action: "Reduce dose/frequency"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Analgesic",
			Name:        "Morphine (Alternative)",
			Description: "Alternative opioid for pain control",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "7052",
			Dose:        "2-4",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "q3-4h PRN",
			Instructions: "Traditional concern about sphincter spasm not supported by evidence.",
		},
		// === ANTIEMETICS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antiemetic",
			Name:        "Ondansetron",
			Description: "Nausea and vomiting control",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "26225",
			Dose:        "4",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "q6-8h PRN",
		},
		// === DVT PROPHYLAXIS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Enoxaparin",
			Description: "DVT prophylaxis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "67108",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "SubQ",
			Frequency:   "daily",
			Conditions: []models.OrderCondition{
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "30", Action: "Reduce to 30mg daily"},
			},
		},
		// === LABORATORY ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Lipase",
			Description: "Confirm diagnosis (if not already done)",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "3040-3",
			Instructions: "Lipase >3x ULN diagnostic. No need to trend for clinical management.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Comprehensive Metabolic Panel",
			Description: "Electrolytes, renal function, liver function",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "24323-8",
			Frequency:   "q12h x 48h, then daily",
			Instructions: "Monitor for AKI, electrolyte abnormalities. ALT >3x ULN suggests gallstone etiology.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count",
			Description: "WBC, hematocrit for severity assessment",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
			Frequency:   "daily",
			Instructions: "Hct drop, WBC elevation part of severity assessment.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Triglycerides",
			Description: "Evaluate for hypertriglyceridemic pancreatitis",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "2571-8",
			Instructions: "TG >1000 suggests hypertriglyceridemic pancreatitis. >500 may contribute.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Calcium",
			Description: "Part of Ranson criteria",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "17861-6",
			Instructions: "Hypocalcemia is marker of severity (Ranson criteria).",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Lactate",
			Description: "Marker of hypoperfusion",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "2524-7",
			Instructions: "Elevated lactate suggests inadequate resuscitation.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "BUN",
			Description: "Severity marker and BISAP component",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "3094-0",
			Instructions: "BUN >25 is BISAP criterion. Rising BUN suggests inadequate resuscitation.",
		},
		// === IMAGING ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "Abdominal Ultrasound",
			Description: "Evaluate for gallstones",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "76700",
			Instructions: "MUST be done within 24h to evaluate for gallstone etiology. Guides ERCP decision.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "CT Abdomen/Pelvis with Contrast",
			Description: "Assess for necrosis and complications",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "74177",
			Instructions: "NOT needed for diagnosis. Obtain at 72-96h if no improvement to assess for necrosis. Or if diagnostic uncertainty.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "clinical_improvement", Operator: "=", Value: "false_at_72h", Action: "Order CT"},
				{Type: "indication", Parameter: "suspected_complication", Operator: "=", Value: "true", Action: "Order CT"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "MRCP",
			Description: "Biliary evaluation if US inconclusive",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "74181",
			Instructions: "If gallstone pancreatitis suspected but US inconclusive. Evaluate for CBD stones.",
		},
		// === NURSING ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Vital Signs with Fluid Balance",
			Description: "Frequent monitoring during resuscitation",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q4h (q1h if unstable)",
			Instructions: "Monitor HR, BP, UOP. Goal UOP >0.5 mL/kg/hr.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Strict Intake and Output",
			Description: "Fluid balance monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Foley catheter recommended for accurate UOP monitoring in severe pancreatitis.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Assessment",
			Name:        "Abdominal Exam",
			Description: "Serial abdominal assessments",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q4h",
			Instructions: "Monitor for worsening tenderness, distension, peritoneal signs.",
		},
		// === NUTRITION ===
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Ancillary",
			Name:        "Nutrition Consult",
			Description: "Nutritional assessment",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Early enteral feeding (within 24-48h) if tolerated. Low-fat solid diet, not clear liquids.",
		},
		// === CONSULTS ===
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "GI Consult",
			Description: "GI evaluation for pancreatitis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Urgent if: gallstone pancreatitis with cholangitis (ERCP <24h), severe/necrotizing pancreatitis",
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Surgery Consult",
			Description: "Surgical evaluation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consult for: cholecystectomy planning in gallstone pancreatitis, infected necrosis (debridement)",
		},
	}
}

// GetGIAdmissionOrderSets returns all GI admission order sets
func GetGIAdmissionOrderSets() []*models.OrderSetTemplate {
	return []*models.OrderSetTemplate{
		GetGIBleedingOrderSet(),
		GetPancreatitisOrderSet(),
	}
}
