// Package ordersets provides clinical order set templates for KB-12
// admission_ordersets_respiratory.go - Respiratory admission order sets
// Templates: Community-Acquired Pneumonia, COPD Exacerbation
package ordersets

import (
	"time"

	"github.com/google/uuid"
	"kb-12-ordersets-careplans/internal/models"
)

// GetPneumoniaOrderSet returns the Community-Acquired Pneumonia admission order set
// Based on IDSA/ATS CAP Guidelines 2019
func GetPneumoniaOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-RESP-001",
		TemplateID:  "OS-RESP-001",
		Name:        "Community-Acquired Pneumonia Admission",
		Description: "Comprehensive order set for CAP admission per IDSA/ATS guidelines",
		Version:     "2.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "Respiratory",
		Specialty:   "Pulmonology",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Infectious Disease/Pulmonology Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level A",
		References: []string{
			"IDSA/ATS CAP Guidelines 2019",
			"Pneumonia Severity Index (PSI)",
			"CURB-65 Score",
		},
		ICDCodes: []string{"J18.9", "J18.1", "J15.9", "J13", "J14"},
		SNOMEDCodes: []string{"385093006", "233604007", "278516003"},
		Orders: getPneumoniaOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:          "TC-CAP-001",
				Name:        "Antibiotic Administration",
				Description: "First antibiotic dose within 4 hours of admission",
				Type:        "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes: 240,
				Priority:    "high",
				Rationale:   "CMS Core Measure - Early antibiotics improve outcomes",
				Regulatory:  true,
			},
			{
				ID:          "TC-CAP-002",
				Name:        "Blood Cultures Before Antibiotics",
				Description: "Blood cultures before first antibiotic dose",
				Type:        "prerequisite",
				ReferenceEvent: "antibiotic_first_dose",
				OffsetMinutes: -30,
				Priority:    "high",
				Rationale:   "Cultures should precede antibiotics for accurate diagnosis",
			},
			{
				ID:          "TC-CAP-003",
				Name:        "Severity Assessment",
				Description: "PSI/CURB-65 calculation within 2 hours",
				Type:        "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes: 120,
				Priority:    "high",
				Rationale:   "Guides level of care and antibiotic selection",
			},
		},
		Metadata: map[string]interface{}{
			"severity_scores":     []string{"PSI", "CURB-65"},
			"antibiotic_stewardship": true,
			"expected_los":        "3-5 days",
			"discharge_criteria":  []string{"afebrile 48h", "hemodynamically stable", "able to take PO", "oxygen requirement stable"},
		},
	}
}

func getPneumoniaOrders() []models.Order {
	return []models.Order{
		// === ADMISSION ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Admit to Medicine/Pulmonology Service",
			Description: "Floor vs ICU based on severity assessment",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "PSI Class IV-V or CURB-65 ≥3: Consider ICU admission",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Isolation",
			Name:        "Respiratory Isolation",
			Description: "Droplet precautions if influenza suspected",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Droplet precautions until influenza ruled out during flu season",
		},
		// === MEDICATIONS - ANTIBIOTICS (Non-ICU, No Risk Factors) ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Ceftriaxone",
			Description: "Beta-lactam for CAP - standard non-ICU regimen",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "2193",
			Dose:        "1",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "daily",
			Duration:    "5-7 days",
			Instructions: "Standard regimen for non-ICU CAP. Give within 4 hours of admission.",
			Conditions: []models.OrderCondition{
				{Type: "severity", Parameter: "ICU_admission", Operator: "=", Value: "false", Action: "Standard dose"},
				{Type: "alternative", Parameter: "penicillin_allergy", Operator: "=", Value: "severe", Action: "Use respiratory FQ"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Azithromycin",
			Description: "Macrolide for atypical coverage",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "18631",
			Dose:        "500",
			DoseUnit:    "mg",
			Route:       "IV/PO",
			Frequency:   "daily",
			Duration:    "5 days",
			Instructions: "Add to beta-lactam for atypical coverage. Can give PO if able.",
			Conditions: []models.OrderCondition{
				{Type: "warning", Parameter: "QTc", Operator: ">", Value: "500", Action: "Consider doxycycline alternative"},
				{Type: "alternative", Parameter: "macrolide_allergy", Operator: "=", Value: "true", Action: "Use doxycycline"},
			},
		},
		// === ALTERNATIVE ANTIBIOTICS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Levofloxacin (Alternative)",
			Description: "Respiratory fluoroquinolone monotherapy",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "82122",
			Dose:        "750",
			DoseUnit:    "mg",
			Route:       "IV/PO",
			Frequency:   "daily",
			Duration:    "5 days",
			Instructions: "Alternative for beta-lactam allergy. Monotherapy adequate for non-ICU.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "penicillin_allergy", Operator: "=", Value: "severe", Action: "Use as monotherapy"},
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "50", Action: "750mg q48h"},
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "20", Action: "500mg q48h"},
				{Type: "warning", Parameter: "tendon_history", Operator: "=", Value: "true", Action: "Avoid if possible"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Doxycycline (Alternative)",
			Description: "Alternative to macrolide for atypical coverage",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "3640",
			Dose:        "100",
			DoseUnit:    "mg",
			Route:       "PO/IV",
			Frequency:   "BID",
			Duration:    "5 days",
			Instructions: "Alternative to azithromycin for atypical coverage",
		},
		// === ICU ANTIBIOTICS (Severe CAP) ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Ceftriaxone (ICU Dose)",
			Description: "Beta-lactam for severe CAP requiring ICU",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "2193",
			Dose:        "2",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "daily",
			Duration:    "7 days",
			Instructions: "Higher dose for severe CAP. Combine with azithromycin.",
			Conditions: []models.OrderCondition{
				{Type: "severity", Parameter: "ICU_admission", Operator: "=", Value: "true", Action: "Use 2g dosing"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Vancomycin (MRSA Coverage)",
			Description: "Add if MRSA risk factors or necrotizing pneumonia",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "11124",
			Dose:        "15-20",
			DoseUnit:    "mg/kg",
			Route:       "IV",
			Frequency:   "q8-12h",
			Duration:    "7-14 days",
			Instructions: "Add if MRSA risk: recent influenza, necrotizing, empyema, cavitation",
			WeightBased: true,
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "MRSA_risk", Operator: "=", Value: "true", Action: "Add vancomycin"},
				{Type: "monitoring", Parameter: "vancomycin_trough", Operator: "target", Value: "15-20", Action: "Check trough before 4th dose"},
				{Type: "renal_adjustment", Parameter: "eGFR", Operator: "<", Value: "50", Action: "Pharmacy dose adjustment"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Piperacillin-Tazobactam (Pseudomonas Coverage)",
			Description: "Add if Pseudomonas risk factors",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "8339",
			Dose:        "4.5",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "q6h",
			Duration:    "7-14 days",
			Instructions: "Add if Pseudomonas risk: structural lung disease, recent hospitalization/antibiotics",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "pseudomonas_risk", Operator: "=", Value: "true", Action: "Add pip-tazo"},
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "40", Action: "3.375g q6h"},
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "20", Action: "2.25g q6h"},
			},
		},
		// === SUPPORTIVE MEDICATIONS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Supportive",
			Name:        "Acetaminophen",
			Description: "Antipyretic for fever",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "161",
			Dose:        "650-1000",
			DoseUnit:    "mg",
			Route:       "PO/IV",
			Frequency:   "q6h PRN",
			MaxDose:     "3g/day",
			Instructions: "For fever >38.5C or discomfort",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Supportive",
			Name:        "Albuterol Nebulizer",
			Description: "Bronchodilator for wheezing/bronchospasm",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "435",
			Dose:        "2.5",
			DoseUnit:    "mg",
			Route:       "Inhalation",
			Frequency:   "q4h PRN",
			Instructions: "For wheezing or bronchospasm",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Enoxaparin",
			Description: "DVT prophylaxis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "67108",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "SubQ",
			Frequency:   "daily",
			Instructions: "DVT prophylaxis unless contraindicated",
			Conditions: []models.OrderCondition{
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "30", Action: "Reduce to 30mg daily"},
				{Type: "contraindication", Parameter: "active_bleeding", Operator: "=", Value: "true", Action: "Use mechanical prophylaxis"},
			},
		},
		// === LABORATORY ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Microbiology",
			Name:        "Blood Cultures x 2",
			Description: "Aerobic and anaerobic cultures from 2 sites",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "600-7",
			Instructions: "Obtain BEFORE first antibiotic dose. 2 sets from different sites.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Microbiology",
			Name:        "Sputum Culture and Gram Stain",
			Description: "Respiratory culture if productive cough",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "624-7",
			Instructions: "If able to produce quality sputum specimen",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Microbiology",
			Name:        "Legionella Urinary Antigen",
			Description: "Legionella testing for severe CAP",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "32781-7",
			Instructions: "Recommend for severe CAP, ICU admission, or epidemiologic risk",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Microbiology",
			Name:        "Pneumococcal Urinary Antigen",
			Description: "S. pneumoniae testing for severe CAP",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "43879-5",
			Instructions: "Recommend for severe CAP or ICU admission",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Microbiology",
			Name:        "Respiratory Viral Panel",
			Description: "Influenza and respiratory virus testing",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "92142-9",
			Instructions: "Test for influenza and COVID-19. Other viruses as clinically indicated.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Basic Metabolic Panel",
			Description: "Electrolytes and renal function",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "51990-0",
			Frequency:   "admission, daily while critical",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count with Differential",
			Description: "WBC, hemoglobin, platelets",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Procalcitonin",
			Description: "Biomarker for bacterial infection",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "33959-8",
			Instructions: "Can guide antibiotic duration. Consider serial levels.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Lactate",
			Description: "Marker of tissue hypoperfusion",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "2524-7",
			Instructions: "If sepsis suspected or severe CAP",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Blood Gas",
			Name:        "Arterial Blood Gas",
			Description: "Assess oxygenation and acid-base status",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "24336-0",
			Instructions: "If hypoxemic, severe CAP, or ICU admission",
		},
		// === IMAGING ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "Chest X-Ray PA and Lateral",
			Description: "Confirm pneumonia and assess extent",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "71046",
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "CT Chest without Contrast",
			Description: "If complicated pneumonia or poor response",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "71250",
			Instructions: "Consider if empyema, abscess suspected, or failure to improve at 48-72h",
		},
		// === RESPIRATORY SUPPORT ===
		{
			ID:          uuid.New().String(),
			Type:        "respiratory",
			Category:    "Oxygen",
			Name:        "Supplemental Oxygen",
			Description: "Maintain SpO2 ≥92% (≥88% if COPD)",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Titrate to SpO2 92-96%. Lower target 88-92% if CO2 retainer.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "respiratory",
			Category:    "Advanced",
			Name:        "High-Flow Nasal Cannula",
			Description: "HFNC for moderate-severe hypoxemia",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consider if O2 >6L NC required or work of breathing increased",
		},
		// === NURSING ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Continuous Pulse Oximetry",
			Description: "Continuous SpO2 monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Vital Signs",
			Description: "Frequent vital sign monitoring",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q4h (q1h if unstable)",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Assessment",
			Name:        "CURB-65 Score Calculation",
			Description: "Severity assessment score",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Confusion, Urea>7, RR≥30, BP<90/60, Age≥65. Score 0-5.",
		},
		// === CONSULTS ===
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Infectious Disease Consult",
			Description: "ID consultation for complex cases",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consider for severe CAP, unusual pathogens, failure to improve",
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Ancillary",
			Name:        "Respiratory Therapy",
			Description: "RT for airway management and treatments",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
		},
	}
}

// GetCOPDExacerbationOrderSet returns the COPD Exacerbation admission order set
// Based on GOLD Guidelines 2023
func GetCOPDExacerbationOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-RESP-002",
		TemplateID:  "OS-RESP-002",
		Name:        "COPD Exacerbation Admission",
		Description: "Comprehensive order set for acute COPD exacerbation admission",
		Version:     "2.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "Respiratory",
		Specialty:   "Pulmonology",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Pulmonology Clinical Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level A",
		References: []string{
			"GOLD Guidelines 2023",
			"NICE COPD Guidelines",
			"ATS/ERS COPD Exacerbation Statement",
		},
		ICDCodes: []string{"J44.1", "J44.0", "J44.9"},
		SNOMEDCodes: []string{"195951007", "313296004"},
		Orders: getCOPDOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:          "TC-COPD-001",
				Name:        "Bronchodilator Administration",
				Description: "First bronchodilator within 30 minutes",
				Type:        "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes: 30,
				Priority:    "high",
				Rationale:   "Immediate bronchodilation is first-line therapy",
			},
			{
				ID:          "TC-COPD-002",
				Name:        "Steroid Administration",
				Description: "Systemic corticosteroid within 4 hours",
				Type:        "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes: 240,
				Priority:    "high",
				Rationale:   "Early steroids reduce treatment failure and LOS",
			},
			{
				ID:          "TC-COPD-003",
				Name:        "ABG Assessment",
				Description: "Arterial blood gas if hypercapnia suspected",
				Type:        "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes: 60,
				Priority:    "high",
				Rationale:   "Assess for acute respiratory failure",
			},
		},
		Metadata: map[string]interface{}{
			"exacerbation_severity": []string{"mild", "moderate", "severe"},
			"niv_criteria":          []string{"pH<7.35", "PaCO2>45", "RR>25"},
			"expected_los":          "4-6 days",
		},
	}
}

func getCOPDOrders() []models.Order {
	return []models.Order{
		// === ADMISSION ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Admit to Medicine/Pulmonology Service",
			Description: "Floor vs ICU based on severity",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "ICU if: pH <7.25, severe respiratory distress, altered mental status, hemodynamic instability",
		},
		{
			ID:          uuid.New().String(),
			Type:        "diet",
			Category:    "Nursing",
			Name:        "Regular Diet",
			Description: "Advance as tolerated",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Small frequent meals to reduce dyspnea",
		},
		// === MEDICATIONS - BRONCHODILATORS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Bronchodilator",
			Name:        "Albuterol-Ipratropium Nebulizer",
			Description: "Combined short-acting bronchodilator",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "142177",
			Dose:        "3/0.5",
			DoseUnit:    "mg",
			Route:       "Inhalation",
			Frequency:   "q4h scheduled, q2h PRN",
			Instructions: "DuoNeb (albuterol 2.5mg + ipratropium 0.5mg). May give q20min x3 for severe exacerbation.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Bronchodilator",
			Name:        "Albuterol MDI with Spacer",
			Description: "Alternative to nebulizer if able to use MDI",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "435",
			Dose:        "4-8",
			DoseUnit:    "puffs",
			Route:       "Inhalation",
			Frequency:   "q4h scheduled",
			Instructions: "Alternative to nebulizer. Use spacer device.",
		},
		// === MEDICATIONS - CORTICOSTEROIDS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Corticosteroid",
			Name:        "Prednisone",
			Description: "Systemic corticosteroid for COPD exacerbation",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "8640",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "daily",
			Duration:    "5 days",
			Instructions: "GOLD recommends 5-day course. No taper needed for ≤14 days.",
			Conditions: []models.OrderCondition{
				{Type: "warning", Parameter: "diabetes", Operator: "=", Value: "true", Action: "Monitor glucose closely"},
				{Type: "alternative", Parameter: "unable_to_take_PO", Operator: "=", Value: "true", Action: "Use methylprednisolone IV"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Corticosteroid",
			Name:        "Methylprednisolone (IV Alternative)",
			Description: "IV corticosteroid if unable to take PO",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "6902",
			Dose:        "40-125",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "daily",
			Duration:    "5 days",
			Instructions: "Use if unable to take PO. Transition to PO prednisone when able.",
		},
		// === MEDICATIONS - ANTIBIOTICS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Azithromycin",
			Description: "Antibiotic for COPD exacerbation with purulent sputum",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "18631",
			Dose:        "500",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "daily x 1, then 250mg daily x 4",
			Duration:    "5 days",
			Instructions: "Indicated if: increased dyspnea + increased sputum volume + purulent sputum (2/3 Anthonisen criteria)",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "purulent_sputum", Operator: "=", Value: "true", Action: "Antibiotic indicated"},
				{Type: "indication", Parameter: "mechanical_ventilation", Operator: "=", Value: "true", Action: "Antibiotic indicated"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Amoxicillin-Clavulanate (Alternative)",
			Description: "Alternative antibiotic for COPD exacerbation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "18631",
			Dose:        "875/125",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "BID",
			Duration:    "5-7 days",
			Instructions: "Alternative if macrolide contraindicated or recent macrolide use",
		},
		// === SUPPORTIVE MEDICATIONS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Electrolyte",
			Name:        "Magnesium Sulfate",
			Description: "Bronchodilator for severe exacerbation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "6585",
			Dose:        "2",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "once",
			Instructions: "Consider for severe exacerbation with poor bronchodilator response",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Enoxaparin",
			Description: "DVT prophylaxis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "67108",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "SubQ",
			Frequency:   "daily",
			Instructions: "DVT prophylaxis for hospitalized COPD patients",
			Conditions: []models.OrderCondition{
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "30", Action: "Reduce to 30mg daily"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Supportive",
			Name:        "Guaifenesin",
			Description: "Expectorant for mucus clearance",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "5032",
			Dose:        "400",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "q4h PRN",
			Instructions: "May help with thick secretions",
		},
		// === LABORATORY ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Blood Gas",
			Name:        "Arterial Blood Gas",
			Description: "Assess respiratory status and acid-base",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "24336-0",
			Instructions: "Baseline ABG. Repeat if clinical deterioration or NIV initiation.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Basic Metabolic Panel",
			Description: "Electrolytes and renal function",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "51990-0",
			Frequency:   "daily",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count",
			Description: "Evaluate for infection, polycythemia",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Cardiac",
			Name:        "BNP",
			Description: "Evaluate for heart failure component",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "30934-4",
			Instructions: "If heart failure suspected as contributing factor",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Microbiology",
			Name:        "Sputum Culture",
			Description: "Culture if purulent sputum",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "624-7",
			Instructions: "If antibiotic indicated and quality specimen obtainable",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Microbiology",
			Name:        "Respiratory Viral Panel",
			Description: "Test for influenza and other viruses",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "92142-9",
		},
		// === IMAGING ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "Chest X-Ray PA and Lateral",
			Description: "Evaluate for pneumonia, pneumothorax",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "71046",
			Instructions: "Rule out pneumonia, pneumothorax, other pathology",
		},
		// === RESPIRATORY SUPPORT ===
		{
			ID:          uuid.New().String(),
			Type:        "respiratory",
			Category:    "Oxygen",
			Name:        "Controlled Oxygen Therapy",
			Description: "Target SpO2 88-92%",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "GOLD recommends SpO2 88-92% to avoid hypercapnia. Venturi mask preferred for precise FiO2.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "respiratory",
			Category:    "NIV",
			Name:        "BiPAP (Non-Invasive Ventilation)",
			Description: "NIV for acute respiratory acidosis",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Initiate if: pH <7.35 with PaCO2 >45, severe dyspnea with accessory muscle use, RR >25. Start IPAP 10-12, EPAP 4-5.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "pH", Operator: "<", Value: "7.35", Action: "Strong indication for NIV"},
				{Type: "indication", Parameter: "PaCO2", Operator: ">", Value: "45", Action: "Hypercapnic respiratory failure"},
				{Type: "contraindication", Parameter: "decreased_consciousness", Operator: "=", Value: "severe", Action: "Consider intubation instead"},
			},
		},
		// === NURSING ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Continuous Pulse Oximetry",
			Description: "Continuous SpO2 monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Target SpO2 88-92%",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Vital Signs with Respiratory Assessment",
			Description: "Frequent monitoring",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q4h (q1-2h if unstable or on NIV)",
			Instructions: "Include respiratory rate, work of breathing, mental status",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Activity",
			Name:        "Activity as Tolerated",
			Description: "Mobilize when stable",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Early mobilization improves outcomes. Chair rest progressing to ambulation.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Intervention",
			Name:        "Incentive Spirometry",
			Description: "Encourage deep breathing",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "10 breaths q1h while awake",
		},
		// === CONSULTS ===
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Pulmonology Consult",
			Description: "Pulmonary specialist evaluation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consider for: severe exacerbation, NIV requirement, frequent exacerbations, GOLD D",
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Ancillary",
			Name:        "Respiratory Therapy",
			Description: "RT for treatments and education",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Ancillary",
			Name:        "Smoking Cessation Counseling",
			Description: "Tobacco cessation support",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Offer cessation counseling and pharmacotherapy to all current smokers",
		},
	}
}

// GetRespiratoryAdmissionOrderSets returns all respiratory admission order sets
func GetRespiratoryAdmissionOrderSets() []*models.OrderSetTemplate {
	return []*models.OrderSetTemplate{
		GetPneumoniaOrderSet(),
		GetCOPDExacerbationOrderSet(),
	}
}
