// Package ordersets provides clinical order set templates for KB-12
// admission_ordersets_metabolic.go - Metabolic admission order sets
// Templates: Sepsis/Septic Shock (SEP-1 Bundle), Diabetic Ketoacidosis (DKA)
package ordersets

import (
	"time"

	"github.com/google/uuid"
	"kb-12-ordersets-careplans/internal/models"
)

// GetSepsisOrderSet returns the Sepsis/Septic Shock admission order set
// Based on Surviving Sepsis Campaign 2021 and CMS SEP-1 Core Measure
func GetSepsisOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-META-001",
		TemplateID:  "OS-META-001",
		Name:        "Sepsis/Septic Shock Admission - SEP-1 Bundle",
		Description: "Time-critical order set for sepsis and septic shock per SSC guidelines and CMS SEP-1",
		Version:     "3.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "Critical Care",
		Specialty:   "Critical Care Medicine",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Critical Care/Sepsis Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level A",
		References: []string{
			"Surviving Sepsis Campaign 2021",
			"CMS SEP-1 Core Measure Specifications",
			"SCCM/ESICM Sepsis-3 Definitions",
		},
		ICDCodes: []string{"A41.9", "R65.20", "R65.21", "A40.9"},
		SNOMEDCodes: []string{"91302008", "76571007", "434821000124109"},
		Orders: getSepsisOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:             "TC-SEP-001",
				Name:           "Initial Lactate",
				Description:    "Lactate level within 3 hours of sepsis presentation",
				Type:           "deadline",
				ReferenceEvent: "sepsis_presentation",
				OffsetMinutes:  180,
				Priority:       "critical",
				Rationale:      "CMS SEP-1 3-hour bundle requirement",
				Regulatory:     true,
			},
			{
				ID:             "TC-SEP-002",
				Name:           "Blood Cultures Before Antibiotics",
				Description:    "Blood cultures before antibiotics within 3 hours",
				Type:           "deadline",
				ReferenceEvent: "sepsis_presentation",
				OffsetMinutes:  180,
				Priority:       "critical",
				Rationale:      "CMS SEP-1 3-hour bundle requirement",
				Regulatory:     true,
			},
			{
				ID:             "TC-SEP-003",
				Name:           "Broad-Spectrum Antibiotics",
				Description:    "Antibiotics within 1 hour of sepsis recognition (3h for sepsis, 1h for shock)",
				Type:           "deadline",
				ReferenceEvent: "sepsis_presentation",
				OffsetMinutes:  60,
				Priority:       "critical",
				Rationale:      "SSC 2021: Antibiotics within 1 hour for sepsis/septic shock",
				Regulatory:     true,
			},
			{
				ID:             "TC-SEP-004",
				Name:           "Fluid Resuscitation",
				Description:    "30 mL/kg crystalloid within 3 hours if hypotensive or lactate ≥4",
				Type:           "deadline",
				ReferenceEvent: "sepsis_presentation",
				OffsetMinutes:  180,
				Priority:       "critical",
				Rationale:      "CMS SEP-1 3-hour bundle for hypotension or lactate ≥4",
				Regulatory:     true,
			},
			{
				ID:             "TC-SEP-005",
				Name:           "Repeat Lactate",
				Description:    "Repeat lactate within 6 hours if initial lactate >2",
				Type:           "deadline",
				ReferenceEvent: "initial_lactate",
				OffsetMinutes:  360,
				Priority:       "high",
				Rationale:      "CMS SEP-1 6-hour bundle requirement if initial lactate elevated",
				Regulatory:     true,
			},
			{
				ID:             "TC-SEP-006",
				Name:           "Vasopressors for Refractory Hypotension",
				Description:    "Start vasopressors if MAP <65 after fluid resuscitation within 6 hours",
				Type:           "deadline",
				ReferenceEvent: "fluid_completion",
				OffsetMinutes:  180,
				Priority:       "critical",
				Rationale:      "CMS SEP-1 6-hour bundle requirement",
				Regulatory:     true,
			},
			{
				ID:             "TC-SEP-007",
				Name:           "Reassessment Documentation",
				Description:    "Focused exam or bedside hemodynamic assessment within 6 hours if persistent hypotension",
				Type:           "deadline",
				ReferenceEvent: "sepsis_presentation",
				OffsetMinutes:  360,
				Priority:       "high",
				Rationale:      "CMS SEP-1 6-hour bundle requirement",
				Regulatory:     true,
			},
		},
		Metadata: map[string]interface{}{
			"bundle_components":   []string{"lactate", "cultures", "antibiotics", "fluids", "vasopressors", "reassessment"},
			"quality_metrics":     []string{"SEP-1", "door_to_antibiotic", "lactate_clearance"},
			"mortality_benefit":   "Each hour delay in antibiotics increases mortality ~7.6%",
			"escalation_triggers": []string{"lactate_rising", "vasopressor_requirement", "ARDS", "DIC"},
		},
	}
}

func getSepsisOrders() []models.Order {
	return []models.Order{
		// === IMMEDIATE CRITICAL ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "alert",
			Category:    "Critical",
			Name:        "SEPSIS ALERT - Activate Bundle",
			Description: "Sepsis identified - initiate SEP-1 bundle immediately",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Document time of sepsis recognition. Start 3-hour bundle clock NOW.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Admit to ICU/Step-Down",
			Description: "Critical care level admission for sepsis/septic shock",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "ICU if: septic shock, vasopressor requirement, mechanical ventilation, multi-organ dysfunction",
		},
		// === SEP-1 3-HOUR BUNDLE ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Critical",
			Name:        "STAT Lactate",
			Description: "Initial lactate level - SEP-1 requirement",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "2524-7",
			Instructions: "MUST be drawn within 3 hours of sepsis presentation. Document time.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Microbiology",
			Name:        "Blood Cultures x 2 - STAT",
			Description: "Aerobic and anaerobic cultures from 2 sites",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "600-7",
			Instructions: "Obtain BEFORE antibiotics. 2 sets from different sites. Do NOT delay antibiotics >45min for cultures.",
		},
		// === ANTIBIOTICS - EMPIRIC BROAD SPECTRUM ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Vancomycin",
			Description: "Gram-positive coverage including MRSA",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "11124",
			Dose:        "25-30",
			DoseUnit:    "mg/kg",
			Route:       "IV",
			Frequency:   "loading dose, then per pharmacy",
			Instructions: "Loading dose 25-30 mg/kg (max 3g). Pharmacy to dose maintenance. Target trough 15-20 for severe infection.",
			WeightBased: true,
			MaxDose:     "3000 mg",
			Conditions: []models.OrderCondition{
				{Type: "monitoring", Parameter: "vanc_trough", Operator: "target", Value: "15-20", Action: "Check trough before 4th dose"},
				{Type: "renal_adjustment", Parameter: "eGFR", Operator: "<", Value: "30", Action: "Pharmacy dosing required"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Piperacillin-Tazobactam",
			Description: "Broad-spectrum gram-negative and anaerobic coverage",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "8339",
			Dose:        "4.5",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "q6h",
			Instructions: "Give within 1 hour of sepsis recognition. Extended infusion (4h) preferred.",
			Conditions: []models.OrderCondition{
				{Type: "alternative", Parameter: "penicillin_allergy", Operator: "=", Value: "severe", Action: "Use meropenem + aztreonam"},
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "40", Action: "3.375g q6h"},
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "20", Action: "2.25g q6h"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Meropenem (Alternative)",
			Description: "Carbapenem for severe penicillin allergy or resistant organisms",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "29561",
			Dose:        "1",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "q8h",
			Instructions: "Use if severe beta-lactam allergy with negative penicillin skin test, or ESBL suspected.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "ESBL_risk", Operator: "=", Value: "true", Action: "Prefer meropenem"},
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "50", Action: "1g q12h"},
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "25", Action: "500mg q12h"},
			},
		},
		// === FLUID RESUSCITATION ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "IV Fluids",
			Name:        "Lactated Ringer's - Rapid Bolus",
			Description: "30 mL/kg crystalloid bolus for hypotension/high lactate",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "313965",
			Dose:        "30",
			DoseUnit:    "mL/kg",
			Route:       "IV",
			Frequency:   "bolus over 30-60 min",
			Instructions: "Required if: SBP <90, MAP <65, or lactate ≥4. Complete within 3 hours. Reassess after each 500-1000mL.",
			WeightBased: true,
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "SBP", Operator: "<", Value: "90", Action: "Bolus required"},
				{Type: "indication", Parameter: "MAP", Operator: "<", Value: "65", Action: "Bolus required"},
				{Type: "indication", Parameter: "lactate", Operator: ">=", Value: "4", Action: "Bolus required"},
				{Type: "warning", Parameter: "CHF", Operator: "=", Value: "severe", Action: "Give in smaller aliquots, reassess frequently"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "IV Fluids",
			Name:        "Normal Saline (Alternative)",
			Description: "Alternative crystalloid if LR unavailable",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "313002",
			Dose:        "30",
			DoseUnit:    "mL/kg",
			Route:       "IV",
			Frequency:   "bolus",
			Instructions: "Use if LR unavailable. Avoid large volumes due to hyperchloremic acidosis risk.",
			WeightBased: true,
		},
		// === SEP-1 6-HOUR BUNDLE ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Critical",
			Name:        "Repeat Lactate",
			Description: "Repeat lactate if initial >2 mmol/L",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "2524-7",
			Frequency:   "q6h until normalized",
			Instructions: "Required within 6 hours if initial lactate >2. Goal: lactate clearance >10%/hour.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "initial_lactate", Operator: ">", Value: "2", Action: "Repeat lactate required"},
			},
		},
		// === VASOPRESSORS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Vasopressor",
			Name:        "Norepinephrine",
			Description: "First-line vasopressor for septic shock",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "7512",
			Dose:        "0.1-0.5",
			DoseUnit:    "mcg/kg/min",
			Route:       "IV continuous",
			Frequency:   "continuous infusion",
			Instructions: "Start if MAP <65 despite 30mL/kg fluids. First-line per SSC. Titrate to MAP ≥65. Central line preferred.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "MAP", Operator: "<", Value: "65", Action: "Start norepinephrine"},
				{Type: "indication", Parameter: "fluid_complete", Operator: "=", Value: "true", Action: "Start after adequate fluid resuscitation"},
				{Type: "warning", Parameter: "peripheral_access", Operator: "=", Value: "true", Action: "Central line preferred, but do not delay"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Vasopressor",
			Name:        "Vasopressin",
			Description: "Second-line vasopressor to reduce norepinephrine dose",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "11149",
			Dose:        "0.03",
			DoseUnit:    "units/min",
			Route:       "IV continuous",
			Frequency:   "continuous infusion",
			Instructions: "Add when norepinephrine >0.25-0.5 mcg/kg/min. Fixed dose 0.03 units/min. Do not titrate.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "norepinephrine_dose", Operator: ">", Value: "0.25", Action: "Add vasopressin"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Vasopressor",
			Name:        "Epinephrine (Alternative)",
			Description: "Alternative or adjunct vasopressor",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "3992",
			Dose:        "0.01-0.1",
			DoseUnit:    "mcg/kg/min",
			Route:       "IV continuous",
			Frequency:   "continuous infusion",
			Instructions: "Add to norepinephrine if refractory shock. Increases cardiac output.",
		},
		// === CORTICOSTEROIDS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Corticosteroid",
			Name:        "Hydrocortisone",
			Description: "Stress-dose steroids for refractory septic shock",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "5492",
			Dose:        "200",
			DoseUnit:    "mg/day",
			Route:       "IV",
			Frequency:   "50mg q6h or 200mg continuous",
			Instructions: "Initiate if vasopressor-dependent despite adequate fluid resuscitation. Continue until vasopressors weaned.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "vasopressor_requirement", Operator: "=", Value: "ongoing", Action: "Consider hydrocortisone"},
				{Type: "indication", Parameter: "norepinephrine_dose", Operator: ">", Value: "0.25", Action: "Strong indication"},
			},
		},
		// === SOURCE CONTROL ===
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Surgical",
			Name:        "Source Control Evaluation",
			Description: "Surgical/IR evaluation for source control",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Evaluate for drainable abscess, obstructed viscus, infected hardware. Source control within 6-12h if feasible.",
		},
		// === ADDITIONAL LABORATORIES ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Comprehensive Metabolic Panel",
			Description: "Electrolytes, renal function, hepatic function",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "24323-8",
			Frequency:   "q6h x 24h, then daily",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count with Differential",
			Description: "WBC, hemoglobin, platelets",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
			Frequency:   "q6h x 24h, then daily",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Coagulation",
			Name:        "Coagulation Panel",
			Description: "PT/INR, PTT, fibrinogen",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "5902-2",
			Instructions: "Monitor for DIC (falling fibrinogen, rising D-dimer, thrombocytopenia)",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Inflammatory",
			Name:        "Procalcitonin",
			Description: "Biomarker for bacterial infection",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "33959-8",
			Instructions: "Can guide antibiotic de-escalation. Serial levels q48-72h.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Blood Gas",
			Name:        "Arterial Blood Gas",
			Description: "Acid-base status and oxygenation",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "24336-0",
			Frequency:   "q6h initially",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Cardiac",
			Name:        "Troponin",
			Description: "Evaluate for sepsis-related myocardial injury",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "10839-9",
		},
		// === IMAGING ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "Chest X-Ray Portable",
			Description: "Evaluate for pulmonary source",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "71045",
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "CT Abdomen/Pelvis with Contrast",
			Description: "Abdominal source evaluation if indicated",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "74177",
			Instructions: "If abdominal source suspected. Evaluate for abscess, perforation, obstruction.",
		},
		// === NURSING/MONITORING ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Continuous Vital Signs and MAP",
			Description: "Continuous hemodynamic monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Arterial line preferred. Target MAP ≥65 mmHg. Document q15min during resuscitation.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Strict Intake and Output",
			Description: "Fluid balance monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Hourly I/O. Foley catheter for accurate UOP monitoring. Target UOP >0.5 mL/kg/hr.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Protocol",
			Name:        "SEP-1 Bundle Documentation",
			Description: "Document all bundle elements and timing",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Document: Time zero, lactate time, culture time, antibiotic time, fluid completion time, reassessment time.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Assessment",
			Name:        "Focused Reassessment",
			Description: "Volume status and tissue perfusion reassessment",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Required within 6h if persistent hypotension or lactate ≥4. Document: volume status, tissue perfusion, cardiopulmonary exam.",
		},
	}
}

// GetDKAOrderSet returns the Diabetic Ketoacidosis admission order set
// Based on ADA DKA Guidelines 2022
func GetDKAOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-META-002",
		TemplateID:  "OS-META-002",
		Name:        "Diabetic Ketoacidosis (DKA) Admission",
		Description: "Comprehensive order set for DKA management per ADA guidelines",
		Version:     "2.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "Metabolic",
		Specialty:   "Endocrinology",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Endocrinology/Critical Care Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level A",
		References: []string{
			"ADA Standards of Medical Care in Diabetes 2023",
			"ADA DKA Treatment Algorithm",
			"Kitabchi AE et al. Diabetes Care 2009",
		},
		ICDCodes: []string{"E10.10", "E11.10", "E13.10", "E10.11", "E11.11"},
		SNOMEDCodes: []string{"420422005", "421847006", "421920002"},
		Orders: getDKAOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:             "TC-DKA-001",
				Name:           "Initial IV Fluids",
				Description:    "IV normal saline bolus within 30 minutes",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  30,
				Priority:       "critical",
				Rationale:      "Rapid fluid resuscitation critical for DKA",
			},
			{
				ID:             "TC-DKA-002",
				Name:           "Potassium Check Before Insulin",
				Description:    "Potassium level verified before starting insulin",
				Type:           "prerequisite",
				ReferenceEvent: "insulin_start",
				OffsetMinutes:  0,
				Priority:       "critical",
				Rationale:      "Hypokalemia can be life-threatening with insulin",
			},
			{
				ID:             "TC-DKA-003",
				Name:           "Insulin Drip Initiation",
				Description:    "Start insulin within 1 hour if K ≥3.3",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  60,
				Priority:       "high",
				Rationale:      "Insulin required to close anion gap",
			},
			{
				ID:             "TC-DKA-004",
				Name:           "Serial Chemistry Monitoring",
				Description:    "BMP q2h until stable, then q4h",
				Type:           "interval",
				ReferenceEvent: "insulin_start",
				OffsetMinutes:  120,
				Priority:       "high",
				Rationale:      "Close monitoring of glucose, electrolytes, anion gap",
			},
		},
		Metadata: map[string]interface{}{
			"dka_criteria":          []string{"glucose>250", "pH<7.3 or bicarb<18", "anion_gap>12", "ketones_positive"},
			"severity_classification": map[string]string{"mild": "pH 7.25-7.30", "moderate": "pH 7.0-7.24", "severe": "pH <7.0"},
			"resolution_criteria":   []string{"glucose<200", "pH>7.3", "bicarb>=15", "anion_gap<=12"},
		},
	}
}

func getDKAOrders() []models.Order {
	return []models.Order{
		// === ADMISSION ===
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Admit to ICU/Step-Down",
			Description: "Level of care based on severity",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "ICU if: pH <7.1, altered mental status, hemodynamic instability, moderate-severe DKA",
		},
		{
			ID:          uuid.New().String(),
			Type:        "diet",
			Category:    "Nursing",
			Name:        "NPO",
			Description: "Nothing by mouth until DKA resolving",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "NPO until anion gap closed and tolerating PO. Then diabetic diet.",
		},
		// === IV FLUIDS - INITIAL RESUSCITATION ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "IV Fluids",
			Name:        "Normal Saline 0.9% - Initial Bolus",
			Description: "Aggressive initial fluid resuscitation",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "313002",
			Dose:        "1000-1500",
			DoseUnit:    "mL",
			Route:       "IV",
			Frequency:   "bolus over 1 hour",
			Instructions: "15-20 mL/kg/hr for first hour. Assess volume status before additional boluses.",
			Conditions: []models.OrderCondition{
				{Type: "warning", Parameter: "CHF", Operator: "=", Value: "true", Action: "Use caution, smaller boluses"},
				{Type: "warning", Parameter: "CKD_severe", Operator: "=", Value: "true", Action: "Reduce rate, monitor closely"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "IV Fluids",
			Name:        "IV Fluids - Maintenance Phase",
			Description: "Ongoing fluid replacement",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "313002",
			Dose:        "250-500",
			DoseUnit:    "mL/hr",
			Route:       "IV",
			Frequency:   "continuous",
			Instructions: "After initial bolus: NS if Na low/normal, 0.45% NS if Na high. Rate 250-500 mL/hr based on hydration.",
			Conditions: []models.OrderCondition{
				{Type: "clinical", Parameter: "corrected_Na", Operator: "<", Value: "135", Action: "Continue NS 0.9%"},
				{Type: "clinical", Parameter: "corrected_Na", Operator: ">=", Value: "135", Action: "Switch to 0.45% NS"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "IV Fluids",
			Name:        "D5 0.45% NS",
			Description: "Add dextrose when glucose <200",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "309778",
			Dose:        "150-250",
			DoseUnit:    "mL/hr",
			Route:       "IV",
			Frequency:   "continuous",
			Instructions: "Switch to D5 0.45% NS when glucose <200 mg/dL. Maintains insulin drip to close gap while preventing hypoglycemia.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "glucose", Operator: "<", Value: "200", Action: "Add dextrose to fluids"},
			},
		},
		// === INSULIN THERAPY ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Insulin",
			Name:        "Regular Insulin IV Drip",
			Description: "Continuous insulin infusion for DKA",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "5856",
			Dose:        "0.1",
			DoseUnit:    "units/kg/hr",
			Route:       "IV continuous",
			Frequency:   "continuous infusion",
			Instructions: "Bolus 0.1 units/kg then 0.1 units/kg/hr infusion. DO NOT START if K <3.3. Target glucose drop 50-70 mg/dL/hr.",
			WeightBased: true,
			Conditions: []models.OrderCondition{
				{Type: "prerequisite", Parameter: "potassium", Operator: ">=", Value: "3.3", Action: "May start insulin"},
				{Type: "contraindication", Parameter: "potassium", Operator: "<", Value: "3.3", Action: "HOLD insulin - replace K first"},
				{Type: "adjustment", Parameter: "glucose_drop", Operator: "<", Value: "50", Action: "Increase rate by 50%"},
				{Type: "adjustment", Parameter: "glucose", Operator: "<", Value: "200", Action: "Reduce to 0.02-0.05 units/kg/hr"},
			},
		},
		// === ELECTROLYTE REPLACEMENT ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Electrolyte",
			Name:        "Potassium Chloride Replacement",
			Description: "Aggressive potassium replacement per protocol",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "8591",
			Dose:        "20-40",
			DoseUnit:    "mEq/L IVF",
			Route:       "IV",
			Frequency:   "in each liter of fluids",
			Instructions: "K <3.3: Hold insulin, give 40 mEq/hr IV until K ≥3.3. K 3.3-5.2: Add 20-40 mEq to each L of fluid. K >5.2: Check q2h, no supplementation.",
			Conditions: []models.OrderCondition{
				{Type: "dosing", Parameter: "K", Operator: "<", Value: "3.3", Action: "Hold insulin, give 40 mEq/hr"},
				{Type: "dosing", Parameter: "K", Operator: "between", Value: "3.3-5.2", Action: "Add 20-40 mEq to each L"},
				{Type: "dosing", Parameter: "K", Operator: ">", Value: "5.2", Action: "Hold potassium, recheck q2h"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Electrolyte",
			Name:        "Sodium Bicarbonate",
			Description: "Bicarbonate for severe acidosis only",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "9863",
			Dose:        "100",
			DoseUnit:    "mEq",
			Route:       "IV",
			Frequency:   "over 2 hours",
			Instructions: "ONLY if pH <6.9. Give 100 mEq NaHCO3 in 400mL water with 20 mEq KCl over 2h. Repeat until pH ≥7.0.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "pH", Operator: "<", Value: "6.9", Action: "Consider bicarbonate"},
				{Type: "warning", Parameter: "pH", Operator: ">=", Value: "6.9", Action: "Bicarbonate NOT indicated"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Electrolyte",
			Name:        "Phosphate Replacement",
			Description: "Phosphate if severely depleted",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "8340",
			Dose:        "20-30",
			DoseUnit:    "mEq",
			Route:       "IV",
			Frequency:   "over 4-6 hours",
			Instructions: "Replace if PO4 <1.0 mg/dL and cardiac dysfunction, hemolytic anemia, or respiratory depression.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "phosphate", Operator: "<", Value: "1.0", Action: "Consider replacement"},
			},
		},
		// === DVT PROPHYLAXIS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Enoxaparin DVT Prophylaxis",
			Description: "DVT prevention",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "67108",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "SubQ",
			Frequency:   "daily",
			Instructions: "Start when hydration adequate. Reduce to 30mg if CrCl <30.",
		},
		// === LABORATORY MONITORING ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Basic Metabolic Panel - Serial",
			Description: "Monitor glucose, electrolytes, renal function, anion gap",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "51990-0",
			Frequency:   "q2h until stable, then q4h",
			Instructions: "Calculate anion gap with each set. Continue until gap closed.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Glucose POC",
			Description: "Point-of-care glucose monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "2345-7",
			Frequency:   "q1h",
			Instructions: "Hourly fingerstick glucose. Target drop 50-70 mg/dL/hr.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Blood Gas",
			Name:        "Venous Blood Gas",
			Description: "Monitor pH and bicarbonate",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "24338-6",
			Frequency:   "q2-4h until pH >7.3",
			Instructions: "VBG adequate for pH monitoring. ABG if hypoxia suspected.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Beta-Hydroxybutyrate",
			Description: "Monitor ketone clearance",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "2086-7",
			Frequency:   "q4-6h",
			Instructions: "More accurate than urine ketones. Goal <0.6 mmol/L.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count",
			Description: "Baseline and monitor for infection",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Metabolic",
			Name:        "Hemoglobin A1c",
			Description: "Baseline glycemic control",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "4548-4",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Urine",
			Name:        "Urinalysis with Culture",
			Description: "Evaluate for UTI as precipitant",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "24356-8",
		},
		// === IMAGING ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "Chest X-Ray",
			Description: "Evaluate for infection as precipitant",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			CPTCode:     "71046",
		},
		// === NURSING ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Vital Signs",
			Description: "Frequent vital sign monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q1h x 4, then q2h until stable",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Strict Intake and Output",
			Description: "Fluid balance monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Hourly I/O. Foley catheter if altered mental status.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Neurological Checks",
			Description: "Monitor for cerebral edema",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q1h",
			Instructions: "Monitor for signs of cerebral edema: headache, altered mental status, bradycardia. Higher risk in pediatrics.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Protocol",
			Name:        "DKA Flow Sheet",
			Description: "Standardized DKA monitoring documentation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Document: glucose, K, anion gap, pH, bicarb, insulin rate, IVF rate, I/O q1-2h",
		},
		// === CONSULTS ===
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Endocrinology Consult",
			Description: "Diabetes specialist evaluation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Recommended for: new diabetes diagnosis, recurrent DKA, complex management",
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Ancillary",
			Name:        "Diabetes Educator",
			Description: "Diabetes education before discharge",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Education on: sick day rules, insulin administration, glucose monitoring, DKA prevention",
		},
	}
}

// GetMetabolicAdmissionOrderSets returns all metabolic admission order sets
func GetMetabolicAdmissionOrderSets() []*models.OrderSetTemplate {
	return []*models.OrderSetTemplate{
		GetSepsisOrderSet(),
		GetDKAOrderSet(),
	}
}
