// Package ordersets provides clinical order set templates for KB-12
// admission_ordersets_infectious.go - Infectious disease admission order sets
// Templates: Cellulitis, UTI/Pyelonephritis
package ordersets

import (
	"time"

	"github.com/google/uuid"
	"kb-12-ordersets-careplans/internal/models"
)

// GetCellulitisOrderSet returns the Cellulitis admission order set
// Based on IDSA Skin and Soft Tissue Infection Guidelines
func GetCellulitisOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-INF-001",
		TemplateID:  "OS-INF-001",
		Name:        "Cellulitis Admission",
		Description: "Order set for cellulitis and skin/soft tissue infection admission",
		Version:     "2.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "Infectious Disease",
		Specialty:   "Infectious Disease",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Infectious Disease Clinical Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level B",
		References: []string{
			"IDSA Skin and Soft Tissue Infection Guidelines 2014",
			"Cellulitis Classification: Purulent vs Non-Purulent",
		},
		ICDCodes: []string{"L03.90", "L03.115", "L03.116", "L03.311", "L03.312"},
		SNOMEDCodes: []string{"128045006", "312141004"},
		Orders: getCellulitisOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:             "TC-CELL-001",
				Name:           "Antibiotic Administration",
				Description:    "IV antibiotics within 2 hours of admission",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  120,
				Priority:       "high",
				Rationale:      "Early antibiotics improve outcomes and prevent progression",
			},
			{
				ID:             "TC-CELL-002",
				Name:           "Wound Marking",
				Description:    "Demarcate erythema borders at admission",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  60,
				Priority:       "high",
				Rationale:      "Tracking progression/improvement of cellulitis",
			},
		},
		Metadata: map[string]interface{}{
			"classification":    []string{"purulent", "non-purulent"},
			"severity":          []string{"mild", "moderate", "severe"},
			"mrsa_risk_factors": []string{"prior_MRSA", "IVDU", "hemodialysis", "recent_hospitalization"},
			"necrotizing_signs": []string{"pain_out_of_proportion", "crepitus", "bullae", "skin_necrosis", "hypotension"},
		},
	}
}

func getCellulitisOrders() []models.Order {
	return []models.Order{
		// === ADMISSION ===
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Admit to Medicine Service",
			Description: "Level of care based on severity",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "ICU if: sepsis, necrotizing fasciitis suspected, hemodynamic instability",
		},
		{
			ID:          uuid.New().String(),
			Type:        "diet",
			Category:    "Nursing",
			Name:        "Regular Diet",
			Description: "Diet as tolerated",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
		},
		// === WOUND CARE ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Wound Care",
			Name:        "Mark Borders of Erythema",
			Description: "Demarcate infection borders with skin marker",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Outline erythema borders with permanent marker. Date and time. Reassess q8-12h.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Wound Care",
			Name:        "Extremity Elevation",
			Description: "Elevate affected extremity",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Elevate affected limb above heart level to reduce edema. Pillows under arm/leg.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Wound Care",
			Name:        "Wound Care - Purulent Cellulitis",
			Description: "Incision and drainage if abscess present",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			Instructions: "I&D required for abscess. Pack wound. Daily dressing changes.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "abscess_present", Operator: "=", Value: "true", Action: "Incision and drainage required"},
			},
		},
		// === ANTIBIOTICS - NON-PURULENT (Strep predominant) ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Cefazolin",
			Description: "First-line for non-purulent cellulitis",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "2180",
			Dose:        "1-2",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "q8h",
			Duration:    "5-7 days",
			Instructions: "First-line for non-purulent cellulitis (strep predominant). Use 2g for severe infection or >80kg.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "purulent", Operator: "=", Value: "false", Action: "Use cefazolin"},
				{Type: "alternative", Parameter: "penicillin_allergy", Operator: "=", Value: "severe", Action: "Use vancomycin"},
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "35", Action: "1g q12h"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Penicillin G (Alternative)",
			Description: "Alternative for non-purulent cellulitis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "7980",
			Dose:        "2-4",
			DoseUnit:    "million units",
			Route:       "IV",
			Frequency:   "q4-6h",
			Duration:    "5-7 days",
			Instructions: "Alternative beta-lactam for streptococcal cellulitis.",
		},
		// === ANTIBIOTICS - PURULENT (MRSA coverage) ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Vancomycin",
			Description: "MRSA coverage for purulent cellulitis",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "11124",
			Dose:        "15-20",
			DoseUnit:    "mg/kg",
			Route:       "IV",
			Frequency:   "q8-12h",
			Duration:    "5-7 days",
			Instructions: "For purulent cellulitis (MRSA coverage) or failed beta-lactam. Pharmacy dosing recommended.",
			WeightBased: true,
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "purulent", Operator: "=", Value: "true", Action: "Use vancomycin"},
				{Type: "indication", Parameter: "MRSA_risk", Operator: "=", Value: "high", Action: "Use vancomycin"},
				{Type: "monitoring", Parameter: "vanc_trough", Operator: "target", Value: "15-20", Action: "Check before 4th dose"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Daptomycin (Alternative)",
			Description: "Alternative MRSA coverage",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "358399",
			Dose:        "4-6",
			DoseUnit:    "mg/kg",
			Route:       "IV",
			Frequency:   "daily",
			Duration:    "5-7 days",
			Instructions: "Alternative to vancomycin for SSTI. Use 4 mg/kg for uncomplicated, 6 mg/kg for complicated.",
			WeightBased: true,
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "vancomycin_intolerance", Operator: "=", Value: "true", Action: "Use daptomycin"},
				{Type: "monitoring", Parameter: "CK", Operator: "check", Value: "weekly", Action: "Monitor for myopathy"},
			},
		},
		// === SEVERE/NECROTIZING ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Piperacillin-Tazobactam",
			Description: "Broad-spectrum for severe/necrotizing",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "8339",
			Dose:        "3.375-4.5",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "q6-8h",
			Duration:    "until surgical debridement/source control",
			Instructions: "For severe infection, diabetic foot, or necrotizing fasciitis suspected. Add vancomycin for MRSA.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "severity", Operator: "=", Value: "severe", Action: "Use broad-spectrum"},
				{Type: "indication", Parameter: "diabetic_foot", Operator: "=", Value: "true", Action: "Use pip-tazo"},
				{Type: "indication", Parameter: "necrotizing_suspected", Operator: "=", Value: "true", Action: "Use pip-tazo + vancomycin + clindamycin"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Clindamycin (Toxin Inhibitor)",
			Description: "Add for toxin-producing strep (necrotizing)",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "2582",
			Dose:        "600-900",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "q8h",
			Instructions: "Add for suspected necrotizing fasciitis or toxic shock. Inhibits toxin production.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "necrotizing", Operator: "=", Value: "suspected", Action: "Add clindamycin"},
				{Type: "indication", Parameter: "toxic_shock", Operator: "=", Value: "suspected", Action: "Add clindamycin"},
			},
		},
		// === SUPPORTIVE ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Analgesic",
			Name:        "Acetaminophen",
			Description: "Pain and fever control",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "161",
			Dose:        "650-1000",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "q6h PRN",
			MaxDose:     "3g/day",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Enoxaparin",
			Description: "DVT prophylaxis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "67108",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "SubQ",
			Frequency:   "daily",
			Conditions: []models.OrderCondition{
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "30", Action: "Reduce to 30mg daily"},
			},
		},
		// === LABORATORY ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count",
			Description: "Evaluate WBC, assess severity",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Basic Metabolic Panel",
			Description: "Electrolytes and renal function",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "51990-0",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Microbiology",
			Name:        "Blood Cultures",
			Description: "If febrile or severe infection",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "600-7",
			Instructions: "Obtain if: fever, severe cellulitis, immunocompromised, systemic symptoms",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "fever", Operator: "=", Value: "true", Action: "Obtain blood cultures"},
				{Type: "indication", Parameter: "severity", Operator: "=", Value: "severe", Action: "Obtain blood cultures"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Microbiology",
			Name:        "Wound Culture",
			Description: "Culture purulent drainage if present",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "11475-1",
			Instructions: "Culture purulent drainage or abscess contents. Not indicated for non-purulent cellulitis.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "purulent", Operator: "=", Value: "true", Action: "Culture drainage"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "CK (Creatine Kinase)",
			Description: "Evaluate for necrotizing fasciitis",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "2157-6",
			Instructions: "Elevated CK suggests muscle involvement - consider necrotizing infection.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "necrotizing_suspected", Operator: "=", Value: "true", Action: "Check CK"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Lactate",
			Description: "Severity marker",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "2524-7",
			Instructions: "If sepsis or necrotizing infection suspected.",
		},
		// === IMAGING ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "X-Ray of Affected Area",
			Description: "Evaluate for gas, foreign body, osteomyelitis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "73630",
			Instructions: "Consider if: diabetic foot, trauma, suspected osteomyelitis, crepitus on exam",
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "CT/MRI of Affected Area",
			Description: "Evaluate for deep space infection or necrotizing fasciitis",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "73720",
			Instructions: "If necrotizing fasciitis suspected. DO NOT delay surgery for imaging if high clinical suspicion.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "necrotizing_suspected", Operator: "=", Value: "true", Action: "Imaging for surgical planning"},
				{Type: "warning", Parameter: "clinical_suspicion", Operator: "=", Value: "high", Action: "Do not delay surgery"},
			},
		},
		// === NURSING ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Vital Signs",
			Description: "Monitor for progression",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q4h",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Assessment",
			Name:        "Erythema Progression Assessment",
			Description: "Track cellulitis borders",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q8-12h",
			Instructions: "Document if erythema is spreading, stable, or improving relative to marked borders.",
		},
		// === CONSULTS ===
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Surgery Consult - STAT",
			Description: "Surgical evaluation for necrotizing fasciitis",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			Instructions: "STAT surgery consult if necrotizing fasciitis suspected. Surgical debridement is definitive treatment.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "necrotizing_suspected", Operator: "=", Value: "true", Action: "STAT surgery consult"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Infectious Disease Consult",
			Description: "ID evaluation for complex cases",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consider for: failure to improve on empiric antibiotics, recurrent cellulitis, unusual pathogens",
		},
	}
}

// GetUTIPyelonephritisOrderSet returns the UTI/Pyelonephritis admission order set
// Based on IDSA UTI Guidelines
func GetUTIPyelonephritisOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-INF-002",
		TemplateID:  "OS-INF-002",
		Name:        "UTI/Pyelonephritis Admission",
		Description: "Order set for complicated UTI and pyelonephritis admission",
		Version:     "2.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "Infectious Disease",
		Specialty:   "Infectious Disease",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Infectious Disease Clinical Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level A",
		References: []string{
			"IDSA Uncomplicated UTI Guidelines 2011",
			"IDSA Complicated UTI Guidelines 2010",
			"AUA Recurrent UTI Guidelines",
		},
		ICDCodes: []string{"N10", "N30.90", "N39.0", "N12"},
		SNOMEDCodes: []string{"45816000", "36689008", "68566005"},
		Orders: getUTIPyelonephritisOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:             "TC-UTI-001",
				Name:           "Antibiotic Administration",
				Description:    "IV antibiotics within 1-2 hours",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  120,
				Priority:       "high",
				Rationale:      "Early antibiotics prevent bacteremia and sepsis progression",
			},
			{
				ID:             "TC-UTI-002",
				Name:           "Urine Culture Before Antibiotics",
				Description:    "Urine culture before first antibiotic dose",
				Type:           "prerequisite",
				ReferenceEvent: "antibiotic_first_dose",
				OffsetMinutes:  0,
				Priority:       "high",
				Rationale:      "Culture guides antibiotic de-escalation",
			},
		},
		Metadata: map[string]interface{}{
			"complicated_criteria": []string{"male", "pregnancy", "obstruction", "catheter", "structural_abnormality", "immunocompromised"},
			"common_pathogens":     []string{"E_coli", "Klebsiella", "Proteus", "Enterococcus", "Pseudomonas"},
			"resistance_concern":   []string{"ESBL", "fluoroquinolone_resistance"},
		},
	}
}

func getUTIPyelonephritisOrders() []models.Order {
	return []models.Order{
		// === ADMISSION ===
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Admit to Medicine Service",
			Description: "Level of care based on severity",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "ICU if: sepsis/septic shock, hemodynamic instability",
		},
		{
			ID:          uuid.New().String(),
			Type:        "diet",
			Category:    "Nursing",
			Name:        "Regular Diet with Hydration",
			Description: "Encourage oral fluids",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Encourage oral fluid intake if tolerated",
		},
		// === ANTIBIOTICS - EMPIRIC ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Ceftriaxone",
			Description: "Empiric IV antibiotic for pyelonephritis",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "2193",
			Dose:        "1",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "daily",
			Duration:    "7-14 days total (IV then PO)",
			Instructions: "First-line empiric therapy. Adjust based on culture results. Transition to PO when improving.",
			Conditions: []models.OrderCondition{
				{Type: "alternative", Parameter: "ESBL_risk", Operator: "=", Value: "high", Action: "Use carbapenem"},
				{Type: "alternative", Parameter: "severe_penicillin_allergy", Operator: "=", Value: "true", Action: "Use fluoroquinolone or aminoglycoside"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Ciprofloxacin (Alternative)",
			Description: "Fluoroquinolone alternative",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "2551",
			Dose:        "400",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "q12h",
			Duration:    "7 days",
			Instructions: "Alternative if beta-lactam allergic. Check local resistance patterns. Transition to 500mg PO BID when able.",
			Conditions: []models.OrderCondition{
				{Type: "warning", Parameter: "FQ_resistance_rate", Operator: ">", Value: "10%", Action: "Avoid empiric FQ"},
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "30", Action: "200mg IV q12h"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Piperacillin-Tazobactam",
			Description: "Broad-spectrum for severe or healthcare-associated",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "8339",
			Dose:        "3.375",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "q6h",
			Duration:    "10-14 days",
			Instructions: "Use for: severe sepsis, healthcare-associated UTI, structural abnormality, recent antibiotics",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "healthcare_associated", Operator: "=", Value: "true", Action: "Use pip-tazo"},
				{Type: "indication", Parameter: "severe_sepsis", Operator: "=", Value: "true", Action: "Use pip-tazo"},
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "40", Action: "2.25g q6h"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antibiotic",
			Name:        "Meropenem",
			Description: "Carbapenem for ESBL or severe infection",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "29561",
			Dose:        "1",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "q8h",
			Duration:    "10-14 days",
			Instructions: "Reserve for: known ESBL, prior resistant organisms, severely ill with risk factors",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "ESBL_history", Operator: "=", Value: "true", Action: "Use carbapenem"},
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "50", Action: "1g q12h"},
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "25", Action: "500mg q12h"},
			},
		},
		// === SUPPORTIVE ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "IV Fluids",
			Name:        "IV Fluids",
			Description: "Hydration",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "313002",
			Dose:        "100-150",
			DoseUnit:    "mL/hr",
			Route:       "IV",
			Frequency:   "continuous",
			Instructions: "Maintain hydration. Bolus if dehydrated or septic.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Analgesic",
			Name:        "Acetaminophen",
			Description: "Fever and pain control",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "161",
			Dose:        "650-1000",
			DoseUnit:    "mg",
			Route:       "PO/IV",
			Frequency:   "q6h PRN",
			MaxDose:     "3g/day",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Antiemetic",
			Name:        "Ondansetron",
			Description: "Nausea control",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "26225",
			Dose:        "4",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "q6-8h PRN",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Enoxaparin",
			Description: "DVT prophylaxis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "67108",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "SubQ",
			Frequency:   "daily",
			Conditions: []models.OrderCondition{
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "30", Action: "Reduce to 30mg daily"},
			},
		},
		// === LABORATORY ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Urine",
			Name:        "Urinalysis with Reflex Culture",
			Description: "UA and culture for diagnosis",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "24356-8",
			Instructions: "Obtain BEFORE antibiotics. Clean-catch or straight cath if unable.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Microbiology",
			Name:        "Urine Culture with Sensitivities",
			Description: "Guide antibiotic therapy",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "630-4",
			Instructions: "MUST be collected before antibiotics. Adjust therapy based on results.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Microbiology",
			Name:        "Blood Cultures x 2",
			Description: "Evaluate for bacteremia",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "600-7",
			Instructions: "Obtain before antibiotics. Pyelonephritis has ~20-30% bacteremia rate.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Basic Metabolic Panel",
			Description: "Renal function and electrolytes",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "51990-0",
			Instructions: "Assess for AKI. Important for antibiotic dosing.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count",
			Description: "WBC count for severity assessment",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Lactate",
			Description: "Sepsis marker if ill-appearing",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "2524-7",
			Instructions: "If sepsis suspected",
		},
		// === IMAGING ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "CT Abdomen/Pelvis with Contrast",
			Description: "Evaluate for obstruction or abscess",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "74177",
			Instructions: "Indicated if: no improvement at 48-72h, suspected obstruction/stone, perinephric abscess concern",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "no_improvement_72h", Operator: "=", Value: "true", Action: "Obtain CT"},
				{Type: "indication", Parameter: "obstruction_suspected", Operator: "=", Value: "true", Action: "Obtain CT urgently"},
				{Type: "contraindication", Parameter: "contrast_allergy", Operator: "=", Value: "severe", Action: "Non-contrast CT"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "Renal Ultrasound",
			Description: "Evaluate for hydronephrosis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "76770",
			Instructions: "Alternative to CT if contrast contraindicated. Good for hydronephrosis but poor for stones/abscess.",
		},
		// === NURSING ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Vital Signs",
			Description: "Monitor for sepsis progression",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q4h",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Intake and Output",
			Description: "Monitor renal function",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
		},
		// === CONSULTS ===
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Urology Consult",
			Description: "Urological evaluation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consult if: obstructive stone, perinephric abscess needing drainage, structural abnormality",
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Infectious Disease Consult",
			Description: "ID evaluation for complex cases",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consider for: resistant organisms, recurrent pyelonephritis, immunocompromised host",
		},
	}
}

// GetInfectiousAdmissionOrderSets returns all infectious disease admission order sets
func GetInfectiousAdmissionOrderSets() []*models.OrderSetTemplate {
	return []*models.OrderSetTemplate{
		GetCellulitisOrderSet(),
		GetUTIPyelonephritisOrderSet(),
	}
}
