// Package ordersets provides clinical order set templates for KB-12
// admission_ordersets_other.go - Other admission order sets
// Templates: Alcohol Withdrawal, General Medicine Admission
package ordersets

import (
	"time"

	"github.com/google/uuid"
	"kb-12-ordersets-careplans/internal/models"
)

// GetAlcoholWithdrawalOrderSet returns the Alcohol Withdrawal admission order set
// Based on ASAM Guidelines
func GetAlcoholWithdrawalOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-OTHER-001",
		TemplateID:  "OS-OTHER-001",
		Name:        "Alcohol Withdrawal Admission",
		Description: "CIWA-based order set for alcohol withdrawal syndrome management",
		Version:     "2.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "Psychiatry/Medicine",
		Specialty:   "Addiction Medicine",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Addiction Medicine/Psychiatry Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level A",
		References: []string{
			"ASAM Clinical Practice Guideline for Alcohol Withdrawal 2020",
			"CIWA-Ar Protocol",
			"APA Practice Guidelines",
		},
		ICDCodes: []string{"F10.239", "F10.231", "F10.232", "F10.230"},
		SNOMEDCodes: []string{"8635005", "291018003"},
		Orders: getAlcoholWithdrawalOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:             "TC-AWS-001",
				Name:           "Thiamine Before Glucose",
				Description:    "Thiamine must be given before or with glucose",
				Type:           "prerequisite",
				ReferenceEvent: "glucose_administration",
				OffsetMinutes:  0,
				Priority:       "critical",
				Rationale:      "Prevent Wernicke encephalopathy - glucose depletes thiamine",
			},
			{
				ID:             "TC-AWS-002",
				Name:           "Initial CIWA Assessment",
				Description:    "CIWA-Ar assessment within 30 minutes of admission",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  30,
				Priority:       "high",
				Rationale:      "Early assessment guides benzodiazepine dosing",
			},
			{
				ID:             "TC-AWS-003",
				Name:           "Serial CIWA Monitoring",
				Description:    "CIWA reassessment per protocol during acute withdrawal",
				Type:           "interval",
				ReferenceEvent: "initial_ciwa",
				OffsetMinutes:  60,
				Priority:       "high",
				Rationale:      "Symptom-triggered therapy requires frequent reassessment",
			},
		},
		Metadata: map[string]interface{}{
			"ciwa_thresholds":  map[string]string{"mild": "8-15", "moderate": "16-20", "severe": ">20"},
			"seizure_risk":     []string{"prior_seizures", "prior_DTs", "concurrent_illness", "electrolyte_abnormalities"},
			"DT_risk_factors":  []string{"prior_DTs", "age>65", "concurrent_illness", "prolonged_drinking", "high_CIWA_at_presentation"},
			"expected_timeline": "Symptoms peak 24-72h, DTs can occur up to 96h",
		},
	}
}

func getAlcoholWithdrawalOrders() []models.Order {
	return []models.Order{
		// === ADMISSION ===
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Admit to Medicine/Telemetry",
			Description: "Level of care based on severity",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "ICU if: delirium tremens, seizures, severe withdrawal (CIWA >20), hemodynamic instability",
		},
		{
			ID:          uuid.New().String(),
			Type:        "diet",
			Category:    "Nursing",
			Name:        "Regular Diet with Supplements",
			Description: "High-calorie, high-protein diet",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "NPO if altered mental status or aspiration risk. Otherwise high-calorie diet with supplements.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Safety",
			Name:        "Fall Precautions and Seizure Precautions",
			Description: "Safety measures for withdrawal",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Bed alarm, padded side rails, suction at bedside. 1:1 observation if agitated/confused.",
		},
		// === THIAMINE - CRITICAL ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Vitamin",
			Name:        "Thiamine (Vitamin B1)",
			Description: "Wernicke prophylaxis/treatment",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "10582",
			Dose:        "500",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "TID x 3 days, then 100mg daily",
			Instructions: "MUST give BEFORE or WITH glucose. High-dose for suspected Wernicke. 100mg if low risk.",
			Conditions: []models.OrderCondition{
				{Type: "prerequisite", Parameter: "timing", Operator: "before", Value: "glucose", Action: "Give thiamine first"},
				{Type: "dosing", Parameter: "wernicke_suspected", Operator: "=", Value: "true", Action: "500mg IV TID x 3-5 days"},
				{Type: "dosing", Parameter: "wernicke_suspected", Operator: "=", Value: "false", Action: "100-250mg IV daily x 3 days"},
			},
		},
		// === BENZODIAZEPINES - CIWA PROTOCOL ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Benzodiazepine",
			Name:        "Chlordiazepoxide - CIWA Protocol",
			Description: "Symptom-triggered benzodiazepine therapy",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "2356",
			Dose:        "25-100",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "per CIWA protocol",
			Instructions: "CIWA 8-15: 25-50mg. CIWA 16-20: 50-100mg. CIWA >20: 100mg. Reassess q1h. Max 300mg in first 3h without MD review.",
			Conditions: []models.OrderCondition{
				{Type: "dosing", Parameter: "CIWA", Operator: "between", Value: "8-15", Action: "25-50mg PO"},
				{Type: "dosing", Parameter: "CIWA", Operator: "between", Value: "16-20", Action: "50-100mg PO"},
				{Type: "dosing", Parameter: "CIWA", Operator: ">", Value: "20", Action: "100mg PO or switch to IV"},
				{Type: "alternative", Parameter: "liver_failure", Operator: "=", Value: "true", Action: "Use lorazepam instead"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Benzodiazepine",
			Name:        "Lorazepam - Hepatic Impairment",
			Description: "Preferred benzodiazepine for liver disease",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "6470",
			Dose:        "1-4",
			DoseUnit:    "mg",
			Route:       "IV/PO",
			Frequency:   "per CIWA protocol",
			Instructions: "Use for hepatic impairment (no hepatic metabolism). CIWA 8-15: 1-2mg. CIWA 16-20: 2-4mg. CIWA >20: 4mg IV.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "liver_disease", Operator: "=", Value: "true", Action: "Use lorazepam"},
				{Type: "dosing", Parameter: "CIWA", Operator: "between", Value: "8-15", Action: "1-2mg"},
				{Type: "dosing", Parameter: "CIWA", Operator: "between", Value: "16-20", Action: "2-4mg"},
				{Type: "dosing", Parameter: "CIWA", Operator: ">", Value: "20", Action: "4mg IV"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Benzodiazepine",
			Name:        "Diazepam IV - Severe Withdrawal/DTs",
			Description: "IV benzodiazepine for severe withdrawal",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "3322",
			Dose:        "5-10",
			DoseUnit:    "mg",
			Route:       "IV",
			Frequency:   "q5-10min PRN",
			Instructions: "For severe withdrawal or DTs. Rapid titration until calm. May need 50-100mg+ in first hour for DTs.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "DTs", Operator: "=", Value: "true", Action: "Use IV diazepam - rapid titration"},
				{Type: "indication", Parameter: "seizures", Operator: "=", Value: "true", Action: "Use IV diazepam"},
			},
		},
		// === ADJUNCTIVE MEDICATIONS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Vitamin",
			Name:        "Folic Acid",
			Description: "Folate supplementation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "4511",
			Dose:        "1",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "daily",
			Duration:    "during admission",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Vitamin",
			Name:        "Multivitamin",
			Description: "General vitamin supplementation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "89905",
			Dose:        "1",
			DoseUnit:    "tablet",
			Route:       "PO",
			Frequency:   "daily",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Electrolyte",
			Name:        "Magnesium Sulfate",
			Description: "Magnesium replacement",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "6585",
			Dose:        "2",
			DoseUnit:    "g",
			Route:       "IV",
			Frequency:   "PRN",
			Instructions: "Replace if Mg <2.0. Hypomagnesemia common and lowers seizure threshold.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "magnesium", Operator: "<", Value: "2.0", Action: "Replace"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Electrolyte",
			Name:        "Potassium Chloride",
			Description: "Potassium replacement",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "8591",
			Dose:        "20-40",
			DoseUnit:    "mEq",
			Route:       "PO/IV",
			Frequency:   "PRN",
			Instructions: "Replace to maintain K >4.0. Hypokalemia common with alcohol use.",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "potassium", Operator: "<", Value: "3.5", Action: "Replace 40 mEq"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Enoxaparin",
			Description: "DVT prophylaxis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "67108",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "SubQ",
			Frequency:   "daily",
			Conditions: []models.OrderCondition{
				{Type: "contraindication", Parameter: "active_bleeding", Operator: "=", Value: "true", Action: "Use mechanical prophylaxis"},
				{Type: "contraindication", Parameter: "thrombocytopenia", Operator: "=", Value: "severe", Action: "Use mechanical prophylaxis"},
			},
		},
		// === IV FLUIDS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "IV Fluids",
			Name:        "D5NS with Potassium",
			Description: "Hydration with glucose and electrolytes",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "309778",
			Dose:        "100-150",
			DoseUnit:    "mL/hr",
			Route:       "IV",
			Frequency:   "continuous",
			Instructions: "D5NS with 20-40 mEq KCl per liter. GIVE THIAMINE BEFORE starting dextrose.",
		},
		// === LABORATORY ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Comprehensive Metabolic Panel",
			Description: "Electrolytes, renal, hepatic function",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "24323-8",
			Frequency:   "admission, daily",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count",
			Description: "Evaluate for anemia, infection",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Magnesium Level",
			Description: "Assess hypomagnesemia",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "19123-9",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Phosphorus Level",
			Description: "Assess hypophosphatemia",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "2777-1",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Toxicology",
			Name:        "Blood Alcohol Level",
			Description: "Baseline alcohol level",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "5643-2",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Toxicology",
			Name:        "Urine Drug Screen",
			Description: "Evaluate for polysubstance use",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "8220-6",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hepatic",
			Name:        "Ammonia Level",
			Description: "If altered mental status",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "1925-7",
			Instructions: "If altered mental status and liver disease - evaluate for hepatic encephalopathy",
		},
		// === IMAGING ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "CT Head without Contrast",
			Description: "If altered mental status, head trauma, or focal neuro findings",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "70450",
			Instructions: "Obtain if: fall with head injury, focal neurological findings, AMS out of proportion to withdrawal",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "head_trauma", Operator: "=", Value: "true", Action: "Obtain CT head"},
				{Type: "indication", Parameter: "focal_neuro_deficit", Operator: "=", Value: "true", Action: "Obtain CT head"},
			},
		},
		// === NURSING ORDERS ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Assessment",
			Name:        "CIWA-Ar Assessment",
			Description: "Clinical Institute Withdrawal Assessment - Alcohol, Revised",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q1h x 8h, then q2h x 16h, then q4h if stable",
			Instructions: "10-item scale (0-67). Score ≥8 triggers benzodiazepine. Score ≥20 is severe - notify MD.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Vital Signs",
			Description: "Frequent vital sign monitoring",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q1h with CIWA, then q4h when stable",
			Instructions: "Monitor HR, BP - tachycardia and hypertension indicate withdrawal severity.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Continuous Telemetry",
			Description: "Cardiac rhythm monitoring",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Monitor for arrhythmias - electrolyte abnormalities common.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Neurological Checks",
			Description: "Monitor mental status",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "with CIWA assessments",
			Instructions: "Assess orientation, hallucinations, tremor. Report DTs signs: confusion, hallucinations, severe agitation.",
		},
		// === CONSULTS ===
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Specialty",
			Name:        "Addiction Medicine/Psychiatry Consult",
			Description: "Substance use disorder evaluation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Evaluate for AUD treatment, medications (naltrexone, acamprosate, disulfiram), and discharge planning.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Ancillary",
			Name:        "Social Work Consult",
			Description: "Psychosocial assessment and discharge planning",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Assess for: housing, outpatient treatment resources, AA/support groups.",
		},
	}
}

// GetGeneralMedicineOrderSet returns the General Medicine admission order set
// NOTE: Uses OS-ADM-001 ID to match CDS Hooks and performance test expectations
func GetGeneralMedicineOrderSet() *models.OrderSetTemplate {
	return &models.OrderSetTemplate{
		ID:          "OS-ADM-001",
		TemplateID:  "OS-ADM-001",
		Name:        "General Medicine Admission",
		Description: "Standard admission order set for general medicine patients",
		Version:     "2.0.0",
		Category:    models.CategoryAdmission,
		Subcategory: "General",
		Specialty:   "Internal Medicine",
		Status:      "active",
		EffectiveDate: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ExpirationDate: time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC),
		Author:      "Hospital Medicine Committee",
		Approver:    "Chief Medical Officer",
		EvidenceLevel: "Class I, Level C",
		References: []string{
			"SHM DVT Prophylaxis Recommendations",
			"Joint Commission Core Measures",
			"CMS Hospital Quality Measures",
		},
		ICDCodes: []string{},
		SNOMEDCodes: []string{},
		Orders: getGeneralMedicineOrders(),
		TimeConstraints: []models.TimeConstraint{
			{
				ID:             "TC-GEN-001",
				Name:           "DVT Prophylaxis",
				Description:    "DVT prophylaxis assessment and initiation within 24 hours",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  1440,
				Priority:       "high",
				Rationale:      "VTE prevention is core quality measure",
			},
			{
				ID:             "TC-GEN-002",
				Name:           "Medication Reconciliation",
				Description:    "Medication reconciliation within 24 hours",
				Type:           "deadline",
				ReferenceEvent: "admission",
				OffsetMinutes:  1440,
				Priority:       "high",
				Rationale:      "Joint Commission requirement",
			},
		},
		Metadata: map[string]interface{}{
			"core_measures":       []string{"VTE_prophylaxis", "med_reconciliation", "fall_risk"},
			"discharge_planning":  "Start on admission",
		},
	}
}

func getGeneralMedicineOrders() []models.Order {
	return []models.Order{
		// === ADMISSION ===
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Admit to Medicine Service",
			Description: "General medicine admission",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Attending physician to be specified. Resident/hospitalist service assignment.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "admission",
			Category:    "Administrative",
			Name:        "Code Status Confirmation",
			Description: "Document code status",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Confirm and document code status. Address advance directives.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "diet",
			Category:    "Nursing",
			Name:        "Diet Order",
			Description: "Appropriate diet for condition",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Select appropriate diet based on diagnosis. Options: Regular, Diabetic, Cardiac, Renal, NPO.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "activity",
			Category:    "Nursing",
			Name:        "Activity Level",
			Description: "Appropriate activity restrictions",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Select: Bed rest, Bed rest with bathroom privileges, Activity as tolerated, Ambulate TID.",
		},
		// === DVT PROPHYLAXIS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Enoxaparin - DVT Prophylaxis",
			Description: "Pharmacologic VTE prophylaxis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "67108",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "SubQ",
			Frequency:   "daily",
			Instructions: "Standard prophylaxis for medical patients. Reduce to 30mg for CrCl <30.",
			Conditions: []models.OrderCondition{
				{Type: "renal_adjustment", Parameter: "CrCl", Operator: "<", Value: "30", Action: "Reduce to 30mg daily"},
				{Type: "contraindication", Parameter: "active_bleeding", Operator: "=", Value: "true", Action: "Use mechanical prophylaxis"},
				{Type: "contraindication", Parameter: "HIT_history", Operator: "=", Value: "true", Action: "Use fondaparinux"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Anticoagulation",
			Name:        "Heparin SubQ - Alternative",
			Description: "Unfractionated heparin for VTE prophylaxis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "5224",
			Dose:        "5000",
			DoseUnit:    "units",
			Route:       "SubQ",
			Frequency:   "q8-12h",
			Instructions: "Alternative to enoxaparin. 5000 units q8h or q12h.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Prevention",
			Name:        "Sequential Compression Devices",
			Description: "Mechanical VTE prophylaxis",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Apply when pharmacologic prophylaxis contraindicated or as adjunct. Remove only for ambulation.",
		},
		// === FALL PREVENTION ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Safety",
			Name:        "Fall Risk Assessment and Precautions",
			Description: "Fall prevention protocol",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Assess fall risk on admission (Morse Fall Scale). Implement precautions if high risk: bed alarm, non-skid socks, assist with ambulation.",
		},
		// === MEDICATIONS ===
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "GI Prophylaxis",
			Name:        "Pantoprazole",
			Description: "Stress ulcer prophylaxis if indicated",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "40790",
			Dose:        "40",
			DoseUnit:    "mg",
			Route:       "PO/IV",
			Frequency:   "daily",
			Instructions: "Only if indicated: ICU admission, mechanical ventilation, coagulopathy, history of GI bleed",
			Conditions: []models.OrderCondition{
				{Type: "indication", Parameter: "ICU_admission", Operator: "=", Value: "true", Action: "Stress ulcer prophylaxis indicated"},
				{Type: "indication", Parameter: "mechanical_ventilation", Operator: "=", Value: "true", Action: "Stress ulcer prophylaxis indicated"},
			},
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Bowel Care",
			Name:        "Docusate Sodium",
			Description: "Stool softener",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "3718",
			Dose:        "100",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "BID",
			Instructions: "If on opioids or at risk for constipation",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Bowel Care",
			Name:        "Senna",
			Description: "Stimulant laxative",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "9351",
			Dose:        "8.6",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "daily-BID PRN",
			Instructions: "PRN constipation. Use with docusate for patients on opioids.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Analgesic",
			Name:        "Acetaminophen",
			Description: "Pain and fever control",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			RxNormCode:  "161",
			Dose:        "650-1000",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "q6h PRN",
			MaxDose:     "3g/day (2g if liver disease)",
			Instructions: "First-line for mild-moderate pain. Reduce max to 2g/day if hepatic impairment.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "medication",
			Category:    "Sleep",
			Name:        "Melatonin",
			Description: "Sleep aid",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			RxNormCode:  "6809",
			Dose:        "3-5",
			DoseUnit:    "mg",
			Route:       "PO",
			Frequency:   "QHS PRN",
			Instructions: "First-line for insomnia in hospitalized patients. Avoid benzodiazepines/zolpidem.",
		},
		// === LABORATORY ===
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Chemistry",
			Name:        "Basic Metabolic Panel",
			Description: "Electrolytes and renal function",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "51990-0",
			Frequency:   "admission",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Hematology",
			Name:        "Complete Blood Count",
			Description: "CBC with differential",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			LOINCCode:   "57021-8",
			Frequency:   "admission",
		},
		{
			ID:          uuid.New().String(),
			Type:        "lab",
			Category:    "Urine",
			Name:        "Urinalysis",
			Description: "Urinalysis if indicated",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			LOINCCode:   "24356-8",
			Instructions: "If symptoms suggest UTI or per clinical indication",
		},
		// === IMAGING ===
		{
			ID:          uuid.New().String(),
			Type:        "imaging",
			Category:    "Radiology",
			Name:        "Chest X-Ray",
			Description: "CXR if clinically indicated",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			CPTCode:     "71046",
			Instructions: "If respiratory symptoms, fever, or clinical indication. Not required for all admissions.",
		},
		// === NURSING ===
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Monitoring",
			Name:        "Vital Signs",
			Description: "Standard vital sign monitoring",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Frequency:   "q4h",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Assessment",
			Name:        "Medication Reconciliation",
			Description: "Complete home medication review",
			Priority:    "stat",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Complete within 24h of admission. Verify home medications, OTC, supplements.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Assessment",
			Name:        "Skin Assessment and Braden Score",
			Description: "Pressure ulcer risk assessment",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Complete Braden score on admission. Initiate pressure injury prevention if high risk.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "nursing",
			Category:    "Assessment",
			Name:        "Nutritional Screening",
			Description: "Malnutrition screening",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Complete nutritional screening. Consult dietitian if at risk for malnutrition.",
		},
		// === CONSULTS ===
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Ancillary",
			Name:        "Pharmacy Consult",
			Description: "Pharmacist medication review",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consider for polypharmacy, high-risk medications, anticoagulation",
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Ancillary",
			Name:        "Case Management/Social Work",
			Description: "Discharge planning",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  true,
			Instructions: "Screen for discharge needs on admission. Initiate early discharge planning.",
		},
		{
			ID:          uuid.New().String(),
			Type:        "consult",
			Category:    "Ancillary",
			Name:        "Physical Therapy Screening",
			Description: "Mobility and fall risk evaluation",
			Priority:    "routine",
			Status:      "active",
			IsRequired:  false,
			Instructions: "Consider for patients with mobility concerns or fall risk",
		},
	}
}

// GetOtherAdmissionOrderSets returns all other admission order sets
func GetOtherAdmissionOrderSets() []*models.OrderSetTemplate {
	return []*models.OrderSetTemplate{
		GetAlcoholWithdrawalOrderSet(),
		GetGeneralMedicineOrderSet(),
	}
}

// GetAllAdmissionOrderSets returns all 15 admission order sets from all domains
func GetAllAdmissionOrderSets() []*models.OrderSetTemplate {
	allOrderSets := make([]*models.OrderSetTemplate, 0, 15)

	// Cardiac (3)
	allOrderSets = append(allOrderSets, GetCardiacAdmissionOrderSets()...)

	// Respiratory (2)
	allOrderSets = append(allOrderSets, GetRespiratoryAdmissionOrderSets()...)

	// Metabolic (2)
	allOrderSets = append(allOrderSets, GetMetabolicAdmissionOrderSets()...)

	// Neuro (2)
	allOrderSets = append(allOrderSets, GetNeuroAdmissionOrderSets()...)

	// GI (2)
	allOrderSets = append(allOrderSets, GetGIAdmissionOrderSets()...)

	// Infectious (2)
	allOrderSets = append(allOrderSets, GetInfectiousAdmissionOrderSets()...)

	// Other (2)
	allOrderSets = append(allOrderSets, GetOtherAdmissionOrderSets()...)

	return allOrderSets
}
