// Package ordersets provides emergency protocol order sets
package ordersets

import (
	"time"

	"kb-12-ordersets-careplans/internal/models"
)

// GetCodeBlueProtocol returns cardiac arrest (Code Blue) protocol
// Guidelines: AHA ACLS Guidelines 2020
func GetCodeBlueProtocol() *models.OrderSetTemplate {
	orders := []models.Order{
		// Immediate Actions
		{
			OrderID:      "CODE-IMMEDIATE-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "immediate_actions",
			Name:         "Activate Code Blue",
			Description:  "Call code team immediately",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     1,
			Instructions: "Call Code Blue (or overhead page). State location clearly. Assign roles: CPR, airway, IV/IO, medications, defibrillator, documentation.",
		},
		{
			OrderID:      "CODE-IMMEDIATE-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "immediate_actions",
			Name:         "Start High-Quality CPR",
			Description:  "Begin chest compressions immediately",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     2,
			Instructions: "Rate 100-120/min, depth ≥2 inches (5cm), full recoil. Minimize interruptions (<10 sec). Rotate compressors every 2 min.",
		},
		{
			OrderID:      "CODE-IMMEDIATE-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "immediate_actions",
			Name:         "Attach Defibrillator/AED",
			Description:  "Apply pads and analyze rhythm",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     3,
			Instructions: "Apply pads anterior-lateral OR anterior-posterior. Analyze rhythm. If VF/pVT: shock 200J biphasic (or AED). Resume CPR immediately after shock.",
		},
		{
			OrderID:      "CODE-IMMEDIATE-004",
			OrderType:    models.OrderTypeNursing,
			Category:     "immediate_actions",
			Name:         "Bag-Valve-Mask Ventilation",
			Description:  "Provide rescue breaths",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     4,
			Instructions: "30:2 compression:ventilation ratio until advanced airway. Connect to O2 at 15L/min. Visible chest rise with each breath.",
		},
		{
			OrderID:      "CODE-IMMEDIATE-005",
			OrderType:    models.OrderTypeNursing,
			Category:     "immediate_actions",
			Name:         "Establish IV/IO Access",
			Description:  "Vascular access for medications",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     5,
			Instructions: "Large bore IV (18G or larger). If no IV within 1-2 min, place IO (proximal tibia or humeral head). Do not delay for central line.",
		},

		// VF/pVT Algorithm
		{
			OrderID:      "CODE-VF-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "vf_pvt_algorithm",
			Name:         "Epinephrine (VF/pVT)",
			Description:  "Vasopressor for VF/pVT",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			DrugCode:     "3992",
			DrugName:     "Epinephrine",
			Dose:         "1 mg",
			DoseValue:    1,
			DoseUnit:     "mg",
			Route:        "IV/IO",
			Frequency:    "q3-5min",
			Instructions: "Give after 2nd shock (during CPR). Repeat every 3-5 minutes during arrest. Flush with 20mL NS and elevate extremity.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "3992", Display: "Epinephrine"},
			},
		},
		{
			OrderID:      "CODE-VF-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "vf_pvt_algorithm",
			Name:         "Amiodarone (VF/pVT)",
			Description:  "Antiarrhythmic for refractory VF/pVT",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			DrugCode:     "703",
			DrugName:     "Amiodarone",
			Dose:         "300 mg first dose, 150 mg second",
			DoseValue:    300,
			DoseUnit:     "mg",
			Route:        "IV/IO",
			Instructions: "Give after 3rd shock (during CPR). Second dose 150mg if refractory. Alternative: Lidocaine 1-1.5 mg/kg, then 0.5-0.75 mg/kg.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "703", Display: "Amiodarone"},
			},
		},

		// Asystole/PEA Algorithm
		{
			OrderID:      "CODE-ASYS-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "asystole_pea_algorithm",
			Name:         "Epinephrine (Asystole/PEA)",
			Description:  "Vasopressor for non-shockable rhythms",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			DrugCode:     "3992",
			DrugName:     "Epinephrine",
			Dose:         "1 mg",
			DoseValue:    1,
			DoseUnit:     "mg",
			Route:        "IV/IO",
			Frequency:    "q3-5min",
			Instructions: "Give as soon as IV/IO access. Repeat every 3-5 minutes. Consider reversible causes (Hs and Ts).",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "3992", Display: "Epinephrine"},
			},
		},
		{
			OrderID:      "CODE-ASYS-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "asystole_pea_algorithm",
			Name:         "Identify Reversible Causes (Hs and Ts)",
			Description:  "Treat underlying cause",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Hs: Hypoxia, Hypovolemia, H+ (acidosis), Hypo/Hyperkalemia, Hypothermia. Ts: Tension pneumothorax, Tamponade, Toxins, Thrombosis (PE/coronary).",
		},

		// Airway Management
		{
			OrderID:      "CODE-AIRWAY-001",
			OrderType:    models.OrderTypeProcedure,
			Category:     "airway_management",
			Name:         "Advanced Airway",
			Description:  "Endotracheal intubation or supraglottic",
			Priority:     models.PriorityUrgent,
			Required:     false,
			Selected:     true,
			Instructions: "Intubate when feasible without interrupting CPR >10 sec. LMA/King airway acceptable alternative. Once placed: continuous compressions, ventilate 10 breaths/min. Confirm with waveform capnography.",
		},
		{
			OrderID:      "CODE-AIRWAY-002",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "airway_management",
			Name:         "Waveform Capnography",
			Description:  "ETCO2 monitoring",
			Priority:     models.PriorityUrgent,
			Required:     true,
			Selected:     true,
			Instructions: "Attach ETCO2 to advanced airway. Target ETCO2 >10 mmHg (indicates adequate CPR). Sudden rise may indicate ROSC. Confirms ETT placement.",
		},

		// Post-ROSC Care
		{
			OrderID:      "CODE-ROSC-001",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "post_rosc",
			Name:         "Post-ROSC Vital Signs",
			Description:  "Continuous monitoring after ROSC",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Continuous ECG, SpO2, BP, ETCO2. Target SpO2 94-98% (avoid hyperoxia). Target SBP >90 or MAP >65.",
		},
		{
			OrderID:      "CODE-ROSC-002",
			OrderType:    models.OrderTypeLab,
			Category:     "post_rosc",
			Name:         "Post-ROSC Labs",
			Description:  "Metabolic assessment",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "arterial_panel",
			LabPanel:     "ABG, BMP, Lactate, Troponin",
			Specimen:     "blood",
			Instructions: "Check ABG, electrolytes, lactate, troponin, CBC. Correct acidosis and electrolyte abnormalities.",
		},
		{
			OrderID:      "CODE-ROSC-003",
			OrderType:    models.OrderTypeMedication,
			Category:     "post_rosc",
			Name:         "Epinephrine Infusion (Post-ROSC)",
			Description:  "Vasopressor support if hypotensive",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			DrugCode:     "3992",
			DrugName:     "Epinephrine",
			Dose:         "0.1-0.5 mcg/kg/min",
			Route:        "IV infusion",
			Instructions: "Start if MAP <65 despite fluids. Titrate to MAP 65-80. Alternative: Norepinephrine 0.1-0.5 mcg/kg/min.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "3992", Display: "Epinephrine"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "map", Operator: "lt", Value: "65"},
			},
		},
		{
			OrderID:      "CODE-ROSC-004",
			OrderType:    models.OrderTypeNursing,
			Category:     "post_rosc",
			Name:         "Targeted Temperature Management",
			Description:  "Post-arrest hypothermia protocol",
			Priority:     models.PriorityUrgent,
			Required:     true,
			Selected:     true,
			Instructions: "For comatose survivors: Target temperature 32-36°C for 24h. Prevent fever. Consider TTM protocol and neuro prognostication >72h.",
		},
		{
			OrderID:      "CODE-ROSC-005",
			OrderType:    models.OrderTypeImaging,
			Category:     "post_rosc",
			Name:         "12-Lead ECG",
			Description:  "Evaluate for STEMI",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Obtain immediately after ROSC. If STEMI: emergent cath. Consider cath for shockable rhythm without obvious non-cardiac cause.",
		},

		// Documentation
		{
			OrderID:      "CODE-DOC-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "documentation",
			Name:         "Code Documentation",
			Description:  "Real-time code documentation",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Designated recorder documents: arrest time, rhythm checks, shocks, medications (with times), CPR quality, ROSC or time of death. Use code sheet or electronic system.",
		},
	}

	timeConstraints := []models.TimeConstraint{
		{
			ConstraintID:   "CODE-TIME-001",
			Action:         "first_shock_vfpvt",
			Deadline:       3 * time.Minute,
			AlertThreshold: 2 * time.Minute,
			Severity:       "critical",
			Reference:      "AHA ACLS Guidelines",
			Description:    "Time to first defibrillation for VF/pVT",
		},
		{
			ConstraintID:   "CODE-TIME-002",
			Action:         "first_epinephrine_nonshockable",
			Deadline:       5 * time.Minute,
			AlertThreshold: 3 * time.Minute,
			Severity:       "critical",
			Reference:      "AHA ACLS Guidelines",
			Description:    "Time to first epinephrine for asystole/PEA",
		},
		{
			ConstraintID:   "CODE-TIME-003",
			Action:         "advanced_airway",
			Deadline:       10 * time.Minute,
			AlertThreshold: 7 * time.Minute,
			Severity:       "major",
			Reference:      "AHA ACLS Guidelines",
			Description:    "Time to advanced airway placement",
		},
	}

	return &models.OrderSetTemplate{
		TemplateID:      "EMERG-CODE-001",
		Category:        models.CategoryEmergency,
		Name:            "Code Blue - Cardiac Arrest",
		Version:         "2024.1",
		GuidelineSource: "AHA ACLS Guidelines 2020",
		Description:     "Cardiac arrest protocol with VF/pVT and asystole/PEA algorithms, post-ROSC care, and targeted temperature management",
		Orders:          orders,
		TimeConstraints: timeConstraints,
		Active:          true,
	}
}

// GetRapidResponseProtocol returns Rapid Response Team (RRT) protocol
// Guidelines: Institute for Healthcare Improvement, AHRQ Rapid Response
func GetRapidResponseProtocol() *models.OrderSetTemplate {
	orders := []models.Order{
		// Activation Criteria
		{
			OrderID:      "RRT-ACTIVATE-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "activation",
			Name:         "Rapid Response Activation Criteria",
			Description:  "Criteria for calling RRT",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Activate RRT for: Acute change in HR<40 or >130, RR<8 or >28, SBP<90, SpO2<90% on supplemental O2, acute mental status change, staff concern about patient condition.",
		},
		{
			OrderID:      "RRT-ACTIVATE-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "activation",
			Name:         "Activate Rapid Response Team",
			Description:  "Call RRT immediately",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     1,
			Instructions: "Call RRT number (or overhead page). State patient location. Stay with patient. Gather recent vitals and history for RRT arrival.",
		},

		// Immediate Assessment
		{
			OrderID:      "RRT-ASSESS-001",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "assessment",
			Name:         "Vital Signs and Monitoring",
			Description:  "Immediate vital sign assessment",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "VS q5min during RRT. Apply continuous pulse oximetry and cardiac monitor. Obtain ETCO2 if respiratory distress.",
		},
		{
			OrderID:      "RRT-ASSESS-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "assessment",
			Name:         "ABCDE Assessment",
			Description:  "Systematic clinical assessment",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Airway: Patent? Breathing: Rate, effort, SpO2. Circulation: Pulse, BP, perfusion. Disability: GCS, pupils. Exposure: Skin, temp, IV access.",
		},
		{
			OrderID:      "RRT-ASSESS-003",
			OrderType:    models.OrderTypeLab,
			Category:     "assessment",
			Name:         "Point-of-Care Testing",
			Description:  "Rapid labs at bedside",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "poc_panel",
			LabPanel:     "Glucose, ECG",
			Instructions: "Fingerstick glucose immediately. 12-lead ECG if cardiac concern. Consider i-STAT: lactate, BMP, blood gas.",
		},

		// Respiratory Interventions
		{
			OrderID:      "RRT-RESP-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "respiratory",
			Name:         "Supplemental Oxygen",
			Description:  "Oxygen for hypoxia",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Apply O2 to maintain SpO2 ≥94%. Start with nasal cannula 2-6L. If SpO2<90%: non-rebreather 15L or high-flow nasal cannula. Consider BiPAP/CPAP for respiratory distress.",
		},
		{
			OrderID:      "RRT-RESP-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "respiratory",
			Name:         "Albuterol Nebulizer",
			Description:  "Bronchodilator for wheezing/bronchospasm",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			DrugCode:     "435",
			DrugName:     "Albuterol",
			Dose:         "2.5 mg",
			Route:        "nebulizer",
			Frequency:    "q20min x 3",
			PRN:          true,
			PRNReason:    "wheezing or bronchospasm",
			Instructions: "Give if wheezing or known asthma/COPD exacerbation.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "435", Display: "Albuterol"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "wheezing", Operator: "eq", Value: "true"},
			},
		},

		// Cardiovascular Interventions
		{
			OrderID:      "RRT-CV-001",
			OrderType:    models.OrderTypeIVFluids,
			Category:     "cardiovascular",
			Name:         "IV Fluid Bolus",
			Description:  "Volume resuscitation for hypotension",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     true,
			DrugCode:     "313002",
			DrugName:     "Lactated Ringer's or Normal Saline",
			Dose:         "500-1000 mL",
			Route:        "IV bolus",
			Instructions: "Give 500mL bolus over 15-20 min for SBP<90 or signs of hypoperfusion. Reassess and repeat if needed. Use caution in CHF.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "313002", Display: "Lactated Ringer's"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "sbp", Operator: "lt", Value: "90"},
			},
		},
		{
			OrderID:      "RRT-CV-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "cardiovascular",
			Name:         "Atropine for Bradycardia",
			Description:  "Anticholinergic for symptomatic bradycardia",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			DrugCode:     "1202",
			DrugName:     "Atropine",
			Dose:         "0.5 mg",
			DoseValue:    0.5,
			DoseUnit:     "mg",
			Route:        "IV",
			Frequency:    "q3-5min",
			MaxDailyDose: "3 mg total",
			Instructions: "For symptomatic bradycardia (HR<50 with hypotension, AMS, chest pain). May repeat to max 3mg.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "1202", Display: "Atropine"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "hr", Operator: "lt", Value: "50"},
				{Type: "if", Field: "symptomatic", Operator: "eq", Value: "true"},
			},
		},

		// Metabolic Interventions
		{
			OrderID:      "RRT-METAB-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "metabolic",
			Name:         "Dextrose 50% for Hypoglycemia",
			Description:  "IV glucose for low blood sugar",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			DrugCode:     "4850",
			DrugName:     "Dextrose 50%",
			Dose:         "25-50 mL (12.5-25 g)",
			Route:        "IV",
			Instructions: "Give for glucose <70 mg/dL (especially if symptomatic or AMS). Recheck glucose in 15 min.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "4850", Display: "Dextrose"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "glucose", Operator: "lt", Value: "70", Unit: "mg/dL"},
			},
		},
		{
			OrderID:      "RRT-METAB-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "metabolic",
			Name:         "Naloxone for Opioid Overdose",
			Description:  "Opioid reversal agent",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			DrugCode:     "7242",
			DrugName:     "Naloxone",
			Dose:         "0.4-2 mg",
			Route:        "IV/IM/IN",
			Instructions: "For suspected opioid overdose (RR<12, pinpoint pupils, unresponsive). Start low (0.4mg IV) to avoid withdrawal. May repeat q2-3min.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "7242", Display: "Naloxone"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "opioid_overdose_suspected", Operator: "eq", Value: "true"},
			},
		},

		// Labs
		{
			OrderID:      "RRT-LAB-001",
			OrderType:    models.OrderTypeLab,
			Category:     "labs",
			Name:         "Stat Labs",
			Description:  "Comprehensive lab panel",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "stat_panel",
			LabPanel:     "CBC, CMP, Troponin, Lactate, ABG if resp distress",
			Specimen:     "blood",
			Instructions: "Draw stat labs. Add troponin if chest pain, lactate if sepsis concern, ABG if respiratory failure.",
		},

		// Disposition
		{
			OrderID:      "RRT-DISPO-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "disposition",
			Name:         "Level of Care Decision",
			Description:  "Determine appropriate level of care",
			Priority:     models.PriorityUrgent,
			Required:     true,
			Selected:     true,
			Instructions: "Assess need for: ICU transfer, telemetry upgrade, additional monitoring, specialist consultation. Document RRT assessment and disposition decision.",
		},
		{
			OrderID:      "RRT-DISPO-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "disposition",
			Name:         "Code Status Verification",
			Description:  "Verify resuscitation preferences",
			Priority:     models.PriorityUrgent,
			Required:     true,
			Selected:     true,
			Instructions: "Verify current code status. If not documented or if patient desires change, facilitate goals-of-care discussion.",
		},

		// Communication
		{
			OrderID:      "RRT-COMM-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "communication",
			Name:         "Notify Attending Physician",
			Description:  "Contact primary team",
			Priority:     models.PriorityUrgent,
			Required:     true,
			Selected:     true,
			Instructions: "Notify attending/primary team of RRT activation, findings, and interventions. Use SBAR format.",
		},
		{
			OrderID:      "RRT-COMM-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "communication",
			Name:         "RRT Documentation",
			Description:  "Document RRT encounter",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Complete RRT documentation: trigger, assessment findings, interventions, response, disposition, time stamps.",
		},
	}

	timeConstraints := []models.TimeConstraint{
		{
			ConstraintID:   "RRT-TIME-001",
			Action:         "rrt_team_response",
			Deadline:       5 * time.Minute,
			AlertThreshold: 3 * time.Minute,
			Severity:       "critical",
			Reference:      "IHI RRT Guidelines",
			Description:    "Time for RRT to arrive at bedside",
		},
		{
			ConstraintID:   "RRT-TIME-002",
			Action:         "initial_assessment",
			Deadline:       10 * time.Minute,
			AlertThreshold: 7 * time.Minute,
			Severity:       "major",
			Reference:      "IHI RRT Guidelines",
			Description:    "Time to complete initial ABCDE assessment",
		},
	}

	return &models.OrderSetTemplate{
		TemplateID:      "EMERG-RRT-001",
		Category:        models.CategoryEmergency,
		Name:            "Rapid Response Team (RRT)",
		Version:         "2024.1",
		GuidelineSource: "Institute for Healthcare Improvement, AHRQ Rapid Response Guidelines",
		Description:     "Rapid Response Team activation and assessment protocol for acute clinical deterioration",
		Orders:          orders,
		TimeConstraints: timeConstraints,
		Active:          true,
	}
}

// GetMalignantHyperthermiaProtocol returns MH crisis protocol
// Guidelines: MHAUS (Malignant Hyperthermia Association of the United States)
func GetMalignantHyperthermiaProtocol() *models.OrderSetTemplate {
	orders := []models.Order{
		// Immediate Actions
		{
			OrderID:      "MH-IMMEDIATE-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "immediate_actions",
			Name:         "Call for Help and MH Cart",
			Description:  "Activate MH response",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     1,
			Instructions: "Call for help. Get MH cart (contains dantrolene). Call MHAUS hotline: 1-800-644-9737. Assign roles: mixing dantrolene, cooling, labs, documentation.",
		},
		{
			OrderID:      "MH-IMMEDIATE-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "immediate_actions",
			Name:         "Stop All Triggers",
			Description:  "Discontinue triggering agents",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     2,
			Instructions: "STOP all volatile anesthetics (sevo, des, iso) and succinylcholine immediately. Do NOT delay dantrolene to change anesthesia circuit. May continue IV anesthetics (propofol, opioids, non-depolarizing NMB).",
		},
		{
			OrderID:      "MH-IMMEDIATE-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "immediate_actions",
			Name:         "Hyperventilate with 100% O2",
			Description:  "High-flow oxygen and hyperventilation",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     3,
			Instructions: "100% FiO2 at high fresh gas flows (10-15 L/min). Hyperventilate to lower ETCO2 (target 35-40). May use charcoal filters on circuit if available.",
		},

		// Dantrolene Administration
		{
			OrderID:      "MH-DANT-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "dantrolene",
			Name:         "Dantrolene Sodium",
			Description:  "Specific MH treatment",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			DrugCode:     "3105",
			DrugName:     "Dantrolene",
			Dose:         "2.5 mg/kg initial, repeat q5min PRN",
			DoseValue:    2.5,
			DoseUnit:     "mg/kg",
			Route:        "IV",
			Instructions: "CRITICAL: Give 2.5 mg/kg IV push. Repeat every 5-10 min until symptoms resolve. May need 10+ mg/kg total. Mix each 20mg vial with 60mL sterile water. Multiple staff needed to mix rapidly.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "3105", Display: "Dantrolene"},
			},
			Notes: "Ryanodex (250mg/vial) requires only 5mL diluent - faster to prepare if available.",
		},

		// Cooling Measures
		{
			OrderID:      "MH-COOL-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "cooling",
			Name:         "Active Cooling",
			Description:  "Aggressive temperature reduction",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Target temp <38.5°C. Use: Cold IV saline (not LR - K+ concern), ice packs to axilla/groin/neck, cooling blanket, cold lavage (gastric, bladder, rectal if severe). STOP cooling at 38.5°C to prevent overshoot hypothermia.",
		},
		{
			OrderID:      "MH-COOL-002",
			OrderType:    models.OrderTypeIVFluids,
			Category:     "cooling",
			Name:         "Cold Normal Saline",
			Description:  "IV cooling",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			DrugCode:     "8591",
			DrugName:     "Normal Saline (cold/iced)",
			Dose:         "boluses",
			Route:        "IV",
			Instructions: "Infuse cold (4°C) NS rapidly. Avoid LR (contains potassium). Monitor for fluid overload.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "8591", Display: "Sodium Chloride 0.9%"},
			},
		},

		// Metabolic Management
		{
			OrderID:      "MH-METAB-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "metabolic",
			Name:         "Treat Hyperkalemia",
			Description:  "Potassium management",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     true,
			Instructions: "For K+ >6.0: Calcium gluconate 30mg/kg (or CaCl 10mg/kg) for cardiac protection. Regular insulin 0.1 U/kg + glucose 0.5g/kg. Sodium bicarbonate 1-2 mEq/kg. Consider furosemide or dialysis.",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "potassium", Operator: "gt", Value: "6.0", Unit: "mEq/L"},
			},
		},
		{
			OrderID:      "MH-METAB-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "metabolic",
			Name:         "Sodium Bicarbonate",
			Description:  "Treat metabolic acidosis",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     true,
			DrugCode:     "9154",
			DrugName:     "Sodium Bicarbonate",
			Dose:         "1-2 mEq/kg",
			Route:        "IV",
			Instructions: "For severe acidosis (pH <7.2, base deficit >10). Hyperventilation is primary treatment.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "9154", Display: "Sodium Bicarbonate"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "ph", Operator: "lt", Value: "7.2"},
			},
		},

		// Arrhythmia Management
		{
			OrderID:      "MH-ARR-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "arrhythmia",
			Name:         "Arrhythmia Treatment",
			Description:  "Avoid calcium channel blockers",
			Priority:     models.PriorityUrgent,
			Required:     false,
			Selected:     true,
			Instructions: "For arrhythmias: Use amiodarone, lidocaine, or beta-blockers. AVOID calcium channel blockers (interaction with dantrolene causes hyperkalemia and cardiovascular collapse).",
		},

		// Monitoring
		{
			OrderID:      "MH-MONITOR-001",
			OrderType:    models.OrderTypeLab,
			Category:     "monitoring",
			Name:         "Frequent Labs",
			Description:  "Serial metabolic monitoring",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "mh_panel",
			LabPanel:     "ABG, K+, Ca++, Lactate, CK, Myoglobin",
			Specimen:     "blood",
			Timing:       "q10min_until_stable",
			Instructions: "Check ABG, electrolytes, lactate q10-15 min during crisis. CK peaks at 12-24h (can be >100,000). Monitor urine for myoglobinuria.",
		},
		{
			OrderID:      "MH-MONITOR-002",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "monitoring",
			Name:         "Core Temperature",
			Description:  "Continuous temperature monitoring",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Continuous core temperature (esophageal, rectal, or bladder). Document trend. Hyperthermia >40°C is ominous.",
		},
		{
			OrderID:      "MH-MONITOR-003",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "monitoring",
			Name:         "Urine Output",
			Description:  "Monitor for myoglobinuria",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Insert Foley. Monitor for dark urine (myoglobin). Target UOP >2 mL/kg/hr to prevent renal failure. May need mannitol or furosemide.",
		},

		// Post-Crisis Care
		{
			OrderID:      "MH-POST-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "post_crisis",
			Name:         "Dantrolene Continuation",
			Description:  "Prevent MH recurrence",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "3105",
			DrugName:     "Dantrolene",
			Dose:         "1 mg/kg",
			Route:        "IV",
			Frequency:    "q4-6h",
			Duration:     "24-48_hours",
			Instructions: "Continue dantrolene 1 mg/kg IV q4-6h for 24-48 hours. MH can recur in 25% of cases.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "3105", Display: "Dantrolene"},
			},
		},
		{
			OrderID:      "MH-POST-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "post_crisis",
			Name:         "ICU Monitoring",
			Description:  "ICU admission for observation",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Transfer to ICU for minimum 24-48h monitoring. Watch for: recurrence, DIC, rhabdomyolysis, renal failure. Serial CK, coags, renal function.",
		},
		{
			OrderID:      "MH-POST-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "post_crisis",
			Name:         "Family Notification and Testing",
			Description:  "Genetic counseling referral",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Notify family of MH susceptibility. Refer to MH testing center for muscle biopsy (CHCT) or genetic testing. Patient and family should carry MH alert card.",
		},
	}

	timeConstraints := []models.TimeConstraint{
		{
			ConstraintID:   "MH-TIME-001",
			Action:         "stop_triggers",
			Deadline:       1 * time.Minute,
			AlertThreshold: 30 * time.Second,
			Severity:       "critical",
			Reference:      "MHAUS Guidelines",
			Description:    "Immediately stop all triggering agents",
		},
		{
			ConstraintID:   "MH-TIME-002",
			Action:         "first_dantrolene",
			Deadline:       5 * time.Minute,
			AlertThreshold: 3 * time.Minute,
			Severity:       "critical",
			Reference:      "MHAUS Guidelines",
			Description:    "Time to first dantrolene dose",
		},
	}

	return &models.OrderSetTemplate{
		TemplateID:      "EMERG-MH-001",
		Category:        models.CategoryEmergency,
		Name:            "Malignant Hyperthermia Crisis",
		Version:         "2024.1",
		GuidelineSource: "MHAUS (Malignant Hyperthermia Association of the United States)",
		Description:     "Emergency protocol for malignant hyperthermia crisis including dantrolene dosing, cooling, and metabolic management",
		Orders:          orders,
		TimeConstraints: timeConstraints,
		Active:          true,
	}
}

// GetAnaphylaxisProtocol returns anaphylaxis emergency protocol
// Guidelines: World Allergy Organization (WAO), ACAAI/AAAAI Anaphylaxis Guidelines
func GetAnaphylaxisProtocol() *models.OrderSetTemplate {
	orders := []models.Order{
		// Immediate Actions
		{
			OrderID:      "ANAPH-IMMEDIATE-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "immediate_actions",
			Name:         "Call for Help",
			Description:  "Activate emergency response",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     1,
			Instructions: "Call code/RRT if severe. If outpatient: call 911. Assign roles. Prepare epinephrine immediately.",
		},
		{
			OrderID:      "ANAPH-IMMEDIATE-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "immediate_actions",
			Name:         "Remove Trigger if Possible",
			Description:  "Stop antigen exposure",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     2,
			Instructions: "Stop IV medications/transfusions. Remove stinger if insect sting. Do NOT induce vomiting if ingested.",
		},
		{
			OrderID:      "ANAPH-IMMEDIATE-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "immediate_actions",
			Name:         "Position Patient",
			Description:  "Optimize perfusion",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     3,
			Instructions: "Lay flat with legs elevated (if tolerated). If respiratory distress: allow to sit up. If vomiting/pregnant: left lateral position. Do NOT let stand suddenly.",
		},

		// Epinephrine
		{
			OrderID:      "ANAPH-EPI-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "epinephrine",
			Name:         "Epinephrine IM (FIRST LINE)",
			Description:  "Epinephrine intramuscular - FIRST AND MOST IMPORTANT",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			DrugCode:     "3992",
			DrugName:     "Epinephrine 1:1000 (1 mg/mL)",
			Dose:         "0.3-0.5 mg (adults), 0.01 mg/kg (peds, max 0.3 mg)",
			DoseValue:    0.5,
			DoseUnit:     "mg",
			Route:        "IM (mid-outer thigh)",
			Instructions: "Give IMMEDIATELY. Adult: 0.3-0.5 mg IM (use 0.3-0.5 mL of 1:1000). May repeat q5-15min if no improvement. Anterolateral thigh preferred (fastest absorption).",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "3992", Display: "Epinephrine"},
			},
			Notes: "Do NOT delay epinephrine for other treatments. IM route preferred (IV only for refractory hypotension).",
		},
		{
			OrderID:      "ANAPH-EPI-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "epinephrine",
			Name:         "Epinephrine IV (Refractory)",
			Description:  "IV epinephrine for refractory anaphylaxis",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			DrugCode:     "3992",
			DrugName:     "Epinephrine 1:10,000",
			Dose:         "0.1-0.2 mg slow push or infusion",
			Route:        "IV",
			Instructions: "Only if refractory to IM epinephrine and IV access. Dilute 1mg in 100mL NS (10 mcg/mL), give 1-2 mL/min, titrate to effect. Monitor closely for arrhythmia.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "3992", Display: "Epinephrine"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "refractory_to_im", Operator: "eq", Value: "true"},
			},
		},

		// Airway and Oxygen
		{
			OrderID:      "ANAPH-AIRWAY-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "airway",
			Name:         "Supplemental Oxygen",
			Description:  "High-flow oxygen",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "High-flow O2 via face mask or non-rebreather. Prepare for airway intervention if stridor or impending obstruction.",
		},
		{
			OrderID:      "ANAPH-AIRWAY-002",
			OrderType:    models.OrderTypeProcedure,
			Category:     "airway",
			Name:         "Advanced Airway if Needed",
			Description:  "Intubation for upper airway edema",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			Instructions: "Early intubation if stridor, voice changes, or tongue swelling. May be difficult airway - have surgical airway backup. Avoid laryngeal manipulation if possible.",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "stridor", Operator: "eq", Value: "true"},
				{Type: "if", Field: "tongue_swelling", Operator: "eq", Value: "true"},
			},
		},

		// IV Fluids
		{
			OrderID:      "ANAPH-IVF-001",
			OrderType:    models.OrderTypeIVFluids,
			Category:     "fluids",
			Name:         "Large Volume Crystalloid",
			Description:  "Aggressive fluid resuscitation",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			DrugCode:     "8591",
			DrugName:     "Normal Saline",
			Dose:         "1-2 L (adult), 20 mL/kg (peds)",
			Route:        "IV rapid infusion",
			Instructions: "Large bore IV access (two if possible). Give 1-2L NS rapidly for hypotension. Patients may need 5-10L in severe anaphylaxis due to third-spacing.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "8591", Display: "Normal Saline"},
			},
		},

		// Second-Line Medications
		{
			OrderID:      "ANAPH-SECOND-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "second_line",
			Name:         "Diphenhydramine (H1 blocker)",
			Description:  "Antihistamine for hives/itching",
			Priority:     models.PriorityUrgent,
			Required:     false,
			Selected:     true,
			DrugCode:     "3498",
			DrugName:     "Diphenhydramine",
			Dose:         "25-50 mg",
			DoseValue:    50,
			DoseUnit:     "mg",
			Route:        "IV/IM",
			Instructions: "Adjunct for urticaria and pruritus. Does NOT replace epinephrine. IV preferred for faster onset.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "3498", Display: "Diphenhydramine"},
			},
			Notes: "Antihistamines are adjuncts only - never delay epinephrine to give antihistamines.",
		},
		{
			OrderID:      "ANAPH-SECOND-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "second_line",
			Name:         "Famotidine (H2 blocker)",
			Description:  "H2 antihistamine adjunct",
			Priority:     models.PriorityUrgent,
			Required:     false,
			Selected:     true,
			DrugCode:     "4278",
			DrugName:     "Famotidine",
			Dose:         "20 mg",
			DoseValue:    20,
			DoseUnit:     "mg",
			Route:        "IV",
			Instructions: "Adjunct to H1 blocker. May help with GI symptoms. Give slow IV push.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "4278", Display: "Famotidine"},
			},
		},
		{
			OrderID:      "ANAPH-SECOND-003",
			OrderType:    models.OrderTypeMedication,
			Category:     "second_line",
			Name:         "Methylprednisolone",
			Description:  "Corticosteroid for biphasic prevention",
			Priority:     models.PriorityUrgent,
			Required:     false,
			Selected:     true,
			DrugCode:     "6902",
			DrugName:     "Methylprednisolone",
			Dose:         "125 mg (or 1-2 mg/kg)",
			DoseValue:    125,
			DoseUnit:     "mg",
			Route:        "IV",
			Instructions: "Does NOT help acute symptoms. May prevent biphasic reaction (occurs in 1-20% within 1-72h). Alternative: Prednisone 50mg PO.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "6902", Display: "Methylprednisolone"},
			},
		},

		// Bronchospasm Treatment
		{
			OrderID:      "ANAPH-BRONCH-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "bronchospasm",
			Name:         "Albuterol Nebulizer",
			Description:  "Beta-agonist for bronchospasm",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     true,
			DrugCode:     "435",
			DrugName:     "Albuterol",
			Dose:         "2.5-5 mg",
			Route:        "nebulizer",
			Frequency:    "continuous or q20min",
			Instructions: "For bronchospasm refractory to epinephrine. May give continuous nebulization if severe.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "435", Display: "Albuterol"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "wheezing", Operator: "eq", Value: "true"},
			},
		},

		// Refractory Hypotension
		{
			OrderID:      "ANAPH-VASO-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "vasopressors",
			Name:         "Vasopressin Infusion",
			Description:  "For catecholamine-resistant shock",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			DrugCode:     "11149",
			DrugName:     "Vasopressin",
			Dose:         "0.01-0.04 units/min",
			Route:        "IV infusion",
			Instructions: "For hypotension refractory to epinephrine and fluids. Alternative: norepinephrine infusion.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "11149", Display: "Vasopressin"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "refractory_hypotension", Operator: "eq", Value: "true"},
			},
		},
		{
			OrderID:      "ANAPH-VASO-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "vasopressors",
			Name:         "Glucagon (for beta-blocker patients)",
			Description:  "Bypass beta-blockade",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			DrugCode:     "4833",
			DrugName:     "Glucagon",
			Dose:         "1-5 mg IV over 5 min, then infusion 5-15 mcg/min",
			Route:        "IV",
			Instructions: "For patients on beta-blockers who are refractory to epinephrine. Glucagon bypasses beta-receptor blockade.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "4833", Display: "Glucagon"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "on_beta_blocker", Operator: "eq", Value: "true"},
				{Type: "if", Field: "refractory_to_epinephrine", Operator: "eq", Value: "true"},
			},
		},

		// Monitoring
		{
			OrderID:      "ANAPH-MON-001",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "monitoring",
			Name:         "Continuous Monitoring",
			Description:  "Close observation",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Continuous: ECG, SpO2, BP. Frequent reassessment of airway, breathing, skin, mental status. Document response to treatment.",
		},
		{
			OrderID:      "ANAPH-MON-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "monitoring",
			Name:         "Observation Period",
			Description:  "Watch for biphasic reaction",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Observe 4-8 hours minimum (up to 24h if severe or history of biphasic reactions). Biphasic reactions occur in 1-20% of cases, typically within 1-72 hours.",
		},

		// Discharge
		{
			OrderID:      "ANAPH-DC-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "discharge",
			Name:         "Epinephrine Auto-injector Prescription",
			Description:  "EpiPen for future emergencies",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "310120",
			DrugName:     "Epinephrine Auto-injector",
			Dose:         "0.3 mg (adult) or 0.15 mg (child <30kg)",
			Instructions: "Prescribe 2 auto-injectors. Teach proper use. Carry at all times. Use immediately for symptoms, then call 911.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "310120", Display: "Epinephrine Auto-injector"},
			},
		},
		{
			OrderID:      "ANAPH-DC-002",
			OrderType:    models.OrderTypeConsult,
			Category:     "discharge",
			Name:         "Allergy/Immunology Referral",
			Description:  "Follow-up for trigger identification",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Specialty:    "Allergy/Immunology",
			Reason:       "Anaphylaxis - trigger identification and management plan",
			Urgency:      "routine",
			Instructions: "Refer for comprehensive evaluation, skin/IgE testing, and action plan development.",
		},
		{
			OrderID:      "ANAPH-DC-003",
			OrderType:    models.OrderTypeEducation,
			Category:     "discharge",
			Name:         "Anaphylaxis Education",
			Description:  "Patient education materials",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Educate on: trigger avoidance, early recognition of symptoms, EpiPen use, calling 911 even after EpiPen use, medical alert bracelet, written action plan.",
		},
	}

	timeConstraints := []models.TimeConstraint{
		{
			ConstraintID:   "ANAPH-TIME-001",
			Action:         "first_epinephrine",
			Deadline:       5 * time.Minute,
			AlertThreshold: 2 * time.Minute,
			Severity:       "critical",
			Reference:      "WAO/AAAAI Guidelines",
			Description:    "Time to first epinephrine dose from symptom recognition",
		},
	}

	return &models.OrderSetTemplate{
		TemplateID:      "EMERG-ANAPH-001",
		Category:        models.CategoryEmergency,
		Name:            "Anaphylaxis",
		Version:         "2024.1",
		GuidelineSource: "WAO Anaphylaxis Guidelines 2020, ACAAI/AAAAI Guidelines",
		Description:     "Emergency anaphylaxis protocol with epinephrine as first-line treatment, adjunct therapies, and discharge planning",
		Orders:          orders,
		TimeConstraints: timeConstraints,
		Active:          true,
	}
}

// GetSepsisProtocol returns SEP-1 Sepsis Bundle protocol
// Guidelines: CMS SEP-1 Core Measure, Surviving Sepsis Campaign 2021
func GetSepsisProtocol() *models.OrderSetTemplate {
	orders := []models.Order{
		// Hour-1 Bundle - Recognition and Initial Labs
		{
			OrderID:      "SEPSIS-RECOG-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "recognition",
			Name:         "Sepsis Recognition and Activation",
			Description:  "Identify sepsis and activate bundle",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     1,
			Instructions: "Criteria: Suspected/confirmed infection + ≥2 SIRS criteria (Temp >38°C or <36°C, HR >90, RR >20 or PaCO2 <32, WBC >12K or <4K). Document time zero. Notify physician. Activate sepsis bundle.",
		},
		{
			OrderID:      "SEPSIS-LAB-001",
			OrderType:    models.OrderTypeLab,
			Category:     "hour1_bundle",
			Name:         "Serum Lactate",
			Description:  "Initial lactate level",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     2,
			LabCode:      "lactate",
			LabPanel:     "Lactate",
			Specimen:     "blood",
			Instructions: "Draw within 3 hours of sepsis recognition. If initial lactate >2 mmol/L, repeat in 2-6 hours to assess clearance. Critical: >4 mmol/L indicates septic shock.",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "2524-7", Display: "Lactate [Moles/volume] in Serum or Plasma"},
			},
		},
		{
			OrderID:      "SEPSIS-LAB-002",
			OrderType:    models.OrderTypeLab,
			Category:     "hour1_bundle",
			Name:         "Blood Cultures x 2",
			Description:  "Blood cultures before antibiotics",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     3,
			LabCode:      "blood_culture",
			LabPanel:     "Blood Culture x 2 sets",
			Specimen:     "blood",
			Instructions: "CRITICAL: Obtain BEFORE antibiotics if possible without delaying antibiotics >45 min. Two sets from different sites. Do NOT delay antibiotics waiting for cultures.",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "600-7", Display: "Blood culture"},
			},
		},
		{
			OrderID:      "SEPSIS-LAB-003",
			OrderType:    models.OrderTypeLab,
			Category:     "hour1_bundle",
			Name:         "Comprehensive Labs",
			Description:  "Complete sepsis workup",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "sepsis_panel",
			LabPanel:     "CBC, CMP, Coags, Procalcitonin",
			Specimen:     "blood",
			Instructions: "Include: CBC with diff, CMP, PT/INR, PTT, Procalcitonin. Add ABG if respiratory distress.",
		},

		// Hour-1 Bundle - Antibiotics
		{
			OrderID:      "SEPSIS-ABX-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "hour1_bundle",
			Name:         "Broad-Spectrum Antibiotics",
			Description:  "Empiric antibiotic therapy",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     4,
			Instructions: "Give within 3 hours of sepsis recognition (1 hour if septic shock). Coverage: Community-acquired: Ceftriaxone 2g + Azithromycin 500mg. Hospital-acquired: Piperacillin-tazobactam 4.5g or Meropenem 1g. Add Vancomycin 25-30 mg/kg if MRSA risk. Adjust for source and local antibiogram.",
			Notes:        "Do NOT delay antibiotics for cultures >45 min. Every hour delay in antibiotics increases mortality 7-8%.",
		},
		{
			OrderID:      "SEPSIS-ABX-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "antibiotics",
			Name:         "Piperacillin-Tazobactam",
			Description:  "Broad-spectrum beta-lactam",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     true,
			DrugCode:     "139462",
			DrugName:     "Piperacillin-Tazobactam",
			Dose:         "4.5 g",
			DoseValue:    4.5,
			DoseUnit:     "g",
			Route:        "IV",
			Frequency:    "q6h or extended infusion",
			Instructions: "Standard dosing: 4.5g IV q6h. Extended infusion preferred: 4.5g IV over 4 hours q8h. Adjust for renal function.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "139462", Display: "Piperacillin-Tazobactam"},
			},
		},
		{
			OrderID:      "SEPSIS-ABX-003",
			OrderType:    models.OrderTypeMedication,
			Category:     "antibiotics",
			Name:         "Vancomycin",
			Description:  "MRSA coverage",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     true,
			DrugCode:     "11124",
			DrugName:     "Vancomycin",
			Dose:         "25-30 mg/kg loading",
			Route:        "IV",
			Instructions: "Loading dose: 25-30 mg/kg IV (actual body weight, max 3g). Maintenance: 15-20 mg/kg q8-12h. Target trough 15-20 mcg/mL for severe infections. Consider level-based dosing.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "11124", Display: "Vancomycin"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "mrsa_risk", Operator: "eq", Value: "true"},
			},
		},

		// Hour-1 Bundle - Fluid Resuscitation
		{
			OrderID:      "SEPSIS-FLUID-001",
			OrderType:    models.OrderTypeIVFluids,
			Category:     "hour1_bundle",
			Name:         "Crystalloid Bolus (30 mL/kg)",
			Description:  "Initial fluid resuscitation",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     5,
			DrugCode:     "313002",
			DrugName:     "Lactated Ringer's or Normal Saline",
			Dose:         "30 mL/kg",
			Route:        "IV rapid infusion",
			Instructions: "CRITICAL for hypotension (SBP <90 or MAP <65) or lactate ≥4: Give 30 mL/kg crystalloid within 3 hours. For 70kg patient = 2100 mL. Reassess volume status with passive leg raise, pulse pressure variation, or POCUS.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "313002", Display: "Lactated Ringer's"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "sbp", Operator: "lt", Value: "90"},
				{Type: "if", Field: "lactate", Operator: "gte", Value: "4", Unit: "mmol/L"},
			},
		},

		// Vasopressors
		{
			OrderID:      "SEPSIS-VASO-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "vasopressors",
			Name:         "Norepinephrine Infusion",
			Description:  "First-line vasopressor",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     true,
			DrugCode:     "7512",
			DrugName:     "Norepinephrine",
			Dose:         "0.1-2 mcg/kg/min",
			Route:        "IV infusion (central line preferred)",
			Instructions: "Start if MAP <65 despite fluid resuscitation. First-line vasopressor per SSC guidelines. Start 0.1 mcg/kg/min, titrate to MAP ≥65. Central line preferred but may start peripheral temporarily. Max 2 mcg/kg/min.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "7512", Display: "Norepinephrine"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "map", Operator: "lt", Value: "65"},
				{Type: "if", Field: "fluid_responsive", Operator: "eq", Value: "false"},
			},
		},
		{
			OrderID:      "SEPSIS-VASO-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "vasopressors",
			Name:         "Vasopressin",
			Description:  "Second-line vasopressor",
			Priority:     models.PriorityUrgent,
			Required:     false,
			Selected:     false,
			DrugCode:     "11149",
			DrugName:     "Vasopressin",
			Dose:         "0.03 units/min (fixed dose)",
			Route:        "IV infusion",
			Instructions: "Add if norepinephrine ≥0.5 mcg/kg/min. Fixed dose 0.03 units/min (do not titrate). May reduce norepinephrine requirement. Alternative: Epinephrine as second agent.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "11149", Display: "Vasopressin"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "norepinephrine_dose", Operator: "gte", Value: "0.5", Unit: "mcg/kg/min"},
			},
		},

		// Corticosteroids
		{
			OrderID:      "SEPSIS-STEROID-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "adjuncts",
			Name:         "Hydrocortisone (Refractory Shock)",
			Description:  "Stress-dose steroids",
			Priority:     models.PriorityUrgent,
			Required:     false,
			Selected:     false,
			DrugCode:     "5492",
			DrugName:     "Hydrocortisone",
			Dose:         "200 mg/day (50 mg q6h or 200 mg infusion)",
			Route:        "IV",
			Instructions: "Consider if vasopressor requirements escalating despite fluids and 2 vasopressors. Give hydrocortisone 50 mg IV q6h or 200 mg/day continuous infusion. Taper as vasopressors weaned.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "5492", Display: "Hydrocortisone"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "refractory_shock", Operator: "eq", Value: "true"},
			},
		},

		// Source Control
		{
			OrderID:      "SEPSIS-SOURCE-001",
			OrderType:    models.OrderTypeConsult,
			Category:     "source_control",
			Name:         "Source Control Evaluation",
			Description:  "Identify and address infection source",
			Priority:     models.PriorityUrgent,
			Required:     true,
			Selected:     true,
			Specialty:    "Surgery/IR/Infectious Disease as appropriate",
			Reason:       "Sepsis source control evaluation",
			Instructions: "Identify source: lungs (CXR, CT), abdomen (CT), urinary (UA, culture), lines (remove if suspected), soft tissue (exam, imaging). Consult surgery/IR for drainage of abscess, debridement, or line removal.",
		},

		// Monitoring
		{
			OrderID:      "SEPSIS-MONITOR-001",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "monitoring",
			Name:         "Hemodynamic Monitoring",
			Description:  "Continuous monitoring",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Continuous: ECG, SpO2, arterial line for BP if on vasopressors. Hourly: UOP (target ≥0.5 mL/kg/hr), lactate clearance, mental status. Consider CVP, ScvO2 if available. POCUS for volume assessment.",
		},
		{
			OrderID:      "SEPSIS-MONITOR-002",
			OrderType:    models.OrderTypeLab,
			Category:     "monitoring",
			Name:         "Repeat Lactate",
			Description:  "Lactate reassessment",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "lactate_repeat",
			LabPanel:     "Lactate",
			Timing:       "q2-6h",
			Instructions: "If initial lactate >2 mmol/L: repeat within 2-6 hours. Target: >10% clearance. Persistent elevation indicates inadequate resuscitation or ongoing tissue hypoperfusion.",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "2524-7", Display: "Lactate"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "initial_lactate", Operator: "gt", Value: "2", Unit: "mmol/L"},
			},
		},

		// ICU Transfer
		{
			OrderID:      "SEPSIS-DISPO-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "disposition",
			Name:         "ICU Transfer",
			Description:  "Higher level of care",
			Priority:     models.PriorityUrgent,
			Required:     true,
			Selected:     true,
			Instructions: "ICU admission if: vasopressor requirement, lactate ≥4, respiratory failure, AMS, or organ dysfunction. Consider step-down for stable patients meeting sepsis criteria without shock.",
		},
	}

	timeConstraints := []models.TimeConstraint{
		{
			ConstraintID:   "SEPSIS-TIME-001",
			Action:         "lactate_measurement",
			Deadline:       3 * time.Hour,
			AlertThreshold: 1 * time.Hour,
			Severity:       "critical",
			Reference:      "CMS SEP-1 Core Measure",
			Description:    "Initial lactate within 3 hours of sepsis recognition",
		},
		{
			ConstraintID:   "SEPSIS-TIME-002",
			Action:         "blood_cultures",
			Deadline:       3 * time.Hour,
			AlertThreshold: 30 * time.Minute,
			Severity:       "critical",
			Reference:      "CMS SEP-1 Core Measure",
			Description:    "Blood cultures before antibiotics (ideally within 45 min)",
		},
		{
			ConstraintID:   "SEPSIS-TIME-003",
			Action:         "broad_spectrum_antibiotics",
			Deadline:       3 * time.Hour,
			AlertThreshold: 1 * time.Hour,
			Severity:       "critical",
			Reference:      "CMS SEP-1 / Surviving Sepsis Campaign",
			Description:    "Broad-spectrum antibiotics within 3 hours (1 hour if septic shock)",
		},
		{
			ConstraintID:   "SEPSIS-TIME-004",
			Action:         "fluid_resuscitation",
			Deadline:       3 * time.Hour,
			AlertThreshold: 1 * time.Hour,
			Severity:       "critical",
			Reference:      "CMS SEP-1 Core Measure",
			Description:    "30 mL/kg crystalloid within 3 hours if hypotensive or lactate ≥4",
		},
		{
			ConstraintID:   "SEPSIS-TIME-005",
			Action:         "repeat_lactate",
			Deadline:       6 * time.Hour,
			AlertThreshold: 4 * time.Hour,
			Severity:       "major",
			Reference:      "CMS SEP-1 Core Measure",
			Description:    "Repeat lactate within 6 hours if initial >2 mmol/L",
		},
		{
			ConstraintID:   "SEPSIS-TIME-006",
			Action:         "vasopressor_initiation",
			Deadline:       6 * time.Hour,
			AlertThreshold: 3 * time.Hour,
			Severity:       "critical",
			Reference:      "CMS SEP-1 Core Measure",
			Description:    "Vasopressors if hypotension persists after fluid challenge",
		},
	}

	return &models.OrderSetTemplate{
		TemplateID:      "OS-EM-002",
		Category:        models.CategoryEmergency,
		Name:            "Sepsis / Severe Sepsis / Septic Shock (SEP-1 Bundle)",
		Version:         "2024.1",
		GuidelineSource: "CMS SEP-1 Core Measure, Surviving Sepsis Campaign 2021",
		Description:     "Comprehensive sepsis bundle including Hour-1 interventions (lactate, cultures, antibiotics, fluids), vasopressors, source control, and monitoring per CMS quality measures",
		Orders:          orders,
		TimeConstraints: timeConstraints,
		Active:          true,
	}
}

// GetStrokeProtocol returns Acute Ischemic Stroke protocol
// Guidelines: AHA/ASA Stroke Guidelines 2019, with 2021 updates
func GetStrokeProtocol() *models.OrderSetTemplate {
	orders := []models.Order{
		// Immediate Assessment
		{
			OrderID:      "STROKE-ASSESS-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "immediate_assessment",
			Name:         "Stroke Alert Activation",
			Description:  "Activate stroke team",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     1,
			Instructions: "Call Stroke Alert. Document 'last known well' time. Assign roles. Prepare for CT. Target: door-to-CT <25 min, door-to-needle <60 min.",
		},
		{
			OrderID:      "STROKE-ASSESS-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "immediate_assessment",
			Name:         "NIHSS Assessment",
			Description:  "NIH Stroke Scale scoring",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     2,
			Instructions: "Complete NIHSS immediately. Score 0-42. Repeat NIHSS: at 24h, if any neurological change, before/after interventions. Document baseline deficits carefully.",
		},
		{
			OrderID:      "STROKE-ASSESS-003",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "immediate_assessment",
			Name:         "Vital Signs and Monitoring",
			Description:  "Continuous neuro monitoring",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Continuous: ECG, SpO2, BP. Neuro checks q15min x 2h, then q30min x 6h, then q1h. Head of bed flat (if no aspiration risk). NPO until swallow evaluation.",
		},

		// Imaging
		{
			OrderID:      "STROKE-IMG-001",
			OrderType:    models.OrderTypeImaging,
			Category:     "imaging",
			Name:         "Non-contrast Head CT",
			Description:  "Emergent CT to rule out hemorrhage",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     3,
			Instructions: "CRITICAL: Obtain immediately to rule out hemorrhage before tPA. Target: door-to-CT <25 min. Do NOT delay for labs except fingerstick glucose.",
		},
		{
			OrderID:      "STROKE-IMG-002",
			OrderType:    models.OrderTypeImaging,
			Category:     "imaging",
			Name:         "CT Angiography (Head/Neck)",
			Description:  "Vascular imaging for LVO",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Obtain simultaneously with non-contrast CT or immediately after. Identifies large vessel occlusion (LVO) for thrombectomy consideration. Check creatinine if history of renal disease.",
		},
		{
			OrderID:      "STROKE-IMG-003",
			OrderType:    models.OrderTypeImaging,
			Category:     "imaging",
			Name:         "CT Perfusion (if indicated)",
			Description:  "Perfusion imaging for extended window",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			Instructions: "Consider for: last known well >6h and <24h, wake-up stroke, unclear symptom onset. Assess penumbra (salvageable tissue) for thrombectomy eligibility.",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "time_from_lkw", Operator: "gt", Value: "6", Unit: "hours"},
			},
		},

		// Labs
		{
			OrderID:      "STROKE-LAB-001",
			OrderType:    models.OrderTypeLab,
			Category:     "labs",
			Name:         "Fingerstick Glucose",
			Description:  "ONLY lab required before tPA",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "glucose_poc",
			Instructions: "ONLY lab needed before tPA. Treat if <60 or >400 mg/dL. Do NOT delay tPA for other labs.",
		},
		{
			OrderID:      "STROKE-LAB-002",
			OrderType:    models.OrderTypeLab,
			Category:     "labs",
			Name:         "Stroke Lab Panel",
			Description:  "Complete lab workup",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "stroke_panel",
			LabPanel:     "CBC, CMP, PT/INR, PTT, Troponin, Lipid Panel",
			Instructions: "Draw but do NOT delay tPA. Exception: if on anticoagulants, need PT/INR or anti-Xa level before tPA.",
		},

		// Thrombolysis (tPA/Alteplase)
		{
			OrderID:      "STROKE-TPA-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "thrombolysis",
			Name:         "Alteplase (tPA)",
			Description:  "IV thrombolysis",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     true,
			DrugCode:     "8410",
			DrugName:     "Alteplase",
			Dose:         "0.9 mg/kg (max 90 mg)",
			Route:        "IV",
			Instructions: "Eligibility: ischemic stroke, age ≥18, symptom onset ≤4.5h (extended window with imaging). Dose: 0.9 mg/kg (max 90 mg), 10% bolus over 1 min, remainder over 60 min. BP must be <185/110 before and <180/105 after. Review ALL contraindications.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "8410", Display: "Alteplase"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "time_from_onset", Operator: "lte", Value: "4.5", Unit: "hours"},
				{Type: "if", Field: "bp_systolic", Operator: "lt", Value: "185"},
				{Type: "if", Field: "no_contraindications", Operator: "eq", Value: "true"},
			},
			Notes: "Contraindications: recent surgery/trauma, active bleeding, INR >1.7, platelets <100K, recent stroke, ICH history. See full checklist.",
		},
		{
			OrderID:      "STROKE-TPA-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "thrombolysis",
			Name:         "Tenecteplase (Alternative)",
			Description:  "Alternative thrombolytic",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			DrugCode:     "76895",
			DrugName:     "Tenecteplase",
			Dose:         "0.25 mg/kg (max 25 mg)",
			Route:        "IV bolus",
			Instructions: "Alternative to alteplase: single IV bolus (easier administration). Dose: 0.25 mg/kg (max 25 mg). Same eligibility criteria as alteplase. May have equivalent or better outcomes for LVO.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "76895", Display: "Tenecteplase"},
			},
		},

		// Blood Pressure Management
		{
			OrderID:      "STROKE-BP-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "blood_pressure",
			Name:         "Labetalol (Pre-tPA)",
			Description:  "BP control for tPA eligibility",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     true,
			DrugCode:     "6185",
			DrugName:     "Labetalol",
			Dose:         "10-20 mg IV q10-20min (max 300 mg)",
			Route:        "IV",
			Instructions: "Target BP <185/110 BEFORE tPA and <180/105 AFTER tPA. Give 10-20 mg IV over 1-2 min. May repeat or start infusion 2-8 mg/min. Alternative: Nicardipine 5-15 mg/hr IV.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "6185", Display: "Labetalol"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "bp_systolic", Operator: "gte", Value: "185"},
			},
		},
		{
			OrderID:      "STROKE-BP-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "blood_pressure",
			Name:         "Nicardipine Infusion",
			Description:  "Continuous BP control",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			DrugCode:     "7417",
			DrugName:     "Nicardipine",
			Dose:         "5-15 mg/hr",
			Route:        "IV infusion",
			Instructions: "Alternative to labetalol. Start 5 mg/hr, increase by 2.5 mg/hr q5-15 min (max 15 mg/hr). Easier to titrate for sustained control.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "7417", Display: "Nicardipine"},
			},
		},

		// Thrombectomy Preparation
		{
			OrderID:      "STROKE-THROMB-001",
			OrderType:    models.OrderTypeConsult,
			Category:     "thrombectomy",
			Name:         "Neurointerventional Consult",
			Description:  "Evaluate for mechanical thrombectomy",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Specialty:    "Neurointerventional Radiology/Neurosurgery",
			Reason:       "Acute ischemic stroke with possible LVO",
			Instructions: "Consult immediately if: CTA shows LVO (ICA, M1, M2, basilar), NIHSS ≥6, pre-stroke mRS 0-2. Thrombectomy window: up to 24h with favorable perfusion imaging.",
		},

		// Post-tPA Monitoring
		{
			OrderID:      "STROKE-POST-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "post_tpa",
			Name:         "Post-tPA Monitoring Protocol",
			Description:  "Intensive neuro monitoring after tPA",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "BP q15min x 2h, q30min x 6h, q1h x 16h. Neuro checks (NIHSS) q15min x 2h, q30min x 6h, q1h x 16h. Watch for: headache, N/V, declining LOC (signs of ICH). NO anticoagulants/antiplatelets x 24h. Repeat CT at 24h before starting antiplatelet.",
		},

		// General Management
		{
			OrderID:      "STROKE-GEN-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "general",
			Name:         "NPO and Swallow Evaluation",
			Description:  "Aspiration precautions",
			Priority:     models.PriorityUrgent,
			Required:     true,
			Selected:     true,
			Instructions: "NPO until formal swallow evaluation by SLP. Bedside screening may allow limited PO. Aspiration pneumonia is a major stroke complication.",
		},
		{
			OrderID:      "STROKE-GEN-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "general",
			Name:         "Aspirin (after 24h if tPA given)",
			Description:  "Antiplatelet therapy",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "1191",
			DrugName:     "Aspirin",
			Dose:         "325 mg",
			Route:        "PO/PR",
			Instructions: "If tPA given: hold aspirin x 24h and until repeat CT shows no hemorrhage. If no tPA: give aspirin 325 mg within 24-48h. Continue aspirin 81 mg daily long-term.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "1191", Display: "Aspirin"},
			},
		},
		{
			OrderID:      "STROKE-GEN-003",
			OrderType:    models.OrderTypeMedication,
			Category:     "general",
			Name:         "Statin (High-Intensity)",
			Description:  "Lipid lowering therapy",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "83367",
			DrugName:     "Atorvastatin",
			Dose:         "80 mg",
			Route:        "PO",
			Frequency:    "daily",
			Instructions: "High-intensity statin for all ischemic strokes regardless of LDL. Atorvastatin 80 mg or Rosuvastatin 20 mg. Start early during hospitalization.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "83367", Display: "Atorvastatin"},
			},
		},
	}

	timeConstraints := []models.TimeConstraint{
		{
			ConstraintID:   "STROKE-TIME-001",
			Action:         "door_to_ct",
			Deadline:       25 * time.Minute,
			AlertThreshold: 15 * time.Minute,
			Severity:       "critical",
			Reference:      "AHA/ASA Target: Stroke Guidelines",
			Description:    "Door-to-CT imaging time",
		},
		{
			ConstraintID:   "STROKE-TIME-002",
			Action:         "door_to_needle",
			Deadline:       60 * time.Minute,
			AlertThreshold: 45 * time.Minute,
			Severity:       "critical",
			Reference:      "AHA/ASA Target: Stroke Guidelines",
			Description:    "Door-to-tPA administration (door-to-needle)",
		},
		{
			ConstraintID:   "STROKE-TIME-003",
			Action:         "door_to_groin",
			Deadline:       90 * time.Minute,
			AlertThreshold: 60 * time.Minute,
			Severity:       "critical",
			Reference:      "AHA/ASA Target: Stroke Guidelines",
			Description:    "Door-to-groin puncture for thrombectomy",
		},
		{
			ConstraintID:   "STROKE-TIME-004",
			Action:         "tpa_window",
			Deadline:       270 * time.Minute, // 4.5 hours
			AlertThreshold: 180 * time.Minute,
			Severity:       "critical",
			Reference:      "AHA/ASA Stroke Guidelines",
			Description:    "tPA eligibility window (4.5 hours from symptom onset)",
		},
	}

	return &models.OrderSetTemplate{
		TemplateID:      "OS-EM-005",
		Category:        models.CategoryEmergency,
		Name:            "Acute Ischemic Stroke",
		Version:         "2024.1",
		GuidelineSource: "AHA/ASA Stroke Guidelines 2019 with 2021 updates",
		Description:     "Acute ischemic stroke protocol including tPA administration, thrombectomy evaluation, BP management, and post-stroke care per AHA/ASA guidelines",
		Orders:          orders,
		TimeConstraints: timeConstraints,
		Active:          true,
	}
}

// GetSTEMIProtocol returns STEMI (ST-Elevation Myocardial Infarction) protocol
// Guidelines: ACC/AHA STEMI Guidelines 2021
func GetSTEMIProtocol() *models.OrderSetTemplate {
	orders := []models.Order{
		// Immediate Recognition
		{
			OrderID:      "STEMI-RECOG-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "recognition",
			Name:         "STEMI Alert Activation",
			Description:  "Activate cath lab",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     1,
			Instructions: "ECG shows STEMI: Activate cath lab immediately. Document 'first medical contact' time. Target: Door-to-balloon <90 min (primary PCI capable) or Door-to-needle <30 min (if PCI not available).",
		},
		{
			OrderID:      "STEMI-RECOG-002",
			OrderType:    models.OrderTypeImaging,
			Category:     "recognition",
			Name:         "12-Lead ECG",
			Description:  "Confirm STEMI diagnosis",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "STEMI criteria: ST elevation ≥1 mm in 2+ contiguous leads (≥2 mm in V2-V3 for men, ≥1.5 mm in V2-V3 for women). Check right-sided leads (V4R) if inferior STEMI. Check posterior leads (V7-V9) if suspected posterior MI.",
		},

		// MONA-B (Morphine if needed, Oxygen if needed, Nitro, Aspirin, Beta-blocker)
		{
			OrderID:      "STEMI-MONA-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "initial_therapy",
			Name:         "Aspirin",
			Description:  "Antiplatelet - load immediately",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     2,
			DrugCode:     "1191",
			DrugName:     "Aspirin",
			Dose:         "325 mg (chewed)",
			Route:        "PO (chewed)",
			Instructions: "Give immediately unless true aspirin allergy (not GI intolerance). Chewing allows faster absorption. Non-enteric coated preferred.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "1191", Display: "Aspirin"},
			},
		},
		{
			OrderID:      "STEMI-MONA-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "initial_therapy",
			Name:         "P2Y12 Inhibitor Loading",
			Description:  "Second antiplatelet",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Sequence:     3,
			Instructions: "Load with: Ticagrelor 180 mg PO (preferred) OR Prasugrel 60 mg PO (if no prior stroke/TIA, <75 yo, >60 kg) OR Clopidogrel 600 mg PO. Give before or at time of PCI.",
		},
		{
			OrderID:      "STEMI-MONA-003",
			OrderType:    models.OrderTypeMedication,
			Category:     "initial_therapy",
			Name:         "Ticagrelor",
			Description:  "P2Y12 inhibitor - preferred",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     true,
			DrugCode:     "1116632",
			DrugName:     "Ticagrelor",
			Dose:         "180 mg loading dose",
			Route:        "PO",
			Instructions: "Preferred P2Y12 inhibitor for STEMI. Loading: 180 mg. Maintenance: 90 mg BID. Avoid in prior ICH. May cause dyspnea and ventricular pauses.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "1116632", Display: "Ticagrelor"},
			},
		},
		{
			OrderID:      "STEMI-MONA-004",
			OrderType:    models.OrderTypeMedication,
			Category:     "initial_therapy",
			Name:         "Nitroglycerin SL",
			Description:  "Coronary vasodilator",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     true,
			DrugCode:     "4917",
			DrugName:     "Nitroglycerin",
			Dose:         "0.4 mg SL q5min x 3",
			Route:        "sublingual",
			Instructions: "Give for ongoing chest pain. HOLD if: SBP <90, HR <50 or >100, right ventricular infarction (inferior STEMI with hypotension), recent PDE-5 inhibitor (sildenafil <24h, tadalafil <48h).",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "4917", Display: "Nitroglycerin"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "sbp", Operator: "gte", Value: "90"},
				{Type: "if", Field: "chest_pain", Operator: "eq", Value: "true"},
			},
		},
		{
			OrderID:      "STEMI-MONA-005",
			OrderType:    models.OrderTypeNursing,
			Category:     "initial_therapy",
			Name:         "Oxygen (if hypoxic)",
			Description:  "Supplemental O2 if SpO2 <90%",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     true,
			Instructions: "Give O2 only if SpO2 <90%. Routine O2 not beneficial and may be harmful. Target SpO2 94-98%.",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "spo2", Operator: "lt", Value: "90"},
			},
		},
		{
			OrderID:      "STEMI-MONA-006",
			OrderType:    models.OrderTypeMedication,
			Category:     "initial_therapy",
			Name:         "Morphine (if refractory pain)",
			Description:  "Pain control if NTG fails",
			Priority:     models.PriorityUrgent,
			Required:     false,
			Selected:     false,
			DrugCode:     "7052",
			DrugName:     "Morphine",
			Dose:         "2-4 mg IV",
			Route:        "IV",
			Frequency:    "q5-15min PRN",
			PRN:          true,
			PRNReason:    "chest pain refractory to nitroglycerin",
			Instructions: "Use cautiously. May cause hypotension, bradycardia, respiratory depression. Consider fentanyl as alternative (less hemodynamic effect).",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "7052", Display: "Morphine"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "pain_refractory", Operator: "eq", Value: "true"},
			},
		},

		// Anticoagulation
		{
			OrderID:      "STEMI-ANTICOAG-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "anticoagulation",
			Name:         "Unfractionated Heparin",
			Description:  "Anticoagulation for PCI",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			DrugCode:     "5224",
			DrugName:     "Heparin",
			Dose:         "60-100 units/kg IV bolus (max 5000 units)",
			Route:        "IV bolus",
			Instructions: "Standard for primary PCI. Dose: 70-100 U/kg bolus (50-70 U/kg if GP IIb/IIIa used). Target ACT 250-300 sec (200-250 if GP IIb/IIIa). May use bivalirudin as alternative.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "5224", Display: "Heparin"},
			},
		},

		// Beta-blocker (early if no contraindications)
		{
			OrderID:      "STEMI-BETA-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "initial_therapy",
			Name:         "Metoprolol",
			Description:  "Beta-blocker within 24h",
			Priority:     models.PriorityUrgent,
			Required:     false,
			Selected:     true,
			DrugCode:     "6918",
			DrugName:     "Metoprolol",
			Dose:         "25-50 mg PO or 5 mg IV",
			Route:        "PO or IV",
			Instructions: "Give within 24h if: HR >60, SBP >100, no signs of heart failure, no AV block. IV: 5 mg q5min x 3 (if high-risk, tachycardic, hypertensive). Then PO 25-50 mg q6-12h. Goal HR 60-70.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "6918", Display: "Metoprolol"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "hr", Operator: "gt", Value: "60"},
				{Type: "if", Field: "sbp", Operator: "gt", Value: "100"},
				{Type: "if", Field: "heart_failure", Operator: "eq", Value: "false"},
			},
		},

		// Statin
		{
			OrderID:      "STEMI-STATIN-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "secondary_prevention",
			Name:         "High-Intensity Statin",
			Description:  "Lipid lowering therapy",
			Priority:     models.PriorityUrgent,
			Required:     true,
			Selected:     true,
			DrugCode:     "83367",
			DrugName:     "Atorvastatin",
			Dose:         "80 mg",
			Route:        "PO",
			Frequency:    "daily",
			Instructions: "Start high-intensity statin immediately regardless of LDL. Atorvastatin 80 mg or Rosuvastatin 20-40 mg. Continue indefinitely.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "83367", Display: "Atorvastatin"},
			},
		},

		// Labs
		{
			OrderID:      "STEMI-LAB-001",
			OrderType:    models.OrderTypeLab,
			Category:     "labs",
			Name:         "Initial Cardiac Labs",
			Description:  "Troponin and baseline labs",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "stemi_panel",
			LabPanel:     "Troponin, CBC, CMP, PT/INR, BNP, Lipid Panel",
			Instructions: "Draw immediately. Do NOT delay cath for lab results. Troponin may be initially normal - confirms diagnosis but not required for STEMI activation.",
		},

		// PCI/Reperfusion
		{
			OrderID:      "STEMI-PCI-001",
			OrderType:    models.OrderTypeProcedure,
			Category:     "reperfusion",
			Name:         "Primary PCI (Emergent Cath)",
			Description:  "Coronary angiography and intervention",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Target: Door-to-balloon <90 min. Transfer to PCI-capable facility if D2B cannot be achieved <120 min. Culprit-vessel PCI recommended. Complete revascularization may be considered during index hospitalization.",
		},
		{
			OrderID:      "STEMI-PCI-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "reperfusion",
			Name:         "Fibrinolytic (if PCI unavailable)",
			Description:  "Thrombolysis if PCI delay >120 min",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			Instructions: "Only if: PCI-capable facility >120 min away AND symptom onset <12h. Tenecteplase weight-based (or alteplase). MUST transfer for angiography within 3-24h after fibrinolysis.",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "pci_delay", Operator: "gt", Value: "120", Unit: "minutes"},
				{Type: "if", Field: "symptom_onset", Operator: "lt", Value: "12", Unit: "hours"},
			},
		},

		// Complications Management
		{
			OrderID:      "STEMI-COMP-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "complications",
			Name:         "Arrhythmia Monitoring",
			Description:  "Watch for reperfusion arrhythmias",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "Continuous telemetry. Watch for: VT/VF, bradycardia, heart block (especially inferior MI). Keep pads attached. Have atropine, transcutaneous pacing available.",
		},
		{
			OrderID:      "STEMI-COMP-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "complications",
			Name:         "Amiodarone (for VT/VF)",
			Description:  "Antiarrhythmic for ventricular arrhythmias",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			DrugCode:     "703",
			DrugName:     "Amiodarone",
			Dose:         "150 mg IV over 10 min, then infusion",
			Route:        "IV",
			Instructions: "For recurrent VT/VF after defibrillation. Load: 150 mg IV over 10 min, then 1 mg/min x 6h, then 0.5 mg/min x 18h. Alternative: Lidocaine.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "703", Display: "Amiodarone"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "vt_vf", Operator: "eq", Value: "true"},
			},
		},

		// Post-PCI Care
		{
			OrderID:      "STEMI-POST-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "post_pci",
			Name:         "Post-PCI Monitoring",
			Description:  "Intensive monitoring after cath",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			Instructions: "VS q15min x 1h, q30min x 2h, then q1h. Sheath site checks: bleeding, hematoma, pseudoaneurysm. Neuro checks q1h x 4h. Monitor for contrast nephropathy (Cr at 24-48h). Continue telemetry x 24-48h.",
		},
		{
			OrderID:      "STEMI-POST-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "post_pci",
			Name:         "ACE Inhibitor",
			Description:  "Start within 24h if stable",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "29046",
			DrugName:     "Lisinopril",
			Dose:         "2.5-5 mg",
			Route:        "PO",
			Frequency:    "daily",
			Instructions: "Start within 24h if: anterior MI, EF <40%, heart failure, hypertension, diabetes. Hold if SBP <100 or Cr rising. Start low, titrate up.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "29046", Display: "Lisinopril"},
			},
		},

		// Discharge Planning
		{
			OrderID:      "STEMI-DC-001",
			OrderType:    models.OrderTypeConsult,
			Category:     "discharge",
			Name:         "Cardiac Rehabilitation Referral",
			Description:  "Outpatient cardiac rehab",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Specialty:    "Cardiac Rehabilitation",
			Instructions: "Refer all STEMI patients to cardiac rehab before discharge. Improves outcomes, reduces mortality.",
		},
		{
			OrderID:      "STEMI-DC-002",
			OrderType:    models.OrderTypeEducation,
			Category:     "discharge",
			Name:         "STEMI Discharge Education",
			Description:  "Patient education",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Educate on: DAPT adherence (do not stop without discussing with cardiologist), stent thrombosis risk, symptoms to report, lifestyle modifications, smoking cessation, cardiac rehab importance.",
		},
	}

	timeConstraints := []models.TimeConstraint{
		{
			ConstraintID:   "STEMI-TIME-001",
			Action:         "ecg_acquisition",
			Deadline:       10 * time.Minute,
			AlertThreshold: 5 * time.Minute,
			Severity:       "critical",
			Reference:      "ACC/AHA STEMI Guidelines",
			Description:    "Time from first medical contact to ECG interpretation",
		},
		{
			ConstraintID:   "STEMI-TIME-002",
			Action:         "door_to_balloon",
			Deadline:       90 * time.Minute,
			AlertThreshold: 60 * time.Minute,
			Severity:       "critical",
			Reference:      "ACC/AHA STEMI Guidelines",
			Description:    "Door-to-balloon time for primary PCI",
		},
		{
			ConstraintID:   "STEMI-TIME-003",
			Action:         "door_to_needle",
			Deadline:       30 * time.Minute,
			AlertThreshold: 20 * time.Minute,
			Severity:       "critical",
			Reference:      "ACC/AHA STEMI Guidelines",
			Description:    "Door-to-needle time if fibrinolysis chosen",
		},
		{
			ConstraintID:   "STEMI-TIME-004",
			Action:         "first_medical_contact_to_device",
			Deadline:       120 * time.Minute,
			AlertThreshold: 90 * time.Minute,
			Severity:       "critical",
			Reference:      "ACC/AHA STEMI Guidelines",
			Description:    "Total ischemic time from first medical contact to PCI",
		},
	}

	return &models.OrderSetTemplate{
		TemplateID:      "OS-EM-004",
		Category:        models.CategoryEmergency,
		Name:            "STEMI (ST-Elevation Myocardial Infarction)",
		Version:         "2024.1",
		GuidelineSource: "ACC/AHA STEMI Guidelines 2021",
		Description:     "ST-Elevation Myocardial Infarction protocol including dual antiplatelet therapy, anticoagulation, primary PCI, and post-MI care per ACC/AHA guidelines",
		Orders:          orders,
		TimeConstraints: timeConstraints,
		Active:          true,
	}
}

// GetAllEmergencyProtocols returns all emergency protocols
func GetAllEmergencyProtocols() []*models.OrderSetTemplate {
	return []*models.OrderSetTemplate{
		GetCodeBlueProtocol(),
		GetRapidResponseProtocol(),
		GetMalignantHyperthermiaProtocol(),
		GetAnaphylaxisProtocol(),
		GetSepsisProtocol(),
		GetStrokeProtocol(),
		GetSTEMIProtocol(),
	}
}
