// Package ordersets provides procedure order set templates for bedside procedures
package ordersets

import (
	"kb-12-ordersets-careplans/internal/models"
)

// GetLumbarPunctureOrderSet returns lumbar puncture (spinal tap) order set
// Guidelines: IDSA Meningitis Guidelines, AAN Practice Guidelines
func GetLumbarPunctureOrderSet() *models.OrderSetTemplate {
	orders := []models.Order{
		// Pre-procedure Assessment
		{
			OrderID:      "LP-PRE-001",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_procedure_labs",
			Name:         "Platelet Count and Coagulation",
			Description:  "Assess bleeding risk before LP",
			Priority:     models.PriorityUrgent,
			Required:     true,
			Selected:     true,
			LabCode:      "777-3",
			LabPanel:     "Platelets, PT/INR",
			Specimen:     "blood",
			Timing:       "before_procedure",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "777-3", Display: "Platelet count"},
				{System: "loinc", Code: "34714-6", Display: "INR"},
			},
			Notes: "LP generally safe if platelets >50,000 and INR <1.5. Delay if coagulopathy.",
		},
		{
			OrderID:      "LP-PRE-002",
			OrderType:    models.OrderTypeImaging,
			Category:     "pre_procedure",
			Name:         "CT Head Before LP",
			Description:  "Rule out mass lesion before LP if indicated",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			ImagingCode:  "70450",
			Modality:     "CT",
			BodySite:     "head",
			Contrast:     false,
			Codes: []models.CodeReference{
				{System: "cpt", Code: "70450", Display: "CT Head without contrast"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "focal_neuro_deficit", Operator: "eq", Value: "true"},
				{Type: "if", Field: "papilledema", Operator: "eq", Value: "true"},
				{Type: "if", Field: "altered_consciousness", Operator: "eq", Value: "true"},
				{Type: "if", Field: "immunocompromised", Operator: "eq", Value: "true"},
				{Type: "if", Field: "recent_seizure", Operator: "eq", Value: "true"},
			},
			Notes: "CT before LP if signs of increased ICP. Do NOT delay antibiotics for imaging in suspected bacterial meningitis.",
		},
		{
			OrderID:      "LP-PRE-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "pre_procedure",
			Name:         "Consent Verification",
			Description:  "Verify informed consent",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Verify signed consent. Discuss: headache (10-30%), back pain, bleeding, infection, nerve injury, brain herniation risk if mass effect.",
		},

		// Procedure Setup
		{
			OrderID:      "LP-SETUP-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "procedure_setup",
			Name:         "LP Tray and Supplies",
			Description:  "Equipment preparation",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Standard LP tray with: 20G or 22G atraumatic needle (Sprotte/Whitacre preferred), manometer, sterile drapes, lidocaine 1%, betadine/chlorhexidine, collection tubes (4-5).",
		},
		{
			OrderID:      "LP-SETUP-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "procedure_setup",
			Name:         "Patient Positioning",
			Description:  "Optimal position for LP",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Lateral decubitus (preferred for opening pressure) OR sitting position. Maximize lumbar flexion ('fetal position'). Mark L3-L4 or L4-L5 interspace.",
		},

		// Local Anesthesia
		{
			OrderID:      "LP-ANES-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "anesthesia",
			Name:         "Lidocaine 1% Local",
			Description:  "Local anesthesia for LP",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "6387",
			DrugName:     "Lidocaine 1%",
			Dose:         "3-5 mL",
			Route:        "SubQ",
			Instructions: "Create subcutaneous wheal, then infiltrate deeper tissues. Wait 2-3 minutes for anesthesia.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "6387", Display: "Lidocaine"},
			},
		},

		// CSF Studies
		{
			OrderID:      "LP-CSF-001",
			OrderType:    models.OrderTypeLab,
			Category:     "csf_studies",
			Name:         "Opening Pressure",
			Description:  "Measure CSF opening pressure",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Measure with patient in lateral position, legs relaxed. Normal: 6-20 cmH2O (up to 25 in obese). Elevated in IIH, meningitis, SAH.",
		},
		{
			OrderID:      "LP-CSF-002",
			OrderType:    models.OrderTypeLab,
			Category:     "csf_studies",
			Name:         "CSF Cell Count and Differential",
			Description:  "WBC, RBC, and differential",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "26465-5",
			Specimen:     "csf",
			Timing:       "tube_1_and_4",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "26465-5", Display: "Leukocytes CSF"},
				{System: "loinc", Code: "26463-0", Display: "Erythrocytes CSF"},
			},
			Notes: "Send tube 1 and tube 4 to compare for traumatic tap vs SAH (RBCs decrease in traumatic tap).",
		},
		{
			OrderID:      "LP-CSF-003",
			OrderType:    models.OrderTypeLab,
			Category:     "csf_studies",
			Name:         "CSF Protein and Glucose",
			Description:  "Basic CSF chemistry",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "2881-1",
			Specimen:     "csf",
			Timing:       "tube_2",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "2881-1", Display: "Protein CSF"},
				{System: "loinc", Code: "2342-4", Display: "Glucose CSF"},
			},
			Notes: "Compare CSF glucose to serum glucose (CSF:serum ratio normally >0.6). Low in bacterial meningitis.",
		},
		{
			OrderID:      "LP-CSF-004",
			OrderType:    models.OrderTypeLab,
			Category:     "csf_studies",
			Name:         "CSF Gram Stain and Culture",
			Description:  "Bacterial meningitis workup",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "664-3",
			Specimen:     "csf",
			Timing:       "tube_3",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "664-3", Display: "Gram stain CSF"},
				{System: "loinc", Code: "600-7", Display: "Bacterial culture CSF"},
			},
		},
		{
			OrderID:      "LP-CSF-005",
			OrderType:    models.OrderTypeLab,
			Category:     "csf_studies",
			Name:         "Meningitis/Encephalitis PCR Panel",
			Description:  "Multiplex PCR for CNS pathogens",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     true,
			LabCode:      "meningitis_panel",
			Specimen:     "csf",
			Instructions: "BioFire FilmArray or equivalent. Detects bacteria, viruses, and yeasts causing meningitis/encephalitis.",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "indication", Operator: "eq", Value: "suspected_meningitis"},
			},
		},
		{
			OrderID:      "LP-CSF-006",
			OrderType:    models.OrderTypeLab,
			Category:     "csf_studies",
			Name:         "CSF HSV PCR",
			Description:  "Herpes simplex virus PCR",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			LabCode:      "16952-4",
			Specimen:     "csf",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "16952-4", Display: "HSV DNA PCR"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "indication", Operator: "eq", Value: "suspected_encephalitis"},
			},
		},
		{
			OrderID:      "LP-CSF-007",
			OrderType:    models.OrderTypeLab,
			Category:     "csf_studies",
			Name:         "CSF Xanthochromia",
			Description:  "SAH workup",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			LabCode:      "xanthochromia",
			Specimen:     "csf",
			Instructions: "Protect from light. Spectrophotometry preferred over visual inspection. Positive 12h-2wk after SAH.",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "indication", Operator: "eq", Value: "rule_out_sah"},
			},
		},
		{
			OrderID:      "LP-CSF-008",
			OrderType:    models.OrderTypeLab,
			Category:     "csf_studies",
			Name:         "CSF Cytology",
			Description:  "Malignant cells",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			LabCode:      "cytology",
			Specimen:     "csf",
			Instructions: "Send ≥10mL for cytology. May need repeat LP for sensitivity.",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "indication", Operator: "eq", Value: "leptomeningeal_carcinomatosis"},
			},
		},

		// Post-procedure
		{
			OrderID:      "LP-POST-001",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "post_procedure",
			Name:         "Post-LP Monitoring",
			Description:  "Monitor for complications",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Neuro checks q1h x 4. Monitor for headache, back pain, leg weakness, urinary retention. Report any new neuro deficits immediately.",
		},
		{
			OrderID:      "LP-POST-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "post_procedure",
			Name:         "Post-LP Rest",
			Description:  "Activity restriction",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Bed rest x 1 hour after LP. Flat position may reduce headache but not mandatory. Encourage oral fluids.",
		},
		{
			OrderID:      "LP-POST-003",
			OrderType:    models.OrderTypeMedication,
			Category:     "post_procedure",
			Name:         "Post-LP Headache Treatment",
			Description:  "Analgesics for headache",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			DrugCode:     "161",
			DrugName:     "Acetaminophen",
			Dose:         "650-1000 mg",
			DoseValue:    1000,
			DoseUnit:     "mg",
			Route:        "PO",
			Frequency:    "q6h",
			PRN:          true,
			PRNReason:    "headache",
			Instructions: "First-line for post-LP headache. Caffeine (coffee, caffeine tablets) may help. Consider blood patch if severe positional headache >24-48h.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "161", Display: "Acetaminophen"},
			},
		},
	}

	return &models.OrderSetTemplate{
		TemplateID:      "PROC-LP-001",
		Category:        models.CategoryProcedure,
		Name:            "Lumbar Puncture",
		Version:         "2024.1",
		GuidelineSource: "IDSA Meningitis Guidelines 2017, AAN Practice Guidelines",
		Description:     "Complete lumbar puncture order set including pre-procedure assessment, CSF studies, and post-procedure care",
		Orders:          orders,
		Active:          true,
	}
}

// GetParacentesisOrderSet returns diagnostic/therapeutic paracentesis order set
// Guidelines: AASLD Ascites Guidelines, EASL Guidelines
func GetParacentesisOrderSet() *models.OrderSetTemplate {
	orders := []models.Order{
		// Pre-procedure Assessment
		{
			OrderID:      "PARA-PRE-001",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_procedure_labs",
			Name:         "Coagulation Studies",
			Description:  "Assess bleeding risk",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			LabCode:      "34714-6",
			LabPanel:     "PT/INR, Platelets",
			Specimen:     "blood",
			Timing:       "within_24_hours",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "34714-6", Display: "INR"},
				{System: "loinc", Code: "777-3", Display: "Platelet count"},
			},
			Notes: "Routine FFP/platelet transfusion NOT recommended before paracentesis in cirrhotic patients. Proceed with caution if platelets <20,000.",
		},
		{
			OrderID:      "PARA-PRE-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "pre_procedure",
			Name:         "Bladder Decompression",
			Description:  "Empty bladder before procedure",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Have patient void immediately before procedure OR place Foley if unable. Prevents bladder perforation.",
		},
		{
			OrderID:      "PARA-PRE-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "pre_procedure",
			Name:         "Consent Verification",
			Description:  "Verify informed consent",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Verify signed consent. Discuss: bleeding, infection, bowel perforation, persistent leak, hypotension (if large volume).",
		},

		// Procedure Setup
		{
			OrderID:      "PARA-SETUP-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "procedure_setup",
			Name:         "Paracentesis Kit",
			Description:  "Equipment preparation",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Standard paracentesis kit OR: 18G needle, 50mL syringes, drainage catheter (if therapeutic), sterile collection containers, lidocaine 1%, betadine/chlorhexidine.",
		},
		{
			OrderID:      "PARA-SETUP-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "procedure_setup",
			Name:         "Ultrasound Guidance",
			Description:  "Image-guided needle placement",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Use bedside ultrasound to identify fluid pocket and mark insertion site. Standard site: LLQ (2cm medial and 2cm superior to ASIS). Confirm no bowel loops.",
		},

		// Local Anesthesia
		{
			OrderID:      "PARA-ANES-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "anesthesia",
			Name:         "Lidocaine 1% Local",
			Description:  "Local anesthesia",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "6387",
			DrugName:     "Lidocaine 1%",
			Dose:         "5-10 mL",
			Route:        "SubQ",
			Instructions: "Anesthetize skin, subcutaneous tissue, and peritoneum. Use Z-track technique to minimize leak.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "6387", Display: "Lidocaine"},
			},
		},

		// Ascitic Fluid Studies
		{
			OrderID:      "PARA-FLUID-001",
			OrderType:    models.OrderTypeLab,
			Category:     "fluid_studies",
			Name:         "Cell Count and Differential",
			Description:  "WBC count for SBP diagnosis",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "26465-5",
			Specimen:     "ascitic_fluid",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "26465-5", Display: "Leukocytes body fluid"},
			},
			Notes: "PMN count ≥250/mm³ = SBP (start antibiotics empirically). Total WBC also helpful.",
		},
		{
			OrderID:      "PARA-FLUID-002",
			OrderType:    models.OrderTypeLab,
			Category:     "fluid_studies",
			Name:         "Total Protein and Albumin (SAAG)",
			Description:  "Calculate serum-ascites albumin gradient",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "2881-1",
			Specimen:     "ascitic_fluid",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "2881-1", Display: "Protein body fluid"},
				{System: "loinc", Code: "1751-7", Display: "Albumin body fluid"},
			},
			Notes: "SAAG ≥1.1 = portal hypertension (cirrhosis). SAAG <1.1 = peritoneal disease (malignancy, TB).",
		},
		{
			OrderID:      "PARA-FLUID-003",
			OrderType:    models.OrderTypeLab,
			Category:     "fluid_studies",
			Name:         "Bacterial Culture",
			Description:  "Culture for SBP diagnosis",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "600-7",
			Specimen:     "ascitic_fluid",
			Instructions: "Inoculate blood culture bottles at bedside (10mL each aerobic and anaerobic). Higher sensitivity than standard culture.",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "600-7", Display: "Bacterial culture body fluid"},
			},
		},
		{
			OrderID:      "PARA-FLUID-004",
			OrderType:    models.OrderTypeLab,
			Category:     "fluid_studies",
			Name:         "Glucose and LDH",
			Description:  "Secondary peritonitis workup",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			LabCode:      "2342-4",
			Specimen:     "ascitic_fluid",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "2342-4", Display: "Glucose body fluid"},
				{System: "loinc", Code: "2532-0", Display: "LDH body fluid"},
			},
			Notes: "Low glucose, high LDH, polymicrobial = secondary peritonitis (perforation). Need CT and surgery.",
		},
		{
			OrderID:      "PARA-FLUID-005",
			OrderType:    models.OrderTypeLab,
			Category:     "fluid_studies",
			Name:         "Cytology",
			Description:  "Malignant cells",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			LabCode:      "cytology",
			Specimen:     "ascitic_fluid",
			Instructions: "Send if malignancy suspected (SAAG <1.1, high protein).",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "malignancy_suspected", Operator: "eq", Value: "true"},
			},
		},
		{
			OrderID:      "PARA-FLUID-006",
			OrderType:    models.OrderTypeLab,
			Category:     "fluid_studies",
			Name:         "AFB Smear and Culture",
			Description:  "TB peritonitis workup",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			LabCode:      "11545-1",
			Specimen:     "ascitic_fluid",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "11545-1", Display: "AFB smear"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "tb_risk", Operator: "eq", Value: "high"},
			},
		},

		// Large Volume Paracentesis
		{
			OrderID:      "PARA-LVP-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "large_volume",
			Name:         "Albumin Infusion for LVP",
			Description:  "Prevent post-paracentesis circulatory dysfunction",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			DrugCode:     "11800",
			DrugName:     "Albumin 25%",
			Dose:         "6-8 g per liter removed",
			Route:        "IV",
			Instructions: "Give 25% albumin: 6-8g per liter of ascites removed for volumes >5L. Prevents PPCD and improves survival.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "11800", Display: "Albumin Human"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "volume_removed", Operator: "gt", Value: "5", Unit: "L"},
			},
			Notes: "Example: If removing 8L → give 50-64g albumin (200-250mL of 25% albumin).",
		},
		{
			OrderID:      "PARA-LVP-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "large_volume",
			Name:         "Volume Tracking",
			Description:  "Monitor drainage volume",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Record total volume drained. Typical LVP removes 4-8L. Monitor VS during drainage. Stop if hypotension develops.",
		},

		// Post-procedure
		{
			OrderID:      "PARA-POST-001",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "post_procedure",
			Name:         "Post-paracentesis Monitoring",
			Description:  "Monitor for complications",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "VS q30min x 2, then q1h x 4. Monitor for hypotension, abdominal pain, persistent leak at site. Check Hgb if bleeding concern.",
		},
		{
			OrderID:      "PARA-POST-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "post_procedure",
			Name:         "Site Care",
			Description:  "Puncture site management",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Apply pressure dressing. Patient may lie on opposite side to minimize leak. Persistent leak >24h may need ostomy bag or suture.",
		},

		// SBP Treatment (if indicated)
		{
			OrderID:      "PARA-SBP-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "sbp_treatment",
			Name:         "Ceftriaxone for SBP",
			Description:  "Empiric antibiotic for SBP",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			DrugCode:     "2193",
			DrugName:     "Ceftriaxone",
			Dose:         "2 g",
			DoseValue:    2,
			DoseUnit:     "g",
			Route:        "IV",
			Frequency:    "daily",
			Duration:     "5-7_days",
			Instructions: "Start immediately if ascitic PMN ≥250/mm³. Do not wait for culture results.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "2193", Display: "Ceftriaxone"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "pmn_count", Operator: "gte", Value: "250"},
			},
		},
		{
			OrderID:      "PARA-SBP-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "sbp_treatment",
			Name:         "Albumin for SBP",
			Description:  "Prevent hepatorenal syndrome in SBP",
			Priority:     models.PriorityUrgent,
			Required:     false,
			Selected:     false,
			DrugCode:     "11800",
			DrugName:     "Albumin 25%",
			Instructions: "Day 1: 1.5 g/kg. Day 3: 1 g/kg. Give if Cr >1.0, BUN >30, or bilirubin >4. Reduces mortality.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "11800", Display: "Albumin Human"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "sbp_with_renal_dysfunction", Operator: "eq", Value: "true"},
			},
		},
	}

	return &models.OrderSetTemplate{
		TemplateID:      "PROC-PARA-001",
		Category:        models.CategoryProcedure,
		Name:            "Paracentesis",
		Version:         "2024.1",
		GuidelineSource: "AASLD Ascites Guidelines 2021, EASL Guidelines",
		Description:     "Complete paracentesis order set including diagnostic studies, large-volume management with albumin, and SBP treatment",
		Orders:          orders,
		Active:          true,
	}
}

// GetThoracentesisOrderSet returns thoracentesis order set
// Guidelines: BTS Pleural Disease Guidelines, ATS/STS/ACCP Guidelines
func GetThoracentesisOrderSet() *models.OrderSetTemplate {
	orders := []models.Order{
		// Pre-procedure Assessment
		{
			OrderID:      "THORA-PRE-001",
			OrderType:    models.OrderTypeImaging,
			Category:     "pre_procedure",
			Name:         "Chest X-ray or Ultrasound",
			Description:  "Confirm pleural effusion location",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			ImagingCode:  "71046",
			Modality:     "X-Ray or Ultrasound",
			BodySite:     "chest",
			Codes: []models.CodeReference{
				{System: "cpt", Code: "71046", Display: "Chest X-ray"},
			},
			Instructions: "Lateral decubitus CXR shows if fluid is free-flowing (>1cm layer). Bedside ultrasound preferred for marking.",
		},
		{
			OrderID:      "THORA-PRE-002",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_procedure_labs",
			Name:         "Coagulation Studies",
			Description:  "Assess bleeding risk",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			LabCode:      "34714-6",
			LabPanel:     "PT/INR, Platelets",
			Specimen:     "blood",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "34714-6", Display: "INR"},
				{System: "loinc", Code: "777-3", Display: "Platelet count"},
			},
			Notes: "Consider correction if INR >2.0 or platelets <50,000. Relative contraindication, not absolute.",
		},
		{
			OrderID:      "THORA-PRE-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "pre_procedure",
			Name:         "Consent Verification",
			Description:  "Verify informed consent",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Verify signed consent. Discuss: pneumothorax (5-15%), bleeding, infection, re-expansion pulmonary edema, pain, vasovagal reaction.",
		},

		// Procedure Setup
		{
			OrderID:      "THORA-SETUP-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "procedure_setup",
			Name:         "Thoracentesis Kit",
			Description:  "Equipment preparation",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Standard thoracentesis kit with: 18G needle, drainage catheter, 60mL syringes, 3-way stopcock, sterile collection containers, vacuum bottles (if large volume), lidocaine 1%.",
		},
		{
			OrderID:      "THORA-SETUP-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "procedure_setup",
			Name:         "Ultrasound Guidance",
			Description:  "Real-time guidance for safety",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Use bedside ultrasound for real-time guidance. Mark site 1-2 intercostal spaces below fluid level, above rib (avoid neurovascular bundle). Confirm no lung in path.",
		},
		{
			OrderID:      "THORA-SETUP-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "procedure_setup",
			Name:         "Patient Positioning",
			Description:  "Optimal position for access",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Sitting upright, leaning forward with arms resting on bedside table (preferred). OR lateral decubitus if cannot sit.",
		},

		// Local Anesthesia
		{
			OrderID:      "THORA-ANES-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "anesthesia",
			Name:         "Lidocaine 1% Local",
			Description:  "Local anesthesia",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "6387",
			DrugName:     "Lidocaine 1%",
			Dose:         "10-20 mL",
			Route:        "SubQ",
			Instructions: "Anesthetize skin, subcutaneous tissue, periosteum of rib (very sensitive), and parietal pleura. Generously anesthetize.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "6387", Display: "Lidocaine"},
			},
		},

		// Pleural Fluid Studies
		{
			OrderID:      "THORA-FLUID-001",
			OrderType:    models.OrderTypeLab,
			Category:     "fluid_studies",
			Name:         "Pleural Fluid Protein and LDH",
			Description:  "Light's criteria for transudate vs exudate",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "2881-1",
			Specimen:     "pleural_fluid",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "2881-1", Display: "Protein body fluid"},
				{System: "loinc", Code: "2532-0", Display: "LDH body fluid"},
			},
			Notes: "Light's Criteria (exudate if any): Protein ratio >0.5, LDH ratio >0.6, or LDH >2/3 upper normal. Must also draw serum LDH and protein.",
		},
		{
			OrderID:      "THORA-FLUID-002",
			OrderType:    models.OrderTypeLab,
			Category:     "fluid_studies",
			Name:         "Serum Protein and LDH",
			Description:  "For Light's criteria calculation",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "2885-2",
			Specimen:     "blood",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "2885-2", Display: "Total protein serum"},
				{System: "loinc", Code: "2532-0", Display: "LDH serum"},
			},
		},
		{
			OrderID:      "THORA-FLUID-003",
			OrderType:    models.OrderTypeLab,
			Category:     "fluid_studies",
			Name:         "Cell Count and Differential",
			Description:  "WBC count and type",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "26465-5",
			Specimen:     "pleural_fluid",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "26465-5", Display: "Leukocytes body fluid"},
			},
			Notes: "Neutrophil predominance → infection, PE, pancreatitis. Lymphocyte predominance → TB, malignancy. Eosinophils → blood, air, drugs, parasites.",
		},
		{
			OrderID:      "THORA-FLUID-004",
			OrderType:    models.OrderTypeLab,
			Category:     "fluid_studies",
			Name:         "Glucose",
			Description:  "Low glucose differential",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			LabCode:      "2342-4",
			Specimen:     "pleural_fluid",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "2342-4", Display: "Glucose body fluid"},
			},
			Notes: "Low glucose (<60 or ratio <0.5): empyema, RA, TB, malignancy, esophageal rupture.",
		},
		{
			OrderID:      "THORA-FLUID-005",
			OrderType:    models.OrderTypeLab,
			Category:     "fluid_studies",
			Name:         "pH",
			Description:  "Pleural fluid pH",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "2746-6",
			Specimen:     "pleural_fluid",
			Instructions: "Send in heparinized syringe on ice to ABG lab. pH <7.2 = complicated parapneumonic/empyema (needs drainage).",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "2746-6", Display: "pH body fluid"},
			},
		},
		{
			OrderID:      "THORA-FLUID-006",
			OrderType:    models.OrderTypeLab,
			Category:     "fluid_studies",
			Name:         "Gram Stain and Culture",
			Description:  "Infection workup",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			LabCode:      "600-7",
			Specimen:     "pleural_fluid",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "664-3", Display: "Gram stain"},
				{System: "loinc", Code: "600-7", Display: "Bacterial culture"},
			},
		},
		{
			OrderID:      "THORA-FLUID-007",
			OrderType:    models.OrderTypeLab,
			Category:     "fluid_studies",
			Name:         "Cytology",
			Description:  "Malignant cells",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			LabCode:      "cytology",
			Specimen:     "pleural_fluid",
			Instructions: "Send ≥50mL for cytology. Sensitivity 60% first tap, increases with repeat.",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "malignancy_suspected", Operator: "eq", Value: "true"},
			},
		},
		{
			OrderID:      "THORA-FLUID-008",
			OrderType:    models.OrderTypeLab,
			Category:     "fluid_studies",
			Name:         "Adenosine Deaminase (ADA)",
			Description:  "TB pleuritis marker",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			LabCode:      "1785-5",
			Specimen:     "pleural_fluid",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "1785-5", Display: "Adenosine deaminase"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "tb_suspected", Operator: "eq", Value: "true"},
			},
			Notes: "ADA >40 U/L with lymphocyte predominance highly suggestive of TB pleuritis.",
		},

		// Post-procedure
		{
			OrderID:      "THORA-POST-001",
			OrderType:    models.OrderTypeImaging,
			Category:     "post_procedure",
			Name:         "Post-thoracentesis Chest X-ray",
			Description:  "Rule out pneumothorax",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			ImagingCode:  "71046",
			Modality:     "X-Ray",
			BodySite:     "chest",
			Codes: []models.CodeReference{
				{System: "cpt", Code: "71046", Display: "Chest X-ray"},
			},
			Instructions: "Obtain if: symptoms (dyspnea, chest pain), air aspirated, multiple passes, or no ultrasound guidance. Routine CXR not required if asymptomatic with US guidance.",
		},
		{
			OrderID:      "THORA-POST-002",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "post_procedure",
			Name:         "Post-thoracentesis Monitoring",
			Description:  "Monitor for complications",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "VS and SpO2 q15min x 4, then q30min x 2. Monitor for dyspnea, chest pain, cough. Report new symptoms immediately.",
		},
		{
			OrderID:      "THORA-POST-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "post_procedure",
			Name:         "Volume Documentation",
			Description:  "Record drainage volume",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Document total volume removed. Stop at 1.5L to minimize re-expansion pulmonary edema risk. Stop earlier if chest tightness, cough, or pain.",
		},
	}

	return &models.OrderSetTemplate{
		TemplateID:      "PROC-THORA-001",
		Category:        models.CategoryProcedure,
		Name:            "Thoracentesis",
		Version:         "2024.1",
		GuidelineSource: "BTS Pleural Disease Guidelines 2010, ATS/STS/ACCP Guidelines",
		Description:     "Complete thoracentesis order set including Light's criteria analysis, infection workup, and post-procedure care",
		Orders:          orders,
		Active:          true,
	}
}

// GetBedsideProcedureOrderSets returns all bedside procedure order sets
func GetBedsideProcedureOrderSets() []*models.OrderSetTemplate {
	return []*models.OrderSetTemplate{
		GetLumbarPunctureOrderSet(),
		GetParacentesisOrderSet(),
		GetThoracentesisOrderSet(),
	}
}

// GetAllProcedureOrderSets returns all procedure order sets (aggregator)
func GetAllProcedureOrderSets() []*models.OrderSetTemplate {
	allProcedures := make([]*models.OrderSetTemplate, 0, 10)
	allProcedures = append(allProcedures, GetSurgicalProcedureOrderSets()...)
	allProcedures = append(allProcedures, GetGIProcedureOrderSets()...)
	allProcedures = append(allProcedures, GetCardiacProcedureOrderSets()...)
	allProcedures = append(allProcedures, GetBedsideProcedureOrderSets()...)
	return allProcedures
}
