// Package ordersets provides procedure order set templates for cardiac procedures
package ordersets

import (
	"time"

	"kb-12-ordersets-careplans/internal/models"
)

// GetCardiacCatheterizationOrderSet returns cardiac catheterization order set
// Guidelines: ACC/AHA/SCAI Guidelines for Coronary Revascularization
func GetCardiacCatheterizationOrderSet() *models.OrderSetTemplate {
	orders := []models.Order{
		// Pre-procedure Labs
		{
			OrderID:      "CATH-LAB-001",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_procedure_labs",
			Name:         "Complete Blood Count",
			Description:  "Baseline hemoglobin and platelets",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			LabCode:      "58410-2",
			LabPanel:     "CBC",
			Specimen:     "blood",
			Timing:       "within_24_hours",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "58410-2", Display: "CBC panel"},
			},
		},
		{
			OrderID:      "CATH-LAB-002",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_procedure_labs",
			Name:         "Basic Metabolic Panel with eGFR",
			Description:  "Renal function for contrast safety",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			LabCode:      "51990-0",
			LabPanel:     "BMP with eGFR",
			Specimen:     "blood",
			Timing:       "within_24_hours",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "51990-0", Display: "BMP"},
				{System: "loinc", Code: "33914-3", Display: "eGFR"},
			},
			Notes: "Critical for contrast dosing. Consider hydration protocol if eGFR<60.",
		},
		{
			OrderID:      "CATH-LAB-003",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_procedure_labs",
			Name:         "PT/INR and aPTT",
			Description:  "Coagulation status",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			LabCode:      "34714-6",
			LabPanel:     "Coagulation",
			Specimen:     "blood",
			Timing:       "within_24_hours",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "34714-6", Display: "INR"},
				{System: "loinc", Code: "14979-9", Display: "aPTT"},
			},
		},
		{
			OrderID:      "CATH-LAB-004",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_procedure_labs",
			Name:         "Type and Screen",
			Description:  "Blood typing for emergency transfusion",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			LabCode:      "882-1",
			Specimen:     "blood",
			Timing:       "within_72_hours",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "882-1", Display: "ABO and Rh group"},
			},
		},

		// Pre-procedure Preparation
		{
			OrderID:      "CATH-PREP-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "preparation",
			Name:         "NPO After Midnight",
			Description:  "Nothing by mouth before cath",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "NPO after midnight except for essential medications with sips of water.",
		},
		{
			OrderID:      "CATH-PREP-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "preparation",
			Name:         "Consent Verification",
			Description:  "Verify informed consent",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Verify signed consent for cardiac cath +/- PCI +/- stent. Discuss: bleeding, MI, stroke, death, contrast allergy, vascular injury, need for CABG.",
		},
		{
			OrderID:      "CATH-PREP-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "preparation",
			Name:         "Access Site Preparation",
			Description:  "Prepare groin or wrist for access",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Shave and prep access site (radial preferred). Check Allen's test for radial. Mark dorsalis pedis and posterior tibial pulses bilaterally.",
		},
		{
			OrderID:      "CATH-PREP-004",
			OrderType:    models.OrderTypeNursing,
			Category:     "preparation",
			Name:         "IV Access",
			Description:  "Large bore IV placement",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Two large bore IVs (18G or larger). One in contralateral arm to radial access. Saline lock if not infusing.",
		},

		// Contrast Nephropathy Prevention
		{
			OrderID:      "CATH-CIN-001",
			OrderType:    models.OrderTypeIVFluids,
			Category:     "cin_prevention",
			Name:         "Pre-hydration Protocol",
			Description:  "IV hydration for contrast nephropathy prevention",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "8591",
			DrugName:     "Normal Saline",
			Dose:         "1-3 mL/kg/hr",
			Route:        "IV",
			Duration:     "3-12_hours_pre",
			Instructions: "Start 3-12 hours before cath: 1 mL/kg/hr. For high CIN risk: 3 mL/kg/hr x 1hr pre, then 1 mL/kg/hr during and 6hr post. Max 500mL/hr.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "8591", Display: "Sodium Chloride 0.9%"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "egfr", Operator: "lt", Value: "60"},
			},
		},
		{
			OrderID:      "CATH-CIN-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "cin_prevention",
			Name:         "Hold Metformin",
			Description:  "Metformin management for contrast",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			Instructions: "Hold metformin morning of procedure. May resume 48h after if creatinine stable.",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "metformin_use", Operator: "eq", Value: "true"},
			},
		},
		{
			OrderID:      "CATH-CIN-003",
			OrderType:    models.OrderTypeMedication,
			Category:     "cin_prevention",
			Name:         "Hold Nephrotoxins",
			Description:  "Hold nephrotoxic medications",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			Instructions: "Hold NSAIDs, ACE/ARB, diuretics day of procedure. Resume post-procedure if renal function stable.",
		},

		// Allergy Premedication
		{
			OrderID:      "CATH-ALLERGY-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "allergy_premedication",
			Name:         "Contrast Allergy Premedication",
			Description:  "Steroid/antihistamine protocol for contrast allergy",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			Instructions: "Prednisone 50mg PO at 13h, 7h, and 1h before. Diphenhydramine 50mg PO/IV 1h before. Consider H2 blocker.",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "contrast_allergy", Operator: "eq", Value: "true"},
			},
			Notes: "For prior anaphylactoid reaction. Low osmolar contrast required.",
		},

		// Antiplatelet Management
		{
			OrderID:      "CATH-ANTI-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "antiplatelet",
			Name:         "Aspirin",
			Description:  "Aspirin for PCI",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "1191",
			DrugName:     "Aspirin",
			Dose:         "325 mg",
			DoseValue:    325,
			DoseUnit:     "mg",
			Route:        "PO",
			Frequency:    "once",
			Instructions: "Give pre-cath if not already on daily aspirin. Continue 81mg daily indefinitely post-PCI.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "1191", Display: "Aspirin"},
			},
		},
		{
			OrderID:      "CATH-ANTI-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "antiplatelet",
			Name:         "Clopidogrel Loading Dose",
			Description:  "P2Y12 inhibitor for PCI",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     true,
			DrugCode:     "32968",
			DrugName:     "Clopidogrel",
			Dose:         "600 mg",
			DoseValue:    600,
			DoseUnit:     "mg",
			Route:        "PO",
			Frequency:    "once",
			Instructions: "Give immediately post-PCI if stent placed. Continue 75mg daily x 12 months (DES) or 1 month (BMS). If CABG likely, defer loading.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "32968", Display: "Clopidogrel"},
			},
			Alternatives: []string{"Ticagrelor 180mg load, then 90mg BID (preferred for ACS)", "Prasugrel 60mg load, then 10mg daily (if PCI planned, no prior stroke)"},
		},

		// Procedural Anticoagulation
		{
			OrderID:      "CATH-HEPARIN-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "anticoagulation",
			Name:         "Unfractionated Heparin",
			Description:  "Procedural anticoagulation",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			DrugCode:     "5224",
			DrugName:     "Heparin",
			Dose:         "70-100 units/kg",
			Route:        "IV bolus",
			Instructions: "Target ACT 250-300 (with GP IIb/IIIa) or 300-350 (without). Rebolus if ACT drops. For radial: lower end of range.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "5224", Display: "Heparin"},
			},
		},
		{
			OrderID:      "CATH-HEPARIN-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "anticoagulation",
			Name:         "Bivalirudin Alternative",
			Description:  "Direct thrombin inhibitor",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			DrugCode:     "256511",
			DrugName:     "Bivalirudin",
			Dose:         "0.75 mg/kg bolus, then 1.75 mg/kg/hr",
			Route:        "IV",
			Instructions: "Alternative to heparin. Consider for HIT history or high bleeding risk. Reduce infusion in CKD.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "256511", Display: "Bivalirudin"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "hit_history", Operator: "eq", Value: "true"},
			},
		},

		// GP IIb/IIIa Inhibitors (for high-risk PCI)
		{
			OrderID:      "CATH-GPIB-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "antiplatelet",
			Name:         "Eptifibatide (Integrilin)",
			Description:  "GP IIb/IIIa inhibitor for ACS/complex PCI",
			Priority:     models.PrioritySTAT,
			Required:     false,
			Selected:     false,
			DrugCode:     "203141",
			DrugName:     "Eptifibatide",
			Dose:         "180 mcg/kg bolus x2, then 2 mcg/kg/min",
			Route:        "IV",
			Duration:     "18-24_hours",
			Instructions: "Double bolus (10 min apart) then infusion. Reduce to 1 mcg/kg/min if CrCl<50. Contraindicated if CrCl<30.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "203141", Display: "Eptifibatide"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "acs_with_complex_pci", Operator: "eq", Value: "true"},
				{Type: "unless", Field: "creatinine_clearance", Operator: "lt", Value: "30"},
			},
		},

		// Post-procedure Monitoring
		{
			OrderID:      "CATH-POST-001",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "post_procedure",
			Name:         "Cath Lab Recovery Monitoring",
			Description:  "Immediate post-cath monitoring",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "VS q15min x4, q30min x2, then q1h x4. Check access site q15min x4, then q30min x4. Monitor distal pulses.",
		},
		{
			OrderID:      "CATH-POST-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "post_procedure",
			Name:         "Femoral Access Site Care",
			Description:  "Femoral sheath/closure device management",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			Instructions: "If manual pressure: Sheath pull when ACT<180. Pressure 20min, then bedrest 4-6h. If closure device: bedrest 2h. Check for hematoma, bruit, distal pulses.",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "access_site", Operator: "eq", Value: "femoral"},
			},
		},
		{
			OrderID:      "CATH-POST-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "post_procedure",
			Name:         "Radial Access Site Care",
			Description:  "Radial artery management",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			Instructions: "TR Band for 2h (gradual deflation). Keep wrist neutral. Check radial pulse and hand perfusion q30min. May ambulate immediately.",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "access_site", Operator: "eq", Value: "radial"},
			},
		},

		// Post-procedure Labs
		{
			OrderID:      "CATH-POSTLAB-001",
			OrderType:    models.OrderTypeLab,
			Category:     "post_procedure_labs",
			Name:         "Post-PCI Troponin",
			Description:  "Detect periprocedural MI",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			LabCode:      "6598-7",
			Specimen:     "blood",
			Timing:       "6-12_hours_post",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "6598-7", Display: "Troponin T"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "pci_performed", Operator: "eq", Value: "true"},
			},
		},
		{
			OrderID:      "CATH-POSTLAB-002",
			OrderType:    models.OrderTypeLab,
			Category:     "post_procedure_labs",
			Name:         "Post-contrast Creatinine",
			Description:  "Monitor for contrast nephropathy",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			LabCode:      "2160-0",
			Specimen:     "blood",
			Timing:       "24-48_hours_post",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "2160-0", Display: "Creatinine"},
			},
		},

		// Post-procedure Medications
		{
			OrderID:      "CATH-POSTMED-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "post_procedure",
			Name:         "High-Intensity Statin",
			Description:  "Lipid management post-PCI",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "617318",
			DrugName:     "Atorvastatin",
			Dose:         "80 mg",
			DoseValue:    80,
			DoseUnit:     "mg",
			Route:        "PO",
			Frequency:    "daily",
			Instructions: "High-intensity statin for all post-ACS/PCI. Continue indefinitely.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "617318", Display: "Atorvastatin 80mg"},
			},
		},
		{
			OrderID:      "CATH-POSTMED-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "post_procedure",
			Name:         "DAPT Continuation",
			Description:  "Dual antiplatelet therapy",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Aspirin 81mg daily indefinitely + P2Y12 inhibitor (clopidogrel 75mg, ticagrelor 90mg BID, or prasugrel 10mg) for 12 months minimum post-DES. DO NOT stop without cardiology consultation.",
		},

		// Discharge Planning
		{
			OrderID:      "CATH-DC-001",
			OrderType:    models.OrderTypeEducation,
			Category:     "discharge",
			Name:         "Post-cath Discharge Instructions",
			Description:  "Patient education for discharge",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "1) No heavy lifting >10lbs x 5 days. 2) Check access site daily for bleeding/swelling. 3) Do not skip DAPT. 4) Cardiac rehab referral. 5) Follow up with cardiologist in 1-2 weeks. 6) Call for: chest pain, access site bleeding, leg pain/numbness.",
		},
	}

	timeConstraints := []models.TimeConstraint{
		{
			ConstraintID:   "CATH-TIME-001",
			Action:         "door_to_balloon",
			Deadline:       90 * time.Minute,
			AlertThreshold: 60 * time.Minute,
			Severity:       "critical",
			Reference:      "ACC/AHA STEMI Guidelines",
			Description:    "Door-to-balloon time for primary PCI in STEMI",
		},
		{
			ConstraintID:   "CATH-TIME-002",
			Action:         "loading_dose_antiplatelet",
			Deadline:       30 * time.Minute,
			AlertThreshold: 15 * time.Minute,
			Severity:       "major",
			Reference:      "SCAI Guidelines",
			Description:    "Administer P2Y12 loading dose before/immediately after PCI",
		},
	}
	return &models.OrderSetTemplate{
		TemplateID:      "PROC-CATH-001",
		Category:        models.CategoryProcedure,
		Name:            "Cardiac Catheterization and PCI",
		Version:         "2024.1",
		GuidelineSource: "ACC/AHA/SCAI Coronary Revascularization Guidelines 2021",
		Description:     "Complete cardiac catheterization and PCI order set including pre-procedure labs, contrast nephropathy prevention, antiplatelet management, and post-procedure care",
		Orders:          orders,
		TimeConstraints: timeConstraints,
		Active:          true,
	}
}

// GetCardioversionOrderSet returns elective cardioversion order set
// Guidelines: ACC/AHA/HRS Atrial Fibrillation Guidelines
func GetCardioversionOrderSet() *models.OrderSetTemplate {
	orders := []models.Order{
		// Pre-cardioversion Assessment
		{
			OrderID:      "DCCV-ASSESS-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "assessment",
			Name:         "Anticoagulation Verification",
			Description:  "Verify adequate anticoagulation",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Confirm therapeutic anticoagulation ≥3 weeks OR TEE without LA appendage thrombus. Document INR (if warfarin), compliance with DOAC (if applicable).",
		},
		{
			OrderID:      "DCCV-ASSESS-002",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_procedure_labs",
			Name:         "Potassium and Magnesium",
			Description:  "Electrolytes before cardioversion",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			LabCode:      "2823-3",
			LabPanel:     "K, Mg",
			Specimen:     "blood",
			Timing:       "day_of",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "2823-3", Display: "Potassium"},
				{System: "loinc", Code: "2601-3", Display: "Magnesium"},
			},
			Notes: "K+ should be ≥4.0, Mg ≥2.0 before cardioversion to reduce arrhythmia risk.",
		},
		{
			OrderID:      "DCCV-ASSESS-003",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_procedure_labs",
			Name:         "INR Check",
			Description:  "Verify therapeutic INR if on warfarin",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			LabCode:      "34714-6",
			Specimen:     "blood",
			Timing:       "day_of",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "34714-6", Display: "INR"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "warfarin_use", Operator: "eq", Value: "true"},
			},
			Notes: "INR must be ≥2.0 and documented therapeutic for ≥3 weeks.",
		},
		{
			OrderID:      "DCCV-ASSESS-004",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_procedure_labs",
			Name:         "TSH",
			Description:  "Rule out hyperthyroidism",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			LabCode:      "3016-3",
			Specimen:     "blood",
			Timing:       "within_3_months",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "3016-3", Display: "TSH"},
			},
			Notes: "Hyperthyroidism causes refractory AFib. Check if not recently obtained.",
		},

		// Pre-procedure Preparation
		{
			OrderID:      "DCCV-PREP-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "preparation",
			Name:         "NPO Status",
			Description:  "Fasting requirement",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "NPO for 6-8 hours before procedure for aspiration prevention during sedation.",
		},
		{
			OrderID:      "DCCV-PREP-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "preparation",
			Name:         "Consent Verification",
			Description:  "Verify informed consent",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Verify signed consent. Discuss: failure to convert, stroke risk, skin burns, arrhythmia, sedation risks.",
		},
		{
			OrderID:      "DCCV-PREP-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "preparation",
			Name:         "IV Access",
			Description:  "Establish IV for sedation",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "18G or larger IV. Saline lock. Confirm patency before sedation.",
		},
		{
			OrderID:      "DCCV-PREP-004",
			OrderType:    models.OrderTypeNursing,
			Category:     "preparation",
			Name:         "12-Lead ECG",
			Description:  "Document pre-cardioversion rhythm",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Obtain 12-lead ECG immediately before procedure. Confirm arrhythmia present.",
		},

		// Electrolyte Replacement (if needed)
		{
			OrderID:      "DCCV-LYTE-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "electrolyte_replacement",
			Name:         "Potassium Chloride IV",
			Description:  "K+ replacement if low",
			Priority:     models.PriorityUrgent,
			Required:     false,
			Selected:     false,
			DrugCode:     "8591",
			DrugName:     "Potassium Chloride",
			Dose:         "20-40 mEq",
			Route:        "IV",
			Instructions: "Replete K+ if <4.0. Goal K+ ≥4.0 before cardioversion. Max 10 mEq/hr peripheral, 20 mEq/hr central.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "8591", Display: "Potassium Chloride"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "potassium", Operator: "lt", Value: "4.0", Unit: "mEq/L"},
			},
		},
		{
			OrderID:      "DCCV-LYTE-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "electrolyte_replacement",
			Name:         "Magnesium Sulfate IV",
			Description:  "Mg replacement if low",
			Priority:     models.PriorityUrgent,
			Required:     false,
			Selected:     false,
			DrugCode:     "6585",
			DrugName:     "Magnesium Sulfate",
			Dose:         "2 g",
			DoseValue:    2,
			DoseUnit:     "g",
			Route:        "IV",
			Duration:     "over_1_hour",
			Instructions: "Replete Mg if <2.0. Goal Mg ≥2.0 before cardioversion.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "6585", Display: "Magnesium Sulfate"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "magnesium", Operator: "lt", Value: "2.0", Unit: "mg/dL"},
			},
		},

		// Sedation
		{
			OrderID:      "DCCV-SED-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "sedation",
			Name:         "Propofol Sedation",
			Description:  "Deep sedation for cardioversion",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "8782",
			DrugName:     "Propofol",
			Dose:         "0.5-1.5 mg/kg",
			Route:        "IV push",
			Instructions: "Titrate to deep sedation/brief unresponsiveness. Brief duration needed. Have airway equipment ready.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "8782", Display: "Propofol"},
			},
			Notes: "Propofol preferred for brief, deep sedation. Etomidate alternative if hemodynamically unstable.",
		},
		{
			OrderID:      "DCCV-SED-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "sedation",
			Name:         "Etomidate Alternative",
			Description:  "Alternative for hemodynamically unstable",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			DrugCode:     "4110",
			DrugName:     "Etomidate",
			Dose:         "0.2-0.3 mg/kg",
			Route:        "IV push",
			Instructions: "Use if hypotension concern. Less hypotension than propofol.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "4110", Display: "Etomidate"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "hemodynamic_instability", Operator: "eq", Value: "true"},
			},
		},

		// Cardioversion Orders
		{
			OrderID:      "DCCV-PROC-001",
			OrderType:    models.OrderTypeProcedure,
			Category:     "procedure",
			Name:         "Synchronized DC Cardioversion",
			Description:  "External cardioversion",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Biphasic: Start 120-200J (AFib), 50-100J (atrial flutter). Synchronized mode ON. Anterior-posterior pad position preferred. May increase energy and repeat up to 3 attempts.",
		},
		{
			OrderID:      "DCCV-PROC-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "procedure",
			Name:         "Defibrillator/Pads",
			Description:  "Equipment preparation",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Biphasic defibrillator at bedside. Self-adhesive pads in anterior-posterior position. Confirm sync mode.",
		},

		// Post-cardioversion
		{
			OrderID:      "DCCV-POST-001",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "post_procedure",
			Name:         "Post-cardioversion Monitoring",
			Description:  "Recovery room monitoring",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Continuous ECG x 2-4 hours. VS q15min x4, then q30min x2. Monitor for arrhythmias, chest pain, skin burns.",
		},
		{
			OrderID:      "DCCV-POST-002",
			OrderType:    models.OrderTypeLab,
			Category:     "post_procedure",
			Name:         "Post-cardioversion ECG",
			Description:  "Document restored rhythm",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "12-lead ECG immediately after successful cardioversion and before discharge.",
		},
		{
			OrderID:      "DCCV-POST-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "post_procedure",
			Name:         "Skin Assessment",
			Description:  "Check for pad burns",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Assess pad sites for erythema, burns. Document any skin changes. Apply topical treatment if needed.",
		},

		// Anticoagulation Continuation
		{
			OrderID:      "DCCV-AC-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "anticoagulation",
			Name:         "Continue Anticoagulation",
			Description:  "Post-cardioversion anticoagulation",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Continue anticoagulation ≥4 weeks post-cardioversion regardless of rhythm. Long-term anticoagulation based on CHA2DS2-VASc score.",
		},

		// Rate/Rhythm Control
		{
			OrderID:      "DCCV-AAD-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "rhythm_control",
			Name:         "Amiodarone for Rhythm Maintenance",
			Description:  "Antiarrhythmic for AFib prevention",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			DrugCode:     "703",
			DrugName:     "Amiodarone",
			Dose:         "200 mg",
			DoseValue:    200,
			DoseUnit:     "mg",
			Route:        "PO",
			Frequency:    "daily",
			Instructions: "For rhythm control strategy. May load 400mg TID x 1 week, 400mg BID x 1 week, then 200mg daily. Monitor thyroid, liver, pulmonary function.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "703", Display: "Amiodarone"},
			},
		},
		{
			OrderID:      "DCCV-AAD-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "rate_control",
			Name:         "Metoprolol for Rate Control",
			Description:  "Beta blocker for ventricular rate control",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			DrugCode:     "6918",
			DrugName:     "Metoprolol Succinate",
			Dose:         "25-200 mg",
			Route:        "PO",
			Frequency:    "daily",
			Instructions: "For rate control strategy. Titrate to resting HR <80. May use immediate-release initially.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "6918", Display: "Metoprolol"},
			},
		},

		// Discharge
		{
			OrderID:      "DCCV-DC-001",
			OrderType:    models.OrderTypeEducation,
			Category:     "discharge",
			Name:         "Discharge Instructions",
			Description:  "Post-cardioversion patient education",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "1) Continue anticoagulation - do not miss doses. 2) Monitor pulse daily. 3) Call for: palpitations, racing heart, lightheadedness, chest pain. 4) Follow up with cardiology 2-4 weeks. 5) No driving day of procedure.",
		},
	}

	return &models.OrderSetTemplate{
		TemplateID:      "PROC-DCCV-001",
		Category:        models.CategoryProcedure,
		Name:            "Elective Cardioversion",
		Version:         "2024.1",
		GuidelineSource: "ACC/AHA/HRS Atrial Fibrillation Guidelines 2023",
		Description:     "Complete elective DC cardioversion order set including anticoagulation verification, sedation, procedure, and post-cardioversion monitoring",
		Orders:          orders,
		Active:          true,
	}
}

// GetCardiacProcedureOrderSets returns all cardiac procedure order sets
func GetCardiacProcedureOrderSets() []*models.OrderSetTemplate {
	return []*models.OrderSetTemplate{
		GetCardiacCatheterizationOrderSet(),
		GetCardioversionOrderSet(),
	}
}
