// Package ordersets provides procedure order set templates for surgical procedures
package ordersets

import (
	"kb-12-ordersets-careplans/internal/models"
)

// GetPreOperativeAssessmentOrderSet returns pre-operative assessment order set
// Guidelines: ASA Pre-Anesthesia Evaluation, ACC/AHA Perioperative Guidelines
func GetPreOperativeAssessmentOrderSet() *models.OrderSetTemplate {
	orders := []models.Order{
		// Pre-operative Labs
		{
			OrderID:      "PREOP-LAB-001",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_operative_labs",
			Name:         "Complete Blood Count with Differential",
			Description:  "Baseline CBC for surgical risk assessment",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			LabCode:      "58410-2",
			LabPanel:     "CBC with differential",
			Specimen:     "blood",
			Timing:       "within_30_days",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "58410-2", Display: "CBC panel - Blood"},
			},
		},
		{
			OrderID:      "PREOP-LAB-002",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_operative_labs",
			Name:         "Basic Metabolic Panel",
			Description:  "Electrolytes, BUN, creatinine, glucose",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			LabCode:      "51990-0",
			LabPanel:     "BMP",
			Specimen:     "blood",
			Timing:       "within_30_days",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "51990-0", Display: "Basic metabolic panel"},
			},
		},
		{
			OrderID:      "PREOP-LAB-003",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_operative_labs",
			Name:         "Coagulation Panel (PT/INR, PTT)",
			Description:  "Assess bleeding risk",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			LabCode:      "34714-6",
			LabPanel:     "Coagulation",
			Specimen:     "blood",
			Timing:       "within_7_days",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "34714-6", Display: "INR coagulation"},
				{System: "loinc", Code: "14979-9", Display: "aPTT coagulation"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "anticoagulant_use", Operator: "eq", Value: "true"},
				{Type: "if", Field: "surgery_type", Operator: "eq", Value: "major"},
			},
		},
		{
			OrderID:      "PREOP-LAB-004",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_operative_labs",
			Name:         "Type and Screen",
			Description:  "Blood typing for potential transfusion",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			LabCode:      "882-1",
			Specimen:     "blood",
			Timing:       "within_72_hours",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "882-1", Display: "ABO and Rh group"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "expected_blood_loss", Operator: "gt", Value: "500", Unit: "mL"},
			},
		},
		{
			OrderID:      "PREOP-LAB-005",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_operative_labs",
			Name:         "Urinalysis",
			Description:  "Screen for UTI that could cause surgical infection",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			LabCode:      "24356-8",
			Specimen:     "urine",
			Timing:       "within_7_days",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "24356-8", Display: "Urinalysis complete"},
			},
		},
		{
			OrderID:      "PREOP-LAB-006",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_operative_labs",
			Name:         "Pregnancy Test (Beta-hCG)",
			Description:  "Required for females of childbearing age",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			LabCode:      "2106-3",
			Specimen:     "urine_or_serum",
			Timing:       "day_of_surgery",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "2106-3", Display: "Choriogonadotropin"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "sex", Operator: "eq", Value: "female"},
				{Type: "if", Field: "age", Operator: "gte", Value: "12"},
				{Type: "if", Field: "age", Operator: "lte", Value: "55"},
			},
		},
		{
			OrderID:      "PREOP-LAB-007",
			OrderType:    models.OrderTypeLab,
			Category:     "pre_operative_labs",
			Name:         "Hemoglobin A1c",
			Description:  "Glycemic control assessment for diabetics",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			LabCode:      "4548-4",
			Specimen:     "blood",
			Timing:       "within_90_days",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "4548-4", Display: "Hemoglobin A1c"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "diabetes", Operator: "eq", Value: "true"},
			},
		},

		// Cardiac Assessment
		{
			OrderID:      "PREOP-CARDIAC-001",
			OrderType:    models.OrderTypeImaging,
			Category:     "cardiac_assessment",
			Name:         "12-Lead ECG",
			Description:  "Baseline cardiac rhythm assessment",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			ImagingCode:  "93000",
			Modality:     "ECG",
			Codes: []models.CodeReference{
				{System: "cpt", Code: "93000", Display: "Electrocardiogram"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "age", Operator: "gte", Value: "50"},
				{Type: "if", Field: "cardiac_history", Operator: "eq", Value: "true"},
				{Type: "if", Field: "surgery_risk", Operator: "eq", Value: "intermediate_or_high"},
			},
		},
		{
			OrderID:      "PREOP-CARDIAC-002",
			OrderType:    models.OrderTypeImaging,
			Category:     "cardiac_assessment",
			Name:         "Chest X-Ray PA and Lateral",
			Description:  "Pulmonary and cardiac silhouette assessment",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			ImagingCode:  "71046",
			Modality:     "X-Ray",
			BodySite:     "chest",
			Codes: []models.CodeReference{
				{System: "cpt", Code: "71046", Display: "Chest X-ray 2 views"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "pulmonary_disease", Operator: "eq", Value: "true"},
				{Type: "if", Field: "cardiac_disease", Operator: "eq", Value: "true"},
				{Type: "if", Field: "age", Operator: "gte", Value: "70"},
			},
		},

		// Consults
		{
			OrderID:     "PREOP-CONSULT-001",
			OrderType:   models.OrderTypeConsult,
			Category:    "consults",
			Name:        "Anesthesiology Pre-operative Evaluation",
			Description: "Pre-anesthesia assessment and planning",
			Priority:    models.PriorityRoutine,
			Required:    true,
			Selected:    true,
			Specialty:   "Anesthesiology",
			Reason:      "Pre-operative anesthesia evaluation",
			Urgency:     "routine",
			Codes: []models.CodeReference{
				{System: "snomed", Code: "11429006", Display: "Anesthesia consultation"},
			},
		},
		{
			OrderID:     "PREOP-CONSULT-002",
			OrderType:   models.OrderTypeConsult,
			Category:    "consults",
			Name:        "Cardiology Clearance",
			Description: "Cardiac risk stratification for high-risk patients",
			Priority:    models.PriorityUrgent,
			Required:    false,
			Selected:    false,
			Specialty:   "Cardiology",
			Reason:      "Perioperative cardiac risk assessment",
			Urgency:     "urgent",
			Codes: []models.CodeReference{
				{System: "snomed", Code: "310518003", Display: "Cardiology consultation"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "rcri_score", Operator: "gte", Value: "2"},
				{Type: "if", Field: "functional_capacity", Operator: "lt", Value: "4", Unit: "METs"},
			},
		},
		{
			OrderID:     "PREOP-CONSULT-003",
			OrderType:   models.OrderTypeConsult,
			Category:    "consults",
			Name:        "Pulmonology Clearance",
			Description: "Pulmonary function optimization",
			Priority:    models.PriorityRoutine,
			Required:    false,
			Selected:    false,
			Specialty:   "Pulmonology",
			Reason:      "Perioperative pulmonary risk assessment",
			Urgency:     "routine",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "severe_copd", Operator: "eq", Value: "true"},
				{Type: "if", Field: "osa_untreated", Operator: "eq", Value: "true"},
			},
		},

		// Pre-operative Medications
		{
			OrderID:      "PREOP-MED-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "prophylaxis",
			Name:         "Cefazolin Pre-operative Prophylaxis",
			Description:  "Surgical site infection prophylaxis",
			Priority:     models.PrioritySTAT,
			Required:     true,
			Selected:     true,
			DrugCode:     "4053",
			DrugName:     "Cefazolin",
			Dose:         "2 g",
			DoseValue:    2,
			DoseUnit:     "g",
			Route:        "IV",
			Frequency:    "once",
			Duration:     "single_dose",
			Instructions: "Administer within 60 minutes before surgical incision",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "4053", Display: "Cefazolin"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "weight", Operator: "gte", Value: "120", Unit: "kg"},
			},
			Alternatives: []string{"Vancomycin if MRSA risk or beta-lactam allergy", "Clindamycin if penicillin allergy"},
			Notes:        "Redose 3g if weight ≥120kg. For beta-lactam allergy: Vancomycin 15mg/kg IV",
		},
		{
			OrderID:      "PREOP-MED-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "glycemic_control",
			Name:         "Insulin Sliding Scale",
			Description:  "Perioperative glucose management",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			DrugCode:     "253182",
			DrugName:     "Insulin Regular",
			Route:        "SubQ",
			Frequency:    "with_meals_and_bedtime",
			Instructions: "Target glucose 140-180 mg/dL perioperatively",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "253182", Display: "Regular Insulin"},
			},
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "diabetes", Operator: "eq", Value: "true"},
			},
		},

		// Nursing Orders
		{
			OrderID:      "PREOP-NURSING-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "pre_operative_care",
			Name:         "NPO After Midnight",
			Description:  "Nothing by mouth after midnight before surgery",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "NPO after midnight. Clear liquids allowed up to 2 hours before surgery per ASA guidelines.",
		},
		{
			OrderID:      "PREOP-NURSING-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "pre_operative_care",
			Name:         "Surgical Site Marking",
			Description:  "Mark surgical site per institutional protocol",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Surgeon to mark surgical site with indelible marker. Patient must verify.",
		},
		{
			OrderID:      "PREOP-NURSING-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "pre_operative_care",
			Name:         "Surgical Safety Checklist",
			Description:  "Complete WHO Surgical Safety Checklist",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Complete Sign In, Time Out, and Sign Out per WHO protocol",
		},
		{
			OrderID:      "PREOP-NURSING-004",
			OrderType:    models.OrderTypeNursing,
			Category:     "pre_operative_care",
			Name:         "Chlorhexidine Bathing",
			Description:  "Pre-operative skin preparation",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			Instructions: "CHG bath the night before and morning of surgery",
		},

		// Documentation
		{
			OrderID:      "PREOP-DOC-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "documentation",
			Name:         "Informed Consent",
			Description:  "Obtain surgical informed consent",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Verify signed informed consent for procedure, anesthesia, and blood transfusion if applicable",
		},
		{
			OrderID:      "PREOP-DOC-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "documentation",
			Name:         "History and Physical",
			Description:  "Complete H&P within required timeframe",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "H&P must be completed within 30 days of surgery with update within 24 hours",
		},

		// Medication Management
		{
			OrderID:      "PREOP-MEDMGMT-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "medication_management",
			Name:         "Hold Anticoagulation",
			Description:  "Discontinue anticoagulants per protocol",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			Instructions: "Hold warfarin 5 days, DOACs 48-72 hours based on renal function",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "anticoagulant_use", Operator: "eq", Value: "true"},
			},
		},
		{
			OrderID:      "PREOP-MEDMGMT-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "medication_management",
			Name:         "Hold Metformin",
			Description:  "Hold metformin per contrast/surgery protocol",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			Instructions: "Hold metformin day of surgery, resume when oral intake established and renal function stable",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "metformin_use", Operator: "eq", Value: "true"},
			},
		},
	}

	return &models.OrderSetTemplate{
		TemplateID:      "PROC-PREOP-001",
		Category:        models.CategoryProcedure,
		Name:            "Pre-Operative Assessment",
		Version:         "2024.1",
		GuidelineSource: "ASA Pre-Anesthesia Evaluation, ACC/AHA Perioperative Guidelines 2014",
		Description:     "Comprehensive pre-operative assessment order set for surgical patients including labs, cardiac evaluation, and consults",
		Orders:          orders,
		Active:          true,
	}
}

// GetPostOperativeCareOrderSet returns post-operative care order set
// Guidelines: ERAS (Enhanced Recovery After Surgery), ASA Post-Anesthesia Care Standards
func GetPostOperativeCareOrderSet() *models.OrderSetTemplate {
	orders := []models.Order{
		// Vital Sign Monitoring
		{
			OrderID:      "POSTOP-MONITOR-001",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "vital_signs",
			Name:         "Post-operative Vital Signs",
			Description:  "Frequent vital sign monitoring post-surgery",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "VS q15min x 4, then q30min x 2, then q4h x 24h, then per unit protocol",
		},
		{
			OrderID:      "POSTOP-MONITOR-002",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "vital_signs",
			Name:         "Continuous Pulse Oximetry",
			Description:  "Oxygen saturation monitoring",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Continuous SpO2 monitoring until fully awake and ambulatory. Target SpO2 ≥94%",
		},
		{
			OrderID:      "POSTOP-MONITOR-003",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "vital_signs",
			Name:         "Intake and Output Monitoring",
			Description:  "Strict I&O tracking",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Record all intake (IV, PO) and output (urine, drains, emesis) every shift",
		},
		{
			OrderID:      "POSTOP-MONITOR-004",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "vital_signs",
			Name:         "Neurological Checks",
			Description:  "Level of consciousness and neurological assessment",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			Instructions: "Assess LOC, pupils, and motor function q1h x 4, then q4h. Alert MD for any decline.",
		},

		// Pain Management
		{
			OrderID:      "POSTOP-PAIN-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "pain_management",
			Name:         "Acetaminophen Scheduled",
			Description:  "Multimodal analgesia - non-opioid base",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "161",
			DrugName:     "Acetaminophen",
			Dose:         "1000 mg",
			DoseValue:    1000,
			DoseUnit:     "mg",
			Route:        "PO/IV",
			Frequency:    "q6h",
			Duration:     "while_hospitalized",
			MaxDailyDose: "4000 mg/day (3000 mg if liver disease)",
			Instructions: "Use IV if NPO. Switch to PO when tolerating diet. Max 3g/day if hepatic impairment.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "161", Display: "Acetaminophen"},
			},
		},
		{
			OrderID:      "POSTOP-PAIN-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "pain_management",
			Name:         "Ketorolac IV",
			Description:  "NSAID for multimodal analgesia",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			DrugCode:     "6403",
			DrugName:     "Ketorolac",
			Dose:         "15-30 mg",
			DoseValue:    15,
			DoseUnit:     "mg",
			Route:        "IV",
			Frequency:    "q6h",
			Duration:     "max_5_days",
			MaxDailyDose: "120 mg/day (60 mg if ≥65yo or <50kg)",
			Instructions: "Max 5 days total use. Reduce dose to 15mg if ≥65yo, <50kg, or CrCl 30-60",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "6403", Display: "Ketorolac"},
			},
			Conditions: []models.OrderCondition{
				{Type: "unless", Field: "renal_impairment", Operator: "eq", Value: "true"},
				{Type: "unless", Field: "gi_bleed_history", Operator: "eq", Value: "true"},
				{Type: "unless", Field: "platelet_dysfunction", Operator: "eq", Value: "true"},
			},
		},
		{
			OrderID:      "POSTOP-PAIN-003",
			OrderType:    models.OrderTypeMedication,
			Category:     "pain_management",
			Name:         "Morphine IV PRN",
			Description:  "Opioid for moderate to severe pain",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			DrugCode:     "7052",
			DrugName:     "Morphine",
			Dose:         "2-4 mg",
			DoseValue:    2,
			DoseUnit:     "mg",
			Route:        "IV",
			Frequency:    "q3h",
			PRN:          true,
			PRNReason:    "moderate to severe pain (NRS ≥4)",
			Instructions: "Start 2mg for opioid-naive, 4mg for opioid-tolerant. Hold for RR<10 or sedation.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "7052", Display: "Morphine"},
			},
			Alternatives: []string{"Hydromorphone 0.2-0.4mg IV q3h PRN if morphine intolerant"},
		},
		{
			OrderID:      "POSTOP-PAIN-004",
			OrderType:    models.OrderTypeMedication,
			Category:     "pain_management",
			Name:         "Oxycodone PO PRN",
			Description:  "Opioid for moderate pain when tolerating PO",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			DrugCode:     "7804",
			DrugName:     "Oxycodone",
			Dose:         "5-10 mg",
			DoseValue:    5,
			DoseUnit:     "mg",
			Route:        "PO",
			Frequency:    "q4h",
			PRN:          true,
			PRNReason:    "moderate pain (NRS ≥4)",
			Instructions: "Use when tolerating oral intake. Start with 5mg for opioid-naive.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "7804", Display: "Oxycodone"},
			},
		},

		// Nausea/Vomiting Prophylaxis
		{
			OrderID:      "POSTOP-PONV-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "ponv_prophylaxis",
			Name:         "Ondansetron PRN",
			Description:  "Antiemetic for post-operative nausea",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "7847",
			DrugName:     "Ondansetron",
			Dose:         "4 mg",
			DoseValue:    4,
			DoseUnit:     "mg",
			Route:        "IV",
			Frequency:    "q6h",
			PRN:          true,
			PRNReason:    "nausea or vomiting",
			MaxDailyDose: "16 mg/day",
			Instructions: "May give scheduled if high PONV risk. Avoid in QT prolongation.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "7847", Display: "Ondansetron"},
			},
		},
		{
			OrderID:      "POSTOP-PONV-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "ponv_prophylaxis",
			Name:         "Promethazine PRN",
			Description:  "Second-line antiemetic",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			DrugCode:     "8745",
			DrugName:     "Promethazine",
			Dose:         "12.5-25 mg",
			DoseValue:    12.5,
			DoseUnit:     "mg",
			Route:        "IV",
			Frequency:    "q6h",
			PRN:          true,
			PRNReason:    "nausea refractory to ondansetron",
			Instructions: "Dilute and give over 10-15 min via large vein. Causes sedation.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "8745", Display: "Promethazine"},
			},
		},

		// VTE Prophylaxis
		{
			OrderID:      "POSTOP-VTE-001",
			OrderType:    models.OrderTypeVTE,
			Category:     "vte_prophylaxis",
			Name:         "Enoxaparin VTE Prophylaxis",
			Description:  "Low molecular weight heparin for DVT prevention",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "67108",
			DrugName:     "Enoxaparin",
			Dose:         "40 mg",
			DoseValue:    40,
			DoseUnit:     "mg",
			Route:        "SubQ",
			Frequency:    "daily",
			Duration:     "until_ambulatory",
			Instructions: "Start 6-12 hours post-op if hemostasis adequate. Reduce to 30mg if CrCl<30.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "67108", Display: "Enoxaparin"},
			},
			Conditions: []models.OrderCondition{
				{Type: "unless", Field: "active_bleeding", Operator: "eq", Value: "true"},
				{Type: "unless", Field: "platelet_count", Operator: "lt", Value: "50000"},
			},
			Alternatives: []string{"Heparin 5000 units SubQ q8h if CrCl<30"},
		},
		{
			OrderID:      "POSTOP-VTE-002",
			OrderType:    models.OrderTypeVTE,
			Category:     "vte_prophylaxis",
			Name:         "Sequential Compression Devices",
			Description:  "Mechanical VTE prophylaxis",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Apply to bilateral lower extremities. Use whenever in bed. Remove for ambulation.",
		},

		// IV Fluids
		{
			OrderID:      "POSTOP-IVF-001",
			OrderType:    models.OrderTypeIVFluids,
			Category:     "fluids",
			Name:         "Lactated Ringer's Maintenance",
			Description:  "Maintenance IV fluid",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			DrugCode:     "313002",
			DrugName:     "Lactated Ringer's",
			Dose:         "125 mL/hr",
			Route:        "IV",
			Instructions: "Adjust rate based on urine output goal 0.5 mL/kg/hr. D/C when tolerating PO.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "313002", Display: "Lactated Ringer's"},
			},
		},

		// GI Prophylaxis
		{
			OrderID:      "POSTOP-GI-001",
			OrderType:    models.OrderTypeMedication,
			Category:     "gi_prophylaxis",
			Name:         "Famotidine Stress Ulcer Prophylaxis",
			Description:  "H2 blocker for stress ulcer prevention",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     true,
			DrugCode:     "4278",
			DrugName:     "Famotidine",
			Dose:         "20 mg",
			DoseValue:    20,
			DoseUnit:     "mg",
			Route:        "IV",
			Frequency:    "q12h",
			Duration:     "while_npo",
			Instructions: "Continue until tolerating oral diet. Switch to PO when able.",
			Codes: []models.CodeReference{
				{System: "rxnorm", Code: "4278", Display: "Famotidine"},
			},
		},

		// Diet and Activity
		{
			OrderID:      "POSTOP-DIET-001",
			OrderType:    models.OrderTypeDiet,
			Category:     "diet",
			Name:         "NPO to Clear Liquids",
			Description:  "Diet advancement protocol",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "NPO until bowel sounds present and passing flatus. Advance clear liquids → regular as tolerated.",
		},
		{
			OrderID:      "POSTOP-ACTIVITY-001",
			OrderType:    models.OrderTypeActivity,
			Category:     "activity",
			Name:         "Early Ambulation Protocol",
			Description:  "ERAS early mobility",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "OOB to chair POD0 evening if stable. Ambulate TID starting POD1. PT consult for major surgery.",
		},

		// Respiratory Care
		{
			OrderID:      "POSTOP-RESP-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "respiratory",
			Name:         "Incentive Spirometry",
			Description:  "Pulmonary toilet for atelectasis prevention",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Use q1h while awake. Goal 10 breaths per session. Document volumes.",
		},
		{
			OrderID:      "POSTOP-RESP-002",
			OrderType:    models.OrderTypeMedication,
			Category:     "respiratory",
			Name:         "Supplemental Oxygen",
			Description:  "Oxygen therapy PRN",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "O2 via nasal cannula to maintain SpO2 ≥94%. Wean as tolerated.",
		},

		// Labs
		{
			OrderID:      "POSTOP-LAB-001",
			OrderType:    models.OrderTypeLab,
			Category:     "labs",
			Name:         "CBC POD1",
			Description:  "Post-operative hemoglobin check",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			LabCode:      "58410-2",
			LabPanel:     "CBC",
			Specimen:     "blood",
			Timing:       "POD1_AM",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "58410-2", Display: "CBC panel"},
			},
		},
		{
			OrderID:      "POSTOP-LAB-002",
			OrderType:    models.OrderTypeLab,
			Category:     "labs",
			Name:         "BMP POD1",
			Description:  "Electrolyte and renal function check",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			LabCode:      "51990-0",
			LabPanel:     "BMP",
			Specimen:     "blood",
			Timing:       "POD1_AM",
			Codes: []models.CodeReference{
				{System: "loinc", Code: "51990-0", Display: "Basic metabolic panel"},
			},
		},

		// Nursing Alerts
		{
			OrderID:      "POSTOP-ALERT-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "alerts",
			Name:         "Notify MD Parameters",
			Description:  "Parameters for physician notification",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Notify MD: HR<50 or >120, SBP<90 or >180, RR<10 or >30, SpO2<92%, UOP<30mL/hr x 2hr, temp>38.5°C, altered mental status, significant bleeding",
		},
	}

	return &models.OrderSetTemplate{
		TemplateID:      "PROC-POSTOP-001",
		Category:        models.CategoryProcedure,
		Name:            "Post-Operative Care",
		Version:         "2024.1",
		GuidelineSource: "ERAS Society Guidelines, ASA Post-Anesthesia Care Standards",
		Description:     "Comprehensive post-operative care order set including pain management, VTE prophylaxis, monitoring, and early recovery protocols",
		Orders:          orders,
		Active:          true,
	}
}

// GetSurgicalAdmissionOrderSet returns general surgical admission orders
func GetSurgicalAdmissionOrderSet() *models.OrderSetTemplate {
	orders := []models.Order{
		// Admission Orders
		{
			OrderID:      "SURGADM-001",
			OrderType:    models.OrderTypeNursing,
			Category:     "admission",
			Name:         "Admit to Surgical Service",
			Description:  "Admission to surgical floor or ICU",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Admit to surgical service under attending [NAME]. Level of care per clinical status.",
		},
		{
			OrderID:      "SURGADM-002",
			OrderType:    models.OrderTypeNursing,
			Category:     "admission",
			Name:         "Diagnosis",
			Description:  "Primary surgical diagnosis",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Document primary diagnosis, secondary diagnoses, and planned procedure",
		},
		{
			OrderID:      "SURGADM-003",
			OrderType:    models.OrderTypeNursing,
			Category:     "admission",
			Name:         "Code Status",
			Description:  "Resuscitation preferences",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Document code status. Review and confirm with patient/family.",
		},
		{
			OrderID:      "SURGADM-004",
			OrderType:    models.OrderTypeNursing,
			Category:     "admission",
			Name:         "Allergies",
			Description:  "Document allergies and reactions",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Verify and document all medication, food, and environmental allergies with reaction type",
		},
		{
			OrderID:      "SURGADM-005",
			OrderType:    models.OrderTypeDiet,
			Category:     "diet",
			Name:         "Surgical Diet Order",
			Description:  "Diet based on procedure",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "NPO if pre-operative. Post-op: advance as tolerated per procedure protocol.",
		},
		{
			OrderID:      "SURGADM-006",
			OrderType:    models.OrderTypeActivity,
			Category:     "activity",
			Name:         "Activity Level",
			Description:  "Mobility orders",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Activity as tolerated unless procedure-specific restrictions. Fall precautions if indicated.",
		},

		// Monitoring
		{
			OrderID:      "SURGADM-007",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "monitoring",
			Name:         "Vital Signs",
			Description:  "Vital sign monitoring frequency",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "VS q4h routine. Increase to q1h if unstable. Document pain score with each VS.",
		},
		{
			OrderID:      "SURGADM-008",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "monitoring",
			Name:         "Daily Weights",
			Description:  "Weight monitoring",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Daily weight each AM before breakfast. Report change >2kg to MD.",
		},
		{
			OrderID:      "SURGADM-009",
			OrderType:    models.OrderTypeMonitoring,
			Category:     "monitoring",
			Name:         "Blood Glucose Monitoring",
			Description:  "Glucose checks for diabetics",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			Instructions: "Fingerstick glucose AC and HS. Target 140-180 mg/dL. Notify MD if <70 or >250.",
			Conditions: []models.OrderCondition{
				{Type: "if", Field: "diabetes", Operator: "eq", Value: "true"},
			},
		},

		// Labs
		{
			OrderID:      "SURGADM-010",
			OrderType:    models.OrderTypeLab,
			Category:     "labs",
			Name:         "Admission Labs",
			Description:  "Standard surgical admission labs",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			LabCode:      "admission_panel",
			LabPanel:     "CBC, BMP, Coags",
			Specimen:     "blood",
			Timing:       "on_admission",
		},

		// Nursing Care
		{
			OrderID:      "SURGADM-011",
			OrderType:    models.OrderTypeNursing,
			Category:     "nursing",
			Name:         "Wound Care",
			Description:  "Surgical wound management",
			Priority:     models.PriorityRoutine,
			Required:     true,
			Selected:     true,
			Instructions: "Keep surgical dressing clean and dry x 48h. Assess wound q shift for signs of infection.",
		},
		{
			OrderID:      "SURGADM-012",
			OrderType:    models.OrderTypeNursing,
			Category:     "nursing",
			Name:         "Drain Management",
			Description:  "Surgical drain care",
			Priority:     models.PriorityRoutine,
			Required:     false,
			Selected:     false,
			Instructions: "Record drain output q shift. Strip drains per protocol. Notify MD if output >100mL/hr.",
		},
	}

	return &models.OrderSetTemplate{
		TemplateID:      "PROC-SURGADM-001",
		Category:        models.CategoryProcedure,
		Name:            "Surgical Service Admission",
		Version:         "2024.1",
		GuidelineSource: "ACS NSQIP Best Practices",
		Description:     "General admission orders for surgical service patients",
		Orders:          orders,
		Active:          true,
	}
}

// GetSurgicalProcedureOrderSets returns all surgical procedure order sets
func GetSurgicalProcedureOrderSets() []*models.OrderSetTemplate {
	return []*models.OrderSetTemplate{
		GetPreOperativeAssessmentOrderSet(),
		GetPostOperativeCareOrderSet(),
		GetSurgicalAdmissionOrderSet(),
	}
}
