package services

func (r *ProtocolRegistry) registerHTN1() {
	r.templates["HTN-1"] = &ProtocolTemplate{
		ProtocolID:   "HTN-1",
		ProtocolName: "Blood Pressure Management Protocol",
		Version:      "1.0.0",
		Category:     "medication",
		Subcategory:  "hemodynamic",
		IsLifelong:   true,
		SuccessMode:  SuccessModeNever,
		TargetMetric: "sbp",
		GuidelineRef: "ADA 2026 Standards of Care Section 10 + AHA PREVENT 2024",
		Targets: &TargetRange{
			Metric:      "sbp",
			Unit:        "mmHg",
			DefaultLow:  90,
			DefaultHigh: 130,
			IndividualisedTargets: []IndividualisedTarget{
				{Archetype: "HighPREVENT", Low: 90, High: 120, Rationale: "AHA PREVENT 10-yr risk ≥15%: intensive target per SPRINT"},
				{Archetype: "IntermediatePREVENT", Low: 90, High: 120, Rationale: "AHA PREVENT 10-yr risk 7.5-14.9%: consider intensive target"},
				{Archetype: "ElderlyFrail", Low: 90, High: 140, Rationale: "ADA 2026 Sec 10: relaxed target, PG-21 dampening applied"},
				{Archetype: "CKDProgressor", Low: 90, High: 130, Rationale: "Standard target; ACEi/ARB mandatory for ACR ≥ 30"},
			},
		},
		Phases: []PhaseDefinition{
			{ID: "BASELINE", Name: "Assessment", DurationDays: 7, AutoAdvance: false, ActiveDrugSteps: []int{}},
			{ID: "MONOTHERAPY", Name: "ACEi/ARB Titration", DurationDays: 28, ExtendableTo: 42, ActiveDrugSteps: []int{1}},
			{ID: "DUAL_THERAPY", Name: "Add CCB", DurationDays: 28, ExtendableTo: 42, ActiveDrugSteps: []int{1, 2}},
			{ID: "TRIPLE_THERAPY", Name: "Add Thiazide", DurationDays: 28, ExtendableTo: 42, ActiveDrugSteps: []int{1, 2, 3}},
			{ID: "RESISTANT_HTN", Name: "Add Spironolactone", DurationDays: 0, ActiveDrugSteps: []int{1, 2, 3, 4}}, // indefinite
		},
		DrugSequence: []DrugStep{
			{
				StepOrder:         1,
				DrugClass:         "acei_arb",
				DrugName:          "ramipril",
				StartingDoseMg:    2.5,
				DoseIncrementMg:   2.5,
				MaxDoseMg:         10,
				FrequencyPerDay:   1,
				EscalationTrigger: "sbp_above_target_4wk",
				ChannelBGuards:    []string{"B-03", "B-04"},
				ChannelCGuards:    []string{"PG-14"},
				Notes:             "Mandatory if ACR ≥ 30 mg/g. Max tolerated dose for renoprotection. ADA 2026 Rec 10.22.",
			},
			{
				StepOrder:         2,
				DrugClass:         "ccb",
				DrugName:          "amlodipine",
				StartingDoseMg:    2.5,
				DoseIncrementMg:   2.5,
				MaxDoseMg:         10,
				FrequencyPerDay:   1,
				EscalationTrigger: "sbp_above_target_4wk_on_step1",
				ChannelBGuards:    []string{"B-15"},
				ChannelCGuards:    []string{},
				Notes:             "Second-line add-on. Check for pedal oedema. ADA 2026 Rec 10.24.",
			},
			{
				StepOrder:         3,
				DrugClass:         "thiazide_like",
				DrugName:          "chlorthalidone",
				StartingDoseMg:    12.5,
				DoseIncrementMg:   12.5,
				MaxDoseMg:         25,
				FrequencyPerDay:   1,
				EscalationTrigger: "sbp_above_target_4wk_on_step2",
				ChannelBGuards:    []string{"B-17", "B-18", "B-19"},
				ChannelCGuards:    []string{},
				Notes:             "Third-line. Monitor Na+, K+, uric acid. ADA 2026 Rec 10.26.",
			},
			{
				StepOrder:         4,
				DrugClass:         "mra",
				DrugName:          "spironolactone",
				StartingDoseMg:    25,
				DoseIncrementMg:   25,
				MaxDoseMg:         50,
				FrequencyPerDay:   1,
				EscalationTrigger: "resistant_htn_confirmed",
				ChannelBGuards:    []string{"B-03"},
				ChannelCGuards:    []string{"PG-14"},
				Notes:             "Fourth-line for resistant hypertension. Monitor K+ closely. PATHWAY-2 evidence.",
			},
		},
		EntryCriteria: []Criterion{
			{Field: "sbp", Operator: ">=", Value: 140},
			{Field: "dbp", Operator: ">=", Value: 90},
			{Field: "has_hypertension", Operator: "==", Value: 1},
		},
		ExclusionCriteria: []ExclusionRule{
			{Field: "bilateral_renal_artery_stenosis", Operator: "==", Value: 1, RuleCode: "BRAS-EXCL"},
			{Field: "pregnancy_status", Operator: "==", Value: 1, RuleCode: "PREG-EXCL"},
		},
		ConcurrentWith:    []string{"GLYC-1", "RENAL-1", "LIPID-1", "M3-PRP", "M3-VFRP", "DEPRESC-1", "V-MCU"},
		EscalationTrigger: "sbp_above_target_on_4_agents",
	}
}
