CREATE (:Nutrient {code: 'NUT_FIBER', name: 'Dietary Fiber', unit: 'g'});
CREATE (:Nutrient {code: 'NUT_SODIUM', name: 'Sodium', unit: 'mg'});
CREATE (:Nutrient {code: 'NUT_POTASSIUM', name: 'Potassium', unit: 'mg'});
CREATE (:Nutrient {code: 'NUT_MAGNESIUM', name: 'Magnesium', unit: 'mg'});
CREATE (:Nutrient {code: 'NUT_CALCIUM', name: 'Calcium', unit: 'mg'});
CREATE (:Nutrient {code: 'NUT_IRON', name: 'Iron', unit: 'mg'});
CREATE (:Nutrient {code: 'NUT_ZINC', name: 'Zinc', unit: 'mg'});
CREATE (:Nutrient {code: 'NUT_VIT_D', name: 'Vitamin D', unit: 'IU'});
CREATE (:Nutrient {code: 'NUT_VIT_B12', name: 'Vitamin B12', unit: 'mcg'});
CREATE (:Nutrient {code: 'NUT_FOLATE', name: 'Folate', unit: 'mcg'});
CREATE (:Nutrient {code: 'NUT_VIT_C', name: 'Vitamin C', unit: 'mg'});
CREATE (:Nutrient {code: 'NUT_OMEGA3', name: 'Omega-3 Fatty Acids', unit: 'g'});
CREATE (:Nutrient {code: 'NUT_PROTEIN', name: 'Protein', unit: 'g'});
CREATE (:Nutrient {code: 'NUT_CARB', name: 'Carbohydrates', unit: 'g'});
CREATE (:Nutrient {code: 'NUT_FAT', name: 'Total Fat', unit: 'g'});
CREATE (:Nutrient {code: 'NUT_SAT_FAT', name: 'Saturated Fat', unit: 'g'});
CREATE (:Nutrient {code: 'NUT_MUFA', name: 'Monounsaturated Fat', unit: 'g'});
CREATE (:Nutrient {code: 'NUT_PUFA', name: 'Polyunsaturated Fat', unit: 'g'});
CREATE (:Nutrient {code: 'NUT_CHROMIUM', name: 'Chromium', unit: 'mcg'});
CREATE (:Nutrient {code: 'NUT_CURCUMIN', name: 'Curcumin', unit: 'mg'});
