// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/clinical_engine.proto

package clinical_engine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClinicalEngine_ExecuteFlow2_FullMethodName                  = "/clinical_engine.ClinicalEngine/ExecuteFlow2"
	ClinicalEngine_ExecuteMedicationIntelligence_FullMethodName = "/clinical_engine.ClinicalEngine/ExecuteMedicationIntelligence"
	ClinicalEngine_ExecuteDoseOptimization_FullMethodName       = "/clinical_engine.ClinicalEngine/ExecuteDoseOptimization"
	ClinicalEngine_ExecuteSafetyValidation_FullMethodName       = "/clinical_engine.ClinicalEngine/ExecuteSafetyValidation"
	ClinicalEngine_HealthCheck_FullMethodName                   = "/clinical_engine.ClinicalEngine/HealthCheck"
)

// ClinicalEngineClient is the client API for ClinicalEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClinicalEngine service provides clinical recipe execution capabilities
type ClinicalEngineClient interface {
	// Execute Flow 2 with multiple recipes
	ExecuteFlow2(ctx context.Context, in *Flow2ExecutionRequest, opts ...grpc.CallOption) (*Flow2ExecutionResponse, error)
	// Execute medication intelligence analysis
	ExecuteMedicationIntelligence(ctx context.Context, in *MedicationIntelligenceRequest, opts ...grpc.CallOption) (*MedicationIntelligenceResponse, error)
	// Execute dose optimization
	ExecuteDoseOptimization(ctx context.Context, in *DoseOptimizationRequest, opts ...grpc.CallOption) (*DoseOptimizationResponse, error)
	// Execute safety validation
	ExecuteSafetyValidation(ctx context.Context, in *SafetyValidationRequest, opts ...grpc.CallOption) (*SafetyValidationResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type clinicalEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewClinicalEngineClient(cc grpc.ClientConnInterface) ClinicalEngineClient {
	return &clinicalEngineClient{cc}
}

func (c *clinicalEngineClient) ExecuteFlow2(ctx context.Context, in *Flow2ExecutionRequest, opts ...grpc.CallOption) (*Flow2ExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Flow2ExecutionResponse)
	err := c.cc.Invoke(ctx, ClinicalEngine_ExecuteFlow2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clinicalEngineClient) ExecuteMedicationIntelligence(ctx context.Context, in *MedicationIntelligenceRequest, opts ...grpc.CallOption) (*MedicationIntelligenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MedicationIntelligenceResponse)
	err := c.cc.Invoke(ctx, ClinicalEngine_ExecuteMedicationIntelligence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clinicalEngineClient) ExecuteDoseOptimization(ctx context.Context, in *DoseOptimizationRequest, opts ...grpc.CallOption) (*DoseOptimizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoseOptimizationResponse)
	err := c.cc.Invoke(ctx, ClinicalEngine_ExecuteDoseOptimization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clinicalEngineClient) ExecuteSafetyValidation(ctx context.Context, in *SafetyValidationRequest, opts ...grpc.CallOption) (*SafetyValidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SafetyValidationResponse)
	err := c.cc.Invoke(ctx, ClinicalEngine_ExecuteSafetyValidation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clinicalEngineClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ClinicalEngine_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClinicalEngineServer is the server API for ClinicalEngine service.
// All implementations must embed UnimplementedClinicalEngineServer
// for forward compatibility.
//
// ClinicalEngine service provides clinical recipe execution capabilities
type ClinicalEngineServer interface {
	// Execute Flow 2 with multiple recipes
	ExecuteFlow2(context.Context, *Flow2ExecutionRequest) (*Flow2ExecutionResponse, error)
	// Execute medication intelligence analysis
	ExecuteMedicationIntelligence(context.Context, *MedicationIntelligenceRequest) (*MedicationIntelligenceResponse, error)
	// Execute dose optimization
	ExecuteDoseOptimization(context.Context, *DoseOptimizationRequest) (*DoseOptimizationResponse, error)
	// Execute safety validation
	ExecuteSafetyValidation(context.Context, *SafetyValidationRequest) (*SafetyValidationResponse, error)
	// Health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedClinicalEngineServer()
}

// UnimplementedClinicalEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClinicalEngineServer struct{}

func (UnimplementedClinicalEngineServer) ExecuteFlow2(context.Context, *Flow2ExecutionRequest) (*Flow2ExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteFlow2 not implemented")
}
func (UnimplementedClinicalEngineServer) ExecuteMedicationIntelligence(context.Context, *MedicationIntelligenceRequest) (*MedicationIntelligenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteMedicationIntelligence not implemented")
}
func (UnimplementedClinicalEngineServer) ExecuteDoseOptimization(context.Context, *DoseOptimizationRequest) (*DoseOptimizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteDoseOptimization not implemented")
}
func (UnimplementedClinicalEngineServer) ExecuteSafetyValidation(context.Context, *SafetyValidationRequest) (*SafetyValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteSafetyValidation not implemented")
}
func (UnimplementedClinicalEngineServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedClinicalEngineServer) mustEmbedUnimplementedClinicalEngineServer() {}
func (UnimplementedClinicalEngineServer) testEmbeddedByValue()                        {}

// UnsafeClinicalEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClinicalEngineServer will
// result in compilation errors.
type UnsafeClinicalEngineServer interface {
	mustEmbedUnimplementedClinicalEngineServer()
}

func RegisterClinicalEngineServer(s grpc.ServiceRegistrar, srv ClinicalEngineServer) {
	// If the following call pancis, it indicates UnimplementedClinicalEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClinicalEngine_ServiceDesc, srv)
}

func _ClinicalEngine_ExecuteFlow2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Flow2ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClinicalEngineServer).ExecuteFlow2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClinicalEngine_ExecuteFlow2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClinicalEngineServer).ExecuteFlow2(ctx, req.(*Flow2ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClinicalEngine_ExecuteMedicationIntelligence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MedicationIntelligenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClinicalEngineServer).ExecuteMedicationIntelligence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClinicalEngine_ExecuteMedicationIntelligence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClinicalEngineServer).ExecuteMedicationIntelligence(ctx, req.(*MedicationIntelligenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClinicalEngine_ExecuteDoseOptimization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoseOptimizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClinicalEngineServer).ExecuteDoseOptimization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClinicalEngine_ExecuteDoseOptimization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClinicalEngineServer).ExecuteDoseOptimization(ctx, req.(*DoseOptimizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClinicalEngine_ExecuteSafetyValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SafetyValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClinicalEngineServer).ExecuteSafetyValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClinicalEngine_ExecuteSafetyValidation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClinicalEngineServer).ExecuteSafetyValidation(ctx, req.(*SafetyValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClinicalEngine_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClinicalEngineServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClinicalEngine_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClinicalEngineServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClinicalEngine_ServiceDesc is the grpc.ServiceDesc for ClinicalEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClinicalEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clinical_engine.ClinicalEngine",
	HandlerType: (*ClinicalEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteFlow2",
			Handler:    _ClinicalEngine_ExecuteFlow2_Handler,
		},
		{
			MethodName: "ExecuteMedicationIntelligence",
			Handler:    _ClinicalEngine_ExecuteMedicationIntelligence_Handler,
		},
		{
			MethodName: "ExecuteDoseOptimization",
			Handler:    _ClinicalEngine_ExecuteDoseOptimization_Handler,
		},
		{
			MethodName: "ExecuteSafetyValidation",
			Handler:    _ClinicalEngine_ExecuteSafetyValidation_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ClinicalEngine_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/clinical_engine.proto",
}
