package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// Collector holds all KB-23 Prometheus metrics.
type Collector struct {
	// Card generation
	CardsGenerated        *prometheus.CounterVec
	CardGenerationLatency prometheus.Histogram

	// Gate transitions
	GateTransitions  *prometheus.CounterVec
	GateQueryLatency prometheus.Histogram

	// Safety fast-path
	HypoglycaemiaAlerts *prometheus.CounterVec
	BehavioralGapAlerts *prometheus.CounterVec
	SafetyAlertLatency  prometheus.Histogram

	// Perturbation tracking
	PerturbationsReceived    prometheus.Counter
	PerturbationQueryLatency prometheus.Histogram

	// Cross-KB communication
	KB19PublishLatency prometheus.Histogram
	KB20FetchLatency   prometheus.Histogram
	KB21FetchLatency   prometheus.Histogram
	KB19PublishErrors  prometheus.Counter

	// Template loading
	TemplatesLoaded prometheus.Gauge
	TemplateReloads prometheus.Counter

	// Hysteresis
	HysteresisBlocked prometheus.Counter
	HysteresisAllowed prometheus.Counter

	// Composite cards
	CompositeCardsCreated prometheus.Counter
	UrgencyUpgrades       prometheus.Counter

	// Phase 7 P7-A: Reactive renal dose gating outcomes.
	// Labelled by drug_class so dashboards can separate metformin vs SGLT2i
	// vs RAAS trajectories. RenalReactiveLatency is measured end-to-end from
	// priority signal receipt to card persistence.
	RenalContraindicationDetected *prometheus.CounterVec
	RenalDoseReduceDetected       *prometheus.CounterVec
	RenalReactiveLatency          prometheus.Histogram

	// Phase 7 P7-B: CKM 4c transition + mandatory-med-check outcomes.
	// CKMStageTransitions is labelled by from/to so dashboards can
	// track both 4c entries (the case we act on) and every other
	// transition observed on the priority topic for audit.
	// CKM4cMandatoryMedAlerts is labelled by drug_class so dashboards
	// can show which GDMT class gaps are most common on 4c transitions.
	CKMStageTransitions      *prometheus.CounterVec
	CKM4cMandatoryMedAlerts  *prometheus.CounterVec

	// Phase 7 P7-C: Renal anticipatory monthly batch outcomes.
	// RenalAnticipatoryAlerts is labelled by drug_class + horizon
	// (CONTRAINDICATION | DOSE_REDUCE | EFFICACY_CLIFF) so dashboards
	// can separate out imminent vs distant projected crossings.
	// StaleEGFR is labelled by CKD stage so dashboards can surface
	// which cohorts are overdue for surveillance.
	// RenalAnticipatoryBatchDuration records end-to-end batch run time
	// in seconds so slow-down regressions are observable.
	RenalAnticipatoryAlerts       *prometheus.CounterVec
	StaleEGFRDetected             *prometheus.CounterVec
	RenalAnticipatoryBatchDuration prometheus.Histogram

	// Phase 7 P7-D: Inertia weekly batch outcomes.
	// InertiaVerdictsDetected is labelled by domain (GLYCAEMIC/HEMODYNAMIC/
	// RENAL) and severity (MILD/MODERATE/SEVERE/CRITICAL).
	// DualDomainInertiaDetected is a simple counter since dual-domain
	// is itself the composite signal — a label would be redundant.
	// InertiaWeeklyBatchDuration records end-to-end batch run time.
	InertiaVerdictsDetected     *prometheus.CounterVec
	DualDomainInertiaDetected   prometheus.Counter
	InertiaWeeklyBatchDuration  prometheus.Histogram

	// Phase 9 P9-A: adherence-exclusion branch outcomes.
	// AdherenceGapDetected is labelled by domain so dashboards show
	// which clinical domains are most affected by non-adherence.
	// InertiaSuppressedByAdherence is the total count of inertia
	// verdicts that were suppressed because the patient was
	// disengaged — the "false positive prevention" counter.
	AdherenceGapDetected           *prometheus.CounterVec
	InertiaSuppressedByAdherence   prometheus.Counter

	// Phase 9 P9-B: monitoring engagement batch outcomes.
	MonitoringLapsedDetected      *prometheus.CounterVec
	MonitoringLapsedBatchDuration prometheus.Histogram

	// Phase 9 P9-F: deprescribing review cards for polypharmacy-
	// elderly patients. Counter of cards generated — advisory cards
	// that accompany inertia verdicts, not replacements for them.
	DeprescribingReviewGenerated prometheus.Counter

	// Phase 10 P10-D: circuit breaker observability. Labelled by
	// service name (kb20, kb26) and state transition direction
	// (from→to). Enables Grafana alerts on open circuits.
	CircuitBreakerTransitions *prometheus.CounterVec
}

func NewCollector() *Collector {
	return &Collector{
		CardsGenerated: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_cards_generated_total",
			Help: "Decision cards generated by source and template",
		}, []string{"source", "template_id"}),

		CardGenerationLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_card_generation_latency_ms",
			Help:    "Card generation time in milliseconds",
			Buckets: []float64{5, 10, 20, 30, 50, 75, 100, 200, 500},
		}),

		GateTransitions: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_gate_transitions_total",
			Help: "MCU gate transitions by from/to gate",
		}, []string{"from_gate", "to_gate"}),

		GateQueryLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_gate_query_latency_ms",
			Help:    "GET /patients/:id/mcu-gate latency (target < 5ms)",
			Buckets: []float64{1, 2, 3, 5, 7, 10, 20, 50},
		}),

		HypoglycaemiaAlerts: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_hypoglycaemia_alerts_total",
			Help: "Hypoglycaemia fast-path alerts by severity and source",
		}, []string{"severity", "source"}),

		BehavioralGapAlerts: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_behavioral_gap_alerts_total",
			Help: "KB-21 behavioral gap alerts by response class",
		}, []string{"response_class"}),

		SafetyAlertLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_safety_alert_latency_ms",
			Help:    "Safety fast-path processing time",
			Buckets: []float64{5, 10, 20, 50, 100, 200, 500, 1000, 2000},
		}),

		PerturbationsReceived: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_perturbations_received_total",
			Help: "Treatment perturbation records received from V-MCU",
		}),

		PerturbationQueryLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_perturbation_query_latency_ms",
			Help:    "GET /perturbations/:patient_id/active latency (target < 3ms)",
			Buckets: []float64{0.5, 1, 2, 3, 5, 10, 20},
		}),

		KB19PublishLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_kb19_publish_latency_ms",
			Help:    "KB-19 event publish latency",
			Buckets: []float64{10, 50, 100, 200, 500, 1000, 2000},
		}),

		KB20FetchLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_kb20_fetch_latency_ms",
			Help:    "KB-20 patient context fetch latency",
			Buckets: []float64{5, 10, 20, 50, 100, 200},
		}),

		KB21FetchLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_kb21_fetch_latency_ms",
			Help:    "KB-21 adherence fetch latency",
			Buckets: []float64{5, 10, 20, 50, 100, 200},
		}),

		KB19PublishErrors: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_kb19_publish_errors_total",
			Help: "KB-19 event publish failures",
		}),

		TemplatesLoaded: promauto.NewGauge(prometheus.GaugeOpts{
			Name: "kb23_templates_loaded",
			Help: "Number of card templates currently loaded",
		}),

		TemplateReloads: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_template_reloads_total",
			Help: "Template hot-reload events",
		}),

		HysteresisBlocked: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_hysteresis_blocked_total",
			Help: "Gate downgrades blocked by hysteresis rules",
		}),

		HysteresisAllowed: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_hysteresis_allowed_total",
			Help: "Gate downgrades allowed after hysteresis confirmation",
		}),

		CompositeCardsCreated: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_composite_cards_created_total",
			Help: "72-hour composite card syntheses",
		}),

		UrgencyUpgrades: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_urgency_upgrades_total",
			Help: "Urgency upgrades from 3+ recurrences",
		}),

		RenalContraindicationDetected: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_renal_contraindication_detected_total",
			Help: "Reactive renal contraindication cards generated, by drug class (Phase 7 P7-A)",
		}, []string{"drug_class"}),

		RenalDoseReduceDetected: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_renal_dose_reduce_detected_total",
			Help: "Reactive renal dose-reduction cards generated, by drug class (Phase 7 P7-A)",
		}, []string{"drug_class"}),

		RenalReactiveLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_renal_reactive_latency_seconds",
			Help:    "End-to-end latency from EGFR_LAB priority signal receipt to renal card persistence",
			Buckets: []float64{0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2, 5},
		}),

		CKMStageTransitions: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_ckm_stage_transitions_total",
			Help: "CKM stage transition events observed on the priority topic, by from/to stage (Phase 7 P7-B)",
		}, []string{"from", "to"}),

		CKM4cMandatoryMedAlerts: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_ckm_4c_mandatory_med_alerts_total",
			Help: "CKM 4c mandatory-medication gap alerts generated, by missing drug class (Phase 7 P7-B)",
		}, []string{"drug_class"}),

		RenalAnticipatoryAlerts: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_renal_anticipatory_alerts_total",
			Help: "Anticipatory renal threshold-approaching alerts, by drug class and horizon type (Phase 7 P7-C)",
		}, []string{"drug_class", "horizon"}),

		StaleEGFRDetected: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_stale_egfr_total",
			Help: "Stale-eGFR surveillance alerts, by CKD stage (Phase 7 P7-C)",
		}, []string{"ckd_stage"}),

		RenalAnticipatoryBatchDuration: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_renal_anticipatory_batch_duration_seconds",
			Help:    "End-to-end duration of the monthly renal anticipatory batch run",
			Buckets: []float64{1, 5, 15, 30, 60, 120, 300, 600, 1200, 3600},
		}),

		InertiaVerdictsDetected: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_inertia_verdicts_detected_total",
			Help: "Therapeutic inertia verdicts persisted as cards, by domain and severity (Phase 7 P7-D)",
		}, []string{"domain", "severity"}),

		DualDomainInertiaDetected: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_dual_domain_inertia_detected_total",
			Help: "Dual-domain inertia cards persisted (composite signal, Phase 7 P7-D)",
		}),

		InertiaWeeklyBatchDuration: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_inertia_weekly_batch_duration_seconds",
			Help:    "End-to-end duration of the weekly inertia batch run",
			Buckets: []float64{1, 5, 15, 30, 60, 120, 300, 600, 1200, 3600},
		}),

		AdherenceGapDetected: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_adherence_gap_detected_total",
			Help: "Adherence gap cards generated (inertia suppressed due to disengagement), by domain (Phase 9 P9-A)",
		}, []string{"domain"}),

		InertiaSuppressedByAdherence: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_inertia_suppressed_by_adherence_total",
			Help: "Inertia verdicts suppressed because patient was disengaged (Phase 9 P9-A false-positive prevention counter)",
		}),

		MonitoringLapsedDetected: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_monitoring_lapsed_total",
			Help: "Monitoring-lapsed cards generated, by monitor type (Phase 9 P9-B)",
		}, []string{"monitor_type"}),

		MonitoringLapsedBatchDuration: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_monitoring_lapsed_batch_duration_seconds",
			Help:    "End-to-end duration of the weekly monitoring engagement batch run",
			Buckets: []float64{1, 5, 15, 30, 60, 120, 300},
		}),

		DeprescribingReviewGenerated: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_deprescribing_review_generated_total",
			Help: "Deprescribing review cards generated for polypharmacy-elderly patients alongside inertia detection (Phase 9 P9-F)",
		}),

		CircuitBreakerTransitions: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_circuit_breaker_transitions_total",
			Help: "Circuit breaker state transitions by service and direction (Phase 10 P10-D)",
		}, []string{"service", "from", "to"}),
	}
}

