package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// Collector holds all KB-23 Prometheus metrics.
type Collector struct {
	// Card generation
	CardsGenerated        *prometheus.CounterVec
	CardGenerationLatency prometheus.Histogram

	// Gate transitions
	GateTransitions  *prometheus.CounterVec
	GateQueryLatency prometheus.Histogram

	// Safety fast-path
	HypoglycaemiaAlerts *prometheus.CounterVec
	BehavioralGapAlerts *prometheus.CounterVec
	SafetyAlertLatency  prometheus.Histogram

	// Perturbation tracking
	PerturbationsReceived    prometheus.Counter
	PerturbationQueryLatency prometheus.Histogram

	// Cross-KB communication
	KB19PublishLatency prometheus.Histogram
	KB20FetchLatency   prometheus.Histogram
	KB21FetchLatency   prometheus.Histogram
	KB19PublishErrors  prometheus.Counter

	// Template loading
	TemplatesLoaded prometheus.Gauge
	TemplateReloads prometheus.Counter

	// Hysteresis
	HysteresisBlocked prometheus.Counter
	HysteresisAllowed prometheus.Counter

	// Composite cards
	CompositeCardsCreated prometheus.Counter
	UrgencyUpgrades       prometheus.Counter
}

func NewCollector() *Collector {
	return &Collector{
		CardsGenerated: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_cards_generated_total",
			Help: "Decision cards generated by source and template",
		}, []string{"source", "template_id"}),

		CardGenerationLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_card_generation_latency_ms",
			Help:    "Card generation time in milliseconds",
			Buckets: []float64{5, 10, 20, 30, 50, 75, 100, 200, 500},
		}),

		GateTransitions: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_gate_transitions_total",
			Help: "MCU gate transitions by from/to gate",
		}, []string{"from_gate", "to_gate"}),

		GateQueryLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_gate_query_latency_ms",
			Help:    "GET /patients/:id/mcu-gate latency (target < 5ms)",
			Buckets: []float64{1, 2, 3, 5, 7, 10, 20, 50},
		}),

		HypoglycaemiaAlerts: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_hypoglycaemia_alerts_total",
			Help: "Hypoglycaemia fast-path alerts by severity and source",
		}, []string{"severity", "source"}),

		BehavioralGapAlerts: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "kb23_behavioral_gap_alerts_total",
			Help: "KB-21 behavioral gap alerts by response class",
		}, []string{"response_class"}),

		SafetyAlertLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_safety_alert_latency_ms",
			Help:    "Safety fast-path processing time",
			Buckets: []float64{5, 10, 20, 50, 100, 200, 500, 1000, 2000},
		}),

		PerturbationsReceived: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_perturbations_received_total",
			Help: "Treatment perturbation records received from V-MCU",
		}),

		PerturbationQueryLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_perturbation_query_latency_ms",
			Help:    "GET /perturbations/:patient_id/active latency (target < 3ms)",
			Buckets: []float64{0.5, 1, 2, 3, 5, 10, 20},
		}),

		KB19PublishLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_kb19_publish_latency_ms",
			Help:    "KB-19 event publish latency",
			Buckets: []float64{10, 50, 100, 200, 500, 1000, 2000},
		}),

		KB20FetchLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_kb20_fetch_latency_ms",
			Help:    "KB-20 patient context fetch latency",
			Buckets: []float64{5, 10, 20, 50, 100, 200},
		}),

		KB21FetchLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "kb23_kb21_fetch_latency_ms",
			Help:    "KB-21 adherence fetch latency",
			Buckets: []float64{5, 10, 20, 50, 100, 200},
		}),

		KB19PublishErrors: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_kb19_publish_errors_total",
			Help: "KB-19 event publish failures",
		}),

		TemplatesLoaded: promauto.NewGauge(prometheus.GaugeOpts{
			Name: "kb23_templates_loaded",
			Help: "Number of card templates currently loaded",
		}),

		TemplateReloads: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_template_reloads_total",
			Help: "Template hot-reload events",
		}),

		HysteresisBlocked: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_hysteresis_blocked_total",
			Help: "Gate downgrades blocked by hysteresis rules",
		}),

		HysteresisAllowed: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_hysteresis_allowed_total",
			Help: "Gate downgrades allowed after hysteresis confirmation",
		}),

		CompositeCardsCreated: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_composite_cards_created_total",
			Help: "72-hour composite card syntheses",
		}),

		UrgencyUpgrades: promauto.NewCounter(prometheus.CounterOpts{
			Name: "kb23_urgency_upgrades_total",
			Help: "Urgency upgrades from 3+ recurrences",
		}),
	}
}
