// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/context_gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type SnapshotStatus int32

const (
	SnapshotStatus_SNAPSHOT_STATUS_UNKNOWN     SnapshotStatus = 0
	SnapshotStatus_SNAPSHOT_STATUS_ACTIVE      SnapshotStatus = 1
	SnapshotStatus_SNAPSHOT_STATUS_EXPIRED     SnapshotStatus = 2
	SnapshotStatus_SNAPSHOT_STATUS_INVALIDATED SnapshotStatus = 3
)

// Enum value maps for SnapshotStatus.
var (
	SnapshotStatus_name = map[int32]string{
		0: "SNAPSHOT_STATUS_UNKNOWN",
		1: "SNAPSHOT_STATUS_ACTIVE",
		2: "SNAPSHOT_STATUS_EXPIRED",
		3: "SNAPSHOT_STATUS_INVALIDATED",
	}
	SnapshotStatus_value = map[string]int32{
		"SNAPSHOT_STATUS_UNKNOWN":     0,
		"SNAPSHOT_STATUS_ACTIVE":      1,
		"SNAPSHOT_STATUS_EXPIRED":     2,
		"SNAPSHOT_STATUS_INVALIDATED": 3,
	}
)

func (x SnapshotStatus) Enum() *SnapshotStatus {
	p := new(SnapshotStatus)
	*p = x
	return p
}

func (x SnapshotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_context_gateway_proto_enumTypes[0].Descriptor()
}

func (SnapshotStatus) Type() protoreflect.EnumType {
	return &file_proto_context_gateway_proto_enumTypes[0]
}

func (x SnapshotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotStatus.Descriptor instead.
func (SnapshotStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{0}
}

type SignatureMethod int32

const (
	SignatureMethod_SIGNATURE_METHOD_UNKNOWN    SignatureMethod = 0
	SignatureMethod_SIGNATURE_METHOD_MOCK       SignatureMethod = 1
	SignatureMethod_SIGNATURE_METHOD_RSA_2048   SignatureMethod = 2
	SignatureMethod_SIGNATURE_METHOD_ECDSA_P256 SignatureMethod = 3
)

// Enum value maps for SignatureMethod.
var (
	SignatureMethod_name = map[int32]string{
		0: "SIGNATURE_METHOD_UNKNOWN",
		1: "SIGNATURE_METHOD_MOCK",
		2: "SIGNATURE_METHOD_RSA_2048",
		3: "SIGNATURE_METHOD_ECDSA_P256",
	}
	SignatureMethod_value = map[string]int32{
		"SIGNATURE_METHOD_UNKNOWN":    0,
		"SIGNATURE_METHOD_MOCK":       1,
		"SIGNATURE_METHOD_RSA_2048":   2,
		"SIGNATURE_METHOD_ECDSA_P256": 3,
	}
)

func (x SignatureMethod) Enum() *SignatureMethod {
	p := new(SignatureMethod)
	*p = x
	return p
}

func (x SignatureMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignatureMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_context_gateway_proto_enumTypes[1].Descriptor()
}

func (SignatureMethod) Type() protoreflect.EnumType {
	return &file_proto_context_gateway_proto_enumTypes[1]
}

func (x SignatureMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignatureMethod.Descriptor instead.
func (SignatureMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{1}
}

type ServiceStatus int32

const (
	ServiceStatus_SERVICE_STATUS_UNKNOWN   ServiceStatus = 0
	ServiceStatus_SERVICE_STATUS_HEALTHY   ServiceStatus = 1
	ServiceStatus_SERVICE_STATUS_DEGRADED  ServiceStatus = 2
	ServiceStatus_SERVICE_STATUS_UNHEALTHY ServiceStatus = 3
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "SERVICE_STATUS_UNKNOWN",
		1: "SERVICE_STATUS_HEALTHY",
		2: "SERVICE_STATUS_DEGRADED",
		3: "SERVICE_STATUS_UNHEALTHY",
	}
	ServiceStatus_value = map[string]int32{
		"SERVICE_STATUS_UNKNOWN":   0,
		"SERVICE_STATUS_HEALTHY":   1,
		"SERVICE_STATUS_DEGRADED":  2,
		"SERVICE_STATUS_UNHEALTHY": 3,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_context_gateway_proto_enumTypes[2].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_proto_context_gateway_proto_enumTypes[2]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{2}
}

type UpdateType int32

const (
	UpdateType_UPDATE_TYPE_UNKNOWN              UpdateType = 0
	UpdateType_UPDATE_TYPE_SNAPSHOT_CREATED     UpdateType = 1
	UpdateType_UPDATE_TYPE_SNAPSHOT_UPDATED     UpdateType = 2
	UpdateType_UPDATE_TYPE_SNAPSHOT_INVALIDATED UpdateType = 3
	UpdateType_UPDATE_TYPE_CACHE_INVALIDATED    UpdateType = 4
	UpdateType_UPDATE_TYPE_RECIPE_UPDATED       UpdateType = 5
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "UPDATE_TYPE_UNKNOWN",
		1: "UPDATE_TYPE_SNAPSHOT_CREATED",
		2: "UPDATE_TYPE_SNAPSHOT_UPDATED",
		3: "UPDATE_TYPE_SNAPSHOT_INVALIDATED",
		4: "UPDATE_TYPE_CACHE_INVALIDATED",
		5: "UPDATE_TYPE_RECIPE_UPDATED",
	}
	UpdateType_value = map[string]int32{
		"UPDATE_TYPE_UNKNOWN":              0,
		"UPDATE_TYPE_SNAPSHOT_CREATED":     1,
		"UPDATE_TYPE_SNAPSHOT_UPDATED":     2,
		"UPDATE_TYPE_SNAPSHOT_INVALIDATED": 3,
		"UPDATE_TYPE_CACHE_INVALIDATED":    4,
		"UPDATE_TYPE_RECIPE_UPDATED":       5,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_context_gateway_proto_enumTypes[3].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_proto_context_gateway_proto_enumTypes[3]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{3}
}

// Request Messages
type CreateSnapshotRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Recipe            *WorkflowRecipe        `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	PatientId         string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	RequestingService string                 `protobuf:"bytes,3,opt,name=requesting_service,json=requestingService,proto3" json:"requesting_service,omitempty"`
	ProviderId        *string                `protobuf:"bytes,4,opt,name=provider_id,json=providerId,proto3,oneof" json:"provider_id,omitempty"`
	EncounterId       *string                `protobuf:"bytes,5,opt,name=encounter_id,json=encounterId,proto3,oneof" json:"encounter_id,omitempty"`
	ForceRefresh      bool                   `protobuf:"varint,6,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"`
	TtlHours          int32                  `protobuf:"varint,7,opt,name=ttl_hours,json=ttlHours,proto3" json:"ttl_hours,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_proto_context_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSnapshotRequest) GetRecipe() *WorkflowRecipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

func (x *CreateSnapshotRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *CreateSnapshotRequest) GetRequestingService() string {
	if x != nil {
		return x.RequestingService
	}
	return ""
}

func (x *CreateSnapshotRequest) GetProviderId() string {
	if x != nil && x.ProviderId != nil {
		return *x.ProviderId
	}
	return ""
}

func (x *CreateSnapshotRequest) GetEncounterId() string {
	if x != nil && x.EncounterId != nil {
		return *x.EncounterId
	}
	return ""
}

func (x *CreateSnapshotRequest) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

func (x *CreateSnapshotRequest) GetTtlHours() int32 {
	if x != nil {
		return x.TtlHours
	}
	return 0
}

type GetSnapshotRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId        string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	RequestingService string                 `protobuf:"bytes,2,opt,name=requesting_service,json=requestingService,proto3" json:"requesting_service,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_proto_context_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GetSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *GetSnapshotRequest) GetRequestingService() string {
	if x != nil {
		return x.RequestingService
	}
	return ""
}

type ValidateSnapshotRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId        string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	RequestingService string                 `protobuf:"bytes,2,opt,name=requesting_service,json=requestingService,proto3" json:"requesting_service,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ValidateSnapshotRequest) Reset() {
	*x = ValidateSnapshotRequest{}
	mi := &file_proto_context_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSnapshotRequest) ProtoMessage() {}

func (x *ValidateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ValidateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *ValidateSnapshotRequest) GetRequestingService() string {
	if x != nil {
		return x.RequestingService
	}
	return ""
}

type InvalidateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId        string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Reason            string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestingService string                 `protobuf:"bytes,3,opt,name=requesting_service,json=requestingService,proto3" json:"requesting_service,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InvalidateRequest) Reset() {
	*x = InvalidateRequest{}
	mi := &file_proto_context_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateRequest) ProtoMessage() {}

func (x *InvalidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateRequest.ProtoReflect.Descriptor instead.
func (*InvalidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *InvalidateRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *InvalidateRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InvalidateRequest) GetRequestingService() string {
	if x != nil {
		return x.RequestingService
	}
	return ""
}

type LiveFetchRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId        string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	MissingFields     []string               `protobuf:"bytes,2,rep,name=missing_fields,json=missingFields,proto3" json:"missing_fields,omitempty"`
	PatientId         string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	RequestingService string                 `protobuf:"bytes,4,opt,name=requesting_service,json=requestingService,proto3" json:"requesting_service,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LiveFetchRequest) Reset() {
	*x = LiveFetchRequest{}
	mi := &file_proto_context_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveFetchRequest) ProtoMessage() {}

func (x *LiveFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveFetchRequest.ProtoReflect.Descriptor instead.
func (*LiveFetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *LiveFetchRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *LiveFetchRequest) GetMissingFields() []string {
	if x != nil {
		return x.MissingFields
	}
	return nil
}

func (x *LiveFetchRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *LiveFetchRequest) GetRequestingService() string {
	if x != nil {
		return x.RequestingService
	}
	return ""
}

type LoadRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      string                 `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	Version       *string                `protobuf:"bytes,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRecipeRequest) Reset() {
	*x = LoadRecipeRequest{}
	mi := &file_proto_context_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRecipeRequest) ProtoMessage() {}

func (x *LoadRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRecipeRequest.ProtoReflect.Descriptor instead.
func (*LoadRecipeRequest) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *LoadRecipeRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *LoadRecipeRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

type ValidateRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        *WorkflowRecipe        `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRecipeRequest) Reset() {
	*x = ValidateRecipeRequest{}
	mi := &file_proto_context_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRecipeRequest) ProtoMessage() {}

func (x *ValidateRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRecipeRequest.ProtoReflect.Descriptor instead.
func (*ValidateRecipeRequest) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateRecipeRequest) GetRecipe() *WorkflowRecipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type HealthRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IncludeDependencies bool                   `protobuf:"varint,1,opt,name=include_dependencies,json=includeDependencies,proto3" json:"include_dependencies,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_context_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *HealthRequest) GetIncludeDependencies() bool {
	if x != nil {
		return x.IncludeDependencies
	}
	return false
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     *string                `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3,oneof" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_proto_context_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *MetricsRequest) GetTimeRange() string {
	if x != nil && x.TimeRange != nil {
		return *x.TimeRange
	}
	return ""
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	RecipeIds     []string               `protobuf:"bytes,2,rep,name=recipe_ids,json=recipeIds,proto3" json:"recipe_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_context_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *StreamRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *StreamRequest) GetRecipeIds() []string {
	if x != nil {
		return x.RecipeIds
	}
	return nil
}

// Core Data Models
type ClinicalSnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId         string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	RecipeId          string                 `protobuf:"bytes,3,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	ContextId         string                 `protobuf:"bytes,4,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Data              *structpb.Struct       `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	CompletenessScore float64                `protobuf:"fixed64,6,opt,name=completeness_score,json=completenessScore,proto3" json:"completeness_score,omitempty"`
	Checksum          string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Signature         string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	SignatureMethod   SignatureMethod        `protobuf:"varint,9,opt,name=signature_method,json=signatureMethod,proto3,enum=context_gateway.SignatureMethod" json:"signature_method,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Status            SnapshotStatus         `protobuf:"varint,12,opt,name=status,proto3,enum=context_gateway.SnapshotStatus" json:"status,omitempty"`
	ProviderId        *string                `protobuf:"bytes,13,opt,name=provider_id,json=providerId,proto3,oneof" json:"provider_id,omitempty"`
	EncounterId       *string                `protobuf:"bytes,14,opt,name=encounter_id,json=encounterId,proto3,oneof" json:"encounter_id,omitempty"`
	AssemblyMetadata  *structpb.Struct       `protobuf:"bytes,15,opt,name=assembly_metadata,json=assemblyMetadata,proto3" json:"assembly_metadata,omitempty"`
	EvidenceEnvelope  *structpb.Struct       `protobuf:"bytes,16,opt,name=evidence_envelope,json=evidenceEnvelope,proto3" json:"evidence_envelope,omitempty"`
	AccessedCount     int32                  `protobuf:"varint,17,opt,name=accessed_count,json=accessedCount,proto3" json:"accessed_count,omitempty"`
	LastAccessedAt    *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=last_accessed_at,json=lastAccessedAt,proto3" json:"last_accessed_at,omitempty"`
	AllowLiveFetch    bool                   `protobuf:"varint,19,opt,name=allow_live_fetch,json=allowLiveFetch,proto3" json:"allow_live_fetch,omitempty"`
	AllowedLiveFields []string               `protobuf:"bytes,20,rep,name=allowed_live_fields,json=allowedLiveFields,proto3" json:"allowed_live_fields,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClinicalSnapshot) Reset() {
	*x = ClinicalSnapshot{}
	mi := &file_proto_context_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClinicalSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicalSnapshot) ProtoMessage() {}

func (x *ClinicalSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicalSnapshot.ProtoReflect.Descriptor instead.
func (*ClinicalSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *ClinicalSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClinicalSnapshot) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ClinicalSnapshot) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *ClinicalSnapshot) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *ClinicalSnapshot) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClinicalSnapshot) GetCompletenessScore() float64 {
	if x != nil {
		return x.CompletenessScore
	}
	return 0
}

func (x *ClinicalSnapshot) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *ClinicalSnapshot) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ClinicalSnapshot) GetSignatureMethod() SignatureMethod {
	if x != nil {
		return x.SignatureMethod
	}
	return SignatureMethod_SIGNATURE_METHOD_UNKNOWN
}

func (x *ClinicalSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ClinicalSnapshot) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ClinicalSnapshot) GetStatus() SnapshotStatus {
	if x != nil {
		return x.Status
	}
	return SnapshotStatus_SNAPSHOT_STATUS_UNKNOWN
}

func (x *ClinicalSnapshot) GetProviderId() string {
	if x != nil && x.ProviderId != nil {
		return *x.ProviderId
	}
	return ""
}

func (x *ClinicalSnapshot) GetEncounterId() string {
	if x != nil && x.EncounterId != nil {
		return *x.EncounterId
	}
	return ""
}

func (x *ClinicalSnapshot) GetAssemblyMetadata() *structpb.Struct {
	if x != nil {
		return x.AssemblyMetadata
	}
	return nil
}

func (x *ClinicalSnapshot) GetEvidenceEnvelope() *structpb.Struct {
	if x != nil {
		return x.EvidenceEnvelope
	}
	return nil
}

func (x *ClinicalSnapshot) GetAccessedCount() int32 {
	if x != nil {
		return x.AccessedCount
	}
	return 0
}

func (x *ClinicalSnapshot) GetLastAccessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessedAt
	}
	return nil
}

func (x *ClinicalSnapshot) GetAllowLiveFetch() bool {
	if x != nil {
		return x.AllowLiveFetch
	}
	return false
}

func (x *ClinicalSnapshot) GetAllowedLiveFields() []string {
	if x != nil {
		return x.AllowedLiveFields
	}
	return nil
}

type WorkflowRecipe struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecipeId           string                 `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	RecipeName         string                 `protobuf:"bytes,2,opt,name=recipe_name,json=recipeName,proto3" json:"recipe_name,omitempty"`
	Version            string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ClinicalScenario   string                 `protobuf:"bytes,4,opt,name=clinical_scenario,json=clinicalScenario,proto3" json:"clinical_scenario,omitempty"`
	WorkflowCategory   string                 `protobuf:"bytes,5,opt,name=workflow_category,json=workflowCategory,proto3" json:"workflow_category,omitempty"`
	ExecutionPattern   string                 `protobuf:"bytes,6,opt,name=execution_pattern,json=executionPattern,proto3" json:"execution_pattern,omitempty"`
	RequiredFields     []*DataPoint           `protobuf:"bytes,7,rep,name=required_fields,json=requiredFields,proto3" json:"required_fields,omitempty"`
	ConditionalRules   []*ConditionalRule     `protobuf:"bytes,8,rep,name=conditional_rules,json=conditionalRules,proto3" json:"conditional_rules,omitempty"`
	QualityConstraints *QualityConstraints    `protobuf:"bytes,9,opt,name=quality_constraints,json=qualityConstraints,proto3" json:"quality_constraints,omitempty"`
	SafetyRequirements *SafetyRequirements    `protobuf:"bytes,10,opt,name=safety_requirements,json=safetyRequirements,proto3" json:"safety_requirements,omitempty"`
	CacheStrategy      *CacheStrategy         `protobuf:"bytes,11,opt,name=cache_strategy,json=cacheStrategy,proto3" json:"cache_strategy,omitempty"`
	AssemblyRules      *AssemblyRules         `protobuf:"bytes,12,opt,name=assembly_rules,json=assemblyRules,proto3" json:"assembly_rules,omitempty"`
	GovernanceMetadata *GovernanceMetadata    `protobuf:"bytes,13,opt,name=governance_metadata,json=governanceMetadata,proto3" json:"governance_metadata,omitempty"`
	SlaMs              int32                  `protobuf:"varint,14,opt,name=sla_ms,json=slaMs,proto3" json:"sla_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkflowRecipe) Reset() {
	*x = WorkflowRecipe{}
	mi := &file_proto_context_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowRecipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowRecipe) ProtoMessage() {}

func (x *WorkflowRecipe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowRecipe.ProtoReflect.Descriptor instead.
func (*WorkflowRecipe) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *WorkflowRecipe) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *WorkflowRecipe) GetRecipeName() string {
	if x != nil {
		return x.RecipeName
	}
	return ""
}

func (x *WorkflowRecipe) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WorkflowRecipe) GetClinicalScenario() string {
	if x != nil {
		return x.ClinicalScenario
	}
	return ""
}

func (x *WorkflowRecipe) GetWorkflowCategory() string {
	if x != nil {
		return x.WorkflowCategory
	}
	return ""
}

func (x *WorkflowRecipe) GetExecutionPattern() string {
	if x != nil {
		return x.ExecutionPattern
	}
	return ""
}

func (x *WorkflowRecipe) GetRequiredFields() []*DataPoint {
	if x != nil {
		return x.RequiredFields
	}
	return nil
}

func (x *WorkflowRecipe) GetConditionalRules() []*ConditionalRule {
	if x != nil {
		return x.ConditionalRules
	}
	return nil
}

func (x *WorkflowRecipe) GetQualityConstraints() *QualityConstraints {
	if x != nil {
		return x.QualityConstraints
	}
	return nil
}

func (x *WorkflowRecipe) GetSafetyRequirements() *SafetyRequirements {
	if x != nil {
		return x.SafetyRequirements
	}
	return nil
}

func (x *WorkflowRecipe) GetCacheStrategy() *CacheStrategy {
	if x != nil {
		return x.CacheStrategy
	}
	return nil
}

func (x *WorkflowRecipe) GetAssemblyRules() *AssemblyRules {
	if x != nil {
		return x.AssemblyRules
	}
	return nil
}

func (x *WorkflowRecipe) GetGovernanceMetadata() *GovernanceMetadata {
	if x != nil {
		return x.GovernanceMetadata
	}
	return nil
}

func (x *WorkflowRecipe) GetSlaMs() int32 {
	if x != nil {
		return x.SlaMs
	}
	return 0
}

type DataPoint struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SourceType           string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Fields               []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Required             bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	MaxAgeHours          int32                  `protobuf:"varint,5,opt,name=max_age_hours,json=maxAgeHours,proto3" json:"max_age_hours,omitempty"`
	QualityThreshold     float64                `protobuf:"fixed64,6,opt,name=quality_threshold,json=qualityThreshold,proto3" json:"quality_threshold,omitempty"`
	TimeoutMs            int32                  `protobuf:"varint,7,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	RetryCount           int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	FallbackSources      []string               `protobuf:"bytes,9,rep,name=fallback_sources,json=fallbackSources,proto3" json:"fallback_sources,omitempty"`
	FreshnessRequirement int32                  `protobuf:"varint,10,opt,name=freshness_requirement,json=freshnessRequirement,proto3" json:"freshness_requirement,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_proto_context_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *DataPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataPoint) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *DataPoint) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DataPoint) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *DataPoint) GetMaxAgeHours() int32 {
	if x != nil {
		return x.MaxAgeHours
	}
	return 0
}

func (x *DataPoint) GetQualityThreshold() float64 {
	if x != nil {
		return x.QualityThreshold
	}
	return 0
}

func (x *DataPoint) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *DataPoint) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *DataPoint) GetFallbackSources() []string {
	if x != nil {
		return x.FallbackSources
	}
	return nil
}

func (x *DataPoint) GetFreshnessRequirement() int32 {
	if x != nil {
		return x.FreshnessRequirement
	}
	return 0
}

type ConditionalRule struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Condition            string                 `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	AdditionalDataPoints []*DataPoint           `protobuf:"bytes,2,rep,name=additional_data_points,json=additionalDataPoints,proto3" json:"additional_data_points,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConditionalRule) Reset() {
	*x = ConditionalRule{}
	mi := &file_proto_context_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionalRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionalRule) ProtoMessage() {}

func (x *ConditionalRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionalRule.ProtoReflect.Descriptor instead.
func (*ConditionalRule) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *ConditionalRule) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *ConditionalRule) GetAdditionalDataPoints() []*DataPoint {
	if x != nil {
		return x.AdditionalDataPoints
	}
	return nil
}

func (x *ConditionalRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type QualityConstraints struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MinimumCompleteness float64                `protobuf:"fixed64,1,opt,name=minimum_completeness,json=minimumCompleteness,proto3" json:"minimum_completeness,omitempty"`
	MaximumAgeHours     int32                  `protobuf:"varint,2,opt,name=maximum_age_hours,json=maximumAgeHours,proto3" json:"maximum_age_hours,omitempty"`
	RequiredFields      []string               `protobuf:"bytes,3,rep,name=required_fields,json=requiredFields,proto3" json:"required_fields,omitempty"`
	AccuracyThreshold   float64                `protobuf:"fixed64,4,opt,name=accuracy_threshold,json=accuracyThreshold,proto3" json:"accuracy_threshold,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QualityConstraints) Reset() {
	*x = QualityConstraints{}
	mi := &file_proto_context_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityConstraints) ProtoMessage() {}

func (x *QualityConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityConstraints.ProtoReflect.Descriptor instead.
func (*QualityConstraints) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *QualityConstraints) GetMinimumCompleteness() float64 {
	if x != nil {
		return x.MinimumCompleteness
	}
	return 0
}

func (x *QualityConstraints) GetMaximumAgeHours() int32 {
	if x != nil {
		return x.MaximumAgeHours
	}
	return 0
}

func (x *QualityConstraints) GetRequiredFields() []string {
	if x != nil {
		return x.RequiredFields
	}
	return nil
}

func (x *QualityConstraints) GetAccuracyThreshold() float64 {
	if x != nil {
		return x.AccuracyThreshold
	}
	return 0
}

type SafetyRequirements struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	MinimumCompletenessScore    float64                `protobuf:"fixed64,1,opt,name=minimum_completeness_score,json=minimumCompletenessScore,proto3" json:"minimum_completeness_score,omitempty"`
	AbsoluteRequiredEnforcement string                 `protobuf:"bytes,2,opt,name=absolute_required_enforcement,json=absoluteRequiredEnforcement,proto3" json:"absolute_required_enforcement,omitempty"`
	PreferredDataHandling       string                 `protobuf:"bytes,3,opt,name=preferred_data_handling,json=preferredDataHandling,proto3" json:"preferred_data_handling,omitempty"`
	CriticalMissingDataAction   string                 `protobuf:"bytes,4,opt,name=critical_missing_data_action,json=criticalMissingDataAction,proto3" json:"critical_missing_data_action,omitempty"`
	StaleDataAction             string                 `protobuf:"bytes,5,opt,name=stale_data_action,json=staleDataAction,proto3" json:"stale_data_action,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SafetyRequirements) Reset() {
	*x = SafetyRequirements{}
	mi := &file_proto_context_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafetyRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafetyRequirements) ProtoMessage() {}

func (x *SafetyRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafetyRequirements.ProtoReflect.Descriptor instead.
func (*SafetyRequirements) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *SafetyRequirements) GetMinimumCompletenessScore() float64 {
	if x != nil {
		return x.MinimumCompletenessScore
	}
	return 0
}

func (x *SafetyRequirements) GetAbsoluteRequiredEnforcement() string {
	if x != nil {
		return x.AbsoluteRequiredEnforcement
	}
	return ""
}

func (x *SafetyRequirements) GetPreferredDataHandling() string {
	if x != nil {
		return x.PreferredDataHandling
	}
	return ""
}

func (x *SafetyRequirements) GetCriticalMissingDataAction() string {
	if x != nil {
		return x.CriticalMissingDataAction
	}
	return ""
}

func (x *SafetyRequirements) GetStaleDataAction() string {
	if x != nil {
		return x.StaleDataAction
	}
	return ""
}

type CacheStrategy struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	L1TtlSeconds       int32                  `protobuf:"varint,1,opt,name=l1_ttl_seconds,json=l1TtlSeconds,proto3" json:"l1_ttl_seconds,omitempty"`
	L2TtlSeconds       int32                  `protobuf:"varint,2,opt,name=l2_ttl_seconds,json=l2TtlSeconds,proto3" json:"l2_ttl_seconds,omitempty"`
	L3TtlSeconds       int32                  `protobuf:"varint,3,opt,name=l3_ttl_seconds,json=l3TtlSeconds,proto3" json:"l3_ttl_seconds,omitempty"`
	InvalidationEvents []string               `protobuf:"bytes,4,rep,name=invalidation_events,json=invalidationEvents,proto3" json:"invalidation_events,omitempty"`
	CacheKeyPattern    string                 `protobuf:"bytes,5,opt,name=cache_key_pattern,json=cacheKeyPattern,proto3" json:"cache_key_pattern,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CacheStrategy) Reset() {
	*x = CacheStrategy{}
	mi := &file_proto_context_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStrategy) ProtoMessage() {}

func (x *CacheStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStrategy.ProtoReflect.Descriptor instead.
func (*CacheStrategy) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *CacheStrategy) GetL1TtlSeconds() int32 {
	if x != nil {
		return x.L1TtlSeconds
	}
	return 0
}

func (x *CacheStrategy) GetL2TtlSeconds() int32 {
	if x != nil {
		return x.L2TtlSeconds
	}
	return 0
}

func (x *CacheStrategy) GetL3TtlSeconds() int32 {
	if x != nil {
		return x.L3TtlSeconds
	}
	return 0
}

func (x *CacheStrategy) GetInvalidationEvents() []string {
	if x != nil {
		return x.InvalidationEvents
	}
	return nil
}

func (x *CacheStrategy) GetCacheKeyPattern() string {
	if x != nil {
		return x.CacheKeyPattern
	}
	return ""
}

type AssemblyRules struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ParallelExecution         bool                   `protobuf:"varint,1,opt,name=parallel_execution,json=parallelExecution,proto3" json:"parallel_execution,omitempty"`
	TimeoutBudgetMs           int32                  `protobuf:"varint,2,opt,name=timeout_budget_ms,json=timeoutBudgetMs,proto3" json:"timeout_budget_ms,omitempty"`
	CircuitBreakerEnabled     bool                   `protobuf:"varint,3,opt,name=circuit_breaker_enabled,json=circuitBreakerEnabled,proto3" json:"circuit_breaker_enabled,omitempty"`
	RetryFailedSources        bool                   `protobuf:"varint,4,opt,name=retry_failed_sources,json=retryFailedSources,proto3" json:"retry_failed_sources,omitempty"`
	ValidateDataFreshness     bool                   `protobuf:"varint,5,opt,name=validate_data_freshness,json=validateDataFreshness,proto3" json:"validate_data_freshness,omitempty"`
	EnforceQualityConstraints bool                   `protobuf:"varint,6,opt,name=enforce_quality_constraints,json=enforceQualityConstraints,proto3" json:"enforce_quality_constraints,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AssemblyRules) Reset() {
	*x = AssemblyRules{}
	mi := &file_proto_context_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssemblyRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssemblyRules) ProtoMessage() {}

func (x *AssemblyRules) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssemblyRules.ProtoReflect.Descriptor instead.
func (*AssemblyRules) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *AssemblyRules) GetParallelExecution() bool {
	if x != nil {
		return x.ParallelExecution
	}
	return false
}

func (x *AssemblyRules) GetTimeoutBudgetMs() int32 {
	if x != nil {
		return x.TimeoutBudgetMs
	}
	return 0
}

func (x *AssemblyRules) GetCircuitBreakerEnabled() bool {
	if x != nil {
		return x.CircuitBreakerEnabled
	}
	return false
}

func (x *AssemblyRules) GetRetryFailedSources() bool {
	if x != nil {
		return x.RetryFailedSources
	}
	return false
}

func (x *AssemblyRules) GetValidateDataFreshness() bool {
	if x != nil {
		return x.ValidateDataFreshness
	}
	return false
}

func (x *AssemblyRules) GetEnforceQualityConstraints() bool {
	if x != nil {
		return x.EnforceQualityConstraints
	}
	return false
}

type GovernanceMetadata struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ApprovedBy              string                 `protobuf:"bytes,1,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	ApprovalDate            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=approval_date,json=approvalDate,proto3" json:"approval_date,omitempty"`
	Version                 string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	EffectiveDate           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=effective_date,json=effectiveDate,proto3" json:"effective_date,omitempty"`
	ExpiryDate              *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	ClinicalBoardApprovalId string                 `protobuf:"bytes,6,opt,name=clinical_board_approval_id,json=clinicalBoardApprovalId,proto3" json:"clinical_board_approval_id,omitempty"`
	Tags                    []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	ChangeLog               []string               `protobuf:"bytes,8,rep,name=change_log,json=changeLog,proto3" json:"change_log,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GovernanceMetadata) Reset() {
	*x = GovernanceMetadata{}
	mi := &file_proto_context_gateway_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernanceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernanceMetadata) ProtoMessage() {}

func (x *GovernanceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernanceMetadata.ProtoReflect.Descriptor instead.
func (*GovernanceMetadata) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{18}
}

func (x *GovernanceMetadata) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *GovernanceMetadata) GetApprovalDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovalDate
	}
	return nil
}

func (x *GovernanceMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GovernanceMetadata) GetEffectiveDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveDate
	}
	return nil
}

func (x *GovernanceMetadata) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

func (x *GovernanceMetadata) GetClinicalBoardApprovalId() string {
	if x != nil {
		return x.ClinicalBoardApprovalId
	}
	return ""
}

func (x *GovernanceMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GovernanceMetadata) GetChangeLog() []string {
	if x != nil {
		return x.ChangeLog
	}
	return nil
}

// Response Messages
type ValidateSnapshotResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Valid                bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ChecksumValid        bool                   `protobuf:"varint,2,opt,name=checksum_valid,json=checksumValid,proto3" json:"checksum_valid,omitempty"`
	SignatureValid       bool                   `protobuf:"varint,3,opt,name=signature_valid,json=signatureValid,proto3" json:"signature_valid,omitempty"`
	NotExpired           bool                   `protobuf:"varint,4,opt,name=not_expired,json=notExpired,proto3" json:"not_expired,omitempty"`
	Errors               []string               `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings             []string               `protobuf:"bytes,6,rep,name=warnings,proto3" json:"warnings,omitempty"`
	ValidationDurationMs float64                `protobuf:"fixed64,7,opt,name=validation_duration_ms,json=validationDurationMs,proto3" json:"validation_duration_ms,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ValidateSnapshotResponse) Reset() {
	*x = ValidateSnapshotResponse{}
	mi := &file_proto_context_gateway_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSnapshotResponse) ProtoMessage() {}

func (x *ValidateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*ValidateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{19}
}

func (x *ValidateSnapshotResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateSnapshotResponse) GetChecksumValid() bool {
	if x != nil {
		return x.ChecksumValid
	}
	return false
}

func (x *ValidateSnapshotResponse) GetSignatureValid() bool {
	if x != nil {
		return x.SignatureValid
	}
	return false
}

func (x *ValidateSnapshotResponse) GetNotExpired() bool {
	if x != nil {
		return x.NotExpired
	}
	return false
}

func (x *ValidateSnapshotResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidateSnapshotResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *ValidateSnapshotResponse) GetValidationDurationMs() float64 {
	if x != nil {
		return x.ValidationDurationMs
	}
	return 0
}

type InvalidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	InvalidatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=invalidated_at,json=invalidatedAt,proto3" json:"invalidated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateResponse) Reset() {
	*x = InvalidateResponse{}
	mi := &file_proto_context_gateway_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateResponse) ProtoMessage() {}

func (x *InvalidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateResponse.ProtoReflect.Descriptor instead.
func (*InvalidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{20}
}

func (x *InvalidateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InvalidateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InvalidateResponse) GetInvalidatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InvalidatedAt
	}
	return nil
}

type LiveFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FetchedData   *structpb.Struct       `protobuf:"bytes,1,opt,name=fetched_data,json=fetchedData,proto3" json:"fetched_data,omitempty"`
	Completeness  float64                `protobuf:"fixed64,2,opt,name=completeness,proto3" json:"completeness,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	AuditEntry    *AuditEntry            `protobuf:"bytes,4,opt,name=audit_entry,json=auditEntry,proto3" json:"audit_entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveFetchResponse) Reset() {
	*x = LiveFetchResponse{}
	mi := &file_proto_context_gateway_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveFetchResponse) ProtoMessage() {}

func (x *LiveFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveFetchResponse.ProtoReflect.Descriptor instead.
func (*LiveFetchResponse) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{21}
}

func (x *LiveFetchResponse) GetFetchedData() *structpb.Struct {
	if x != nil {
		return x.FetchedData
	}
	return nil
}

func (x *LiveFetchResponse) GetCompleteness() float64 {
	if x != nil {
		return x.Completeness
	}
	return 0
}

func (x *LiveFetchResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *LiveFetchResponse) GetAuditEntry() *AuditEntry {
	if x != nil {
		return x.AuditEntry
	}
	return nil
}

type RecipeValidationResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Valid                bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings             []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	ValidationDurationMs float64                `protobuf:"fixed64,4,opt,name=validation_duration_ms,json=validationDurationMs,proto3" json:"validation_duration_ms,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RecipeValidationResponse) Reset() {
	*x = RecipeValidationResponse{}
	mi := &file_proto_context_gateway_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeValidationResponse) ProtoMessage() {}

func (x *RecipeValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeValidationResponse.ProtoReflect.Descriptor instead.
func (*RecipeValidationResponse) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{22}
}

func (x *RecipeValidationResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *RecipeValidationResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *RecipeValidationResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *RecipeValidationResponse) GetValidationDurationMs() float64 {
	if x != nil {
		return x.ValidationDurationMs
	}
	return 0
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ServiceStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=context_gateway.ServiceStatus" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Dependencies  []*DependencyHealth    `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	CacheStats    *CacheStats            `protobuf:"bytes,5,opt,name=cache_stats,json=cacheStats,proto3" json:"cache_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_context_gateway_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{23}
}

func (x *HealthResponse) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_SERVICE_STATUS_UNKNOWN
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthResponse) GetDependencies() []*DependencyHealth {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *HealthResponse) GetCacheStats() *CacheStats {
	if x != nil {
		return x.CacheStats
	}
	return nil
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *structpb.Struct       `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_context_gateway_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{24}
}

func (x *MetricsResponse) GetMetrics() *structpb.Struct {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *MetricsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ContextUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	RecipeId      string                 `protobuf:"bytes,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	UpdateType    UpdateType             `protobuf:"varint,3,opt,name=update_type,json=updateType,proto3,enum=context_gateway.UpdateType" json:"update_type,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextUpdate) Reset() {
	*x = ContextUpdate{}
	mi := &file_proto_context_gateway_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextUpdate) ProtoMessage() {}

func (x *ContextUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextUpdate.ProtoReflect.Descriptor instead.
func (*ContextUpdate) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{25}
}

func (x *ContextUpdate) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ContextUpdate) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *ContextUpdate) GetUpdateType() UpdateType {
	if x != nil {
		return x.UpdateType
	}
	return UpdateType_UPDATE_TYPE_UNKNOWN
}

func (x *ContextUpdate) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ContextUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Supporting Messages
type AuditEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Event             string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	SnapshotId        string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	PatientId         string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	RequestingService string                 `protobuf:"bytes,4,opt,name=requesting_service,json=requestingService,proto3" json:"requesting_service,omitempty"`
	FieldsFetched     []string               `protobuf:"bytes,5,rep,name=fields_fetched,json=fieldsFetched,proto3" json:"fields_fetched,omitempty"`
	Reason            string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_proto_context_gateway_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{26}
}

func (x *AuditEntry) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *AuditEntry) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *AuditEntry) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *AuditEntry) GetRequestingService() string {
	if x != nil {
		return x.RequestingService
	}
	return ""
}

func (x *AuditEntry) GetFieldsFetched() []string {
	if x != nil {
		return x.FieldsFetched
	}
	return nil
}

func (x *AuditEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuditEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type DependencyHealth struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceName    string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Status         ServiceStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=context_gateway.ServiceStatus" json:"status,omitempty"`
	Endpoint       string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ResponseTimeMs int32                  `protobuf:"varint,4,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	LastCheck      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	Error          *string                `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DependencyHealth) Reset() {
	*x = DependencyHealth{}
	mi := &file_proto_context_gateway_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyHealth) ProtoMessage() {}

func (x *DependencyHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyHealth.ProtoReflect.Descriptor instead.
func (*DependencyHealth) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{27}
}

func (x *DependencyHealth) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DependencyHealth) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_SERVICE_STATUS_UNKNOWN
}

func (x *DependencyHealth) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *DependencyHealth) GetResponseTimeMs() int32 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *DependencyHealth) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

func (x *DependencyHealth) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type CacheStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalEntries  int64                  `protobuf:"varint,1,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	HitRatio      float64                `protobuf:"fixed64,2,opt,name=hit_ratio,json=hitRatio,proto3" json:"hit_ratio,omitempty"`
	L1Entries     int64                  `protobuf:"varint,3,opt,name=l1_entries,json=l1Entries,proto3" json:"l1_entries,omitempty"`
	L2Entries     int64                  `protobuf:"varint,4,opt,name=l2_entries,json=l2Entries,proto3" json:"l2_entries,omitempty"`
	L3Entries     int64                  `protobuf:"varint,5,opt,name=l3_entries,json=l3Entries,proto3" json:"l3_entries,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheStats) Reset() {
	*x = CacheStats{}
	mi := &file_proto_context_gateway_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStats) ProtoMessage() {}

func (x *CacheStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_gateway_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStats.ProtoReflect.Descriptor instead.
func (*CacheStats) Descriptor() ([]byte, []int) {
	return file_proto_context_gateway_proto_rawDescGZIP(), []int{28}
}

func (x *CacheStats) GetTotalEntries() int64 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

func (x *CacheStats) GetHitRatio() float64 {
	if x != nil {
		return x.HitRatio
	}
	return 0
}

func (x *CacheStats) GetL1Entries() int64 {
	if x != nil {
		return x.L1Entries
	}
	return 0
}

func (x *CacheStats) GetL2Entries() int64 {
	if x != nil {
		return x.L2Entries
	}
	return 0
}

func (x *CacheStats) GetL3Entries() int64 {
	if x != nil {
		return x.L3Entries
	}
	return 0
}

func (x *CacheStats) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_proto_context_gateway_proto protoreflect.FileDescriptor

const file_proto_context_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/context_gateway.proto\x12\x0fcontext_gateway\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xcf\x02\n" +
	"\x15CreateSnapshotRequest\x127\n" +
	"\x06recipe\x18\x01 \x01(\v2\x1f.context_gateway.WorkflowRecipeR\x06recipe\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12-\n" +
	"\x12requesting_service\x18\x03 \x01(\tR\x11requestingService\x12$\n" +
	"\vprovider_id\x18\x04 \x01(\tH\x00R\n" +
	"providerId\x88\x01\x01\x12&\n" +
	"\fencounter_id\x18\x05 \x01(\tH\x01R\vencounterId\x88\x01\x01\x12#\n" +
	"\rforce_refresh\x18\x06 \x01(\bR\fforceRefresh\x12\x1b\n" +
	"\tttl_hours\x18\a \x01(\x05R\bttlHoursB\x0e\n" +
	"\f_provider_idB\x0f\n" +
	"\r_encounter_id\"d\n" +
	"\x12GetSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12-\n" +
	"\x12requesting_service\x18\x02 \x01(\tR\x11requestingService\"i\n" +
	"\x17ValidateSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12-\n" +
	"\x12requesting_service\x18\x02 \x01(\tR\x11requestingService\"{\n" +
	"\x11InvalidateRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12-\n" +
	"\x12requesting_service\x18\x03 \x01(\tR\x11requestingService\"\xa8\x01\n" +
	"\x10LiveFetchRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12%\n" +
	"\x0emissing_fields\x18\x02 \x03(\tR\rmissingFields\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12-\n" +
	"\x12requesting_service\x18\x04 \x01(\tR\x11requestingService\"[\n" +
	"\x11LoadRecipeRequest\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\tR\brecipeId\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tH\x00R\aversion\x88\x01\x01B\n" +
	"\n" +
	"\b_version\"P\n" +
	"\x15ValidateRecipeRequest\x127\n" +
	"\x06recipe\x18\x01 \x01(\v2\x1f.context_gateway.WorkflowRecipeR\x06recipe\"B\n" +
	"\rHealthRequest\x121\n" +
	"\x14include_dependencies\x18\x01 \x01(\bR\x13includeDependencies\"C\n" +
	"\x0eMetricsRequest\x12\"\n" +
	"\n" +
	"time_range\x18\x01 \x01(\tH\x00R\ttimeRange\x88\x01\x01B\r\n" +
	"\v_time_range\"M\n" +
	"\rStreamRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x1d\n" +
	"\n" +
	"recipe_ids\x18\x02 \x03(\tR\trecipeIds\"\xd1\a\n" +
	"\x10ClinicalSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1b\n" +
	"\trecipe_id\x18\x03 \x01(\tR\brecipeId\x12\x1d\n" +
	"\n" +
	"context_id\x18\x04 \x01(\tR\tcontextId\x12+\n" +
	"\x04data\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04data\x12-\n" +
	"\x12completeness_score\x18\x06 \x01(\x01R\x11completenessScore\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\x12K\n" +
	"\x10signature_method\x18\t \x01(\x0e2 .context_gateway.SignatureMethodR\x0fsignatureMethod\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x127\n" +
	"\x06status\x18\f \x01(\x0e2\x1f.context_gateway.SnapshotStatusR\x06status\x12$\n" +
	"\vprovider_id\x18\r \x01(\tH\x00R\n" +
	"providerId\x88\x01\x01\x12&\n" +
	"\fencounter_id\x18\x0e \x01(\tH\x01R\vencounterId\x88\x01\x01\x12D\n" +
	"\x11assembly_metadata\x18\x0f \x01(\v2\x17.google.protobuf.StructR\x10assemblyMetadata\x12D\n" +
	"\x11evidence_envelope\x18\x10 \x01(\v2\x17.google.protobuf.StructR\x10evidenceEnvelope\x12%\n" +
	"\x0eaccessed_count\x18\x11 \x01(\x05R\raccessedCount\x12D\n" +
	"\x10last_accessed_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastAccessedAt\x12(\n" +
	"\x10allow_live_fetch\x18\x13 \x01(\bR\x0eallowLiveFetch\x12.\n" +
	"\x13allowed_live_fields\x18\x14 \x03(\tR\x11allowedLiveFieldsB\x0e\n" +
	"\f_provider_idB\x0f\n" +
	"\r_encounter_id\"\xaa\x06\n" +
	"\x0eWorkflowRecipe\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\tR\brecipeId\x12\x1f\n" +
	"\vrecipe_name\x18\x02 \x01(\tR\n" +
	"recipeName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12+\n" +
	"\x11clinical_scenario\x18\x04 \x01(\tR\x10clinicalScenario\x12+\n" +
	"\x11workflow_category\x18\x05 \x01(\tR\x10workflowCategory\x12+\n" +
	"\x11execution_pattern\x18\x06 \x01(\tR\x10executionPattern\x12C\n" +
	"\x0frequired_fields\x18\a \x03(\v2\x1a.context_gateway.DataPointR\x0erequiredFields\x12M\n" +
	"\x11conditional_rules\x18\b \x03(\v2 .context_gateway.ConditionalRuleR\x10conditionalRules\x12T\n" +
	"\x13quality_constraints\x18\t \x01(\v2#.context_gateway.QualityConstraintsR\x12qualityConstraints\x12T\n" +
	"\x13safety_requirements\x18\n" +
	" \x01(\v2#.context_gateway.SafetyRequirementsR\x12safetyRequirements\x12E\n" +
	"\x0ecache_strategy\x18\v \x01(\v2\x1e.context_gateway.CacheStrategyR\rcacheStrategy\x12E\n" +
	"\x0eassembly_rules\x18\f \x01(\v2\x1e.context_gateway.AssemblyRulesR\rassemblyRules\x12T\n" +
	"\x13governance_metadata\x18\r \x01(\v2#.context_gateway.GovernanceMetadataR\x12governanceMetadata\x12\x15\n" +
	"\x06sla_ms\x18\x0e \x01(\x05R\x05slaMs\"\xe5\x02\n" +
	"\tDataPoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\"\n" +
	"\rmax_age_hours\x18\x05 \x01(\x05R\vmaxAgeHours\x12+\n" +
	"\x11quality_threshold\x18\x06 \x01(\x01R\x10qualityThreshold\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\a \x01(\x05R\ttimeoutMs\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x12)\n" +
	"\x10fallback_sources\x18\t \x03(\tR\x0ffallbackSources\x123\n" +
	"\x15freshness_requirement\x18\n" +
	" \x01(\x05R\x14freshnessRequirement\"\xa3\x01\n" +
	"\x0fConditionalRule\x12\x1c\n" +
	"\tcondition\x18\x01 \x01(\tR\tcondition\x12P\n" +
	"\x16additional_data_points\x18\x02 \x03(\v2\x1a.context_gateway.DataPointR\x14additionalDataPoints\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xcb\x01\n" +
	"\x12QualityConstraints\x121\n" +
	"\x14minimum_completeness\x18\x01 \x01(\x01R\x13minimumCompleteness\x12*\n" +
	"\x11maximum_age_hours\x18\x02 \x01(\x05R\x0fmaximumAgeHours\x12'\n" +
	"\x0frequired_fields\x18\x03 \x03(\tR\x0erequiredFields\x12-\n" +
	"\x12accuracy_threshold\x18\x04 \x01(\x01R\x11accuracyThreshold\"\xbb\x02\n" +
	"\x12SafetyRequirements\x12<\n" +
	"\x1aminimum_completeness_score\x18\x01 \x01(\x01R\x18minimumCompletenessScore\x12B\n" +
	"\x1dabsolute_required_enforcement\x18\x02 \x01(\tR\x1babsoluteRequiredEnforcement\x126\n" +
	"\x17preferred_data_handling\x18\x03 \x01(\tR\x15preferredDataHandling\x12?\n" +
	"\x1ccritical_missing_data_action\x18\x04 \x01(\tR\x19criticalMissingDataAction\x12*\n" +
	"\x11stale_data_action\x18\x05 \x01(\tR\x0fstaleDataAction\"\xde\x01\n" +
	"\rCacheStrategy\x12$\n" +
	"\x0el1_ttl_seconds\x18\x01 \x01(\x05R\fl1TtlSeconds\x12$\n" +
	"\x0el2_ttl_seconds\x18\x02 \x01(\x05R\fl2TtlSeconds\x12$\n" +
	"\x0el3_ttl_seconds\x18\x03 \x01(\x05R\fl3TtlSeconds\x12/\n" +
	"\x13invalidation_events\x18\x04 \x03(\tR\x12invalidationEvents\x12*\n" +
	"\x11cache_key_pattern\x18\x05 \x01(\tR\x0fcacheKeyPattern\"\xcc\x02\n" +
	"\rAssemblyRules\x12-\n" +
	"\x12parallel_execution\x18\x01 \x01(\bR\x11parallelExecution\x12*\n" +
	"\x11timeout_budget_ms\x18\x02 \x01(\x05R\x0ftimeoutBudgetMs\x126\n" +
	"\x17circuit_breaker_enabled\x18\x03 \x01(\bR\x15circuitBreakerEnabled\x120\n" +
	"\x14retry_failed_sources\x18\x04 \x01(\bR\x12retryFailedSources\x126\n" +
	"\x17validate_data_freshness\x18\x05 \x01(\bR\x15validateDataFreshness\x12>\n" +
	"\x1benforce_quality_constraints\x18\x06 \x01(\bR\x19enforceQualityConstraints\"\x80\x03\n" +
	"\x12GovernanceMetadata\x12\x1f\n" +
	"\vapproved_by\x18\x01 \x01(\tR\n" +
	"approvedBy\x12?\n" +
	"\rapproval_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fapprovalDate\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12A\n" +
	"\x0eeffective_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\reffectiveDate\x12;\n" +
	"\vexpiry_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\x12;\n" +
	"\x1aclinical_board_approval_id\x18\x06 \x01(\tR\x17clinicalBoardApprovalId\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"change_log\x18\b \x03(\tR\tchangeLog\"\x8b\x02\n" +
	"\x18ValidateSnapshotResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12%\n" +
	"\x0echecksum_valid\x18\x02 \x01(\bR\rchecksumValid\x12'\n" +
	"\x0fsignature_valid\x18\x03 \x01(\bR\x0esignatureValid\x12\x1f\n" +
	"\vnot_expired\x18\x04 \x01(\bR\n" +
	"notExpired\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x06 \x03(\tR\bwarnings\x124\n" +
	"\x16validation_duration_ms\x18\a \x01(\x01R\x14validationDurationMs\"\x8b\x01\n" +
	"\x12InvalidateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\x0einvalidated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rinvalidatedAt\"\xc9\x01\n" +
	"\x11LiveFetchResponse\x12:\n" +
	"\ffetched_data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\vfetchedData\x12\"\n" +
	"\fcompleteness\x18\x02 \x01(\x01R\fcompleteness\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\x12<\n" +
	"\vaudit_entry\x18\x04 \x01(\v2\x1b.context_gateway.AuditEntryR\n" +
	"auditEntry\"\x9a\x01\n" +
	"\x18RecipeValidationResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\x124\n" +
	"\x16validation_duration_ms\x18\x04 \x01(\x01R\x14validationDurationMs\"\xa1\x02\n" +
	"\x0eHealthResponse\x126\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1e.context_gateway.ServiceStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12E\n" +
	"\fdependencies\x18\x04 \x03(\v2!.context_gateway.DependencyHealthR\fdependencies\x12<\n" +
	"\vcache_stats\x18\x05 \x01(\v2\x1b.context_gateway.CacheStatsR\n" +
	"cacheStats\"~\n" +
	"\x0fMetricsResponse\x121\n" +
	"\ametrics\x18\x01 \x01(\v2\x17.google.protobuf.StructR\ametrics\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xf0\x01\n" +
	"\rContextUpdate\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x1b\n" +
	"\trecipe_id\x18\x02 \x01(\tR\brecipeId\x12<\n" +
	"\vupdate_type\x18\x03 \x01(\x0e2\x1b.context_gateway.UpdateTypeR\n" +
	"updateType\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x8a\x02\n" +
	"\n" +
	"AuditEntry\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12-\n" +
	"\x12requesting_service\x18\x04 \x01(\tR\x11requestingService\x12%\n" +
	"\x0efields_fetched\x18\x05 \x03(\tR\rfieldsFetched\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x93\x02\n" +
	"\x10DependencyHealth\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.context_gateway.ServiceStatusR\x06status\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12(\n" +
	"\x10response_time_ms\x18\x04 \x01(\x05R\x0eresponseTimeMs\x129\n" +
	"\n" +
	"last_check\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\x12\x19\n" +
	"\x05error\x18\x06 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xea\x01\n" +
	"\n" +
	"CacheStats\x12#\n" +
	"\rtotal_entries\x18\x01 \x01(\x03R\ftotalEntries\x12\x1b\n" +
	"\thit_ratio\x18\x02 \x01(\x01R\bhitRatio\x12\x1d\n" +
	"\n" +
	"l1_entries\x18\x03 \x01(\x03R\tl1Entries\x12\x1d\n" +
	"\n" +
	"l2_entries\x18\x04 \x01(\x03R\tl2Entries\x12\x1d\n" +
	"\n" +
	"l3_entries\x18\x05 \x01(\x03R\tl3Entries\x12=\n" +
	"\flast_updated\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated*\x87\x01\n" +
	"\x0eSnapshotStatus\x12\x1b\n" +
	"\x17SNAPSHOT_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16SNAPSHOT_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17SNAPSHOT_STATUS_EXPIRED\x10\x02\x12\x1f\n" +
	"\x1bSNAPSHOT_STATUS_INVALIDATED\x10\x03*\x8a\x01\n" +
	"\x0fSignatureMethod\x12\x1c\n" +
	"\x18SIGNATURE_METHOD_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15SIGNATURE_METHOD_MOCK\x10\x01\x12\x1d\n" +
	"\x19SIGNATURE_METHOD_RSA_2048\x10\x02\x12\x1f\n" +
	"\x1bSIGNATURE_METHOD_ECDSA_P256\x10\x03*\x82\x01\n" +
	"\rServiceStatus\x12\x1a\n" +
	"\x16SERVICE_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16SERVICE_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17SERVICE_STATUS_DEGRADED\x10\x02\x12\x1c\n" +
	"\x18SERVICE_STATUS_UNHEALTHY\x10\x03*\xd2\x01\n" +
	"\n" +
	"UpdateType\x12\x17\n" +
	"\x13UPDATE_TYPE_UNKNOWN\x10\x00\x12 \n" +
	"\x1cUPDATE_TYPE_SNAPSHOT_CREATED\x10\x01\x12 \n" +
	"\x1cUPDATE_TYPE_SNAPSHOT_UPDATED\x10\x02\x12$\n" +
	" UPDATE_TYPE_SNAPSHOT_INVALIDATED\x10\x03\x12!\n" +
	"\x1dUPDATE_TYPE_CACHE_INVALIDATED\x10\x04\x12\x1e\n" +
	"\x1aUPDATE_TYPE_RECIPE_UPDATED\x10\x052\x9e\a\n" +
	"\x0eContextGateway\x12[\n" +
	"\x0eCreateSnapshot\x12&.context_gateway.CreateSnapshotRequest\x1a!.context_gateway.ClinicalSnapshot\x12U\n" +
	"\vGetSnapshot\x12#.context_gateway.GetSnapshotRequest\x1a!.context_gateway.ClinicalSnapshot\x12g\n" +
	"\x10ValidateSnapshot\x12(.context_gateway.ValidateSnapshotRequest\x1a).context_gateway.ValidateSnapshotResponse\x12]\n" +
	"\x12InvalidateSnapshot\x12\".context_gateway.InvalidateRequest\x1a#.context_gateway.InvalidateResponse\x12X\n" +
	"\x0fFetchLiveFields\x12!.context_gateway.LiveFetchRequest\x1a\".context_gateway.LiveFetchResponse\x12Q\n" +
	"\n" +
	"LoadRecipe\x12\".context_gateway.LoadRecipeRequest\x1a\x1f.context_gateway.WorkflowRecipe\x12c\n" +
	"\x0eValidateRecipe\x12&.context_gateway.ValidateRecipeRequest\x1a).context_gateway.RecipeValidationResponse\x12S\n" +
	"\x10GetServiceHealth\x12\x1e.context_gateway.HealthRequest\x1a\x1f.context_gateway.HealthResponse\x12O\n" +
	"\n" +
	"GetMetrics\x12\x1f.context_gateway.MetricsRequest\x1a .context_gateway.MetricsResponse\x12X\n" +
	"\x14StreamContextUpdates\x12\x1e.context_gateway.StreamRequest\x1a\x1e.context_gateway.ContextUpdate0\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_context_gateway_proto_rawDescOnce sync.Once
	file_proto_context_gateway_proto_rawDescData []byte
)

func file_proto_context_gateway_proto_rawDescGZIP() []byte {
	file_proto_context_gateway_proto_rawDescOnce.Do(func() {
		file_proto_context_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_context_gateway_proto_rawDesc), len(file_proto_context_gateway_proto_rawDesc)))
	})
	return file_proto_context_gateway_proto_rawDescData
}

var file_proto_context_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_context_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_context_gateway_proto_goTypes = []any{
	(SnapshotStatus)(0),              // 0: context_gateway.SnapshotStatus
	(SignatureMethod)(0),             // 1: context_gateway.SignatureMethod
	(ServiceStatus)(0),               // 2: context_gateway.ServiceStatus
	(UpdateType)(0),                  // 3: context_gateway.UpdateType
	(*CreateSnapshotRequest)(nil),    // 4: context_gateway.CreateSnapshotRequest
	(*GetSnapshotRequest)(nil),       // 5: context_gateway.GetSnapshotRequest
	(*ValidateSnapshotRequest)(nil),  // 6: context_gateway.ValidateSnapshotRequest
	(*InvalidateRequest)(nil),        // 7: context_gateway.InvalidateRequest
	(*LiveFetchRequest)(nil),         // 8: context_gateway.LiveFetchRequest
	(*LoadRecipeRequest)(nil),        // 9: context_gateway.LoadRecipeRequest
	(*ValidateRecipeRequest)(nil),    // 10: context_gateway.ValidateRecipeRequest
	(*HealthRequest)(nil),            // 11: context_gateway.HealthRequest
	(*MetricsRequest)(nil),           // 12: context_gateway.MetricsRequest
	(*StreamRequest)(nil),            // 13: context_gateway.StreamRequest
	(*ClinicalSnapshot)(nil),         // 14: context_gateway.ClinicalSnapshot
	(*WorkflowRecipe)(nil),           // 15: context_gateway.WorkflowRecipe
	(*DataPoint)(nil),                // 16: context_gateway.DataPoint
	(*ConditionalRule)(nil),          // 17: context_gateway.ConditionalRule
	(*QualityConstraints)(nil),       // 18: context_gateway.QualityConstraints
	(*SafetyRequirements)(nil),       // 19: context_gateway.SafetyRequirements
	(*CacheStrategy)(nil),            // 20: context_gateway.CacheStrategy
	(*AssemblyRules)(nil),            // 21: context_gateway.AssemblyRules
	(*GovernanceMetadata)(nil),       // 22: context_gateway.GovernanceMetadata
	(*ValidateSnapshotResponse)(nil), // 23: context_gateway.ValidateSnapshotResponse
	(*InvalidateResponse)(nil),       // 24: context_gateway.InvalidateResponse
	(*LiveFetchResponse)(nil),        // 25: context_gateway.LiveFetchResponse
	(*RecipeValidationResponse)(nil), // 26: context_gateway.RecipeValidationResponse
	(*HealthResponse)(nil),           // 27: context_gateway.HealthResponse
	(*MetricsResponse)(nil),          // 28: context_gateway.MetricsResponse
	(*ContextUpdate)(nil),            // 29: context_gateway.ContextUpdate
	(*AuditEntry)(nil),               // 30: context_gateway.AuditEntry
	(*DependencyHealth)(nil),         // 31: context_gateway.DependencyHealth
	(*CacheStats)(nil),               // 32: context_gateway.CacheStats
	(*structpb.Struct)(nil),          // 33: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),    // 34: google.protobuf.Timestamp
}
var file_proto_context_gateway_proto_depIdxs = []int32{
	15, // 0: context_gateway.CreateSnapshotRequest.recipe:type_name -> context_gateway.WorkflowRecipe
	15, // 1: context_gateway.ValidateRecipeRequest.recipe:type_name -> context_gateway.WorkflowRecipe
	33, // 2: context_gateway.ClinicalSnapshot.data:type_name -> google.protobuf.Struct
	1,  // 3: context_gateway.ClinicalSnapshot.signature_method:type_name -> context_gateway.SignatureMethod
	34, // 4: context_gateway.ClinicalSnapshot.created_at:type_name -> google.protobuf.Timestamp
	34, // 5: context_gateway.ClinicalSnapshot.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 6: context_gateway.ClinicalSnapshot.status:type_name -> context_gateway.SnapshotStatus
	33, // 7: context_gateway.ClinicalSnapshot.assembly_metadata:type_name -> google.protobuf.Struct
	33, // 8: context_gateway.ClinicalSnapshot.evidence_envelope:type_name -> google.protobuf.Struct
	34, // 9: context_gateway.ClinicalSnapshot.last_accessed_at:type_name -> google.protobuf.Timestamp
	16, // 10: context_gateway.WorkflowRecipe.required_fields:type_name -> context_gateway.DataPoint
	17, // 11: context_gateway.WorkflowRecipe.conditional_rules:type_name -> context_gateway.ConditionalRule
	18, // 12: context_gateway.WorkflowRecipe.quality_constraints:type_name -> context_gateway.QualityConstraints
	19, // 13: context_gateway.WorkflowRecipe.safety_requirements:type_name -> context_gateway.SafetyRequirements
	20, // 14: context_gateway.WorkflowRecipe.cache_strategy:type_name -> context_gateway.CacheStrategy
	21, // 15: context_gateway.WorkflowRecipe.assembly_rules:type_name -> context_gateway.AssemblyRules
	22, // 16: context_gateway.WorkflowRecipe.governance_metadata:type_name -> context_gateway.GovernanceMetadata
	16, // 17: context_gateway.ConditionalRule.additional_data_points:type_name -> context_gateway.DataPoint
	34, // 18: context_gateway.GovernanceMetadata.approval_date:type_name -> google.protobuf.Timestamp
	34, // 19: context_gateway.GovernanceMetadata.effective_date:type_name -> google.protobuf.Timestamp
	34, // 20: context_gateway.GovernanceMetadata.expiry_date:type_name -> google.protobuf.Timestamp
	34, // 21: context_gateway.InvalidateResponse.invalidated_at:type_name -> google.protobuf.Timestamp
	33, // 22: context_gateway.LiveFetchResponse.fetched_data:type_name -> google.protobuf.Struct
	30, // 23: context_gateway.LiveFetchResponse.audit_entry:type_name -> context_gateway.AuditEntry
	2,  // 24: context_gateway.HealthResponse.status:type_name -> context_gateway.ServiceStatus
	34, // 25: context_gateway.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	31, // 26: context_gateway.HealthResponse.dependencies:type_name -> context_gateway.DependencyHealth
	32, // 27: context_gateway.HealthResponse.cache_stats:type_name -> context_gateway.CacheStats
	33, // 28: context_gateway.MetricsResponse.metrics:type_name -> google.protobuf.Struct
	34, // 29: context_gateway.MetricsResponse.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 30: context_gateway.ContextUpdate.update_type:type_name -> context_gateway.UpdateType
	33, // 31: context_gateway.ContextUpdate.data:type_name -> google.protobuf.Struct
	34, // 32: context_gateway.ContextUpdate.timestamp:type_name -> google.protobuf.Timestamp
	34, // 33: context_gateway.AuditEntry.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 34: context_gateway.DependencyHealth.status:type_name -> context_gateway.ServiceStatus
	34, // 35: context_gateway.DependencyHealth.last_check:type_name -> google.protobuf.Timestamp
	34, // 36: context_gateway.CacheStats.last_updated:type_name -> google.protobuf.Timestamp
	4,  // 37: context_gateway.ContextGateway.CreateSnapshot:input_type -> context_gateway.CreateSnapshotRequest
	5,  // 38: context_gateway.ContextGateway.GetSnapshot:input_type -> context_gateway.GetSnapshotRequest
	6,  // 39: context_gateway.ContextGateway.ValidateSnapshot:input_type -> context_gateway.ValidateSnapshotRequest
	7,  // 40: context_gateway.ContextGateway.InvalidateSnapshot:input_type -> context_gateway.InvalidateRequest
	8,  // 41: context_gateway.ContextGateway.FetchLiveFields:input_type -> context_gateway.LiveFetchRequest
	9,  // 42: context_gateway.ContextGateway.LoadRecipe:input_type -> context_gateway.LoadRecipeRequest
	10, // 43: context_gateway.ContextGateway.ValidateRecipe:input_type -> context_gateway.ValidateRecipeRequest
	11, // 44: context_gateway.ContextGateway.GetServiceHealth:input_type -> context_gateway.HealthRequest
	12, // 45: context_gateway.ContextGateway.GetMetrics:input_type -> context_gateway.MetricsRequest
	13, // 46: context_gateway.ContextGateway.StreamContextUpdates:input_type -> context_gateway.StreamRequest
	14, // 47: context_gateway.ContextGateway.CreateSnapshot:output_type -> context_gateway.ClinicalSnapshot
	14, // 48: context_gateway.ContextGateway.GetSnapshot:output_type -> context_gateway.ClinicalSnapshot
	23, // 49: context_gateway.ContextGateway.ValidateSnapshot:output_type -> context_gateway.ValidateSnapshotResponse
	24, // 50: context_gateway.ContextGateway.InvalidateSnapshot:output_type -> context_gateway.InvalidateResponse
	25, // 51: context_gateway.ContextGateway.FetchLiveFields:output_type -> context_gateway.LiveFetchResponse
	15, // 52: context_gateway.ContextGateway.LoadRecipe:output_type -> context_gateway.WorkflowRecipe
	26, // 53: context_gateway.ContextGateway.ValidateRecipe:output_type -> context_gateway.RecipeValidationResponse
	27, // 54: context_gateway.ContextGateway.GetServiceHealth:output_type -> context_gateway.HealthResponse
	28, // 55: context_gateway.ContextGateway.GetMetrics:output_type -> context_gateway.MetricsResponse
	29, // 56: context_gateway.ContextGateway.StreamContextUpdates:output_type -> context_gateway.ContextUpdate
	47, // [47:57] is the sub-list for method output_type
	37, // [37:47] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_proto_context_gateway_proto_init() }
func file_proto_context_gateway_proto_init() {
	if File_proto_context_gateway_proto != nil {
		return
	}
	file_proto_context_gateway_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_context_gateway_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_context_gateway_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_context_gateway_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_context_gateway_proto_msgTypes[27].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_context_gateway_proto_rawDesc), len(file_proto_context_gateway_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_context_gateway_proto_goTypes,
		DependencyIndexes: file_proto_context_gateway_proto_depIdxs,
		EnumInfos:         file_proto_context_gateway_proto_enumTypes,
		MessageInfos:      file_proto_context_gateway_proto_msgTypes,
	}.Build()
	File_proto_context_gateway_proto = out.File
	file_proto_context_gateway_proto_goTypes = nil
	file_proto_context_gateway_proto_depIdxs = nil
}
