package com.cardiofit.flink.models;

import com.cardiofit.flink.cds.time.TimeConstraintStatus;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Clinical Recommendation - Evidence-based clinical action recommendations
 *
 * Comprehensive clinical recommendation with protocol-based actions,
 * contraindication checking, and evidence attribution. Generated by
 * Module 3 Clinical Recommendation Processor.
 *
 * @author CardioFit Platform - Module 3
 * @version 1.0
 * @since 2025-10-20
 */
public class ClinicalRecommendation implements Serializable {
    private static final long serialVersionUID = 1L;

    // Identification
    @JsonProperty("recommendation_id")
    private String recommendationId;

    @JsonProperty("patient_id")
    private String patientId;

    @JsonProperty("triggered_by_alert")
    private String triggeredByAlert;

    @JsonProperty("timestamp")
    private long timestamp;

    // Protocol Information
    @JsonProperty("protocol_id")
    private String protocolId;

    @JsonProperty("protocol_name")
    private String protocolName;

    @JsonProperty("protocol_category")
    private String protocolCategory;  // INFECTION, CARDIOVASCULAR, RESPIRATORY, METABOLIC

    @JsonProperty("evidence_base")
    private String evidenceBase;

    @JsonProperty("guideline_section")
    private String guidelineSection;

    // Actions
    @JsonProperty("actions")
    private List<ClinicalAction> actions;

    // Priority & Timing
    @JsonProperty("priority")
    private String priority;  // CRITICAL, HIGH, MEDIUM, LOW

    @JsonProperty("timeframe")
    private String timeframe;  // IMMEDIATE, <1hr, <4hr, ROUTINE

    @JsonProperty("urgency_rationale")
    private String urgencyRationale;

    // Safety Validation
    @JsonProperty("contraindications_checked")
    private List<Contraindication> contraindicationsChecked;

    @JsonProperty("safe_to_implement")
    private boolean safeToImplement;

    @JsonProperty("warnings")
    private List<String> warnings;

    // Alternative Plans
    @JsonProperty("alternatives")
    private List<ClinicalAction> alternatives;

    // Monitoring Requirements
    @JsonProperty("monitoring_requirements")
    private List<String> monitoringRequirements;

    @JsonProperty("escalation_criteria")
    private String escalationCriteria;

    // Confidence & Source
    @JsonProperty("confidence_score")
    private double confidenceScore;

    @JsonProperty("reasoning_path")
    private String reasoningPath;

    // NEW: Module 3 Phase 3 Integration Fields

    /**
     * Confidence score from ConfidenceCalculator.
     * Range: 0.0 to 1.0
     * Higher values indicate greater confidence in protocol match.
     */
    @JsonProperty("confidence")
    private double confidence;

    /**
     * Time constraint tracking status.
     * Contains evaluation results for all time-based protocol constraints.
     */
    @JsonProperty("time_constraint_status")
    private TimeConstraintStatus timeConstraintStatus;

    /**
     * Escalation recommendations from EscalationRuleEvaluator.
     * Contains triggered escalation paths and personnel requirements.
     */
    @JsonProperty("escalation_recommendations")
    private List<EscalationRecommendation> escalationRecommendations;

    // Default constructor
    public ClinicalRecommendation() {
        this.timestamp = System.currentTimeMillis();
        this.recommendationId = java.util.UUID.randomUUID().toString();
        this.actions = new ArrayList<>();
        this.contraindicationsChecked = new ArrayList<>();
        this.warnings = new ArrayList<>();
        this.alternatives = new ArrayList<>();
        this.monitoringRequirements = new ArrayList<>();
        this.escalationRecommendations = new ArrayList<>();
        this.safeToImplement = true;
        this.confidence = 0.0;
    }

    // Builder pattern
    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {
        private ClinicalRecommendation recommendation = new ClinicalRecommendation();

        public Builder recommendationId(String recommendationId) {
            recommendation.recommendationId = recommendationId;
            return this;
        }

        public Builder patientId(String patientId) {
            recommendation.patientId = patientId;
            return this;
        }

        public Builder triggeredByAlert(String triggeredByAlert) {
            recommendation.triggeredByAlert = triggeredByAlert;
            return this;
        }

        public Builder protocolId(String protocolId) {
            recommendation.protocolId = protocolId;
            return this;
        }

        public Builder protocolName(String protocolName) {
            recommendation.protocolName = protocolName;
            return this;
        }

        public Builder protocolCategory(String protocolCategory) {
            recommendation.protocolCategory = protocolCategory;
            return this;
        }

        public Builder evidenceBase(String evidenceBase) {
            recommendation.evidenceBase = evidenceBase;
            return this;
        }

        public Builder actions(List<ClinicalAction> actions) {
            recommendation.actions = actions;
            return this;
        }

        public Builder addAction(ClinicalAction action) {
            recommendation.actions.add(action);
            return this;
        }

        public Builder priority(String priority) {
            recommendation.priority = priority;
            return this;
        }

        public Builder timeframe(String timeframe) {
            recommendation.timeframe = timeframe;
            return this;
        }

        public Builder urgencyRationale(String urgencyRationale) {
            recommendation.urgencyRationale = urgencyRationale;
            return this;
        }

        public Builder safeToImplement(boolean safeToImplement) {
            recommendation.safeToImplement = safeToImplement;
            return this;
        }

        public Builder confidenceScore(double confidenceScore) {
            recommendation.confidenceScore = confidenceScore;
            return this;
        }

        public ClinicalRecommendation build() {
            return recommendation;
        }
    }

    // Getters and Setters
    public String getRecommendationId() { return recommendationId; }
    public void setRecommendationId(String recommendationId) { this.recommendationId = recommendationId; }

    public String getPatientId() { return patientId; }
    public void setPatientId(String patientId) { this.patientId = patientId; }

    public String getTriggeredByAlert() { return triggeredByAlert; }
    public void setTriggeredByAlert(String triggeredByAlert) { this.triggeredByAlert = triggeredByAlert; }

    public long getTimestamp() { return timestamp; }
    public void setTimestamp(long timestamp) { this.timestamp = timestamp; }

    public String getProtocolId() { return protocolId; }
    public void setProtocolId(String protocolId) { this.protocolId = protocolId; }

    public String getProtocolName() { return protocolName; }
    public void setProtocolName(String protocolName) { this.protocolName = protocolName; }

    public String getProtocolCategory() { return protocolCategory; }
    public void setProtocolCategory(String protocolCategory) { this.protocolCategory = protocolCategory; }

    public String getEvidenceBase() { return evidenceBase; }
    public void setEvidenceBase(String evidenceBase) { this.evidenceBase = evidenceBase; }

    public String getGuidelineSection() { return guidelineSection; }
    public void setGuidelineSection(String guidelineSection) { this.guidelineSection = guidelineSection; }

    public List<ClinicalAction> getActions() { return actions; }
    public void setActions(List<ClinicalAction> actions) { this.actions = actions; }

    public String getPriority() { return priority; }
    public void setPriority(String priority) { this.priority = priority; }

    public String getTimeframe() { return timeframe; }
    public void setTimeframe(String timeframe) { this.timeframe = timeframe; }

    public String getUrgencyRationale() { return urgencyRationale; }
    public void setUrgencyRationale(String urgencyRationale) { this.urgencyRationale = urgencyRationale; }

    public List<Contraindication> getContraindicationsChecked() { return contraindicationsChecked; }
    public void setContraindicationsChecked(List<Contraindication> contraindicationsChecked) {
        this.contraindicationsChecked = contraindicationsChecked;
    }

    public boolean isSafeToImplement() { return safeToImplement; }
    public void setSafeToImplement(boolean safeToImplement) { this.safeToImplement = safeToImplement; }

    public List<String> getWarnings() { return warnings; }
    public void setWarnings(List<String> warnings) { this.warnings = warnings; }

    public List<ClinicalAction> getAlternatives() { return alternatives; }
    public void setAlternatives(List<ClinicalAction> alternatives) { this.alternatives = alternatives; }

    public List<String> getMonitoringRequirements() { return monitoringRequirements; }
    public void setMonitoringRequirements(List<String> monitoringRequirements) {
        this.monitoringRequirements = monitoringRequirements;
    }

    public String getEscalationCriteria() { return escalationCriteria; }
    public void setEscalationCriteria(String escalationCriteria) { this.escalationCriteria = escalationCriteria; }

    public double getConfidenceScore() { return confidenceScore; }
    public void setConfidenceScore(double confidenceScore) { this.confidenceScore = confidenceScore; }

    public String getReasoningPath() { return reasoningPath; }
    public void setReasoningPath(String reasoningPath) { this.reasoningPath = reasoningPath; }

    // NEW: Module 3 Phase 3 Integration Getters and Setters

    public double getConfidence() {
        return confidence;
    }

    public void setConfidence(double confidence) {
        this.confidence = confidence;
    }

    public TimeConstraintStatus getTimeConstraintStatus() {
        return timeConstraintStatus;
    }

    public void setTimeConstraintStatus(TimeConstraintStatus timeConstraintStatus) {
        this.timeConstraintStatus = timeConstraintStatus;
    }

    public List<EscalationRecommendation> getEscalationRecommendations() {
        return escalationRecommendations;
    }

    public void setEscalationRecommendations(List<EscalationRecommendation> escalationRecommendations) {
        this.escalationRecommendations = escalationRecommendations;
    }

    // Utility methods

    /**
     * Check if recommendation is critical priority
     */
    public boolean isCritical() {
        return "CRITICAL".equals(priority);
    }

    /**
     * Check if recommendation requires immediate action
     */
    public boolean isImmediate() {
        return "IMMEDIATE".equals(timeframe);
    }

    /**
     * Check if recommendation has any warnings
     */
    public boolean hasWarnings() {
        return warnings != null && !warnings.isEmpty();
    }

    /**
     * Check if alternatives are available
     */
    public boolean hasAlternatives() {
        return alternatives != null && !alternatives.isEmpty();
    }

    /**
     * Get count of recommended actions
     */
    public int getActionCount() {
        return actions != null ? actions.size() : 0;
    }

    @Override
    public String toString() {
        return "ClinicalRecommendation{" +
            "recommendationId='" + recommendationId + '\'' +
            ", patientId='" + patientId + '\'' +
            ", protocolName='" + protocolName + '\'' +
            ", priority='" + priority + '\'' +
            ", timeframe='" + timeframe + '\'' +
            ", actionCount=" + getActionCount() +
            ", safeToImplement=" + safeToImplement +
            '}';
    }
}
