package com.cardiofit.flink.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.io.Serializable;
import java.util.*;

/**
 * Unified patient context state for the PatientContextAggregator operator.
 *
 * This is the single source of truth for all patient data across vitals, labs,
 * and medications. Stored in RocksDB keyed by patientId.
 *
 * Architecture Pattern: Unified State Management
 * - Single operator maintains this state
 * - All event types (vitals, labs, meds) update the same state object
 * - Eliminates race conditions from multiple operators
 * - Guarantees state consistency with exactly-once semantics
 *
 * State Size Optimization:
 * - Uses Map<String, Object> for flexible storage
 * - LOINC/RxNorm codes as keys for efficient lookup
 * - Time-windowed data retention to bound state size
 * - RocksDB compression reduces memory footprint
 * - Empty collections excluded from JSON to reduce payload size
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY)
public class PatientContextState implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * Patient identifier (state key)
     */
    @JsonProperty("patientId")
    private String patientId;

    /**
     * Latest vital signs snapshot
     * Key: vital parameter name (lowercase)
     * Value: numeric value or String for BP ("120/80")
     *
     * Example entries:
     * - "heartrate" → 85
     * - "systolicbloodpressure" → 130
     * - "oxygensaturation" → 96
     * - "temperature" → 37.1
     */
    @JsonProperty("latestVitals")
    private Map<String, Object> latestVitals;

    /**
     * Recent lab results (time-windowed)
     * Key: LOINC code (e.g., "10839-9" for Troponin I)
     * Value: LabResult object with value, timestamp, abnormal flags
     *
     * Window: Last 24-48 hours depending on lab type
     * - Cardiac markers: 24 hours
     * - Metabolic panel: 48 hours
     * - Hematology: 48 hours
     */
    @JsonProperty("recentLabs")
    private Map<String, LabResult> recentLabs;

    /**
     * Active medications (current regimen)
     * Key: RxNorm code (e.g., "83367" for Telmisartan)
     * Value: Medication object with dose, frequency, start time
     *
     * Only includes actively prescribed medications
     * Removed when discontinued or expired
     */
    @JsonProperty("activeMedications")
    private Map<String, Medication> activeMedications;

    /**
     * Active alerts generated by clinical rules
     * Set of unique alerts (deduplicated)
     * Alerts cleared when condition resolves
     *
     * Note: Internal storage includes all alerts (visible + suppressed)
     * JSON output filtered via getActiveAlerts() to show only visible alerts
     */
    @com.fasterxml.jackson.annotation.JsonIgnore
    private Set<SimpleAlert> activeAlertsInternal;

    /**
     * Returns only visible alerts (excludes suppressed child alerts)
     * Used for JSON serialization
     */
    @JsonProperty("activeAlerts")
    public Set<SimpleAlert> getActiveAlerts() {
        if (activeAlertsInternal == null) {
            return null;
        }
        // Filter out suppressed alerts for display
        Set<SimpleAlert> visible = new java.util.LinkedHashSet<>();
        for (SimpleAlert alert : activeAlertsInternal) {
            if (alert.getSuppressDisplay() == null || !alert.getSuppressDisplay()) {
                visible.add(alert);
            }
        }
        return visible;
    }

    /**
     * Returns all alerts including suppressed ones (for internal processing)
     */
    public Set<SimpleAlert> getAllAlerts() {
        return activeAlertsInternal;
    }

    /**
     * Computed risk indicators from current state
     * Updated after each event processing
     */
    @JsonProperty("riskIndicators")
    private RiskIndicators riskIndicators;

    /**
     * Clinical scores computed from current state
     */
    @JsonProperty("news2Score")
    private Integer news2Score; // National Early Warning Score 2

    @JsonProperty("qsofaScore")
    private Integer qsofaScore; // Quick SOFA for sepsis screening

    @JsonProperty("combinedAcuityScore")
    private Double combinedAcuityScore; // Combined risk metric

    /**
     * Combined Acuity Calculation Metadata
     * Provides transparency into how combinedAcuityScore is calculated
     */
    @JsonProperty("acuityLevel")
    private String acuityLevel; // LOW, MEDIUM, HIGH, CRITICAL

    @JsonProperty("acuityCalculationMethod")
    private String acuityCalculationMethod; // Formula description

    @JsonProperty("acuityComponents")
    private Map<String, Object> acuityComponents; // NEWS2, metabolic scores and weights

    /**
     * Patient demographics and chronic conditions
     * Enriched from FHIR/Neo4j on first event
     */
    @JsonProperty("demographics")
    private PatientDemographics demographics;

    @JsonProperty("chronicConditions")
    private List<Condition> chronicConditions;

    /**
     * FHIR Enrichment Data
     * Populated by PatientContextEnricher from Google Healthcare FHIR API
     */
    @JsonProperty("allergies")
    private List<String> allergies;

    @JsonProperty("fhirMedications")
    private List<Medication> fhirMedications;

    @JsonProperty("fhirCareTeam")
    private List<String> fhirCareTeam;

    /**
     * Neo4j Graph Enrichment Data
     * Populated by PatientContextEnricher from Neo4j graph database
     */
    @JsonProperty("neo4jCareTeam")
    private List<String> neo4jCareTeam;

    @JsonProperty("riskCohorts")
    private List<String> riskCohorts;

    @JsonProperty("carePathways")
    private List<String> carePathways;

    /**
     * Advanced Graph Analytics (Phase 2 placeholders)
     * Will be populated in future enhancement
     */
    @JsonProperty("similarPatients")
    private List<String> similarPatients;

    @JsonProperty("cohortInsights")
    private Map<String, Object> cohortInsights;

    /**
     * State metadata
     */
    @JsonProperty("lastUpdated")
    private long lastUpdated;

    @JsonProperty("lastVitalUpdate")
    private Long lastVitalUpdate;

    @JsonProperty("lastLabUpdate")
    private Long lastLabUpdate;

    @JsonProperty("lastMedicationUpdate")
    private Long lastMedicationUpdate;

    @JsonProperty("eventCount")
    private long eventCount;

    /**
     * Flags for data completeness
     */
    @JsonProperty("hasFhirData")
    private boolean hasFhirData;

    @JsonProperty("hasNeo4jData")
    private boolean hasNeo4jData;

    @JsonProperty("enrichmentComplete")
    private boolean enrichmentComplete;

    public PatientContextState() {
        this.latestVitals = new HashMap<>();
        this.recentLabs = new HashMap<>();
        this.activeMedications = new HashMap<>();
        this.activeAlertsInternal = new LinkedHashSet<>();
        this.chronicConditions = new ArrayList<>();
        this.riskIndicators = new RiskIndicators();

        // Initialize FHIR enrichment collections
        this.allergies = new ArrayList<>();
        this.fhirMedications = new ArrayList<>();
        this.fhirCareTeam = new ArrayList<>();

        // Initialize Neo4j enrichment collections
        this.neo4jCareTeam = new ArrayList<>();
        this.riskCohorts = new ArrayList<>();
        this.carePathways = new ArrayList<>();

        // Initialize Phase 2 placeholders
        this.similarPatients = new ArrayList<>();
        this.cohortInsights = new HashMap<>();

        this.lastUpdated = System.currentTimeMillis();
        this.eventCount = 0;
        this.hasFhirData = false;
        this.hasNeo4jData = false;
        this.enrichmentComplete = false;
    }

    /**
     * Constructor with patient ID
     */
    public PatientContextState(String patientId) {
        this();
        this.patientId = patientId;
    }

    // Getters and setters

    public String getPatientId() {
        return patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public Map<String, Object> getLatestVitals() {
        return latestVitals;
    }

    public void setLatestVitals(Map<String, Object> latestVitals) {
        this.latestVitals = latestVitals;
    }

    public Map<String, LabResult> getRecentLabs() {
        return recentLabs;
    }

    public void setRecentLabs(Map<String, LabResult> recentLabs) {
        this.recentLabs = recentLabs;
    }

    public Map<String, Medication> getActiveMedications() {
        return activeMedications;
    }

    public void setActiveMedications(Map<String, Medication> activeMedications) {
        this.activeMedications = activeMedications;
    }

    /**
     * Set active alerts (stores all alerts including suppressed ones internally)
     */
    public void setActiveAlerts(Set<SimpleAlert> activeAlerts) {
        this.activeAlertsInternal = activeAlerts;
    }

    /**
     * Add a single alert to the active alerts set
     */
    public void addAlert(SimpleAlert alert) {
        if (activeAlertsInternal == null) {
            activeAlertsInternal = new java.util.LinkedHashSet<>();
        }
        activeAlertsInternal.add(alert);
    }

    public RiskIndicators getRiskIndicators() {
        return riskIndicators;
    }

    public void setRiskIndicators(RiskIndicators riskIndicators) {
        this.riskIndicators = riskIndicators;
    }

    public Integer getNews2Score() {
        return news2Score;
    }

    public void setNews2Score(Integer news2Score) {
        this.news2Score = news2Score;
    }

    public Integer getQsofaScore() {
        return qsofaScore;
    }

    public void setQsofaScore(Integer qsofaScore) {
        this.qsofaScore = qsofaScore;
    }

    public Double getCombinedAcuityScore() {
        return combinedAcuityScore;
    }

    public void setCombinedAcuityScore(Double combinedAcuityScore) {
        this.combinedAcuityScore = combinedAcuityScore;
    }

    public String getAcuityLevel() {
        return acuityLevel;
    }

    public void setAcuityLevel(String acuityLevel) {
        this.acuityLevel = acuityLevel;
    }

    public String getAcuityCalculationMethod() {
        return acuityCalculationMethod;
    }

    public void setAcuityCalculationMethod(String acuityCalculationMethod) {
        this.acuityCalculationMethod = acuityCalculationMethod;
    }

    public Map<String, Object> getAcuityComponents() {
        return acuityComponents;
    }

    public void setAcuityComponents(Map<String, Object> acuityComponents) {
        this.acuityComponents = acuityComponents;
    }

    public PatientDemographics getDemographics() {
        return demographics;
    }

    public void setDemographics(PatientDemographics demographics) {
        this.demographics = demographics;
    }

    public List<Condition> getChronicConditions() {
        return chronicConditions;
    }

    public void setChronicConditions(List<Condition> chronicConditions) {
        this.chronicConditions = chronicConditions;
    }

    // FHIR Enrichment Getters and Setters

    public List<String> getAllergies() {
        return allergies;
    }

    public void setAllergies(List<String> allergies) {
        this.allergies = allergies;
    }

    public List<Medication> getFhirMedications() {
        return fhirMedications;
    }

    public void setFhirMedications(List<Medication> fhirMedications) {
        this.fhirMedications = fhirMedications;
    }

    public List<String> getFhirCareTeam() {
        return fhirCareTeam;
    }

    public void setFhirCareTeam(List<String> fhirCareTeam) {
        this.fhirCareTeam = fhirCareTeam;
    }

    // Neo4j Graph Enrichment Getters and Setters

    public List<String> getNeo4jCareTeam() {
        return neo4jCareTeam;
    }

    public void setNeo4jCareTeam(List<String> neo4jCareTeam) {
        this.neo4jCareTeam = neo4jCareTeam;
    }

    public List<String> getRiskCohorts() {
        return riskCohorts;
    }

    public void setRiskCohorts(List<String> riskCohorts) {
        this.riskCohorts = riskCohorts;
    }

    public List<String> getCarePathways() {
        return carePathways;
    }

    public void setCarePathways(List<String> carePathways) {
        this.carePathways = carePathways;
    }

    // Phase 2 Advanced Analytics Getters and Setters

    public List<String> getSimilarPatients() {
        return similarPatients;
    }

    public void setSimilarPatients(List<String> similarPatients) {
        this.similarPatients = similarPatients;
    }

    public Map<String, Object> getCohortInsights() {
        return cohortInsights;
    }

    public void setCohortInsights(Map<String, Object> cohortInsights) {
        this.cohortInsights = cohortInsights;
    }

    public long getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(long lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public Long getLastVitalUpdate() {
        return lastVitalUpdate;
    }

    public void setLastVitalUpdate(Long lastVitalUpdate) {
        this.lastVitalUpdate = lastVitalUpdate;
    }

    public Long getLastLabUpdate() {
        return lastLabUpdate;
    }

    public void setLastLabUpdate(Long lastLabUpdate) {
        this.lastLabUpdate = lastLabUpdate;
    }

    public Long getLastMedicationUpdate() {
        return lastMedicationUpdate;
    }

    public void setLastMedicationUpdate(Long lastMedicationUpdate) {
        this.lastMedicationUpdate = lastMedicationUpdate;
    }

    public long getEventCount() {
        return eventCount;
    }

    public void setEventCount(long eventCount) {
        this.eventCount = eventCount;
    }

    public boolean isHasFhirData() {
        return hasFhirData;
    }

    public void setHasFhirData(boolean hasFhirData) {
        this.hasFhirData = hasFhirData;
    }

    public boolean isHasNeo4jData() {
        return hasNeo4jData;
    }

    public void setHasNeo4jData(boolean hasNeo4jData) {
        this.hasNeo4jData = hasNeo4jData;
    }

    public boolean isEnrichmentComplete() {
        return enrichmentComplete;
    }

    public void setEnrichmentComplete(boolean enrichmentComplete) {
        this.enrichmentComplete = enrichmentComplete;
    }

    /**
     * Increment event count and update timestamp
     */
    public void recordEvent(String eventType) {
        this.eventCount++;
        this.lastUpdated = System.currentTimeMillis();

        if ("VITAL_SIGN".equals(eventType)) {
            this.lastVitalUpdate = this.lastUpdated;
        } else if ("LAB_RESULT".equals(eventType)) {
            this.lastLabUpdate = this.lastUpdated;
        } else if ("MEDICATION_UPDATE".equals(eventType)) {
            this.lastMedicationUpdate = this.lastUpdated;
        }
    }

    /**
     * Clear alerts of a specific type
     */
    public void clearAlerts(AlertType alertType) {
        if (activeAlertsInternal != null) {
            this.activeAlertsInternal.removeIf(alert -> alert.getAlertType() == alertType);
        }
    }

    /**
     * Check if state has minimum data for analysis
     */
    public boolean hasMinimumData() {
        return !latestVitals.isEmpty() || !recentLabs.isEmpty() || !activeMedications.isEmpty();
    }

    /**
     * Check if vitals are stale (no update in last 5 minutes)
     */
    public boolean areVitalsStale() {
        if (lastVitalUpdate == null) return true;
        long fiveMinutesAgo = System.currentTimeMillis() - (5 * 60 * 1000);
        return lastVitalUpdate < fiveMinutesAgo;
    }

    /**
     * Prune old lab results beyond retention window
     * Call periodically to bound state size
     */
    public void pruneOldLabs(long retentionMillis) {
        long cutoffTime = System.currentTimeMillis() - retentionMillis;
        recentLabs.entrySet().removeIf(entry ->
            entry.getValue().getTimestamp() < cutoffTime
        );
    }

    @Override
    public String toString() {
        return "PatientContextState{" +
                "patientId='" + patientId + '\'' +
                ", vitalsCount=" + latestVitals.size() +
                ", labsCount=" + recentLabs.size() +
                ", medsCount=" + activeMedications.size() +
                ", alertsCount=" + (activeAlertsInternal != null ? activeAlertsInternal.size() : 0) +
                ", eventCount=" + eventCount +
                ", enriched=" + enrichmentComplete +
                ", news2=" + news2Score +
                ", qsofa=" + qsofaScore +
                ", acuity=" + combinedAcuityScore +
                '}';
    }
}
