package com.cardiofit.flink.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * SimpleAlert represents threshold-based alerts generated by Module 2 (Context Assembly & Enrichment)
 * These are immediate concerns that don't require complex pattern matching
 *
 * Examples:
 * - Heart rate > 140 bpm
 * - Systolic BP < 90 mmHg
 * - Temperature > 38.3°C
 * - SpO2 < 92%
 * - MEWS score >= 5
 * - Lab critical values
 *
 * Example usage:
 * <pre>
 * SimpleAlert alert = SimpleAlert.builder()
 *     .patientId("P12345")
 *     .alertType(AlertType.VITAL_THRESHOLD_BREACH)
 *     .severity(AlertSeverity.CRITICAL)
 *     .message("Heart rate critically elevated: 165 bpm")
 *     .addContext("heart_rate", 165)
 *     .addContext("threshold", 140)
 *     .sourceModule("MODULE_2_THRESHOLD")
 *     .build();
 * </pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class SimpleAlert implements Serializable {
    private static final long serialVersionUID = 1L;

    @JsonProperty("alert_id")
    private String alertId;

    @JsonProperty("patient_id")
    private String patientId;

    @JsonProperty("alert_type")
    private AlertType alertType;

    @JsonProperty("severity")
    private AlertSeverity severity;  // INFO, WARNING, HIGH, CRITICAL

    @JsonProperty("message")
    private String message;  // Human-readable alert message

    @JsonProperty("context")
    private Map<String, Object> context;  // Additional context data (vital values, thresholds, etc.)

    @JsonProperty("timestamp")
    private long timestamp;  // When the alert was generated

    @JsonProperty("source_module")
    private String sourceModule;  // "MODULE_2_THRESHOLD", "MODULE_4_CEP_SEPSIS", etc.

    // Temporal correlation fields for downstream joins (Module 4)
    @JsonProperty("observation_time")
    private Long observationTime;  // When the clinical observation occurred (lab collection, vital reading)

    @JsonProperty("source_type")
    private String sourceType;  // "LAB", "VITAL", "MEDICATION" - enables event correlation

    @JsonProperty("source_code")
    private String sourceCode;  // LOINC code, vital sign code, RxNorm code - specific identifier

    @JsonProperty("encounter_id")
    private String encounterId;  // Links alert to specific clinical encounter

    // Alert Deduplication and Hierarchy Fields
    @JsonProperty("related_alerts")
    private java.util.List<String> relatedAlerts;  // Alert IDs of related/child alerts

    @JsonProperty("consolidated_from")
    private java.util.List<String> consolidatedFrom;  // Alert IDs that were merged into this alert

    @JsonProperty("alert_hierarchy")
    private String alertHierarchy;  // "parent", "child", or null for standalone alerts

    @JsonProperty("suppress_display")
    private Boolean suppressDisplay;  // If true, this alert is consolidated into a parent and shouldn't be shown

    // Alert Prioritization Fields (Multi-dimensional scoring)
    @JsonProperty("priority_score")
    private Double priorityScore;  // 0-30 points from multi-dimensional scoring

    @JsonProperty("priority_level")
    private AlertPriority priorityLevel;  // P0-P4 classification

    @JsonProperty("priority_breakdown")
    private Map<String, Object> priorityBreakdown;  // Transparent breakdown of dimension scores

    public SimpleAlert() {
        this.context = new HashMap<>();
        this.timestamp = System.currentTimeMillis();
        this.sourceModule = "MODULE_2_THRESHOLD";
    }

    /**
     * Convenience constructor for quick alert creation (Unified Pipeline use case)
     * Auto-generates alertId and sets timestamp
     */
    public SimpleAlert(AlertType alertType, AlertSeverity severity, String message, String patientId) {
        this();
        this.alertId = UUID.randomUUID().toString();
        this.alertType = alertType;
        this.severity = severity;
        this.message = message;
        this.patientId = patientId;
        this.sourceModule = "MODULE_2_UNIFIED_PIPELINE";
    }

    private SimpleAlert(Builder builder) {
        this.alertId = builder.alertId;
        this.patientId = builder.patientId;
        this.alertType = builder.alertType;
        this.severity = builder.severity;
        this.message = builder.message;
        this.context = builder.context;
        this.timestamp = builder.timestamp;
        this.sourceModule = builder.sourceModule;
    }

    // Builder pattern
    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {
        private String alertId;
        private String patientId;
        private AlertType alertType;
        private AlertSeverity severity;
        private String message;
        private Map<String, Object> context = new HashMap<>();
        private long timestamp;
        private String sourceModule;

        public Builder alertId(String alertId) {
            this.alertId = alertId;
            return this;
        }

        public Builder patientId(String patientId) {
            this.patientId = patientId;
            return this;
        }

        public Builder alertType(AlertType alertType) {
            this.alertType = alertType;
            return this;
        }

        public Builder severity(AlertSeverity severity) {
            this.severity = severity;
            return this;
        }

        public Builder message(String message) {
            this.message = message;
            return this;
        }

        public Builder context(Map<String, Object> context) {
            this.context = context != null ? new HashMap<>(context) : new HashMap<>();
            return this;
        }

        public Builder addContext(String key, Object value) {
            this.context.put(key, value);
            return this;
        }

        public Builder timestamp(long timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        public Builder sourceModule(String sourceModule) {
            this.sourceModule = sourceModule;
            return this;
        }

        public SimpleAlert build() {
            // Validation
            if (patientId == null || patientId.trim().isEmpty()) {
                throw new IllegalArgumentException("Patient ID is required");
            }
            if (alertType == null) {
                throw new IllegalArgumentException("Alert type is required");
            }
            if (severity == null) {
                throw new IllegalArgumentException("Severity is required");
            }
            if (message == null || message.trim().isEmpty()) {
                throw new IllegalArgumentException("Message is required");
            }

            // Set defaults
            if (alertId == null) {
                this.alertId = UUID.randomUUID().toString();
            }
            if (timestamp == 0) {
                this.timestamp = System.currentTimeMillis();
            }
            if (sourceModule == null) {
                this.sourceModule = "MODULE_2_THRESHOLD";
            }

            return new SimpleAlert(this);
        }
    }

    // Getters and Setters
    public String getAlertId() { return alertId; }
    public void setAlertId(String alertId) { this.alertId = alertId; }

    public String getPatientId() { return patientId; }
    public void setPatientId(String patientId) { this.patientId = patientId; }

    public AlertType getAlertType() { return alertType; }
    public void setAlertType(AlertType alertType) { this.alertType = alertType; }

    public AlertSeverity getSeverity() { return severity; }
    public void setSeverity(AlertSeverity severity) { this.severity = severity; }

    public String getMessage() { return message; }
    public void setMessage(String message) { this.message = message; }

    public Map<String, Object> getContext() { return context; }
    public void setContext(Map<String, Object> context) { this.context = context; }

    public long getTimestamp() { return timestamp; }
    public void setTimestamp(long timestamp) { this.timestamp = timestamp; }

    public String getSourceModule() { return sourceModule; }
    public void setSourceModule(String sourceModule) { this.sourceModule = sourceModule; }

    // Temporal correlation getters/setters
    public Long getObservationTime() { return observationTime; }
    public void setObservationTime(Long observationTime) { this.observationTime = observationTime; }

    public String getSourceType() { return sourceType; }
    public void setSourceType(String sourceType) { this.sourceType = sourceType; }

    public String getSourceCode() { return sourceCode; }
    public void setSourceCode(String sourceCode) { this.sourceCode = sourceCode; }

    public String getEncounterId() { return encounterId; }
    public void setEncounterId(String encounterId) { this.encounterId = encounterId; }

    // Alert deduplication getters/setters
    public java.util.List<String> getRelatedAlerts() { return relatedAlerts; }
    public void setRelatedAlerts(java.util.List<String> relatedAlerts) { this.relatedAlerts = relatedAlerts; }

    public java.util.List<String> getConsolidatedFrom() { return consolidatedFrom; }
    public void setConsolidatedFrom(java.util.List<String> consolidatedFrom) { this.consolidatedFrom = consolidatedFrom; }

    public String getAlertHierarchy() { return alertHierarchy; }
    public void setAlertHierarchy(String alertHierarchy) { this.alertHierarchy = alertHierarchy; }

    public Boolean getSuppressDisplay() { return suppressDisplay; }
    public void setSuppressDisplay(Boolean suppressDisplay) { this.suppressDisplay = suppressDisplay; }

    // Alert prioritization getters/setters
    public Double getPriorityScore() { return priorityScore; }
    public void setPriorityScore(Double priorityScore) { this.priorityScore = priorityScore; }

    public AlertPriority getPriorityLevel() { return priorityLevel; }
    public void setPriorityLevel(AlertPriority priorityLevel) { this.priorityLevel = priorityLevel; }

    public Map<String, Object> getPriorityBreakdown() { return priorityBreakdown; }
    public void setPriorityBreakdown(Map<String, Object> priorityBreakdown) { this.priorityBreakdown = priorityBreakdown; }

    /**
     * Alerts are considered equal if they represent the same clinical condition
     * for the same patient, regardless of timestamp or alert ID.
     *
     * This enables proper deduplication in HashSet<SimpleAlert> collections.
     * For example, multiple "Elevated lactate" alerts for the same patient
     * should be deduplicated to a single alert.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        SimpleAlert that = (SimpleAlert) o;

        // Alert identity based on clinical semantics, not timing
        if (!patientId.equals(that.patientId)) return false;
        if (alertType != that.alertType) return false;
        if (severity != that.severity) return false;
        return message.equals(that.message);
    }

    /**
     * Hash code based on alert semantic identity (patientId, alertType, severity, message)
     * Excludes timestamp and alertId to enable deduplication of identical clinical alerts
     */
    @Override
    public int hashCode() {
        int result = patientId.hashCode();
        result = 31 * result + alertType.hashCode();
        result = 31 * result + severity.hashCode();
        result = 31 * result + message.hashCode();
        return result;
    }

    @Override
    public String toString() {
        return "SimpleAlert{" +
            "alertId='" + alertId + '\'' +
            ", patientId='" + patientId + '\'' +
            ", alertType=" + alertType +
            ", severity=" + severity +
            ", message='" + message + '\'' +
            ", sourceModule='" + sourceModule + '\'' +
            ", timestamp=" + timestamp +
            '}';
    }
}
