@echo off
REM Setup script for local PostgreSQL database for KB-Drug-Rules service
REM This script works on Windows

setlocal enabledelayedexpansion

echo 🗄️  Setting up local PostgreSQL for KB-Drug-Rules service...
echo.

REM Configuration
set DB_NAME=kb_drug_rules
set DB_USER=kb_drug_rules_user
set DB_PASSWORD=kb_password
set POSTGRES_USER=postgres

REM Check if PostgreSQL is installed
echo [INFO] Checking PostgreSQL installation...
psql --version >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] PostgreSQL is not installed or not in PATH
    echo.
    echo Please install PostgreSQL first:
    echo   Download from: https://www.postgresql.org/download/windows/
    echo   Or use chocolatey: choco install postgresql
    echo.
    pause
    exit /b 1
)

for /f "tokens=*" %%i in ('psql --version') do set PSQL_VERSION=%%i
echo [SUCCESS] PostgreSQL found: !PSQL_VERSION!

REM Check if PostgreSQL service is running
echo [INFO] Checking PostgreSQL service...
pg_isready -h localhost -p 5432 >nul 2>&1
if %errorlevel% neq 0 (
    echo [WARNING] PostgreSQL service is not running
    echo.
    echo Please start PostgreSQL service:
    echo   1. Press Win+R, type "services.msc"
    echo   2. Find "postgresql" service and start it
    echo   3. Or run: net start postgresql-x64-14 (adjust version as needed)
    echo.
    pause
    
    REM Check again
    pg_isready -h localhost -p 5432 >nul 2>&1
    if !errorlevel! neq 0 (
        echo [ERROR] PostgreSQL service is still not running
        pause
        exit /b 1
    )
)

echo [SUCCESS] PostgreSQL service is running

REM Setup database
echo [INFO] Setting up KB-Drug-Rules database...

REM Get the directory of this script
set SCRIPT_DIR=%~dp0
set SQL_FILE=%SCRIPT_DIR%setup-local-postgres.sql

if not exist "%SQL_FILE%" (
    echo [ERROR] SQL setup file not found: %SQL_FILE%
    pause
    exit /b 1
)

echo [INFO] Running database setup script...
echo Please enter the PostgreSQL superuser password when prompted...

psql -U %POSTGRES_USER% -h localhost -f "%SQL_FILE%"
if %errorlevel% neq 0 (
    echo [ERROR] Failed to setup database
    pause
    exit /b 1
)

echo [SUCCESS] Database setup completed

REM Test database connection
echo [INFO] Testing database connection...

set PGPASSWORD=%DB_PASSWORD%
psql -U %DB_USER% -h localhost -d %DB_NAME% -c "SELECT 'Connection successful!' as status;" >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Database connection test failed
    pause
    exit /b 1
)

echo [SUCCESS] Database connection test passed

REM Show sample data
echo.
echo [INFO] Sample data in database:
psql -U %DB_USER% -h localhost -d %DB_NAME% -c "SELECT drug_id, version, signature_valid FROM drug_rule_packs;"

REM Create environment file
echo [INFO] Creating environment configuration...

set ENV_FILE=..\.env.local

(
echo # Local PostgreSQL configuration for KB-Drug-Rules service
echo # Generated by setup-local-postgres.bat
echo.
echo # Server configuration
echo PORT=8081
echo DEBUG=true
echo.
echo # Database configuration
echo DATABASE_URL=postgresql://%DB_USER%:%DB_PASSWORD%@localhost:5432/%DB_NAME%
echo.
echo # Redis configuration ^(you'll need to install Redis separately^)
echo REDIS_URL=redis://localhost:6379/0
echo.
echo # Security configuration
echo SIGNING_KEY_PATH=./keys/signing.key
echo JWT_SECRET=your-jwt-secret-key-here
echo REQUIRE_APPROVAL=false
echo REQUIRE_SIGNATURE=false
echo.
echo # Regional configuration
echo SUPPORTED_REGIONS=US,EU,CA,AU
echo DEFAULT_REGION=US
echo.
echo # Monitoring configuration
echo METRICS_ENABLED=true
echo TRACING_ENABLED=false
) > "%ENV_FILE%"

echo [SUCCESS] Environment file created: %ENV_FILE%

echo.
echo Database connection details:
echo   Host:     localhost
echo   Port:     5432
echo   Database: %DB_NAME%
echo   Username: %DB_USER%
echo   Password: %DB_PASSWORD%

echo.
echo 🎉 Setup completed successfully!
echo.
echo Next steps:
echo 1. Install Redis ^(if not already installed^):
echo    Download from: https://github.com/microsoftarchive/redis/releases
echo    Or use chocolatey: choco install redis-64
echo.
echo 2. Start the KB-Drug-Rules service:
echo    cd ..\kb-drug-rules
echo    set DATABASE_URL=postgresql://%DB_USER%:%DB_PASSWORD%@localhost:5432/%DB_NAME%
echo    set PORT=8081
echo    set DEBUG=true
echo    go run cmd/server/main.go
echo.
echo 3. Test the service:
echo    curl http://localhost:8081/health
echo    curl http://localhost:8081/v1/items/metformin
echo.
echo 4. Access database with:
echo    psql -U %DB_USER% -h localhost -d %DB_NAME%
echo    Password: %DB_PASSWORD%

pause
